(function(){var g=this;function h(a,d){var b=a.split("."),c=g;b[0]in c||!c.execScript||c.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)b.length||void 0===d?c[e]?c=c[e]:c=c[e]={}:c[e]=d};var n=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function p(a,d){return a<d?-1:a>d?1:0};var q={};function r(a){var d=a.length;if(0<d){for(var b=Array(d),c=0;c<d;c++)b[c]=a[c];return b}return[]};var t;a:{var u=g.navigator;if(u){var v=u.userAgent;if(v){t=v;break a}}t=""};var w=-1!=t.indexOf("Opera"),x=-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"),y=-1!=t.indexOf("Edge"),z=-1!=t.indexOf("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge"))&&!(-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"))&&-1==t.indexOf("Edge"),A=-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge");function B(){var a=g.document;return a?a.documentMode:void 0}var C;
a:{var D="",E=function(){var a=t;if(z)return/rv\:([^\);]+)(\)|;)/.exec(a);if(y)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(A)return/WebKit\/(\S+)/.exec(a);if(w)return/(?:Version)[ \/]?(\S+)/.exec(a)}();E&&(D=E?E[1]:"");if(x){var F=B();if(null!=F&&F>parseFloat(D)){C=String(F);break a}}C=D}var H={};
function I(a){if(!H[a]){for(var d=0,b=n(String(C)).split("."),c=n(String(a)).split("."),e=Math.max(b.length,c.length),f=0;0==d&&f<e;f++){var k=b[f]||"",G=c[f]||"",R=RegExp("(\\d*)(\\D*)","g"),S=RegExp("(\\d*)(\\D*)","g");do{var l=R.exec(k)||["","",""],m=S.exec(G)||["","",""];if(0==l[0].length&&0==m[0].length)break;d=p(0==l[1].length?0:parseInt(l[1],10),0==m[1].length?0:parseInt(m[1],10))||p(0==l[2].length,0==m[2].length)||p(l[2],m[2])}while(0==d)}H[a]=0<=d}}
var J=g.document,K=J&&x?B()||("CSS1Compat"==J.compatMode?parseInt(C,10):5):void 0;var L;if(!(L=!z&&!x)){var M;if(M=x)M=9<=Number(K);L=M}L||z&&I("1.9.1");x&&I("9");function N(a){var d=window;if(d.addEventListener)d.addEventListener("load",a,!1);else if(d.attachEvent)d.attachEvent("onload",a);else{var b=d.onload;d.onload=function(){a.call(this);b&&b.call(this)}}};var O;function P(a,d,b,c,e){this.h=a;this.j=d;this.l=b;this.f=e;this.g={height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth};this.i=c;this.b={};this.a=[];this.c={}}
function Q(a,d){var b,c,e=d.getAttribute("data-pagespeed-url-hash");if(b=e&&!(e in a.c))if(0>=d.offsetWidth&&0>=d.offsetHeight)b=!1;else{c=d.getBoundingClientRect();var f=document.body;b=c.top+("pageYOffset"in window?window.pageYOffset:(document.documentElement||f.parentNode||f).scrollTop);c=c.left+("pageXOffset"in window?window.pageXOffset:(document.documentElement||f.parentNode||f).scrollLeft);f=b.toString()+","+c;a.b.hasOwnProperty(f)?b=!1:(a.b[f]=!0,b=b<=a.g.height&&c<=a.g.width)}b&&(a.a.push(e),
a.c[e]=!0)}P.prototype.checkImageForCriticality=function(a){a.getBoundingClientRect&&Q(this,a)};h("pagespeed.CriticalImages.checkImageForCriticality",function(a){O.checkImageForCriticality(a)});h("pagespeed.CriticalImages.checkCriticalImages",function(){T(O)});
function T(a){a.b={};for(var d=["IMG","INPUT"],b=[],c=0;c<d.length;++c)b=b.concat(r(document.getElementsByTagName(d[c])));if(0!=b.length&&b[0].getBoundingClientRect){for(c=0;d=b[c];++c)Q(a,d);b="oh="+a.l;a.f&&(b+="&n="+a.f);if(d=0!=a.a.length)for(b+="&ci="+encodeURIComponent(a.a[0]),c=1;c<a.a.length;++c){var e=","+encodeURIComponent(a.a[c]);131072>=b.length+e.length&&(b+=e)}a.i&&(e="&rd="+encodeURIComponent(JSON.stringify(U())),131072>=b.length+e.length&&(b+=e),d=!0);V=b;if(d){c=a.h;a=a.j;var f;if(window.XMLHttpRequest)f=
new XMLHttpRequest;else if(window.ActiveXObject)try{f=new ActiveXObject("Msxml2.XMLHTTP")}catch(k){try{f=new ActiveXObject("Microsoft.XMLHTTP")}catch(G){}}f&&(f.open("POST",c+(-1==c.indexOf("?")?"?":"&")+"url="+encodeURIComponent(a)),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.send(b))}}}
function U(){var a={},d=q.getElementsByTagName("IMG");if(0==d.length)return{};var b=d[0];if(!("naturalWidth"in b&&"naturalHeight"in b))return{};for(var c=0;b=d[c];++c){var e=b.getAttribute("data-pagespeed-url-hash");e&&(!(e in a)&&0<b.width&&0<b.height&&0<b.naturalWidth&&0<b.naturalHeight||e in a&&b.width>=a[e].o&&b.height>=a[e].m)&&(a[e]={rw:b.width,rh:b.height,ow:b.naturalWidth,oh:b.naturalHeight})}return a}var V="";h("pagespeed.CriticalImages.getBeaconData",function(){return V});
h("pagespeed.CriticalImages.Run",function(a,d,b,c,e,f){var k=new P(a,d,b,e,f);O=k;c&&N(function(){window.setTimeout(function(){T(k)},0)})});})();
