(function(){var g=this;function h(a,c){var b=a.split("."),d=g;b[0]in d||!d.execScript||d.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)b.length||void 0===c?d[e]?d=d[e]:d=d[e]={}:d[e]=c};var k=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function p(a,c){return a<c?-1:a>c?1:0};var q={};function r(a){var c=a.length;if(0<c){for(var b=Array(c),d=0;d<c;d++)b[d]=a[d];return b}return[]};var t;a:{var u=g.navigator;if(u){var v=u.userAgent;if(v){t=v;break a}}t=""};var w=-1!=t.indexOf("Opera")||-1!=t.indexOf("OPR"),x=-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"),y=-1!=t.indexOf("Edge"),z=-1!=t.indexOf("Gecko")&&!(-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge"))&&!(-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"))&&-1==t.indexOf("Edge"),A=-1!=t.toLowerCase().indexOf("webkit")&&-1==t.indexOf("Edge");
function B(){var a=t;if(z)return/rv\:([^\);]+)(\)|;)/.exec(a);if(y)return/Edge\/([\d\.]+)/.exec(a);if(x)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(A)return/WebKit\/(\S+)/.exec(a)}function C(){var a=g.document;return a?a.documentMode:void 0}var E=function(){if(w&&g.opera){var a;var c=g.opera.version;try{a=c()}catch(b){a=c}return a}a="";(c=B())&&(a=c?c[1]:"");return x&&(c=C(),null!=c&&c>parseFloat(a))?String(c):a}(),F={};
function G(a){if(!F[a]){for(var c=0,b=k(String(E)).split("."),d=k(String(a)).split("."),e=Math.max(b.length,d.length),f=0;0==c&&f<e;f++){var l=b[f]||"",D=d[f]||"",P=RegExp("(\\d*)(\\D*)","g"),Q=RegExp("(\\d*)(\\D*)","g");do{var m=P.exec(l)||["","",""],n=Q.exec(D)||["","",""];if(0==m[0].length&&0==n[0].length)break;c=p(0==m[1].length?0:parseInt(m[1],10),0==n[1].length?0:parseInt(n[1],10))||p(0==m[2].length,0==n[2].length)||p(m[2],n[2])}while(0==c)}F[a]=0<=c}}
var H=g.document,I=H&&x?C()||("CSS1Compat"==H.compatMode?parseInt(E,10):5):void 0;var J;if(!(J=!z&&!x)){var K;if(K=x)K=9<=Number(I);J=K}J||z&&G("1.9.1");x&&G("9");function L(a){var c=window;if(c.addEventListener)c.addEventListener("load",a,!1);else if(c.attachEvent)c.attachEvent("onload",a);else{var b=c.onload;c.onload=function(){a.call(this);b&&b.call(this)}}};var M;function N(a,c,b,d,e){this.h=a;this.j=c;this.l=b;this.f=e;this.g={height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth};this.i=d;this.b={};this.a=[];this.c={}}
function O(a,c){var b,d,e=c.getAttribute("data-pagespeed-url-hash");if(b=e&&!(e in a.c))if(0>=c.offsetWidth&&0>=c.offsetHeight)b=!1;else{d=c.getBoundingClientRect();var f=document.body;b=d.top+("pageYOffset"in window?window.pageYOffset:(document.documentElement||f.parentNode||f).scrollTop);d=d.left+("pageXOffset"in window?window.pageXOffset:(document.documentElement||f.parentNode||f).scrollLeft);f=b.toString()+","+d;a.b.hasOwnProperty(f)?b=!1:(a.b[f]=!0,b=b<=a.g.height&&d<=a.g.width)}b&&(a.a.push(e),
a.c[e]=!0)}N.prototype.checkImageForCriticality=function(a){a.getBoundingClientRect&&O(this,a)};h("pagespeed.CriticalImages.checkImageForCriticality",function(a){M.checkImageForCriticality(a)});h("pagespeed.CriticalImages.checkCriticalImages",function(){R(M)});
function R(a){a.b={};for(var c=["IMG","INPUT"],b=[],d=0;d<c.length;++d)b=b.concat(r(document.getElementsByTagName(c[d])));if(0!=b.length&&b[0].getBoundingClientRect){for(d=0;c=b[d];++d)O(a,c);b="oh="+a.l;a.f&&(b+="&n="+a.f);if(c=0!=a.a.length)for(b+="&ci="+encodeURIComponent(a.a[0]),d=1;d<a.a.length;++d){var e=","+encodeURIComponent(a.a[d]);131072>=b.length+e.length&&(b+=e)}a.i&&(e="&rd="+encodeURIComponent(JSON.stringify(S())),131072>=b.length+e.length&&(b+=e),c=!0);T=b;if(c){d=a.h;a=a.j;var f;if(window.XMLHttpRequest)f=
new XMLHttpRequest;else if(window.ActiveXObject)try{f=new ActiveXObject("Msxml2.XMLHTTP")}catch(l){try{f=new ActiveXObject("Microsoft.XMLHTTP")}catch(D){}}f&&(f.open("POST",d+(-1==d.indexOf("?")?"?":"&")+"url="+encodeURIComponent(a)),f.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),f.send(b))}}}
function S(){var a={},c=q.getElementsByTagName("IMG");if(0==c.length)return{};var b=c[0];if(!("naturalWidth"in b&&"naturalHeight"in b))return{};for(var d=0;b=c[d];++d){var e=b.getAttribute("data-pagespeed-url-hash");e&&(!(e in a)&&0<b.width&&0<b.height&&0<b.naturalWidth&&0<b.naturalHeight||e in a&&b.width>=a[e].o&&b.height>=a[e].m)&&(a[e]={rw:b.width,rh:b.height,ow:b.naturalWidth,oh:b.naturalHeight})}return a}var T="";h("pagespeed.CriticalImages.getBeaconData",function(){return T});
h("pagespeed.CriticalImages.Run",function(a,c,b,d,e,f){var l=new N(a,c,b,e,f);M=l;d&&L(function(){window.setTimeout(function(){R(l)},0)})});})();
