(function(){var e=Object,f=document,g="appendChild",k="evaluate",m="createElement",n="setAttribute",p="propertyIsEnumerable",q="push",r="length",s="prototype",t="call",v="",w=" != ",x="#.###%",y="#4ECDC4",z="#556270",A="#C7F464",B="#E5E5E5",C="#F2F2F2",D="&end_time=",E="&granularity=",aa="&start_time=",ba="&var_titles=",ca=")",da=",",ea="/mod_pagespeed_statistics?json",fa="CSS files not rewritten because of parse errors",ga="Cache lookups that were expired",ha="Cache misses",ia="Data failed to load for graph ",
ja="GET",ka="Image rewrite failures",la="JSON data missing required variable.",ma="JSON response is malformed. (",na="JavaScript minification failures",oa="MMM d, y hh:mma",pa="Resources not loaded because of fetch failures",qa="Resources not rewritten because domain wasn't authorized",ra="Resources not rewritten because of restrictive Cache-Control headers",sa="Time",ta="XHR request failed.",ua="[object Array]",va="[object Function]",wa="[object Window]",F="array",xa="bottom",ya="cache_backend_hits",
G="cache_backend_misses",za="cache_expirations",Aa="call",H="class",Ba="css_filter_blocks_rewritten",Ca="css_filter_parse_failures",Da="datetime",I="div",Ea="explicit",J="function",Fa="id",K="image_norewrites_high_resolution",Ga="image_rewrites",Ha="image_rewrites_dropped_decode_failure",Ia="image_rewrites_dropped_mime_type_unknown",Ja="image_rewrites_dropped_nosaving_noresize",Ka="image_rewrites_dropped_nosaving_resize",La="image_rewrites_dropped_server_write_fail",Ma="javascript_blocks_minified",
Na="javascript_minification_failures",Oa="null",Pa="num_cache_control_not_rewritable_resources",Qa="num_cache_control_rewritable_resources",L="number",Ra="o",M="object",Sa="pagespeed-graph",Ta="pagespeed-graphs-container",N="pagespeed-title",Ua="pagespeed-widgets",Va="pagespeed-widgets-topbar",Wa="resource_url_domain_acceptances",Xa="resource_url_domain_rejections",Ya="serf_fetch_failure_count",Za="serf_fetch_request_count",$a="span",ab="splice",bb="string",cb="{",O,db=function(a){var b=typeof a;
if(b==M)if(a){if(a instanceof Array)return F;if(a instanceof e)return b;var c=e[s].toString[t](a);if(c==wa)return M;if(c==ua||typeof a[r]==L&&"undefined"!=typeof a.splice&&"undefined"!=typeof a[p]&&!a[p](ab))return F;if(c==va||"undefined"!=typeof a[t]&&"undefined"!=typeof a[p]&&!a[p](Aa))return J}else return Oa;else if(b==J&&"undefined"==typeof a[t])return M;return b},P="closure_uid_"+(1E9*Math.random()>>>0),eb=0;var Q="StopIteration"in this?this.StopIteration:Error("StopIteration"),R=function(){};R[s].next=function(){throw Q;};R[s].k=function(){return this};var S=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};var T=function(a,b){this.b={};this.a=[];var c=arguments[r];if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.e(a)};O=T[s];O.j=0;O.h=0;O.f=function(){this.i();for(var a=[],b=0;b<this.a[r];b++)a[q](this.b[this.a[b]]);return a};O.s=function(){this.i();return this.a.concat()};
O.i=function(){if(this.j!=this.a[r]){for(var a=0,b=0;a<this.a[r];){var c=this.a[a];e[s].hasOwnProperty[t](this.b,c)&&(this.a[b++]=c);a++}this.a.length=b}if(this.j!=this.a[r]){for(var d={},b=a=0;a<this.a[r];)c=this.a[a],e[s].hasOwnProperty[t](d,c)||(this.a[b++]=c,d[c]=1),a++;this.a.length=b}};O.set=function(a,b){e[s].hasOwnProperty[t](this.b,a)||(this.j++,this.a[q](a),this.h++);this.b[a]=b};
O.e=function(a){var b;if(a instanceof T)b=a.s(),a=a.f();else{b=[];var c=0,d;for(d in a)b[c++]=d;a=S(a)}for(c=0;c<b[r];c++)this.set(b[c],a[c])};O.k=function(a){this.i();var b=0,c=this.a,d=this.b,h=this.h,l=this,u=new R;u.next=function(){for(;;){if(h!=l.h)throw Error("The map has changed since the iterator was created");if(b>=c[r])throw Q;var u=c[b++];return a?u:d[u]}};return u};var fb=function(a){if(typeof a.f==J)return a.f();if(typeof a==bb)return a.split(v);var b=db(a);if(b==F||b==M&&typeof a[r]==L){for(var b=[],c=a[r],d=0;d<c;d++)b[q](a[d]);return b}return S(a)};var U=function(a){this.b=new T;a&&this.e(a)},gb=function(a){var b=typeof a;return b==M&&a||b==J?Ra+(a[P]||(a[P]=++eb)):b.substr(0,1)+a};U[s].add=function(a){this.b.set(gb(a),a)};U[s].e=function(a){a=fb(a);for(var b=a[r],c=0;c<b;c++)this.add(a[c])};U[s].f=function(){return this.b.f()};U[s].k=function(){return this.b.k(!1)};google.load("visualization","1.0",{packages:["corechart"]});
var V=function(a){window.console&&console.error(a)},W=function(){this.a=[];this.l=new U;this.b=this.g=null;this.m={width:900,height:255,colors:[y,z,A],legend:{position:xa},hAxis:{format:oa,gridlines:{color:C},baselineColor:B},vAxis:{format:x,minValue:0,viewWindowMode:Ea,viewWindow:{min:0},gridlines:{color:C},baselineColor:B},chartArea:{left:60,top:20,width:800},pointSize:2}},X=function(a){var b={};b.c=new U([a]);b.evaluate=function(b){return b(a)};return b},Y=function(a){var b={};b.c=new U;for(var c=
0;c<a[r];c++)b.c.e(a[c].c);b.evaluate=function(b){for(var c=0,l=0;l<a[r];l++)c+=a[l][k](b);return c};return b},Z=function(a,b){var c={};c.c=new U;c.c.e(a.c);c.c.e(b.c);c.evaluate=function(c){var h=b[k](c);return 0==h?0:a[k](c)/h};return c},$=function(a,b){return Z(a,Y([a,b]))};O=W[s];
O.u=function(){this.d(pa,Z(X(Ya),X(Za)));this.d(qa,$(X(Xa),X(Wa)));this.d(ra,$(X(Pa),X(Qa)));var a=Y([X(G),X(ya)]);this.d(ha,Z(X(G),a));this.d(ga,Z(X(za),a));this.d(fa,$(X(Ca),X(Ba)));this.d(na,$(X(Na),X(Ma)));var a=Y([X(Ga),X(Ka),X(Ja)]),b=Y([X(K),X(Ha),X(La),X(Ia),X(K)]);this.d(ka,$(b,a))};
O.d=function(a,b){var c={};c.title=a;c.value=b;var d=google.visualization.LineChart,h=this.a[r],l=f[m](I);l[n](H,Ua);l[g](hb(a,h));h=f[m](I);h[n](H,Sa);l[g](h);f.getElementById(Ta)[g](l);c.n=new d(h);this.a[q](c);this.l.e(b.c);return c};O.v=function(){var a=new Date;this.w(new Date(a-864E5),a,6E4)};O.q=function(a,b,c,d){b=ea+(aa+b.getTime());b+=D+c.getTime();b=b+(E+d)+ba;for(c=0;c<a[r];c++)b+=a[c]+da;return b};
O.w=function(a,b,c){var d=new XMLHttpRequest,h=this;a=this.q(this.l.f(),a,b,c);d.onreadystatechange=function(){if(4==this.readyState)if(200!=this.status||1>this.responseText[r]||this.responseText[0]!=cb)V(ta);else{var a=JSON.parse(this.responseText);h.r(a)}};d.open(ja,a);d.send()};
O.r=function(a){this.g=a.variables;this.b=a.timestamps;this.o(this.b,this.g);for(a=0;a<this.a[r];a++){for(var b=[],c=0;c<this.b[r];c++)b[q](this.a[a].value[k](function(a){return function(b){if(b in a)return a[b][c];V(la)}}(this.g)));this.p(this.a[a],this.b,b)}};O.o=function(a,b){for(var c in b)a[r]!=b[c][r]&&V(ma+a[r]+w+b[c][r]+ca)};O.p=function(a,b,c){for(var d=this.t(a.title),h=0;h<b[r];h++)d.addRow([new Date(b[h]),c[h]]);0==d.getNumberOfRows()&&V(ia+a.title);a.n.draw(d,this.m)};
O.t=function(a){var b=new google.visualization.DataTable;b.addColumn(Da,sa);b.addColumn(L,a);return b};var hb=function(a,b){var c=f[m](I);c[n](H,Va);var d=f[m]($a);d[n](H,N);d[n](Fa,N+b);d.innerHTML=a;c[g](d);return c};google.setOnLoadCallback(function(){var a=new W;a.u();a.v();return a});})();
