(function(){var e=Object,f=document,g="appendChild",k="evaluate",m="createElement",p="setAttribute",q="propertyIsEnumerable",r="push",s="length",t="prototype",u="call",v="",w=" != ",x=' (<a href="',y='">doc</a>)',z="#.###%",A="#4ECDC4",B="#556270",C="#C7F464",D="#E5E5E5",E="#F2F2F2",F="&end_time=",aa="&granularity=",ba="&start_time=",ca="&var_titles=",da=")",ea=",",fa="/mod_pagespeed_statistics?json",ga="CSS files not rewritten because of parse errors",ha="Cache lookups that were expired",ia="Cache misses",ja=
"Data failed to load for graph ",ka="GET",la="Image rewrite failures",ma="JSON data missing required variable.",na="JSON response is malformed. (",oa="JavaScript minification failures",pa="MMM d, y hh:mma",qa="Resources not loaded because of fetch failures",ra="Resources not rewritten because domain wasn't authorized",sa="Resources not rewritten because of restrictive Cache-Control headers",ta="Time",ua="XHR request failed.",va="[object Array]",wa="[object Function]",xa="[object Window]",G="array",
ya="bottom",za="cache-control",Aa="cache-expired",Ba="cache-miss",Ca="cache_backend_hits",H="cache_backend_misses",Da="cache_expirations",Ea="call",I="class",Fa="css-error",Ga="css_filter_blocks_rewritten",Ha="css_filter_parse_failures",Ia="datetime",J="div",Ja="explicit",Ka="fetch-failure",K="function",La="https://developers.google.com/speed/pagespeed/module/console#",Ma="id",Na="image-error",Oa="image_norewrites_high_resolution",Pa="image_rewrites",Qa="image_rewrites_dropped_decode_failure",Ra=
"image_rewrites_dropped_due_to_load",Sa="image_rewrites_dropped_mime_type_unknown",Ta="image_rewrites_dropped_nosaving_noresize",Ua="image_rewrites_dropped_nosaving_resize",Va="image_rewrites_dropped_server_write_fail",Wa="javascript_blocks_minified",Xa="javascript_minification_failures",Ya="js-error",Za="not-authorized",$a="null",ab="num_cache_control_not_rewritable_resources",bb="num_cache_control_rewritable_resources",L="number",cb="o",M="object",db="pagespeed-graph",eb="pagespeed-graphs-container",
N="pagespeed-title",fb="pagespeed-widgets",gb="pagespeed-widgets-topbar",hb="resource_url_domain_acceptances",ib="resource_url_domain_rejections",jb="serf_fetch_failure_count",kb="serf_fetch_request_count",lb="span",mb="splice",nb="string",ob="{",O,pb=function(a){var b=typeof a;if(b==M)if(a){if(a instanceof Array)return G;if(a instanceof e)return b;var c=e[t].toString[u](a);if(c==xa)return M;if(c==va||typeof a[s]==L&&"undefined"!=typeof a.splice&&"undefined"!=typeof a[q]&&!a[q](mb))return G;if(c==
wa||"undefined"!=typeof a[u]&&"undefined"!=typeof a[q]&&!a[q](Ea))return K}else return $a;else if(b==K&&"undefined"==typeof a[u])return M;return b},P="closure_uid_"+(1E9*Math.random()>>>0),qb=0;var Q="StopIteration"in this?this.StopIteration:Error("StopIteration"),R=function(){};R[t].next=function(){throw Q;};R[t].k=function(){return this};var S=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};var T=function(a,b){this.b={};this.a=[];var c=arguments[s];if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.e(a)};O=T[t];O.j=0;O.h=0;O.f=function(){this.i();for(var a=[],b=0;b<this.a[s];b++)a[r](this.b[this.a[b]]);return a};O.t=function(){this.i();return this.a.concat()};
O.i=function(){if(this.j!=this.a[s]){for(var a=0,b=0;a<this.a[s];){var c=this.a[a];e[t].hasOwnProperty[u](this.b,c)&&(this.a[b++]=c);a++}this.a.length=b}if(this.j!=this.a[s]){for(var d={},b=a=0;a<this.a[s];)c=this.a[a],e[t].hasOwnProperty[u](d,c)||(this.a[b++]=c,d[c]=1),a++;this.a.length=b}};O.set=function(a,b){e[t].hasOwnProperty[u](this.b,a)||(this.j++,this.a[r](a),this.h++);this.b[a]=b};
O.e=function(a){var b;if(a instanceof T)b=a.t(),a=a.f();else{b=[];var c=0,d;for(d in a)b[c++]=d;a=S(a)}for(c=0;c<b[s];c++)this.set(b[c],a[c])};O.k=function(a){this.i();var b=0,c=this.a,d=this.b,h=this.h,n=this,l=new R;l.next=function(){for(;;){if(h!=n.h)throw Error("The map has changed since the iterator was created");if(b>=c[s])throw Q;var l=c[b++];return a?l:d[l]}};return l};var rb=function(a){if(typeof a.f==K)return a.f();if(typeof a==nb)return a.split(v);var b=pb(a);if(b==G||b==M&&typeof a[s]==L){for(var b=[],c=a[s],d=0;d<c;d++)b[r](a[d]);return b}return S(a)};var U=function(a){this.b=new T;a&&this.e(a)},sb=function(a){var b=typeof a;return b==M&&a||b==K?cb+(a[P]||(a[P]=++qb)):b.substr(0,1)+a};U[t].add=function(a){this.b.set(sb(a),a)};U[t].e=function(a){a=rb(a);for(var b=a[s],c=0;c<b;c++)this.add(a[c])};U[t].f=function(){return this.b.f()};U[t].k=function(){return this.b.k(!1)};google.load("visualization","1.0",{packages:["corechart"]});
var V=function(a){window.console&&console.error(a)},W=function(){this.a=[];this.l=new U;this.b=this.g=null;this.n={width:900,height:255,colors:[A,B,C],legend:{position:ya},hAxis:{format:pa,gridlines:{color:E},baselineColor:D},vAxis:{format:z,minValue:0,viewWindowMode:Ja,viewWindow:{min:0},gridlines:{color:E},baselineColor:D},chartArea:{left:60,top:20,width:800},pointSize:2}},X=function(a){var b={};b.c=new U([a]);b.evaluate=function(b){return b(a)};return b},Y=function(a){var b={};b.c=new U;for(var c=
0;c<a[s];c++)b.c.e(a[c].c);b.evaluate=function(b){for(var c=0,n=0;n<a[s];n++)c+=a[n][k](b);return c};return b},Z=function(a,b){var c={};c.c=new U;c.c.e(a.c);c.c.e(b.c);c.evaluate=function(c){var h=b[k](c);return 0==h?0:a[k](c)/h};return c},$=function(a,b){return Z(a,Y([a,b]))};O=W[t];
O.v=function(){this.d(qa,Ka,Z(X(jb),X(kb)));this.d(ra,Za,$(X(ib),X(hb)));this.d(sa,za,$(X(ab),X(bb)));var a=Y([X(H),X(Ca)]);this.d(ia,Ba,Z(X(H),a));this.d(ha,Aa,Z(X(Da),a));this.d(ga,Fa,$(X(Ha),X(Ga)));this.d(oa,Ya,$(X(Xa),X(Wa)));var a=Y([X(Pa),X(Ua),X(Ta)]),b=Y([X(Oa),X(Qa),X(Ra),X(Sa),X(Va)]);this.d(la,Na,$(b,a))};
O.d=function(a,b,c){var d={};d.title=a;d.o=La+b;d.value=c;b=google.visualization.LineChart;var h=d.o,n=this.a[s],l=f[m](J);l[p](I,fb);l[g](tb(a,h,n));a=f[m](J);a[p](I,db);l[g](a);f.getElementById(eb)[g](l);d.m=new b(a);this.a[r](d);this.l.e(c.c);return d};O.w=function(){var a=new Date;this.A(new Date(a-864E5),a,6E4)};O.r=function(a,b,c,d){b=fa+(ba+b.getTime());b+=F+c.getTime();b=b+(aa+d)+ca;for(c=0;c<a[s];c++)b+=a[c]+ea;return b};
O.A=function(a,b,c){var d=new XMLHttpRequest,h=this;a=this.r(this.l.f(),a,b,c);d.onreadystatechange=function(){if(4==this.readyState)if(200!=this.status||1>this.responseText[s]||this.responseText[0]!=ob)V(ua);else{var a=JSON.parse(this.responseText);h.s(a)}};d.open(ka,a);d.send()};
O.s=function(a){this.g=a.variables;this.b=a.timestamps;this.p(this.b,this.g);for(a=0;a<this.a[s];a++){for(var b=[],c=0;c<this.b[s];c++)b[r](this.a[a].value[k](function(a){return function(b){if(b in a)return a[b][c];V(ma)}}(this.g)));this.q(this.a[a],this.b,b)}};O.p=function(a,b){for(var c in b)a[s]!=b[c][s]&&V(na+a[s]+w+b[c][s]+da)};O.q=function(a,b,c){for(var d=this.u(a.title),h=0;h<b[s];h++)d.addRow([new Date(b[h]),c[h]]);0==d.getNumberOfRows()&&V(ja+a.title);a.m.draw(d,this.n)};
O.u=function(a){var b=new google.visualization.DataTable;b.addColumn(Ia,ta);b.addColumn(L,a);return b};var tb=function(a,b,c){var d=f[m](J);d[p](I,gb);var h=f[m](lb);h[p](I,N);h[p](Ma,N+c);h.innerHTML=a+x+b+y;d[g](h);return d};google.setOnLoadCallback(function(){var a=new W;a.v();a.w();return a});})();
