(function(){var l,q=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){return"string"==typeof a}function t(a){return"function"==ba(a)}function da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return u.apply(null,arguments)}var ga=Date.now||function(){return+new Date};
function v(a,b){var c=a.split("."),d=q;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}function ha(a,b){function c(){}c.prototype=b.prototype;a.Ib=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Hb=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function ia(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function ja(a){var b=[];ka(new la,a,b);return b.join("")}function la(){this.aa=void 0}
function ka(a,b,c){switch(typeof b){case "string":ma(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==ba(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],ka(a,a.aa?a.aa.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
ma(f,c),c.push(":"),ka(a,a.aa?a.aa.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var na={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},oa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function ma(a,b){b.push('"',a.replace(oa,function(a){if(a in na)return na[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return na[a]=e+b.toString(16)}),'"')};function pa(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function qa(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function ra(a,b){this.width=a;this.height=b}l=ra.prototype;l.clone=function(){return new ra(this.width,this.height)};l.toString=function(){return"("+this.width+" x "+this.height+")"};l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
l.scale=function(a,b){this.width*=a;this.height*="number"==typeof b?b:a;return this};function sa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function ta(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function ua(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}ha(x,Error);x.prototype.name="CustomError";var va=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function y(a,b){return-1!=a.toLowerCase().indexOf(b.toLowerCase())}function wa(a,b){return a<b?-1:a>b?1:0};var z=Array.prototype,xa=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(r(a))return r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ya=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},za=z.filter?function(a,b,c){return z.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=r(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},Aa=z.some?function(a,b,c){return z.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function Ba(a){return z.concat.apply(z,arguments)}function Ca(a){return z.concat.apply(z,arguments)}function Da(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ea(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}l=Ea.prototype;l.clone=function(){return new Ea(this.top,this.right,this.bottom,this.left)};l.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};l.contains=function(a){return this&&a?a instanceof Ea?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
l.expand=function(a,b,c,d){da(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=b,this.bottom+=c,this.left-=d);return this};l.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};l.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
l.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};l.translate=function(a,b){this.left+=a;this.right+=a;"number"==typeof b&&(this.top+=b,this.bottom+=b);return this};l.scale=function(a,b){var c="number"==typeof b?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function Fa(a){if("function"==typeof a.s)return a.s();if(r(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ta(a)}function Ga(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ca(a)||r(a))ya(a,b,c);else{var d;if("function"==typeof a.F)d=a.F();else if("function"!=typeof a.s)if(ca(a)||r(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=ua(a);else d=void 0;for(var e=Fa(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};function Ha(a,b){this.o={};this.e=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Ha?(c=a.F(),d=a.s()):(c=ua(a),d=ta(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}l=Ha.prototype;l.s=function(){Ia(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.o[this.e[b]]);return a};l.F=function(){Ia(this);return this.e.concat()};l.O=function(a){return A(this.o,a)};
l.clear=function(){this.o={};this.c=this.e.length=0};l.remove=function(a){return A(this.o,a)?(delete this.o[a],this.c--,this.e.length>2*this.c&&Ia(this),!0):!1};function Ia(a){if(a.c!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];A(a.o,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.c!=a.e.length){for(var e={},c=b=0;b<a.e.length;)d=a.e[b],A(e,d)||(a.e[c++]=d,e[d]=1),b++;a.e.length=c}}l.get=function(a,b){return A(this.o,a)?this.o[a]:b};
l.set=function(a,b){A(this.o,a)||(this.c++,this.e.push(a));this.o[a]=b};l.forEach=function(a,b){for(var c=this.F(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new Ha(this)};function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ja(a){return 1==a.length?"0"+a:a}function Ka(a,b,c){var d=0,e=0,f=0;if(0==b)f=e=d=c;else{var g=Math.floor(a/60),h=a/60-g;a=c*(1-b);var k=c*(1-b*h);b=c*(1-b*(1-h));switch(g){case 1:d=k;e=c;f=a;break;case 2:d=a;e=c;f=b;break;case 3:d=a;e=k;f=c;break;case 4:d=b;e=a;f=c;break;case 5:d=c;e=a;f=k;break;case 6:case 0:d=c,e=b,f=a}}return[Math.floor(d),Math.floor(e),Math.floor(f)]}
function La(a,b,c){var d=Math.max(Math.max(a,b),c),e=Math.min(Math.min(a,b),c);if(e==d)e=a=0;else{var f=d-e,e=f/d;a=60*(a==d?(b-c)/f:b==d?2+(c-a)/f:4+(a-b)/f);0>a&&(a+=360);360<a&&(a-=360)}return[a,e,d]};function Ma(a){if(a.classList)return a.classList;a=a.className;return r(a)&&a.match(/\S+/g)||[]}function B(a,b){var c;a.classList?c=a.classList.contains(b):(c=Ma(a),c=0<=xa(c,b));return c}function C(a,b){a.classList?a.classList.add(b):B(a,b)||(a.className+=0<a.className.length?" "+b:b)}function Na(a,b){a.classList?a.classList.remove(b):B(a,b)&&(a.className=za(Ma(a),function(a){return a!=b}).join(" "))}function Oa(a,b){B(a,b)?Na(a,b):C(a,b)};var D;a:{var Pa=q.navigator;if(Pa){var Qa=Pa.userAgent;if(Qa){D=Qa;break a}}D=""};function Ra(a){q.setTimeout(function(){throw a;},0)}var Sa;
function Ta(){var a=q.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=u(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},
this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==D.indexOf("Trident")&&-1==D.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.Ga;c.Ga=null;a()}};return function(a){d.next={Ga:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){q.setTimeout(a,0)}};function Ua(a,b){Va||Wa();Xa||(Va(),Xa=!0);Ya.push(new Za(a,b))}var Va;function Wa(){if(q.Promise&&q.Promise.resolve){var a=q.Promise.resolve();Va=function(){a.then($a)}}else Va=function(){var a=$a;!t(q.setImmediate)||q.Window&&q.Window.prototype.setImmediate==q.setImmediate?(Sa||(Sa=Ta()),Sa(a)):q.setImmediate(a)}}var Xa=!1,Ya=[];function $a(){for(;Ya.length;){var a=Ya;Ya=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.tb.call(c.scope)}catch(d){Ra(d)}}}Xa=!1}
function Za(a,b){this.tb=a;this.scope=b};var ab=-1!=D.indexOf("Opera")||-1!=D.indexOf("OPR"),E=-1!=D.indexOf("Trident")||-1!=D.indexOf("MSIE"),bb=-1!=D.indexOf("Gecko")&&!y(D,"WebKit")&&!(-1!=D.indexOf("Trident")||-1!=D.indexOf("MSIE")),cb=y(D,"WebKit");function db(){var a=q.document;return a?a.documentMode:void 0}
var eb=function(){var a="",b;if(ab&&q.opera)return a=q.opera.version,t(a)?a():a;bb?b=/rv\:([^\);]+)(\)|;)/:E?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:cb&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(D))?a[1]:"");return E&&(b=db(),b>parseFloat(a))?String(b):a}(),fb={};
function gb(a){if(!fb[a]){for(var b=0,c=va(String(eb)).split("."),d=va(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var n=k.exec(g)||["","",""],p=m.exec(h)||["","",""];if(0==n[0].length&&0==p[0].length)break;b=wa(0==n[1].length?0:parseInt(n[1],10),0==p[1].length?0:parseInt(p[1],10))||wa(0==n[2].length,0==p[2].length)||wa(n[2],p[2])}while(0==b)}fb[a]=0<=b}}
var hb=q.document,ib=hb&&E?db()||("CSS1Compat"==hb.compatMode?parseInt(eb,10):5):void 0;function F(a,b){this.j=G;this.t=void 0;this.g=this.m=null;this.X=this.ja=!1;try{var c=this;a.call(b,function(a){H(c,jb,a)},function(a){if(!(a instanceof I))try{if(a instanceof Error)throw a;throw Error("Promise rejected.");}catch(b){}H(c,J,a)})}catch(d){H(this,J,d)}}var G=0,jb=2,J=3;F.prototype.then=function(a,b,c){return kb(this,t(a)?a:null,t(b)?b:null,c)};pa(F);F.prototype.cancel=function(a){this.j==G&&Ua(function(){var b=new I(a);lb(this,b)},this)};
function lb(a,b){if(a.j==G)if(a.m){var c=a.m;if(c.g){for(var d=0,e=-1,f=0,g;g=c.g[f];f++)if(g=g.N)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.j==G&&1==d?lb(c,b):(d=c.g.splice(e,1)[0],mb(c,d,J,b)))}}else H(a,J,b)}function nb(a,b){a.g&&a.g.length||a.j!=jb&&a.j!=J||ob(a);a.g||(a.g=[]);a.g.push(b)}
function kb(a,b,c,d){var e={N:null,Ta:null,Ua:null};e.N=new F(function(a,g){e.Ta=b?function(c){try{var e=b.call(d,c);a(e)}catch(m){g(m)}}:a;e.Ua=c?function(b){try{var e=c.call(d,b);void 0===e&&b instanceof I?g(b):a(e)}catch(m){g(m)}}:g});e.N.m=a;nb(a,e);return e.N}F.prototype.ab=function(a){this.j=G;H(this,jb,a)};F.prototype.bb=function(a){this.j=G;H(this,J,a)};
function H(a,b,c){if(a.j==G){if(a==c)b=J,c=new TypeError("Promise cannot resolve to itself");else{if(qa(c)){a.j=1;c.then(a.ab,a.bb,a);return}if(da(c))try{var d=c.then;if(t(d)){pb(a,c,d);return}}catch(e){b=J,c=e}}a.t=c;a.j=b;ob(a);b!=J||c instanceof I||qb(a,c)}}function pb(a,b,c){function d(b){f||(f=!0,a.bb(b))}function e(b){f||(f=!0,a.ab(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function ob(a){a.ja||(a.ja=!0,Ua(a.sb,a))}
F.prototype.sb=function(){for(;this.g&&this.g.length;){var a=this.g;this.g=[];for(var b=0;b<a.length;b++)mb(this,a[b],this.j,this.t)}this.ja=!1};function mb(a,b,c,d){if(c==jb)b.Ta(d);else{if(b.N)for(;a&&a.X;a=a.m)a.X=!1;b.Ua(d)}}function qb(a,b){a.X=!0;Ua(function(){a.X&&rb.call(null,b)})}var rb=Ra;function I(a){x.call(this,a)}ha(I,x);I.prototype.name="cancel";var sb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function tb(a){if(ub){ub=!1;var b=q.location;if(b){var c=b.href;if(c&&(c=vb(c))&&c!=b.hostname)throw ub=!0,Error();}}return a.match(sb)}var ub=cb;function vb(a){return(a=tb(a)[3]||null)?decodeURI(a):a};function wb(a,b){var c;if(a instanceof wb)this.i=void 0!==b?b:a.i,xb(this,a.v),c=a.H,K(this),this.H=c,c=a.r,K(this),this.r=c,yb(this,a.K),c=a.p,K(this),this.p=c,zb(this,a.q.clone()),c=a.D,K(this),this.D=c;else if(a&&(c=tb(String(a)))){this.i=!!b;xb(this,c[1]||"",!0);var d=c[2]||"";K(this);this.H=L(d);d=c[3]||"";K(this);this.r=L(d,!0);yb(this,c[4]);d=c[5]||"";K(this);this.p=L(d,!0);zb(this,c[6]||"",!0);c=c[7]||"";K(this);this.D=L(c)}else this.i=!!b,this.q=new Ab(null,0,this.i)}l=wb.prototype;l.v="";
l.H="";l.r="";l.K=null;l.p="";l.D="";l.vb=!1;l.i=!1;l.toString=function(){var a=[],b=this.v;b&&a.push(Bb(b,Cb,!0),":");if(b=this.r){a.push("//");var c=this.H;c&&a.push(Bb(c,Cb,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.K;null!=b&&a.push(":",String(b))}if(b=this.p)this.r&&"/"!=b.charAt(0)&&a.push("/"),a.push(Bb(b,"/"==b.charAt(0)?Db:Eb,!0));(b=this.q.toString())&&a.push("?",b);(b=this.D)&&a.push("#",Bb(b,Fb));return a.join("")};
l.resolve=function(a){var b=this.clone(),c=!!a.v;c?xb(b,a.v):c=!!a.H;if(c){var d=a.H;K(b);b.H=d}else c=!!a.r;c?(d=a.r,K(b),b.r=d):c=null!=a.K;d=a.p;if(c)yb(b,a.K);else if(c=!!a.p){if("/"!=d.charAt(0))if(this.r&&!this.p)d="/"+d;else{var e=b.p.lastIndexOf("/");-1!=e&&(d=b.p.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var d=0==e.lastIndexOf("/",0),e=e.split("/"),f=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&f.push(""):".."==h?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?(K(b),b.p=d):c=""!==a.q.toString();c?zb(b,L(a.q.toString())):c=!!a.D;c&&(a=a.D,K(b),b.D=a);return b};l.clone=function(){return new wb(this)};function xb(a,b,c){K(a);a.v=c?L(b,!0):b;a.v&&(a.v=a.v.replace(/:$/,""))}function yb(a,b){K(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.K=b}else a.K=null}
function zb(a,b,c){K(a);b instanceof Ab?(a.q=b,a.q.wa(a.i)):(c||(b=Bb(b,Gb)),a.q=new Ab(b,0,a.i))}function Hb(a,b,c){K(a);"array"==ba(c)||(c=[String(c)]);Ib(a.q,b,c)}function K(a){if(a.vb)throw Error("Tried to modify a read-only Uri");}l.wa=function(a){this.i=a;this.q&&this.q.wa(a);return this};function L(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}function Bb(a,b,c){return r(a)?(a=encodeURI(a).replace(b,Jb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function Jb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Cb=/[#\/\?@]/g,Eb=/[\#\?:]/g,Db=/[\#\?]/g,Gb=/[\#\?@]/g,Fb=/#/g;function Ab(a,b,c){this.f=a||null;this.i=!!c}function M(a){if(!a.b&&(a.b=new Ha,a.c=0,a.f))for(var b=a.f.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=N(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}l=Ab.prototype;
l.b=null;l.c=null;l.add=function(a,b){M(this);this.f=null;a=N(this,a);var c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.c++;return this};l.remove=function(a){M(this);a=N(this,a);return this.b.O(a)?(this.f=null,this.c-=this.b.get(a).length,this.b.remove(a)):!1};l.clear=function(){this.b=this.f=null;this.c=0};l.O=function(a){M(this);a=N(this,a);return this.b.O(a)};l.F=function(){M(this);for(var a=this.b.s(),b=this.b.F(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
l.s=function(a){M(this);var b=[];if(r(a))this.O(a)&&(b=Ba(b,this.b.get(N(this,a))));else{a=this.b.s();for(var c=0;c<a.length;c++)b=Ba(b,a[c])}return b};l.set=function(a,b){M(this);this.f=null;a=N(this,a);this.O(a)&&(this.c-=this.b.get(a).length);this.b.set(a,[b]);this.c++;return this};l.get=function(a,b){var c=a?this.s(a):[];return 0<c.length?String(c[0]):b};function Ib(a,b,c){a.remove(b);0<c.length&&(a.f=null,a.b.set(N(a,b),Da(c)),a.c+=c.length)}
l.toString=function(){if(this.f)return this.f;if(!this.b)return"";for(var a=[],b=this.b.F(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.s(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.f=a.join("&")};l.clone=function(){var a=new Ab;a.f=this.f;this.b&&(a.b=this.b.clone(),a.c=this.c);return a};function N(a,b){var c=String(b);a.i&&(c=c.toLowerCase());return c}
l.wa=function(a){a&&!this.i&&(M(this),this.f=null,this.b.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),Ib(this,d,a))},this));this.i=a};l.extend=function(a){for(var b=0;b<arguments.length;b++)Ga(arguments[b],function(a,b){this.add(b,a)},this)};var Kb;if(!(Kb=!bb&&!E)){var Lb;if(Lb=E)Lb=E&&9<=ib;Kb=Lb}Kb||bb&&gb("1.9.1");E&&gb("9");function Mb(a,b){sa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Nb?a.setAttribute(Nb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Nb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Ob(a){return da(a)&&1==a.nodeType};function Pb(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}E&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Qb(a,b){var c;a:{c=9==b.nodeType?b:b.ownerDocument||b.document;if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(b,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}if("none"!=(c||(b.currentStyle?b.currentStyle.display:null)||b.style&&b.style.display))return a(b);c=b.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";var g=a(b);c.display=d;c.position=f;c.visibility=e;return g}
function Rb(a){var b=a.offsetWidth,c=a.offsetHeight,d=cb&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Pb(a),new ra(a.right-a.left,a.bottom-a.top)):new ra(b,c)}function Sb(a){if(!a.getBoundingClientRect)return null;a=Qb(Pb,a);return new ra(a.right-a.left,a.bottom-a.top)};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function O(a,b){this.ba=[];this.Sa=a;this.Ka=b||null;this.R=this.I=!1;this.t=void 0;this.xa=this.lb=this.ha=!1;this.da=0;this.m=null;this.ia=0}O.prototype.cancel=function(a){if(this.I)this.t instanceof O&&this.t.cancel();else{if(this.m){var b=this.m;delete this.m;a?b.cancel(a):(b.ia--,0>=b.ia&&b.cancel())}this.Sa?this.Sa.call(this.Ka,this):this.xa=!0;this.I||(a=new Tb,Ub(this),Vb(this,!1,a))}};O.prototype.Ia=function(a,b){this.ha=!1;Vb(this,a,b)};function Vb(a,b,c){a.I=!0;a.t=c;a.R=!b;Wb(a)}
function Ub(a){if(a.I){if(!a.xa)throw new Xb;a.xa=!1}}function Yb(a,b,c,d){a.ba.push([b,c,d]);a.I&&Wb(a)}O.prototype.then=function(a,b,c){var d,e,f=new F(function(a,b){d=a;e=b});Yb(this,d,function(a){a instanceof Tb?f.cancel():e(a)});return f.then(a,b,c)};pa(O);function Zb(a){return Aa(a.ba,function(a){return t(a[1])})}
function Wb(a){if(a.da&&a.I&&Zb(a)){var b=a.da,c=$b[b];c&&(q.clearTimeout(c.G),delete $b[b]);a.da=0}a.m&&(a.m.ia--,delete a.m);for(var b=a.t,d=c=!1;a.ba.length&&!a.ha;){var e=a.ba.shift(),f=e[0],g=e[1],e=e[2];if(f=a.R?g:f)try{var h=f.call(e||a.Ka,b);void 0!==h&&(a.R=a.R&&(h==b||h instanceof Error),a.t=b=h);qa(b)&&(d=!0,a.ha=!0)}catch(k){b=k,a.R=!0,Zb(a)||(c=!0)}}a.t=b;d&&(h=u(a.Ia,a,!0),d=u(a.Ia,a,!1),b instanceof O?(Yb(b,h,d),b.lb=!0):b.then(h,d));c&&(b=new ac(b),$b[b.G]=b,a.da=b.G)}
function Xb(){x.call(this)}ha(Xb,x);Xb.prototype.message="Deferred has already fired";Xb.prototype.name="AlreadyCalledError";function Tb(){x.call(this)}ha(Tb,x);Tb.prototype.message="Deferred was canceled";Tb.prototype.name="CanceledError";function ac(a){this.G=q.setTimeout(u(this.Cb,this),0);this.rb=a}ac.prototype.Cb=function(){delete $b[this.G];throw this.rb;};var $b={};function bc(a,b){var c=b||{},d=c.document||document,e=document.createElement("SCRIPT"),f={Ya:e,ca:void 0},g=new O(cc,f),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){dc(e,!0);var b=new ec(fc,"Timeout reached for loading script "+a);Ub(g);Vb(g,!1,b)},k),f.ca=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(dc(e,c.ob||!1,h),Ub(g),Vb(g,!0,null))};e.onerror=function(){dc(e,!0,h);var b=new ec(gc,"Error while loading script "+
a);Ub(g);Vb(g,!1,b)};Mb(e,{type:"text/javascript",charset:"UTF-8",src:a});hc(d).appendChild(e);return g}function hc(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}function cc(){if(this&&this.Ya){var a=this.Ya;a&&"SCRIPT"==a.tagName&&dc(a,!0,this.ca)}}function dc(a,b,c){null!=c&&q.clearTimeout(c);a.onload=aa;a.onerror=aa;a.onreadystatechange=aa;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var gc=0,fc=1;
function ec(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);x.call(this,c);this.code=a}ha(ec,x);function ic(a,b){this.Db=new wb(a);this.mb=b?b:"callback";this.ca=5E3}var jc=0;ic.prototype.send=function(a,b,c,d){a=a||null;d=d||"_"+(jc++).toString(36)+ga().toString(36);q._callbacks_||(q._callbacks_={});var e=this.Db.clone();if(a)for(var f in a)a.hasOwnProperty&&!a.hasOwnProperty(f)||Hb(e,f,a[f]);b&&(q._callbacks_[d]=kc(d,b),Hb(e,this.mb,"_callbacks_."+d));b=bc(e.toString(),{timeout:this.ca,ob:!0});Yb(b,null,lc(d,a,c),void 0);return{G:d,La:b}};
ic.prototype.cancel=function(a){a&&(a.La&&a.La.cancel(),a.G&&mc(a.G,!1))};function lc(a,b,c){return function(){mc(a,!1);c&&c(b)}}function kc(a,b){return function(c){mc(a,!0);b.apply(void 0,arguments)}}function mc(a,b){q._callbacks_[a]&&(b?delete q._callbacks_[a]:q._callbacks_[a]=aa)};function nc(){this.height=this.width=this.bottom=this.right=this.left=this.top=0}function oc(a,b){this.width=a;this.height=b}function P(a){var b=null;if(a&&"string"==typeof a){var c=a.indexOf("px");-1!=c&&(a=a.substring(0,c));c=a.length-1;a.length<=c?c=!1:(c=a.charCodeAt(c),c=48<=c&&57>=c);c&&(b=parseInt(a,10),isNaN(b)&&(b=null))}return b}function Q(a,b){var c=null;a&&(c=P(a.getPropertyValue(b)));return c}function R(a,b){a.style&&a.style.removeProperty(b);a.removeAttribute(b)}
function pc(a,b){var c=null;a.style&&(c=P(a.style.getPropertyValue(b)));null==c&&(c=P(a.getAttribute(b)));return c}function S(a,b,c){a.style.setProperty(b,c,"important")}function qc(a,b){if(b&&0!=b.length){var c=a.getAttribute("style")||"";0<c.length&&";"!=c[c.length-1]&&(c+=";");a.setAttribute("style",c+b)}}
function rc(a){a=a.getBoundingClientRect();var b=document.body,c=document.documentElement||b.parentNode||b,b="pageXOffset"in window?window.pageXOffset:c.scrollLeft,c="pageYOffset"in window?window.pageYOffset:c.scrollTop;return new Ea(a.top+c,a.right+b,a.bottom+c,a.left+b)}
function sc(a){var b=null;return"SCRIPT"!=a.tagName&&"STYLE"!=a.tagName&&a.style&&(a=window.getComputedStyle(a))&&(b=a.getPropertyValue("background-image"),"none"==b&&(b=null),b&&5<b.length&&0==b.indexOf("url(")&&")"==b[b.length-1])?b=b.substring(4,b.length-1):null}function tc(){if(null!=window.parent&&window!=window.parent)try{if(window.parent.document.domain==document.domain)return!0}catch(a){}return!1}function uc(a){var b=1;for(a=a.firstChild;a;a=a.nextSibling)b+=uc(a);return b}
function T(a){return Ob(a)?a:null}var vc={Fb:"IMG",Gb:"SVG",Eb:"background-image"};v("pagespeed.MobUtil.ImageSource",vc);function wc(a,b,c,d){this.qa=a;this.Ra=b;this.zb=c;this.yb=d}
function U(a){for(var b=0,c=a.length;b<c;++b){var d=Math.round(a[b]);0>d?d=0:255<d&&(d=255);a[b]=d}c=a[0];b=a[1];a=a[2];c=Number(c);b=Number(b);a=Number(a);if(isNaN(c)||0>c||255<c||isNaN(b)||0>b||255<b||isNaN(a)||0>a||255<a)throw Error('"('+c+","+b+","+a+'") is not a valid RGB color');c=Ja(c.toString(16));b=Ja(b.toString(16));a=Ja(a.toString(16));return"#"+c+b+a}function V(a){a=a.toLowerCase();for(var b="",c=0,d=a.length;c<d;++c){var e=a.charAt(c);if("a"<=e&&"z">=e||"0"<=e&&"9">=e)b+=e}return b}
function xc(a){a=rc(a);var b=new nc;b.top=a.top;b.bottom=a.bottom;b.left=a.left;b.right=a.right;b.height=a.bottom-a.top;b.width=a.right-a.left;return b}function yc(a){var b=P(a.top);a=P(a.left);return null!=b&&-100>b||null!=a&&-100>a}function zc(a){a=a.replace(/\\/g,"\\\\");a=a.replace(/"/g,'\\"');a=a.replace(/\n/g,"\\a ");a=a.replace(/\f/g,"\\c ");a=a.replace(/\r/g,"\\d ");return'"'+a+'"'}function W(a){console&&console.log&&console.log(a)};function Ac(){this.ta=0;this.W=this.pa=null}Ac.prototype.Ba=1E-10;Ac.prototype.fa=3;function Bc(a,b){this.background=a;this.Pa=b}function Cc(a,b){if(3!=a.length||3!=b.length)return Infinity;var c=a[0]-b[0],d=a[1]-b[1],e=a[2]-b[2];return Math.sqrt(c*c+d*d+e*e)}function X(a){a/=255;return a=.03928>=a?a/12.92:Math.pow((a+.055)/1.055,2.4)}
function Dc(a,b){var c=b.background,d=b.Pa,e=.2126*X(c[0])+.7152*X(c[1])+.0722*X(c[2]),f=.2126*X(d[0])+.7152*X(d[1])+.0722*X(d[2]);if(e<a.Ba&&f<a.Ba)return b;e=f/e;1>e&&(e=1/e);if(e>a.fa)return b;c=La(c[0],c[1],c[2]);d=La(d[0],d[1],d[2]);f=e=null;c[2]<d[2]?(e=c[2],f=d[2]):(e=d[2],f=c[2]);var g=(a.fa*e-f)/(a.fa+1),e=e>g?e-g:0,f=f<1-2*g?f+2*g:255;c[2]<d[2]?(c[2]=e,d[2]=f):(d[2]=e,c[2]=f);c=Ka(c[0],c[1],c[2]);d=Ka(d[0],d[1],d[2]);return new Bc(c,d)}
function Ec(a,b,c,d,e){var f=[],g,h,k;for(h=0;h<e;++h)for(g=0;g<d;++g){var m=4*(h*d+g);k=3*(h*d+g);var n=b[m+3]/255,p=1-n;f[k]=n*b[m]+p*c[0];f[k+1]=n*b[m+1]+p*c[1];f[k+2]=n*b[m+2]+p*c[2]}m=[0,0,0];for(g=n=h=0;g<d;++g)p=(e-1)*d+g,k=3*p,m[0]+=f[k],m[1]+=f[k+1],m[2]+=f[k+2],n+=b[4*p+3],++h;if(n>127.5*h)for(g=0;3>g;++g)m[g]=Math.floor(m[g]/h);else m=c;b=Math.floor(.25*d);c=Math.floor(.75*d);n=Math.floor(.25*e);e=Math.floor(.75*e);var p=0,w=[];for(h=n;h<=e;++h)for(g=b;g<=c;++g)k=3*(h*d+g),w[p]=Cc(f.slice(k,
k+3),m),++p;g=w.sort(function(a,b){return a-b});var jd=Math.max(1,g[Math.floor(.75*p)]),p=0,w=[0,0,0];for(h=n;h<=e;++h)for(g=b;g<=c;++g)k=3*(h*d+g),Cc(f.slice(k,k+3),m)>=jd&&(w[0]+=f[k],w[1]+=f[k+1],w[2]+=f[k+2],++p);if(0<p)for(g=0;3>g;++g)w[g]=Math.floor(w[g]/p);return Dc(a,new Bc(m,w))}
Ac.prototype.ya=function(){--this.ta;if(!(0<this.ta)){var a=[255,255,255],b=[0,0,0],c=this.pa;this.W&&this.W.data&&c&&c.n&&c.backgroundColor?(b=Ec(this,this.W.data,c.backgroundColor,c.n.width,c.n.height),a=b.background,b=b.Pa):c&&c.backgroundColor&&(a=c.backgroundColor,b=178.5<La(a[0],a[1],a[2])[2]?[0,0,0]:[255,255,255]);W("Theme color. Background: "+a+" foreground: "+b);this.Ma(this.pa,a,b)}};
function Fc(a,b,c){var d=new Image;d.onload=u(function(){var a=document.createElement("canvas"),b=null,g=null;c&&0<c.width&&0<c.height?(b=c.width,g=c.height):(b=d.naturalWidth,g=d.naturalHeight);a.width=b;a.height=g;a=a.getContext("2d");a.drawImage(d,0,0);this.W=a.getImageData(0,0,b,g);this.ya()},a);d.onerror=u(a.ya,a);d.src=b}
Ac.prototype.run=function(a,b){this.pa=a;this.Ma&&alert("A callback which was supposed to run after extracting theme color  was not executed.");this.Ma=b;var c;if(c=a)if(c=a.u)c=a.u,c=!(0!=c.lastIndexOf(document.location.origin+"/",0)&&0!=c.lastIndexOf("data:image/",0));c?(this.ta=1,Fc(this,a.u,a.n),W("Found logo. Theme color will be computed from logo.")):(a&&a.u?W("Found logo but its origin is different that of HTML. Use default color."):W("Could not find logo. Use default color."),this.ya())};function Y(a){this.U=a;this.Na={};if(a=document.documentElement.clientWidth)for(var b=window.getComputedStyle(document.body),c=["padding-left","padding-right"],d=0;d<c.length;++d){var e=Q(b,c[d]);e&&(a-=e)}else a=400;this.l=a;W("window.pagespeed.MobLayout.maxWidth="+this.l)}
var Gc="padding-left padding-bottom padding-right padding-top margin-left margin-bottom margin-right margin-top border-left-width border-bottom-width border-right-width border-top-width left top".split(" "),Hc={A:!0,DIV:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,P:!0,SPAN:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0},Ic=["left","width"];
function Jc(a,b){if(!b)return!0;var c=b.tagName.toUpperCase();return"SCRIPT"==c||"STYLE"==c||"IFRAME"==c||b.id&&a.Na[b.id]||b.classList.contains("psmob-nav-panel")||b.classList.contains("psmob-header-bar")||b.classList.contains("psmob-header-spacer-div")||b.classList.contains("psmob-logo-span")}function Kc(a,b){var c=T(b);return Jc(a,c)?null:c}function Lc(a){var b=[];for(a=a.firstChild;a;a=a.nextSibling)null!=T(a)&&b.push(a);return b}
function Mc(a,b,c){for(b=b.firstChild;b;b=b.nextSibling)null!=Kc(a,b)&&c.call(a,b)}l=Y.prototype;
l.Za=function(a){var b=window.getComputedStyle(a),c=sc(a);if(c){var c=Nc(this.U,c),d;if(d=c&&c.width&&c.height)"auto"==b.getPropertyValue("background-size")?d=!1:(d=b.getPropertyValue("background-position"),"none"==d?d=!1:(d=d.split(" "),d=2==d.length&&null!=P(d[0])&&null!=P(d[1])?!0:!1)),d=!d;if(d){d=c.width;c=c.height;if(d>this.l){c=Math.round(this.l/d*c);d="background-size:"+this.l+"px "+c+"px;background-repeat:no-repeat;";var e=Q(b,"height");c==e&&(d+="height:"+c+"px;");qc(a,d)}S(a,"min-height",
""+c+"px")}}if("PRE"==a.tagName.toUpperCase()||"pre"==b.getPropertyValue("white-space")&&a.offsetWidth>this.l)a.style.overflowX="scroll";Mc(this,a,this.Za)};function Oc(a){S(a,"overflow-x","auto");S(a,"width","auto");S(a,"display","block")}l.Ab=function(a){Pc(this,a,0)};
function Pc(a,b,c){var d;if(d=rc(b))c=d.top,d=d.bottom;else{if(b.offsetParent==b.parentNode)c+=b.offsetTop;else if(b.offsetParent!=b.parentNode.parentNode)return null;d=c+b.offsetHeight-1}if(Jc(a,b))return d;d=c-1;var e=window.getComputedStyle(b);if(!e)return null;var f=Q(e,"min-height");null!=f&&(d+=f);for(var f=c+b.offsetHeight-1,g=!1,h=!1,k,m=b.firstChild;m;m=m.nextSibling)if(k=T(m)){var n=window.getComputedStyle(k);n&&("absolute"!=n.position||yc(n)||"0px"==n.getPropertyValue("height")||"hidden"==
n.getPropertyValue("visibility")||(h=!0));k=Pc(a,k,c);null!=k&&(g=!0,d=Math.max(d,k))}if("fixed"==e.getPropertyValue("position")&&g)return null;a=b.tagName.toUpperCase();"BODY"!=a&&(e=f-c+1,g?d!=f&&(h?S(b,"height",""+(d-c+1)+"px"):S(b,"height","auto")):("IMG"!=a&&0<e&&""==b.style.backgroundSize&&(R(b,"height"),S(b,"height","auto"),b.offsetHeight&&(f=c+b.offsetHeight)),d=f));return d}
l.Xa=function(a){for(var b=Lc(a),c=0;c<b.length;++c)this.Xa(b[c]);if(!(a.offsetWidth<=this.l))if(b=a.tagName.toUpperCase(),"TABLE"==b){a:{b=0;for(c=a.firstChild;c;c=c.nextSibling)for(var d=c.firstChild;d;d=d.nextSibling){var e=c.tagName.toUpperCase();if("THEAD"==e||"TFOOT"==e){b=!0;break a}for(e=d.firstChild;e;e=e.nextSibling){if(e.tagName&&"TH"==e.tagName.toUpperCase()){b=!0;break a}++b}}b=3*Qc(this,a)>b?!1:!0}if(b)Oc(a);else if("CSS1Compat"!==document.compatMode){var f,g,h,k=document.createElement("DIV");
k.style.display="inline-block";for(var m=Lc(a),b=0;b<m.length;++b)for(var n=Lc(m[b]),c=0;c<n.length;++c)for(var p=Lc(n[c]),d=0;d<p.length;++d)if(g=p[d],1==g.childNodes.length)f=g.childNodes[0],g.removeChild(f),k.appendChild(f);else if(1<g.childNodes.length){h=document.createElement("DIV");h.style.display="inline-block";for(var w=Lc(g),e=0;e<w.length;++e)f=w[e],g.removeChild(f),h.appendChild(f);k.appendChild(h)}a.parentNode.replaceChild(k,a)}else for(R(a,"width"),S(a,"max-width","100%"),a=a.firstChild;a;a=
a.nextSibling)if(b=T(a),null!=b)for(R(b,"width"),S(b,"max-width","100%"),b=b.firstChild;b;b=b.nextSibling)if(c=T(b),null!=c&&"TR"==c.tagName.toUpperCase())for(R(c,"width"),S(c,"max-width","100%"),c=c.firstChild;c;c=c.nextSibling)d=T(c),null!=d&&"TD"==d.tagName.toUpperCase()&&(S(d,"max-width","100%"),S(d,"display","inline-block"))}else{c=null;d=a.offsetWidth;e=a.offsetHeight;f="img";if("IMG"==b)c=a.getAttribute("src");else if(f="background-image",c=sc(a),g=null==c?null:Nc(this.U,c))d=g.width,e=g.height;
null!=c?(g=d/this.l,1<g&&(g=e/g,W("Shrinking "+f+" "+c+" from "+d+"x"+e+" to "+this.l+"x"+g),"IMG"==b?(S(a,"width",""+this.l+"px"),S(a,"height",""+g+"px")):S(a,"background-size",""+this.l+"px "+g+"px"))):"CODE"==b||"PRE"==b||"UL"==b?Oc(a):Hc[b]?(S(a,"max-width","100%"),R(a,"width")):W("Punting on resize of "+b+" which wants to be "+a.offsetWidth+" but this.maxWidth_="+this.l)}};
function Qc(a,b){var c=0,d=b.tagName.toUpperCase();"DIV"!=d&&"TABLE"!=d&&"UL"!=d||++c;for(d=b.firstChild;d;d=d.nextSibling){var e=T(d);null!=e&&(c+=Qc(a,e))}return c}l.nb=function(a){var b=document.body.style.display;document.body.style.display="none";this.Ha(a);document.body.style.display=b};
l.Ha=function(a){var b=window.getComputedStyle(a);"nowrap"==b.getPropertyValue("white-space")&&S(a,"white-space","normal");Mc(this,a,this.Ha);var b=window.getComputedStyle(a),c,d,e;for(c=0;c<Ic.length;++c)d=Ic[c],(e=b.getPropertyValue(d))&&"100%"!=e&&"auto"!=e&&0<e.length&&"%"==e[e.length-1]&&S(a,d,"auto");c=a.tagName.toUpperCase();var f="UL"==c||"OL"==c,g="BODY"==c,h=!1,k="";for(c=0;c<Gc.length;++c){d=Gc[c];if(e=f)e=d.length-5,e=0<=e&&d.indexOf("-left",e)==e;e||g&&0==d.lastIndexOf("margin-",0)||
(e=Q(b,d),null!=e&&(4<e?k+=d+":4px !important;":0>e&&(h=!0,"margin-bottom"==d&&(h=-30<e),h?k+=d+":0px !important;":a.setAttribute("data-pagespeed-negative-bottom-margin","1"))))}qc(a,k)};
l.Wa=function(a){Mc(this,a,this.Wa);if("IMG"==a.tagName.toUpperCase()){var b=window.getComputedStyle(a),c=pc(a,"width"),d=pc(a,"height");if(c&&d&&b){var e=Q(b,"width"),b=Q(b,"height");if(e&&b&&(e/=c,b/=d,.95<(e>b?b/e:e/b)||(W("aspect ratio problem for "+a.getAttribute("src")),1==a.naturalHeight&&1==a.naturalWidth?(b=Math.min(e,b),R(a,"width"),R(a,"height"),a.style.width=c*b,a.style.height=d*b):e>b?R(a,"height"):(R(a,"width"),R(a,"height"),a.style.maxHeight=d)),.25>e)){for(W("overshrinkage for "+a.getAttribute("src"));a&&
a.tagName&&"TD"!=a.tagName.toUpperCase();)a=a.parentNode;if(a&&(c=a.parentNode)){d=0;for(a=c.firstChild;a;a=a.nextSibling)a.tagName&&"TD"==a.tagName.toUpperCase()&&++d;if(1<d)for(d="width:"+Math.round(100/d)+"%;",c=c.firstChild;c;c=c.nextSibling)a=T(c),null!=a&&"TD"==a.tagName.toUpperCase()&&qc(a,d)}}}}};
l.$a=function(a){var b=window.getComputedStyle(a).getPropertyValue("position");if("fixed"==b)return"fixed";if(a.classList.contains("nivoSlider"))return b;var c,d,e,f,g=[];c=null;var h,k=!1;for(d=a.firstChild;d;d=d.nextSibling)if(e=Kc(this,d),null!=e){var m=window.getComputedStyle(e);f=this.$a(e);if("fixed"!=f&&null!=m&&null!=Kc(this,e)){"absolute"!=f||yc(m)||S(e,"position","relative");f=m.getPropertyValue("float");var n="right"==f;h="inline-block";if(n||"left"==f)n&&"right"==m.getPropertyValue("clear")&&
(n=!1,h="block",c&&k&&S(c,"margin-bottom","0px")),S(e,"float","none"),"none"!=m.getPropertyValue("display")&&S(e,"display",h);n&&g.push(e);c=e;e=Q(m,"margin-bottom");k=null!=e&&0>e}}for(c=g.length-1;0<=c;--c)d=g[c],a.removeChild(d);for(c=g.length-1;0<=c;--c)d=g[c],a.appendChild(d);return b};
l.Oa=function(a){if("fixed"!=window.getComputedStyle(a).getPropertyValue("position")){var b,c,d,e=[],f=[];for(c=a.firstChild;c;c=c.nextSibling)if(d=Kc(this,c),null!=d){b=window.getComputedStyle(d);var g=b.getPropertyValue("position");"fixed"!=g&&"absolute"!=g&&0!=c.offsetWidth&&(e.push(d),f.push(b))}var h=null;for(c=0;c<e.length;++c)d=e[c],b=c<e.length-1?e[c+1]:null,g=d.offsetLeft+d.offsetWidth,(null==h||d.offsetLeft<h)&&(null==b||b.offsetLeft<g)&&(b=d,h=b.tagName.toUpperCase(),"INPUT"!=h&&"SELECT"!=
h&&(""==b.style.backgroundSize&&"auto"!=f[c].width&&S(b,"width","auto"),"IMG"!=h&&b.removeAttribute("width"),R(b,"border-left"),R(b,"border-right"),R(b,"margin-left"),R(b,"margin-right"),R(b,"padding-left"),R(b,"padding-right"),b.className=""!=b.className?b.className+" psSingleColumn":"psSingleColumn"),this.Oa(d)),a.getAttribute("data-pagespeed-negative-bottom-margin")&&(a.removeAttribute("data-pagespeed-negative-bottom-margin"),b=window.getComputedStyle(a),d=Q(b,"height"),null!=d&&S(a,"margin-bottom",
""+-d+"px")),h=g}};var Rc=[Y.prototype.Za,"shrink wide elements",Y.prototype.$a,"string floats",Y.prototype.nb,"cleanup styles",Y.prototype.Wa,"repair distored images",Y.prototype.Xa,"resize if too wide",Y.prototype.Oa,"expand columns",Y.prototype.Ab,"resize vertically"];function Sc(a){this.U=a;this.Fa=[]}function Tc(){this.T=-1;this.Q=this.xb=null;this.u="";this.backgroundColor=this.kb=this.ib=this.n=this.la=null}l=Sc.prototype;l.Ea=20;l.Da=10;l.ea=400;l.gb=400;l.Ca=6E3;l.hb=.5;
function Uc(a,b,c,d){var e=xc(b),f="hidden"!=Vc(b),g=e.width*e.height,h=e.width>a.Ea&&e.height>a.Da&&g>a.gb&&e.top<a.Ca&&e.height<a.ea;if(f&&h&&g>=c){var g=f=null,k;for(k in vc){f=b;g=vc[k];h=null;switch(g){case "IMG":f.tagName==g&&(h=f.src);break;case "SVG":f.tagName==g&&(f=(new XMLSerializer).serializeToString(f),h=(self.URL||self.webkitURL||self).createObjectURL(new Blob([f],{type:"image/svg+xml;charset=utf-8"})));break;case "background-image":h=sc(f)}if(h){var f=h,g=document.location.origin,m=
vb(g),h=vb(f);if(null!=m&&null!=h){var n=!1;if(m==h)n=!0;else if(0<=m.indexOf(h)){var m=m.split("."),p=m.length;3<=p&&(h==m.slice(0,p-2).join(".")||"www"==m[0]&&(h==m.slice(1,p-2).join(".")||h==m.slice(1,p).join(".")))&&(n=!0)}f=n?g+f.substring(f.indexOf(h)+h.length):f}}else f=null;if(g=f)if(f=vc[k],h=!0,"IMG"==f&&((n=Nc(a.U,b.src))?(e.width=n.width,e.height=n.height):b.naturalWidth?(e.width=b.naturalWidth,e.height=b.naturalHeight):e.width&&e.height||(W("Image "+b.src+" may be the logo. It has not been loaded so may be missed."),
h=!1),h&&(e.width<=a.Ea||e.height<=a.Da||e.height>=a.ea)&&(h=!1)),h)return a=new Tc,a.u=g,a.Q=b,a.la=f,a.n=e,a}}if(d)for(b=b.firstChild;b;b=b.nextSibling){if(e=T(b),null!=e&&(e=Uc(a,e,c,d)))return e}else if(b.parentNode&&(b=T(b.parentNode),null!=b))return Uc(a,b,c,d);return null}
function Wc(a,b,c){var d;a:{var e=xc(b);d="hidden"!=Vc(b);if(e.top<a.Ca&&e.height<a.ea&&d){d=0;b.title&&(d+=y(b.title,"logo"));b.id&&(d+=y(b.id,"logo"));b.className&&(d+=y(b.className,"logo"));b.alt&&(d+=y(b.alt,"logo"));var f;f=document.domain.toLowerCase().split(".");var g=f.length;f=4<g&&2==f[g-3].length?f[g-5]:3<g?f[g-4]:null;g=0;f&&(b.id&&(d+=y(b.id,f)),b.className&&(d+=y(b.className,f)),b.title&&(g+=0<=V(b.title).indexOf(V(f))?1:0),b.alt&&(g+=0<=V(b.alt).indexOf(V(f))?1:0));var h=e.width*e.height,
k=h*a.hb,e=0;b.href&&b.href==window.location.origin+window.location.pathname&&++e;(k=Uc(a,b,k,!0))||(k=Uc(a,b,h,!1));if(k){h=k.u;if(!h||0<=h.indexOf("data:image/"))h="";else{var m=h.lastIndexOf("/");0>m?m=0:++m;var n=h.indexOf(".",m);0>n&&(n=h.length);h=h.substring(m,n)}b:{if(m=h)if(m=m.toLowerCase(),0<=m.indexOf("logo")&&0>m.indexOf("logout")&&0>m.indexOf("no_logo")&&0>m.indexOf("no-logo")){m=1;break b}m=0}h&&f&&(g+=0<=V(h).indexOf(V(f))?1:0);d=d+m+g+e;if(0<d){k.T=d;k.xb=b;d=k;break a}}}d=null}d&&
(a.Fa.push(d),++c);for(b=b.firstChild;b;b=b.nextSibling)d=T(b),null!=d&&Wc(a,d,c)}
function Xc(a){var b=null,c=a.Fa;if(!c||0==c.length)return null;if(1==c.length)return b=c[0];var d=0,e=Infinity,f;for(a=0;b=c[a];++a)f=b.n,e=Math.min(e,f.top),d=Math.max(d,f.bottom);for(a=0;b=c[a];++a)f=b.n,b.T*=Math.sqrt((d-f.top)/(d-e));for(a=f=0;b=c[a];++a)f=Math.max(f,b.T);d=[];for(a=0;b=c[a];++a)b.T==f&&d.push(b);if(1==d.length)return b=d[0];c=d[0];e=c.n;for(a=1;b=d[a];++a)if(f=b.n,e.top>f.top||e.top==f.top&&e.left>f.left||e.top==f.top&&e.left==f.left&&e.width*e.height>f.width*f.height)c=b,e=
c.n;return c}function Yc(a){if(a=document.defaultView.getComputedStyle(a,null)){var b=a.getPropertyValue("background-color");if(b){a:{a=b.indexOf("(");var c=b.lastIndexOf(")");if(a=0<=a&&c>a?b.substring(a+1,c):null){a=a.split(",");for(var b=[],c=0,d=a.length;c<d;++c)if(b[c]=3!=c?parseInt(a[c],10):parseFloat(a[c]),isNaN(b[c])){a=null;break a}a=3==b.length||4==b.length?b:null}else a="transparent"==b?[0,0,0,0]:null}if(a&&(3==a.length||4==a.length&&0!=a[3]))return a}}return null}
l.run=function(){if(!document.body)return null;Wc(this,document.body,0);var a;if((a=Xc(this))&&a.Q){var b=a.Q,c=Yc(b),d=null;for(b.parentNode&&(d=T(b.parentNode));d&&!c;)b=d,c=Yc(b),d=b.parentNode?T(b.parentNode):null;a.ib=b;a.backgroundColor=c||[255,255,255];a.kb=xc(b)}else a=null;return a};v("pagespeed.MobLogo.prototype.run",Sc.prototype.run);function Zc(){this.sa=[];this.cb=!0;this.L=this.a=this.B=this.$=this.Z=this.M=this.d=null;this.na=this.V=0;this.ma=this.Y=!1;this.ka=[];this.va=!1}Zc.prototype.eb="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAQAAABNTyozAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwAACxMBAJqcGAAAATdJREFUeNrt0klOBTEQREHfDI7FTEn/4M2GBULQo22wK+ICKT1lKQAAAAAAAAAAAAAAAAAA/Jm7rmv3o+W5laU8d1uLspQYLc/SLVF8rsVoefokii9rMVqe9oni21qMlqdtovhhLUbL0y5R/LIWo+VZylKeuuX5t4nW8tRPFBtrMV6gmolic+t9xA/VSjRonl6JBs7TI9HgeVonmiDPvkSPmfO0SjRRnhaJJstTO9GEeWom2s7zVgZVI9HEeWokmjzPvkQPmfNcSZQkz9lEifKcSZQsz9FECfMcSZQ0z95E23ley8S2E6XOcz3R9HmuJUqR53yiNHnOJUqV53iidHmOJUqZZ3+itHn2JXopyd3kOZ9IntVE8qwmkmc1kTyrieRZTSTPaiJ5AAAAAAAAAAAAAAAAAGjgA62rM0XB6dNxAAAAAElFTkSuQmCC";
Zc.prototype.fb="R0lGODlhgACAAPAAAAAAAAAAACH5BAEAAAEALAAAAACAAIAAAAL+jI+pCL0Po5y02vuaBrj7D4bMtonmiXrkyqXuC7MsTNefLNv6nuE4D9z5fMFibEg0KkVI5PLZaTah1IlUWs0qrletl9v1VsFcMZQMNivRZHWRnXbz4G25jY621/B1vYuf54cCyCZ4QlhoGIIYqKjC2Oh4AZkoaUEZaWmF2acpwZnpuQAaKjpCWmbag5qqmsAa53oK6yT7SjtkO4r7o7vLS+K7Cuwg/EtsDIGcrMzLHOH8DM0qvUlabY2JXaG9zc3ojYEYLk5IXs53Pgmovo7XfskOTyE//1lv3/yeP53Or0/nH8CAAo/BKTjsIMJb/hYewOcwAMSF5iIamEixYcTMihY5bsRY0GNGkP9Ejtx3poUbk0GCrSR5Z8VLmDRyqBnXMokYnEJq7WT5J8wXni86ZQF3JJYWpCkILiXKBOUYpouAGqEU1eobSCCwHvXqDmxKrmHFPuH07drUbv3UUgHVFtVXuFuijVVLrNjbvLTm8pW79q/bu4LZ7i2M1i9isoEXQz3smObVyBqHUlZ483Kpn5qxCOrs+TNonYZG27RkuoSo1HpXj7YFWtjlZJGlId72l9wy3bjmweI3OJ/hkFqBO7U4KzTyuDKXaykAADs=";
function $c(a,b){if(!Ob(b))return!1;if("IMG"===b.tagName)return!a||null!==b.offsetParent;var c=b.getElementsByTagName("IMG");if(a){for(var d=c.length-1;0<=d;d--)if(null!==c[d].offsetParent)return!0;return!1}return 0<c.length}
function ad(a){var b=a.parentNode;if(!b||0<b.getElementsByTagName("SCRIPT").length)return!1;for(var c=null!==a.offsetParent,d=!1,e=0,b=b.firstChild;b;b=b.nextSibling)if(b==a)d=!0;else if(null!==b.offsetParent||!c)if(3==b.nodeType||1==b.nodeType){if($c(c,b))return!1;var f=va(b.textContent).length;if(0<f){if(d)return!1;e+=f;if(60<e)return!1}}return!0}
function bd(a){var b="scale("+window.innerWidth/document.documentElement.clientWidth+")";a.d.style["-webkit-transform"]=b;a.d.style.transform=b;Na(a.d,"hide");b=a.d.offsetHeight+"px";a.$.style.width=b;a.B&&(a.B.style.width=b);a.Z.style.left=b;a.Z.style.right=b;var b=Math.round(Sb(a.d).height),c=Qb(Rb,a.M).height;a.M.style.height=b+"px";for(var d=0;d<a.ka.length;d++){var e=a.ka[d];if(a.va){var f=e.style.top,f=Number(e.style.top.split("px")[0]);e.style.top=String(f+(b-c))+"px"}else f=rc(e).top,e.style.top=
String(f+b)+"px"}a.va&&b!=c&&(a.ma=!0,window.scrollBy(0,b-c));a.d.style.top=window.scrollY+"px";a.d.style.left=window.scrollX+"px";a.va=!0}function cd(a){if(a.a){a.a.style.top=window.scrollY+"px";a.a.style.left=window.scrollX+"px";var b=.8*window.innerWidth/250,c=B(a.a,"open")?0:-250*b,c="scale("+b+") translatex("+c+"px)";a.a.style["-webkit-transform"]=c;a.a.style.transform=c;c=a.d.getBoundingClientRect();a.a.style.marginTop=c.height+"px";a.a.style.height=(window.innerHeight-c.height)/b+"px"}}
function dd(a){bd(a);cd(a);window.addEventListener("scroll",u(function(a){this.ma?this.ma=!1:(null!=this.L&&(window.clearTimeout(this.L),this.L=null),this.L=window.setTimeout(u(function(){0==this.V&&(cd(this),bd(this));this.L=null},this),50),B(this.a,"open")&&!this.a.contains(a.target)&&(a.stopPropagation(),a.preventDefault()))},a),!1);window.addEventListener("touchstart",u(function(a){this.V=a.targetTouches.length;this.na=a.touches[0].clientY},a),!1);window.addEventListener("touchmove",u(function(a){this.Y?
a.preventDefault():C(this.d,"hide")},a),!1);window.addEventListener("touchend",u(function(a){this.V=a.targetTouches.length;null==this.L&&0==this.V&&(cd(this),bd(this))},a),!1)}function ed(){if(window.psStaticJs||!window.psConversionLabel)return window.psPhoneNumber;var a=document.cookie.match(/(^|;| )gwcm=([^;]+)/);return a&&a[2]&&(a=ia(unescape(a[2])),a.fallback==window.psPhoneNumber&&a.clabel==window.psConversionLabel)?a.mobile_number:null}
v("psRequestDynamicPhoneNumberAndCall",function(){if(window.psConversionLabel&&window.psPhoneNumber){var a="https://www.googleadservices.com/pagead/conversion/"+window.psConversionId+"/wcm?cl="+escape(window.psConversionLabel)+"&fb="+escape(window.psPhoneNumber);window.psDebugMode&&alert("requesting dynamic phone number: "+a);(new ic(a,"callback")).send(null,fd,function(){window.psDebugMode&&alert("error callback called");window.psPhoneNumber&&gd(window.psPhoneNumber)})}});
function gd(a){location.href="tel:"+a}v("psDialPhone",gd);
function fd(a){var b=null;if(a&&a.wcm){var c=a.wcm;c&&(b=c.mobile_number)}b?(a={expires:c.expires,formatted_number:c.formatted_number,mobile_number:b,clabel:window.psConversionLabel,fallback:window.psPhoneNumber},a=ja(a),window.psDebugMode&&alert("saving phone in cookie: "+a),document.cookie="gwcm="+escape(a)+";path=/;max-age=7776000",gd(b),document.getElementById("psmob-phone-dialer").href='javascript:psDialPhone("'+b+'")'):window.psPhoneNumber&&(window.psDebugMode&&alert("receivePhoneNumber: "+
ja(a)),gd(window.psPhoneNumber))}function hd(a,b,c){var d=[];for(b=b.firstChild;b;b=b.nextSibling)"UL"==b.tagName?d=Ca(d,hd(a,b,c+1)):("A"==b.tagName&&(b.setAttribute("data-mobilize-nav-level",c),d.push(b)),d=Ca(d,hd(a,b,c)));return d}
function id(a){var b=a.a.getElementsByTagName("a"),c={};a=[];for(var d=0,e;e=b[d];d++)if(e.href in c){var f=e.innerHTML.toLowerCase();-1==c[e.href].indexOf(f)?c[e.href].push(f):"LI"==e.parentNode.tagName&&a.push(e.parentNode)}else c[e.href]=[],c[e.href].push(e.innerHTML.toLowerCase());for(d=0;b=a[d];d++)b.parentNode.removeChild(b)}
function kd(a){for(var b=a.a.querySelectorAll("*"),c=[],d=0,e;e=b[d];d++)e.removeAttribute("style"),e.removeAttribute("width"),e.removeAttribute("height"),"A"==e.tagName&&(""==e.textContent&&e.hasAttribute("title")&&e.appendChild(document.createTextNode(e.getAttribute("title"))),""==e.href&&c.push(e));for(d=0;e=c[d];d++)e.parentNode.removeChild(e);a=a.a.querySelectorAll("img:not(.psmob-menu-expand-icon)");for(d=0;b=a[d];++d)c=Math.min(2*b.naturalHeight,40),b.setAttribute("height",c)}
function ld(a){a.a=document.createElement("nav");document.body.insertBefore(a.a,a.d.nextSibling);C(a.a,"psmob-nav-panel");var b=document.createElement("ul");a.a.appendChild(b);C(b,"open");for(var c=0,d;d=a.sa[c];c++)if(d.parentNode){d.setAttribute("data-mobilize-nav-section",c);var e=hd(a,d,0),f=[];f.push(b);for(var g=0,h=e.length;g<h;g++){var k=e[g].getAttribute("data-mobilize-nav-level"),m=g+1==h?k:e[g+1].getAttribute("data-mobilize-nav-level");if(k<m){var n=document.createElement("li"),k=n.appendChild(document.createElement("div")),
m=document.createElement("img");k.appendChild(document.createElement("img"));m.setAttribute("src",a.eb);C(m,"psmob-menu-expand-icon");k.appendChild(document.createTextNode(e[g].textContent||e[g].innerText));f[f.length-1].appendChild(n);k=document.createElement("ul");n.appendChild(k);f.push(k)}else for(n=document.createElement("li"),f[f.length-1].appendChild(n),n.appendChild(e[g].cloneNode(!0)),n=k-m;0<n&&1<f.length;)f.pop(),n--}window.psLayoutMode&&d.parentNode.removeChild(d)}id(a);kd(a);a.a.addEventListener("touchmove",
u(function(a){if(this.Y){var b=a.touches[0].clientY;if(1!=a.targetTouches.length)a.preventDefault();else{var c=b>this.na,d=0==this.a.scrollTop,e=this.a.scrollTop>=this.a.scrollHeight-this.a.offsetHeight-1;(c&&d||!c&&e)&&a.preventDefault();a.stopImmediatePropagation();this.na=b}}},a),!1);cd(a)}function md(a){Oa(a.d,"open");Oa(a.a,"open");Oa(document.body,"noscroll");a.Y=!a.Y;cd(a)}
function nd(a){document.body.addEventListener("click",function(a){this.$.contains(a.target)?md(this):B(this.a,"open")&&!this.a.contains(a.target)&&(md(this),a.stopPropagation(),a.preventDefault())}.bind(a),!0)}function od(){document.querySelector("nav.psmob-nav-panel > ul").addEventListener("click",function(a){a=Ob(a.target)&&B(a.target,"psmob-menu-expand-icon")?a.target.parentNode:a.target;"DIV"==a.tagName&&(Oa(a.nextSibling,"open"),Oa(a.firstChild,"open"))},!1)};function pd(){this.Qa=null}
pd.prototype.pb=function(a,b,c){var d=document.createElement("span");d.id="psmob-logo-span";if(a&&a.u){var e=document.createElement("IMG");e.src=a.u;e.style.backgroundColor=U(b);e.id="psmob-logo-image";d.appendChild(e)}else d.textContent=window.location.host,d.style.color=U(c);e=document.createElement("button");C(e,"psmob-menu-button");var f=document.createElement("div");C(f,"psmob-hamburger-div");e.appendChild(f);for(var g=U(c),h=0;3>h;++h){var k=document.createElement("div");C(k,"psmob-hamburger-line");
k.style.backgroundColor=g;f.appendChild(k)}b=new wc(c,b,e,d);if(window.psLayoutMode&&a&&a.Q&&a.la)switch(c=a.Q,a.la){case "IMG":case "SVG":c.parentNode.removeChild(c);break;case "background-image":c.style.backgroundImage="none"}this.qb(b)};function Z(){this.ga=0;this.S={};this.Bb=Date.now();this.Ja=!1;this.J=this.za=this.Va=this.k=this.C=0;this.ra=!1;this.Aa=this.ua=0;this.oa=new Y(this);this.oa.Na["ps-progress-scrim"]=!0}var qd=new oc(-1,-1);function rd(a){if(0==a.J)if(W("mobilizing site"),window.psNavMode&&!tc()){++a.ua;var b=a.wb.bind(a);b||alert("Not expecting to start onloads after the callback is called");var c=new pd;c.qb=b;c.Qa=(new Sc(a)).run();(new Ac).run(c.Qa,u(c.pb,c))}else sd(a);else a.ra=!0}
Z.prototype.wb=function(a){--this.ua;td(this,this.C,"extract theme");var b=new Zc;W("Starting nav resynthesis.");var c=[];if(window.pagespeedNavigationalIds)for(var d=window.pagespeedNavigationalIds.length,e={},f=0;f<d;f++){var g=window.pagespeedNavigationalIds[f],g=document.getElementById(g)||document.querySelector("[id="+zc(g)+"]"),h=g.parentNode;h?(h.id||(g.id.match(/^PageSpeed-.*-[0-9]+$/)?h.id=g.id.replace(/-[0-9]+$/,""):h.id="PageSpeed-"+g.id+"-P"),h.id in e?e[h.id]||c.push(g):(e[h.id]=ad(g),
c.push(e[h.id]?h:g))):c.push(g)}b.sa=c;c=document.getElementsByTagName("*");for(d=0;e=c[d];d++)f=window.getComputedStyle(e),"fixed"==f.getPropertyValue("position")&&"ps-progress-scrim"!=e.id&&b.ka.push(e),999999<=f.getPropertyValue("z-index")&&(W("Element z-index exceeded 999999, setting to 999998."),e.style.zIndex=999998);b.M=document.createElement("div");document.body.insertBefore(b.M,document.body.childNodes[0]);C(b.M,"psmob-header-spacer-div");b.d=document.createElement("header");document.body.insertBefore(b.d,
b.M);C(b.d,"psmob-header-bar");b.$=a.zb;b.d.appendChild(b.$);b.Z=a.yb;b.d.appendChild(b.Z);b.d.style.borderBottom="thin solid "+U(a.qa);b.d.style.backgroundColor=U(a.Ra);window.psPhoneNumber&&(d=a.qa,c=document.createElement("img"),c.id="psmob-phone-image",e=window.atob(b.fb),c.src="data:image/gif;base64,"+window.btoa(e.substring(0,13)+String.fromCharCode(d[0],d[1],d[2])+e.substring(16,e.length)),b.B=document.createElement("a"),b.B.id="psmob-phone-dialer",d=ed(),b.B.href=d?'javascript:psDialPhone("'+
d+'")':"javascript:psRequestDynamicPhoneNumberAndCall()",b.B.appendChild(c),b.d.appendChild(b.B));dd(b);c=b.cb?U(a.Ra):"#3c78d8";a=b.cb?U(a.qa):"white";d=document.createElement("style");d.type="text/css";d.appendChild(document.createTextNode(".psmob-header-bar { background-color: "+c+"; }\n.psmob-nav-panel { background-color: "+a+"; }\n.psmob-nav-panel > ul li { color: "+c+"; }\n.psmob-nav-panel > ul li a { color: "+c+"; }\n"));document.head.appendChild(d);0==b.sa.length||tc()||(ld(b),nd(b),od());
td(this,this.C,"navigation");sd(this)};Z.prototype.jb=function(a){this.S[a.src]=new oc(a.width,a.height);--this.J;td(this,1E3,"background image");0==this.J&&this.ra&&(rd(this),this.ra=!1)};function ud(a,b){var c=Kc(a.oa,b);if(null!=c){var d=sc(c);if(d&&(0==d.lastIndexOf("http://",0)||0==d.lastIndexOf("https://",0))&&!a.S[d]){a.S[d]=qd;var e=new Image;++a.J;e.onload=a.jb.bind(a,e);e.onerror=e.onload;e.src=d}for(c=c.firstChild;c;c=c.nextSibling)ud(a,c)}}Z.prototype.xhrSendHook=function(){++this.ga};
Z.prototype.xhrResponseHook=function(){--this.ga;this.k+=this.Aa;sd(this)};Z.prototype.ub=function(){vd(this,window.psDebugMode);this.C=uc(document.body);this.Aa=Rc.length/2*this.C;this.k+=this.Aa;window.psNavMode&&tc()&&(this.k+=this.C,this.k+=this.C);if(null!=document.body){for(var a in window.psMobStaticImageInfo){var b=window.psMobStaticImageInfo[a];this.S[a]=new oc(b.w,b.h)}ud(this,document.body)}this.k+=1E3*this.J;window.psLayoutMode&&window.pagespeedXhrHijackSetListener(this);rd(this)};
function sd(a){if(0==a.ga&&0==a.ua&&0==a.J){if(window.psLayoutMode){var b=a.oa;if(null!=document.body)for(var c=0;c<Rc.length;++c){Rc[c].call(b,document.body);++c;var d=b.U;td(d,d.C,Rc[c])}}if(a.Ja){if(a=document.getElementById("ps-progress-remove"))a.textContent="Remove Progress Bar and show mobilized site"}else wd()}}function Nc(a,b){var c=a.S[b];c==qd&&(c=null);return c}
function vd(a,b){a.Ja=b;var c=document.getElementById("ps-progress-log");c&&(c.style.color=b?"#333":"white");b&&(c=document.getElementById("ps-progress-show-log"))&&(c.style.display="none")}function Vc(a){var b=a.getAttribute("ps-save-visibility");b||((a=window.getComputedStyle(a))&&(b=a.getPropertyValue("visibility")),b||(b="visible"));return b}
function td(a,b,c){a.za+=b;b=100;0<a.k&&(b=Math.round(100*a.za/a.k),100<b&&(b=100));if(b!=a.Va){var d=document.getElementById("ps-progress-span");d&&(d.style.width=b+"%");a.Va=b}a=""+b+"% "+(Date.now()-a.Bb)+"ms: "+c;W(a);if(c=document.getElementById("ps-progress-log"))c.textContent+=a+"\n"}function wd(){var a=document.getElementById("ps-progress-scrim");a&&(a.style.display="none",a.parentNode.removeChild(a))}var xd=new Z;window.addEventListener("load",u(xd.ub,xd));
v("psSetDebugMode",function(){vd(xd,!0)});v("psRemoveProgressBar",function(){wd()});})();
