(function(){var l,p=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function q(a){return"string"==typeof a}function t(a){return"function"==ba(a)}function da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function u(a,b,c){u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return u.apply(null,arguments)}var ga=Date.now||function(){return+new Date};
function v(a,b){var c=a.split("."),d=p;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}function x(a,b){function c(){}c.prototype=b.prototype;a.Fb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Eb=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function ha(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function ia(a){var b=[];ja(new ka,a,b);return b.join("")}function ka(){this.aa=void 0}
function ja(a,b,c){switch(typeof b){case "string":la(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==ba(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],ja(a,a.aa?a.aa.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
la(f,c),c.push(":"),ja(a,a.aa?a.aa.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ma={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},na=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function la(a,b){b.push('"',a.replace(na,function(a){if(a in ma)return ma[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ma[a]=e+b.toString(16)}),'"')};function y(a){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}x(y,Error);y.prototype.name="CustomError";var oa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function z(a,b){return-1!=a.toLowerCase().indexOf(b.toLowerCase())}function pa(a,b){return a<b?-1:a>b?1:0};var A;a:{var qa=p.navigator;if(qa){var ra=qa.userAgent;if(ra){A=ra;break a}}A=""};function sa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function ta(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function ua(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};function va(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function wa(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var B=Array.prototype,xa=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(q(a))return q(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ya=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},za=B.filter?function(a,b,c){return B.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=q(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},Aa=B.some?function(a,b,c){return B.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function Ba(a){return B.concat.apply(B,arguments)}function Ca(a){return B.concat.apply(B,arguments)}function Da(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ea(a){if("function"==typeof a.s)return a.s();if(q(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ta(a)}function Fa(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ca(a)||q(a))ya(a,b,c);else{var d;if("function"==typeof a.F)d=a.F();else if("function"!=typeof a.s)if(ca(a)||q(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=ua(a);else d=void 0;for(var e=Ea(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};function Ga(a){p.setTimeout(function(){throw a;},0)}var Ha;
function Ia(){var a=p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=u(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},
this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==A.indexOf("Trident")&&-1==A.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.Ca;c.Ca=null;a()}};return function(a){d.next={Ca:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){p.setTimeout(a,0)}};function Ja(a,b){Ka||La();Ma||(Ka(),Ma=!0);Na.push(new Oa(a,b))}var Ka;function La(){if(p.Promise&&p.Promise.resolve){var a=p.Promise.resolve();Ka=function(){a.then(Pa)}}else Ka=function(){var a=Pa;!t(p.setImmediate)||p.Window&&p.Window.prototype.setImmediate==p.setImmediate?(Ha||(Ha=Ia()),Ha(a)):p.setImmediate(a)}}var Ma=!1,Na=[];function Pa(){for(;Na.length;){var a=Na;Na=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.qb.call(c.scope)}catch(d){Ga(d)}}}Ma=!1}
function Oa(a,b){this.qb=a;this.scope=b};function Qa(a){return 1==a.length?"0"+a:a}function Ra(a,b,c){var d=0,e=0,f=0;if(0==b)f=e=d=c;else{var g=Math.floor(a/60),h=a/60-g;a=c*(1-b);var k=c*(1-b*h);b=c*(1-b*(1-h));switch(g){case 1:d=k;e=c;f=a;break;case 2:d=a;e=c;f=b;break;case 3:d=a;e=k;f=c;break;case 4:d=b;e=a;f=c;break;case 5:d=c;e=a;f=k;break;case 6:case 0:d=c,e=b,f=a}}return[Math.floor(d),Math.floor(e),Math.floor(f)]}
function Sa(a,b,c){var d=Math.max(Math.max(a,b),c),e=Math.min(Math.min(a,b),c);if(e==d)e=a=0;else{var f=d-e,e=f/d;a=60*(a==d?(b-c)/f:b==d?2+(c-a)/f:4+(a-b)/f);0>a&&(a+=360);360<a&&(a-=360)}return[a,e,d]};function Ta(a,b){this.o={};this.e=[];this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Ta?(c=a.F(),d=a.s()):(c=ua(a),d=ta(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}l=Ta.prototype;l.s=function(){Ua(this);for(var a=[],b=0;b<this.e.length;b++)a.push(this.o[this.e[b]]);return a};l.F=function(){Ua(this);return this.e.concat()};l.N=function(a){return C(this.o,a)};
l.clear=function(){this.o={};this.c=this.e.length=0};l.remove=function(a){return C(this.o,a)?(delete this.o[a],this.c--,this.e.length>2*this.c&&Ua(this),!0):!1};function Ua(a){if(a.c!=a.e.length){for(var b=0,c=0;b<a.e.length;){var d=a.e[b];C(a.o,d)&&(a.e[c++]=d);b++}a.e.length=c}if(a.c!=a.e.length){for(var e={},c=b=0;b<a.e.length;)d=a.e[b],C(e,d)||(a.e[c++]=d,e[d]=1),b++;a.e.length=c}}l.get=function(a,b){return C(this.o,a)?this.o[a]:b};
l.set=function(a,b){C(this.o,a)||(this.c++,this.e.push(a));this.o[a]=b};l.forEach=function(a,b){for(var c=this.F(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};l.clone=function(){return new Ta(this)};function C(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Va(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}l=Va.prototype;l.clone=function(){return new Va(this.top,this.right,this.bottom,this.left)};l.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};l.contains=function(a){return this&&a?a instanceof Va?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
l.expand=function(a,b,c,d){da(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=b,this.bottom+=c,this.left-=d);return this};l.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};l.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
l.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};l.translate=function(a,b){this.left+=a;this.right+=a;"number"==typeof b&&(this.top+=b,this.bottom+=b);return this};l.scale=function(a,b){var c="number"==typeof b?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Wa=-1!=A.indexOf("Opera")||-1!=A.indexOf("OPR"),D=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),Xa=-1!=A.indexOf("Gecko")&&!z(A,"WebKit")&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE")),Ya=z(A,"WebKit");function Za(){var a=p.document;return a?a.documentMode:void 0}
var $a=function(){var a="",b;if(Wa&&p.opera)return a=p.opera.version,t(a)?a():a;Xa?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Ya&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(A))?a[1]:"");return D&&(b=Za(),b>parseFloat(a))?String(b):a}(),ab={};
function bb(a){if(!ab[a]){for(var b=0,c=oa(String($a)).split("."),d=oa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var n=k.exec(g)||["","",""],r=m.exec(h)||["","",""];if(0==n[0].length&&0==r[0].length)break;b=pa(0==n[1].length?0:parseInt(n[1],10),0==r[1].length?0:parseInt(r[1],10))||pa(0==n[2].length,0==r[2].length)||pa(n[2],r[2])}while(0==b)}ab[a]=0<=b}}
var cb=p.document,db=cb&&D?Za()||("CSS1Compat"==cb.compatMode?parseInt($a,10):5):void 0;function E(a,b){this.j=F;this.t=void 0;this.g=this.m=null;this.Z=this.ja=!1;try{var c=this;a.call(b,function(a){G(c,eb,a)},function(a){if(!(a instanceof H))try{if(a instanceof Error)throw a;throw Error("Promise rejected.");}catch(b){}G(c,I,a)})}catch(d){G(this,I,d)}}var F=0,eb=2,I=3;E.prototype.then=function(a,b,c){return fb(this,t(a)?a:null,t(b)?b:null,c)};va(E);E.prototype.cancel=function(a){this.j==F&&Ja(function(){var b=new H(a);gb(this,b)},this)};
function gb(a,b){if(a.j==F)if(a.m){var c=a.m;if(c.g){for(var d=0,e=-1,f=0,g;g=c.g[f];f++)if(g=g.M)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.j==F&&1==d?gb(c,b):(d=c.g.splice(e,1)[0],hb(c,d,I,b)))}}else G(a,I,b)}function ib(a,b){a.g&&a.g.length||a.j!=eb&&a.j!=I||jb(a);a.g||(a.g=[]);a.g.push(b)}
function fb(a,b,c,d){var e={M:null,Qa:null,Ra:null};e.M=new E(function(a,g){e.Qa=b?function(c){try{var e=b.call(d,c);a(e)}catch(m){g(m)}}:a;e.Ra=c?function(b){try{var e=c.call(d,b);void 0===e&&b instanceof H?g(b):a(e)}catch(m){g(m)}}:g});e.M.m=a;ib(a,e);return e.M}E.prototype.Ya=function(a){this.j=F;G(this,eb,a)};E.prototype.Za=function(a){this.j=F;G(this,I,a)};
function G(a,b,c){if(a.j==F){if(a==c)b=I,c=new TypeError("Promise cannot resolve to itself");else{if(wa(c)){a.j=1;c.then(a.Ya,a.Za,a);return}if(da(c))try{var d=c.then;if(t(d)){kb(a,c,d);return}}catch(e){b=I,c=e}}a.t=c;a.j=b;jb(a);b!=I||c instanceof H||lb(a,c)}}function kb(a,b,c){function d(b){f||(f=!0,a.Za(b))}function e(b){f||(f=!0,a.Ya(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function jb(a){a.ja||(a.ja=!0,Ja(a.pb,a))}
E.prototype.pb=function(){for(;this.g&&this.g.length;){var a=this.g;this.g=[];for(var b=0;b<a.length;b++)hb(this,a[b],this.j,this.t)}this.ja=!1};function hb(a,b,c,d){if(c==eb)b.Qa(d);else{if(b.M)for(;a&&a.Z;a=a.m)a.Z=!1;b.Ra(d)}}function lb(a,b){a.Z=!0;Ja(function(){a.Z&&mb.call(null,b)})}var mb=Ga;function H(a){y.call(this,a)}x(H,y);H.prototype.name="cancel";/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function J(a,b){this.ba=[];this.Pa=a;this.Ga=b||null;this.R=this.I=!1;this.t=void 0;this.ta=this.ib=this.ha=!1;this.da=0;this.m=null;this.ia=0}J.prototype.cancel=function(a){if(this.I)this.t instanceof J&&this.t.cancel();else{if(this.m){var b=this.m;delete this.m;a?b.cancel(a):(b.ia--,0>=b.ia&&b.cancel())}this.Pa?this.Pa.call(this.Ga,this):this.ta=!0;this.I||(a=new nb,ob(this),pb(this,!1,a))}};J.prototype.Ea=function(a,b){this.ha=!1;pb(this,a,b)};function pb(a,b,c){a.I=!0;a.t=c;a.R=!b;qb(a)}
function ob(a){if(a.I){if(!a.ta)throw new rb;a.ta=!1}}function sb(a,b,c,d){a.ba.push([b,c,d]);a.I&&qb(a)}J.prototype.then=function(a,b,c){var d,e,f=new E(function(a,b){d=a;e=b});sb(this,d,function(a){a instanceof nb?f.cancel():e(a)});return f.then(a,b,c)};va(J);function tb(a){return Aa(a.ba,function(a){return t(a[1])})}
function qb(a){if(a.da&&a.I&&tb(a)){var b=a.da,c=ub[b];c&&(p.clearTimeout(c.G),delete ub[b]);a.da=0}a.m&&(a.m.ia--,delete a.m);for(var b=a.t,d=c=!1;a.ba.length&&!a.ha;){var e=a.ba.shift(),f=e[0],g=e[1],e=e[2];if(f=a.R?g:f)try{var h=f.call(e||a.Ga,b);void 0!==h&&(a.R=a.R&&(h==b||h instanceof Error),a.t=b=h);wa(b)&&(d=!0,a.ha=!0)}catch(k){b=k,a.R=!0,tb(a)||(c=!0)}}a.t=b;d&&(h=u(a.Ea,a,!0),d=u(a.Ea,a,!1),b instanceof J?(sb(b,h,d),b.ib=!0):b.then(h,d));c&&(b=new vb(b),ub[b.G]=b,a.da=b.G)}
function rb(){y.call(this)}x(rb,y);rb.prototype.message="Deferred has already fired";rb.prototype.name="AlreadyCalledError";function nb(){y.call(this)}x(nb,y);nb.prototype.message="Deferred was canceled";nb.prototype.name="CanceledError";function vb(a){this.G=p.setTimeout(u(this.zb,this),0);this.ob=a}vb.prototype.zb=function(){delete ub[this.G];throw this.ob;};var ub={};function wb(a){if(a.classList)return a.classList;a=a.className;return q(a)&&a.match(/\S+/g)||[]}function K(a,b){var c;a.classList?c=a.classList.contains(b):(c=wb(a),c=0<=xa(c,b));return c}function L(a,b){a.classList?a.classList.add(b):K(a,b)||(a.className+=0<a.className.length?" "+b:b)}function xb(a,b){a.classList?a.classList.remove(b):K(a,b)&&(a.className=za(wb(a),function(a){return a!=b}).join(" "))}function yb(a,b){K(a,b)?xb(a,b):L(a,b)};var zb;if(!(zb=!Xa&&!D)){var Ab;if(Ab=D)Ab=D&&9<=db;zb=Ab}zb||Xa&&bb("1.9.1");D&&bb("9");function Bb(a,b){sa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Cb?a.setAttribute(Cb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Cb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Db(a){return da(a)&&1==a.nodeType};function Eb(a,b){var c=b||{},d=c.document||document,e=document.createElement("SCRIPT"),f={Va:e,ca:void 0},g=new J(Fb,f),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){Gb(e,!0);var b=new Hb(Ib,"Timeout reached for loading script "+a);ob(g);pb(g,!1,b)},k),f.ca=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(Gb(e,c.lb||!1,h),ob(g),pb(g,!0,null))};e.onerror=function(){Gb(e,!0,h);var b=new Hb(Jb,"Error while loading script "+
a);ob(g);pb(g,!1,b)};Bb(e,{type:"text/javascript",charset:"UTF-8",src:a});Kb(d).appendChild(e);return g}function Kb(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}function Fb(){if(this&&this.Va){var a=this.Va;a&&"SCRIPT"==a.tagName&&Gb(a,!0,this.ca)}}function Gb(a,b,c){null!=c&&p.clearTimeout(c);a.onload=aa;a.onerror=aa;a.onreadystatechange=aa;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var Jb=0,Ib=1;
function Hb(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);y.call(this,c);this.code=a}x(Hb,y);var Lb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function Mb(a){if(Nb){Nb=!1;var b=p.location;if(b){var c=b.href;if(c&&(c=Ob(c))&&c!=b.hostname)throw Nb=!0,Error();}}return a.match(Lb)}var Nb=Ya;function Ob(a){return(a=Mb(a)[3]||null)?decodeURI(a):a};function Pb(a,b){var c;if(a instanceof Pb)this.i=void 0!==b?b:a.i,Qb(this,a.v),c=a.H,M(this),this.H=c,c=a.r,M(this),this.r=c,Rb(this,a.K),c=a.p,M(this),this.p=c,Sb(this,a.q.clone()),c=a.D,M(this),this.D=c;else if(a&&(c=Mb(String(a)))){this.i=!!b;Qb(this,c[1]||"",!0);var d=c[2]||"";M(this);this.H=N(d);d=c[3]||"";M(this);this.r=N(d,!0);Rb(this,c[4]);d=c[5]||"";M(this);this.p=N(d,!0);Sb(this,c[6]||"",!0);c=c[7]||"";M(this);this.D=N(c)}else this.i=!!b,this.q=new Tb(null,0,this.i)}l=Pb.prototype;l.v="";
l.H="";l.r="";l.K=null;l.p="";l.D="";l.sb=!1;l.i=!1;l.toString=function(){var a=[],b=this.v;b&&a.push(Ub(b,Vb,!0),":");if(b=this.r){a.push("//");var c=this.H;c&&a.push(Ub(c,Vb,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.K;null!=b&&a.push(":",String(b))}if(b=this.p)this.r&&"/"!=b.charAt(0)&&a.push("/"),a.push(Ub(b,"/"==b.charAt(0)?Wb:Xb,!0));(b=this.q.toString())&&a.push("?",b);(b=this.D)&&a.push("#",Ub(b,Yb));return a.join("")};
l.resolve=function(a){var b=this.clone(),c=!!a.v;c?Qb(b,a.v):c=!!a.H;if(c){var d=a.H;M(b);b.H=d}else c=!!a.r;c?(d=a.r,M(b),b.r=d):c=null!=a.K;d=a.p;if(c)Rb(b,a.K);else if(c=!!a.p){if("/"!=d.charAt(0))if(this.r&&!this.p)d="/"+d;else{var e=b.p.lastIndexOf("/");-1!=e&&(d=b.p.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var d=0==e.lastIndexOf("/",0),e=e.split("/"),f=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&f.push(""):".."==h?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?(M(b),b.p=d):c=""!==a.q.toString();c?Sb(b,N(a.q.toString())):c=!!a.D;c&&(a=a.D,M(b),b.D=a);return b};l.clone=function(){return new Pb(this)};function Qb(a,b,c){M(a);a.v=c?N(b,!0):b;a.v&&(a.v=a.v.replace(/:$/,""))}function Rb(a,b){M(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.K=b}else a.K=null}
function Sb(a,b,c){M(a);b instanceof Tb?(a.q=b,a.q.sa(a.i)):(c||(b=Ub(b,Zb)),a.q=new Tb(b,0,a.i))}function $b(a,b,c){M(a);"array"==ba(c)||(c=[String(c)]);ac(a.q,b,c)}function M(a){if(a.sb)throw Error("Tried to modify a read-only Uri");}l.sa=function(a){this.i=a;this.q&&this.q.sa(a);return this};function N(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}function Ub(a,b,c){return q(a)?(a=encodeURI(a).replace(b,bc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}
function bc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Vb=/[#\/\?@]/g,Xb=/[\#\?:]/g,Wb=/[\#\?]/g,Zb=/[\#\?@]/g,Yb=/#/g;function Tb(a,b,c){this.f=a||null;this.i=!!c}function O(a){if(!a.b&&(a.b=new Ta,a.c=0,a.f))for(var b=a.f.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=P(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}l=Tb.prototype;
l.b=null;l.c=null;l.add=function(a,b){O(this);this.f=null;a=P(this,a);var c=this.b.get(a);c||this.b.set(a,c=[]);c.push(b);this.c++;return this};l.remove=function(a){O(this);a=P(this,a);return this.b.N(a)?(this.f=null,this.c-=this.b.get(a).length,this.b.remove(a)):!1};l.clear=function(){this.b=this.f=null;this.c=0};l.N=function(a){O(this);a=P(this,a);return this.b.N(a)};l.F=function(){O(this);for(var a=this.b.s(),b=this.b.F(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
l.s=function(a){O(this);var b=[];if(q(a))this.N(a)&&(b=Ba(b,this.b.get(P(this,a))));else{a=this.b.s();for(var c=0;c<a.length;c++)b=Ba(b,a[c])}return b};l.set=function(a,b){O(this);this.f=null;a=P(this,a);this.N(a)&&(this.c-=this.b.get(a).length);this.b.set(a,[b]);this.c++;return this};l.get=function(a,b){var c=a?this.s(a):[];return 0<c.length?String(c[0]):b};function ac(a,b,c){a.remove(b);0<c.length&&(a.f=null,a.b.set(P(a,b),Da(c)),a.c+=c.length)}
l.toString=function(){if(this.f)return this.f;if(!this.b)return"";for(var a=[],b=this.b.F(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.s(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.f=a.join("&")};l.clone=function(){var a=new Tb;a.f=this.f;this.b&&(a.b=this.b.clone(),a.c=this.c);return a};function P(a,b){var c=String(b);a.i&&(c=c.toLowerCase());return c}
l.sa=function(a){a&&!this.i&&(O(this),this.f=null,this.b.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),ac(this,d,a))},this));this.i=a};l.extend=function(a){for(var b=0;b<arguments.length;b++)Fa(arguments[b],function(a,b){this.add(b,a)},this)};function cc(a,b){this.Ab=new Pb(a);this.jb=b?b:"callback";this.ca=5E3}var dc=0;cc.prototype.send=function(a,b,c,d){a=a||null;d=d||"_"+(dc++).toString(36)+ga().toString(36);p._callbacks_||(p._callbacks_={});var e=this.Ab.clone();if(a)for(var f in a)a.hasOwnProperty&&!a.hasOwnProperty(f)||$b(e,f,a[f]);b&&(p._callbacks_[d]=ec(d,b),$b(e,this.jb,"_callbacks_."+d));b=Eb(e.toString(),{timeout:this.ca,lb:!0});sb(b,null,fc(d,a,c),void 0);return{G:d,Ha:b}};
cc.prototype.cancel=function(a){a&&(a.Ha&&a.Ha.cancel(),a.G&&gc(a.G,!1))};function fc(a,b,c){return function(){gc(a,!1);c&&c(b)}}function ec(a,b){return function(c){gc(a,!0);b.apply(void 0,arguments)}}function gc(a,b){p._callbacks_[a]&&(b?delete p._callbacks_[a]:p._callbacks_[a]=aa)};function hc(){this.height=this.width=this.bottom=this.right=this.left=this.top=0}function ic(a,b){this.width=a;this.height=b}function Q(a){var b=null;if(a&&"string"==typeof a){var c=a.indexOf("px");-1!=c&&(a=a.substring(0,c));c=a.length-1;a.length<=c?c=!1:(c=a.charCodeAt(c),c=48<=c&&57>=c);c&&(b=parseInt(a,10),isNaN(b)&&(b=null))}return b}function R(a,b){var c=null;a&&(c=Q(a.getPropertyValue(b)));return c}function S(a,b){a.style&&a.style.removeProperty(b);a.removeAttribute(b)}
function jc(a,b){var c=null;a.style&&(c=Q(a.style.getPropertyValue(b)));null==c&&(c=Q(a.getAttribute(b)));return c}function T(a,b,c){a.style.setProperty(b,c,"important")}function kc(a,b){if(b&&0!=b.length){var c=a.getAttribute("style")||"";0<c.length&&";"!=c[c.length-1]&&(c+=";");a.setAttribute("style",c+b)}}
function lc(a){a=a.getBoundingClientRect();var b=document.body,c=document.documentElement||b.parentNode||b,b="pageXOffset"in window?window.pageXOffset:c.scrollLeft,c="pageYOffset"in window?window.pageYOffset:c.scrollTop;return new Va(a.top+c,a.right+b,a.bottom+c,a.left+b)}
function mc(a){var b=null;return"SCRIPT"!=a.tagName&&"STYLE"!=a.tagName&&a.style&&(a=window.getComputedStyle(a))&&(b=a.getPropertyValue("background-image"),"none"==b&&(b=null),b&&5<b.length&&0==b.indexOf("url(")&&")"==b[b.length-1])?b=b.substring(4,b.length-1):null}function nc(){if(null!=window.parent&&window!=window.parent)try{if(window.parent.document.domain==document.domain)return!0}catch(a){}return!1}function oc(a){var b=1;for(a=a.firstChild;a;a=a.nextSibling)b+=oc(a);return b}
function U(a){return Db(a)?a:null}var pc={Cb:"IMG",Db:"SVG",Bb:"background-image"};v("pagespeed.MobUtil.ImageSource",pc);function qc(a,b,c,d){this.na=a;this.Oa=b;this.wb=c;this.vb=d}
function V(a){for(var b=0,c=a.length;b<c;++b){var d=Math.round(a[b]);0>d?d=0:255<d&&(d=255);a[b]=d}c=a[0];b=a[1];a=a[2];c=Number(c);b=Number(b);a=Number(a);if(isNaN(c)||0>c||255<c||isNaN(b)||0>b||255<b||isNaN(a)||0>a||255<a)throw Error('"('+c+","+b+","+a+'") is not a valid RGB color');c=Qa(c.toString(16));b=Qa(b.toString(16));a=Qa(a.toString(16));return"#"+c+b+a}function W(a){a=a.toLowerCase();for(var b="",c=0,d=a.length;c<d;++c){var e=a.charAt(c);if("a"<=e&&"z">=e||"0"<=e&&"9">=e)b+=e}return b}
function rc(a,b){var c=null;switch(b){case "IMG":a.tagName==b&&(c=a.src);break;case "SVG":a.tagName==b&&(c=(new XMLSerializer).serializeToString(a),c=(self.URL||self.webkitURL||self).createObjectURL(new Blob([c],{type:"image/svg+xml;charset=utf-8"})));break;case "background-image":c=mc(a)}if(c){var d=document.location.origin,e=Ob(d),f=Ob(c);if(null!=e&&null!=f){var g=!1;if(e==f)g=!0;else if(0<=e.indexOf(f)){var e=e.split("."),h=e.length;3<=h&&(f==e.slice(0,h-2).join(".")||"www"==e[0]&&(f==e.slice(1,
h-2).join(".")||f==e.slice(1,h).join(".")))&&(g=!0)}c=g?d+c.substring(c.indexOf(f)+f.length):c}}else c=null;return c}function sc(a){a=lc(a);var b=new hc;b.top=a.top;b.bottom=a.bottom;b.left=a.left;b.right=a.right;b.height=a.bottom-a.top;b.width=a.right-a.left;return b}function tc(a){var b=Q(a.top);a=Q(a.left);return null!=b&&-100>b||null!=a&&-100>a}
function uc(a){a=a.replace(/\\/g,"\\\\");a=a.replace(/"/g,'\\"');a=a.replace(/\n/g,"\\a ");a=a.replace(/\f/g,"\\c ");a=a.replace(/\r/g,"\\d ");return'"'+a+'"'};function vc(){this.qa=0;this.Y=this.ma=null}vc.prototype.xa=1E-10;vc.prototype.fa=3;function wc(a,b){this.background=a;this.La=b}function xc(a,b){if(3!=a.length||3!=b.length)return Infinity;var c=a[0]-b[0],d=a[1]-b[1],e=a[2]-b[2];return Math.sqrt(c*c+d*d+e*e)}function X(a){a/=255;return a=.03928>=a?a/12.92:Math.pow((a+.055)/1.055,2.4)}
function yc(a,b){var c=b.background,d=b.La,e=.2126*X(c[0])+.7152*X(c[1])+.0722*X(c[2]),f=.2126*X(d[0])+.7152*X(d[1])+.0722*X(d[2]);if(e<a.xa&&f<a.xa)return b;e=f/e;1>e&&(e=1/e);if(e>a.fa)return b;c=Sa(c[0],c[1],c[2]);d=Sa(d[0],d[1],d[2]);f=e=null;c[2]<d[2]?(e=c[2],f=d[2]):(e=d[2],f=c[2]);var g=(a.fa*e-f)/(a.fa+1),e=e>g?e-g:0,f=f<1-2*g?f+2*g:255;c[2]<d[2]?(c[2]=e,d[2]=f):(d[2]=e,c[2]=f);c=Ra(c[0],c[1],c[2]);d=Ra(d[0],d[1],d[2]);return new wc(c,d)}
function zc(a,b,c,d,e){var f=[],g,h,k;for(h=0;h<e;++h)for(g=0;g<d;++g){var m=4*(h*d+g);k=3*(h*d+g);var n=b[m+3]/255,r=1-n;f[k]=n*b[m]+r*c[0];f[k+1]=n*b[m+1]+r*c[1];f[k+2]=n*b[m+2]+r*c[2]}m=[0,0,0];for(g=n=h=0;g<d;++g)r=(e-1)*d+g,k=3*r,m[0]+=f[k],m[1]+=f[k+1],m[2]+=f[k+2],n+=b[4*r+3],++h;if(n>127.5*h)for(g=0;3>g;++g)m[g]=Math.floor(m[g]/h);else m=c;b=Math.floor(.25*d);c=Math.floor(.75*d);n=Math.floor(.25*e);e=Math.floor(.75*e);var r=0,w=[];for(h=n;h<=e;++h)for(g=b;g<=c;++g)k=3*(h*d+g),w[r]=xc(f.slice(k,
k+3),m),++r;g=w.sort(function(a,b){return a-b});var ed=Math.max(1,g[Math.floor(.75*r)]),r=0,w=[0,0,0];for(h=n;h<=e;++h)for(g=b;g<=c;++g)k=3*(h*d+g),xc(f.slice(k,k+3),m)>=ed&&(w[0]+=f[k],w[1]+=f[k+1],w[2]+=f[k+2],++r);if(0<r)for(g=0;3>g;++g)w[g]=Math.floor(w[g]/r);return yc(a,new wc(m,w))}
vc.prototype.ua=function(){--this.qa;if(!(0<this.qa)){var a=[255,255,255],b=[0,0,0],c=this.ma;this.Y&&this.Y.data&&c&&c.n&&c.backgroundColor?(b=zc(this,this.Y.data,c.backgroundColor,c.n.width,c.n.height),a=b.background,b=b.La):c&&c.backgroundColor&&(a=c.backgroundColor,b=178.5<Sa(a[0],a[1],a[2])[2]?[0,0,0]:[255,255,255]);console.log("Theme color. Background: "+a+" foreground: "+b);this.Ia(this.ma,a,b)}};
function Ac(a,b,c){var d=new Image;d.onload=u(function(){var a=document.createElement("canvas"),b=null,g=null;c&&0<c.width&&0<c.height?(b=c.width,g=c.height):(b=d.naturalWidth,g=d.naturalHeight);a.width=b;a.height=g;a=a.getContext("2d");a.drawImage(d,0,0);this.Y=a.getImageData(0,0,b,g);this.ua()},a);d.onerror=u(a.ua,a);d.src=b}
vc.prototype.run=function(a,b){this.ma=a;this.Ia&&alert("A callback which was supposed to run after extracting theme color  was not executed.");this.Ia=b;var c;if(c=a)if(c=a.u)c=a.u,c=!(0!=c.lastIndexOf(document.location.origin+"/",0)&&0!=c.lastIndexOf("data:image/",0));c?(this.qa=1,Ac(this,a.u,a.n),console.log("Found logo. Theme color will be computed from logo.")):(a&&a.u?console.log("Found logo but its origin is different that of HTML. Use default color."):console.log("Could not find logo. Use default color."),
this.ua())};function Y(a){this.V=a;this.Ja={};if(a=document.documentElement.clientWidth)for(var b=window.getComputedStyle(document.body),c=["padding-left","padding-right"],d=0;d<c.length;++d){var e=R(b,c[d]);e&&(a-=e)}else a=400;this.l=a;console.log("window.pagespeed.MobLayout.maxWidth="+this.l)}
var Bc="padding-left padding-bottom padding-right padding-top margin-left margin-bottom margin-right margin-top border-left-width border-bottom-width border-right-width border-top-width left top".split(" "),Cc={A:!0,DIV:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,P:!0,SPAN:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0},Dc=["left","width"];
function Ec(a,b){if(!b)return!0;var c=b.tagName.toUpperCase();return"SCRIPT"==c||"STYLE"==c||"IFRAME"==c||b.id&&a.Ja[b.id]||b.classList.contains("psmob-nav-panel")||b.classList.contains("psmob-header-bar")||b.classList.contains("psmob-header-spacer-div")||b.classList.contains("psmob-logo-span")}function Fc(a,b){var c=U(b);return Ec(a,c)?null:c}function Gc(a){var b=[];for(a=a.firstChild;a;a=a.nextSibling)null!=U(a)&&b.push(a);return b}
function Hc(a,b,c){for(b=b.firstChild;b;b=b.nextSibling)null!=Fc(a,b)&&c.call(a,b)}l=Y.prototype;
l.Wa=function(a){var b=window.getComputedStyle(a),c=mc(a);if(c){var c=Ic(this.V,c),d;if(d=c&&c.width&&c.height)"auto"==b.getPropertyValue("background-size")?d=!1:(d=b.getPropertyValue("background-position"),"none"==d?d=!1:(d=d.split(" "),d=2==d.length&&null!=Q(d[0])&&null!=Q(d[1])?!0:!1)),d=!d;if(d){d=c.width;c=c.height;if(d>this.l){c=Math.round(this.l/d*c);d="background-size:"+this.l+"px "+c+"px;background-repeat:no-repeat;";var e=R(b,"height");c==e&&(d+="height:"+c+"px;");kc(a,d)}T(a,"min-height",
""+c+"px")}}if("PRE"==a.tagName.toUpperCase()||"pre"==b.getPropertyValue("white-space")&&a.offsetWidth>this.l)a.style.overflowX="scroll";Hc(this,a,this.Wa)};function Jc(a){T(a,"overflow-x","auto");T(a,"width","auto");T(a,"display","block")}l.xb=function(a){Kc(this,a,0)};
function Kc(a,b,c){var d;if(d=lc(b))c=d.top,d=d.bottom;else{if(b.offsetParent==b.parentNode)c+=b.offsetTop;else if(b.offsetParent!=b.parentNode.parentNode)return null;d=c+b.offsetHeight-1}if(Ec(a,b))return d;d=c-1;var e=window.getComputedStyle(b);if(!e)return null;var f=R(e,"min-height");null!=f&&(d+=f);for(var f=c+b.offsetHeight-1,g=!1,h=!1,k,m=b.firstChild;m;m=m.nextSibling)if(k=U(m)){var n=window.getComputedStyle(k);n&&("absolute"!=n.position||tc(n)||"0px"==n.getPropertyValue("height")||"hidden"==
n.getPropertyValue("visibility")||(h=!0));k=Kc(a,k,c);null!=k&&(g=!0,d=Math.max(d,k))}if("fixed"==e.getPropertyValue("position")&&g)return null;a=b.tagName.toUpperCase();"BODY"!=a&&(e=f-c+1,g?d!=f&&(h?T(b,"height",""+(d-c+1)+"px"):T(b,"height","auto")):("IMG"!=a&&0<e&&""==b.style.backgroundSize&&(S(b,"height"),T(b,"height","auto"),b.offsetHeight&&(f=c+b.offsetHeight)),d=f));return d}
l.Ua=function(a){for(var b=Gc(a),c=0;c<b.length;++c)this.Ua(b[c]);if(!(a.offsetWidth<=this.l))if(b=a.tagName.toUpperCase(),"TABLE"==b){a:{b=0;for(c=a.firstChild;c;c=c.nextSibling)for(var d=c.firstChild;d;d=d.nextSibling){var e=c.tagName.toUpperCase();if("THEAD"==e||"TFOOT"==e){b=!0;break a}for(e=d.firstChild;e;e=e.nextSibling){if(e.tagName&&"TH"==e.tagName.toUpperCase()){b=!0;break a}++b}}b=3*Lc(this,a)>b?!1:!0}if(b)Jc(a);else if("CSS1Compat"!==document.compatMode){var f,g,h,k=document.createElement("DIV");
k.style.display="inline-block";for(var m=Gc(a),b=0;b<m.length;++b)for(var n=Gc(m[b]),c=0;c<n.length;++c)for(var r=Gc(n[c]),d=0;d<r.length;++d)if(g=r[d],1==g.childNodes.length)f=g.childNodes[0],g.removeChild(f),k.appendChild(f);else if(1<g.childNodes.length){h=document.createElement("DIV");h.style.display="inline-block";for(var w=Gc(g),e=0;e<w.length;++e)f=w[e],g.removeChild(f),h.appendChild(f);k.appendChild(h)}a.parentNode.replaceChild(k,a)}else for(S(a,"width"),T(a,"max-width","100%"),a=a.firstChild;a;a=
a.nextSibling)if(b=U(a),null!=b)for(S(b,"width"),T(b,"max-width","100%"),b=b.firstChild;b;b=b.nextSibling)if(c=U(b),null!=c&&"TR"==c.tagName.toUpperCase())for(S(c,"width"),T(c,"max-width","100%"),c=c.firstChild;c;c=c.nextSibling)d=U(c),null!=d&&"TD"==d.tagName.toUpperCase()&&(T(d,"max-width","100%"),T(d,"display","inline-block"))}else{c=null;d=a.offsetWidth;e=a.offsetHeight;f="img";if("IMG"==b)c=a.getAttribute("src");else if(f="background-image",c=mc(a),g=null==c?null:Ic(this.V,c))d=g.width,e=g.height;
null!=c?(g=d/this.l,1<g&&(g=e/g,console.log("Shrinking "+f+" "+c+" from "+d+"x"+e+" to "+this.l+"x"+g),"IMG"==b?(T(a,"width",""+this.l+"px"),T(a,"height",""+g+"px")):T(a,"background-size",""+this.l+"px "+g+"px"))):"CODE"==b||"PRE"==b||"UL"==b?Jc(a):Cc[b]?(T(a,"max-width","100%"),S(a,"width")):console.log("Punting on resize of "+b+" which wants to be "+a.offsetWidth+" but this.maxWidth_="+this.l)}};
function Lc(a,b){var c=0,d=b.tagName.toUpperCase();"DIV"!=d&&"TABLE"!=d&&"UL"!=d||++c;for(d=b.firstChild;d;d=d.nextSibling){var e=U(d);null!=e&&(c+=Lc(a,e))}return c}l.kb=function(a){var b=document.body.style.display;document.body.style.display="none";this.Da(a);document.body.style.display=b};
l.Da=function(a){var b=window.getComputedStyle(a);"nowrap"==b.getPropertyValue("white-space")&&T(a,"white-space","normal");Hc(this,a,this.Da);var b=window.getComputedStyle(a),c,d,e;for(c=0;c<Dc.length;++c)d=Dc[c],(e=b.getPropertyValue(d))&&"100%"!=e&&"auto"!=e&&0<e.length&&"%"==e[e.length-1]&&T(a,d,"auto");c=a.tagName.toUpperCase();var f="UL"==c||"OL"==c,g="BODY"==c,h=!1,k="";for(c=0;c<Bc.length;++c){d=Bc[c];if(e=f)e=d.length-5,e=0<=e&&d.indexOf("-left",e)==e;e||g&&0==d.lastIndexOf("margin-",0)||
(e=R(b,d),null!=e&&(4<e?k+=d+":4px !important;":0>e&&(h=!0,"margin-bottom"==d&&(h=-30<e),h?k+=d+":0px !important;":a.setAttribute("data-pagespeed-negative-bottom-margin","1"))))}kc(a,k)};
l.Ta=function(a){Hc(this,a,this.Ta);if("IMG"==a.tagName.toUpperCase()){var b=window.getComputedStyle(a),c=jc(a,"width"),d=jc(a,"height");if(c&&d&&b){var e=R(b,"width"),b=R(b,"height");if(e&&b&&(e/=c,b/=d,.95<(e>b?b/e:e/b)||(console.log("aspect ratio problem for "+a.getAttribute("src")),1==a.naturalHeight&&1==a.naturalWidth?(b=Math.min(e,b),S(a,"width"),S(a,"height"),a.style.width=c*b,a.style.height=d*b):e>b?S(a,"height"):(S(a,"width"),S(a,"height"),a.style.maxHeight=d)),.25>e)){for(console.log("overshrinkage for "+
a.getAttribute("src"));a&&a.tagName&&"TD"!=a.tagName.toUpperCase();)a=a.parentNode;if(a&&(c=a.parentNode)){d=0;for(a=c.firstChild;a;a=a.nextSibling)a.tagName&&"TD"==a.tagName.toUpperCase()&&++d;if(1<d)for(d="width:"+Math.round(100/d)+"%;",c=c.firstChild;c;c=c.nextSibling)a=U(c),null!=a&&"TD"==a.tagName.toUpperCase()&&kc(a,d)}}}}};
l.Xa=function(a){var b=window.getComputedStyle(a).getPropertyValue("position");if("fixed"==b)return"fixed";if(a.classList.contains("nivoSlider"))return b;var c,d,e,f,g=[];c=null;var h,k=!1;for(d=a.firstChild;d;d=d.nextSibling)if(e=Fc(this,d),null!=e){var m=window.getComputedStyle(e);f=this.Xa(e);if("fixed"!=f&&null!=m&&null!=Fc(this,e)){"absolute"!=f||tc(m)||T(e,"position","relative");f=m.getPropertyValue("float");var n="right"==f;h="inline-block";if(n||"left"==f)n&&"right"==m.getPropertyValue("clear")&&
(n=!1,h="block",c&&k&&T(c,"margin-bottom","0px")),T(e,"float","none"),"none"!=m.getPropertyValue("display")&&T(e,"display",h);n&&g.push(e);c=e;e=R(m,"margin-bottom");k=null!=e&&0>e}}for(c=g.length-1;0<=c;--c)d=g[c],a.removeChild(d);for(c=g.length-1;0<=c;--c)d=g[c],a.appendChild(d);return b};
l.Ka=function(a){if("fixed"!=window.getComputedStyle(a).getPropertyValue("position")){var b,c,d,e=[],f=[];for(c=a.firstChild;c;c=c.nextSibling)if(d=Fc(this,c),null!=d){b=window.getComputedStyle(d);var g=b.getPropertyValue("position");"fixed"!=g&&"absolute"!=g&&0!=c.offsetWidth&&(e.push(d),f.push(b))}var h=null;for(c=0;c<e.length;++c)d=e[c],b=c<e.length-1?e[c+1]:null,g=d.offsetLeft+d.offsetWidth,(null==h||d.offsetLeft<h)&&(null==b||b.offsetLeft<g)&&(b=d,h=b.tagName.toUpperCase(),"INPUT"!=h&&"SELECT"!=
h&&(""==b.style.backgroundSize&&"auto"!=f[c].width&&T(b,"width","auto"),"IMG"!=h&&b.removeAttribute("width"),S(b,"border-left"),S(b,"border-right"),S(b,"margin-left"),S(b,"margin-right"),S(b,"padding-left"),S(b,"padding-right"),b.className=""!=b.className?b.className+" psSingleColumn":"psSingleColumn"),this.Ka(d)),a.getAttribute("data-pagespeed-negative-bottom-margin")&&(a.removeAttribute("data-pagespeed-negative-bottom-margin"),b=window.getComputedStyle(a),d=R(b,"height"),null!=d&&T(a,"margin-bottom",
""+-d+"px")),h=g}};var Mc=[Y.prototype.Wa,"shrink wide elements",Y.prototype.Xa,"string floats",Y.prototype.kb,"cleanup styles",Y.prototype.Ta,"repair distored images",Y.prototype.Ua,"resize if too wide",Y.prototype.Ka,"expand columns",Y.prototype.xb,"resize vertically"];function Nc(a){this.V=a;this.Ba=[]}function Oc(){this.U=-1;this.O=this.ub=null;this.u="";this.backgroundColor=this.hb=this.backgroundImage=this.fb=this.n=this.Q=null}l=Nc.prototype;l.Aa=20;l.za=10;l.ea=400;l.cb=400;l.ya=6E3;l.eb=.5;
function Pc(a,b,c,d){var e=sc(b),f="hidden"!=Qc(b),g=e.width*e.height,h=e.width>a.Aa&&e.height>a.za&&g>a.cb&&e.top<a.ya&&e.height<a.ea;if(f&&h&&g>=c){var g=f=null,k;for(k in pc)if(g=rc(b,pc[k])){f=pc[k];h=!0;if("IMG"==f){var m=Ic(a.V,b.src);m?(e.width=m.width,e.height=m.height):b.naturalWidth?(e.width=b.naturalWidth,e.height=b.naturalHeight):e.width&&e.height||(console.log("Image "+b.src+" may be the logo. It has not been loaded so may be missed."),h=!1);h&&(e.width<=a.Aa||e.height<=a.za||e.height>=
a.ea)&&(h=!1)}if(h)return a=new Oc,a.u=g,a.O=b,a.Q=f,a.n=e,a}}if(d)for(b=b.firstChild;b;b=b.nextSibling){if(e=U(b),null!=e&&(e=Pc(a,e,c,d)))return e}else if(b.parentNode&&(b=U(b.parentNode),null!=b))return Pc(a,b,c,d);return null}
function Rc(a,b,c){var d;a:{var e=sc(b);d="hidden"!=Qc(b);if(e.top<a.ya&&e.height<a.ea&&d){d=0;b.title&&(d+=z(b.title,"logo"));b.id&&(d+=z(b.id,"logo"));b.className&&(d+=z(b.className,"logo"));b.alt&&(d+=z(b.alt,"logo"));var f;f=document.domain.toLowerCase().split(".");var g=f.length;f=4<g&&2==f[g-3].length?f[g-5]:3<g?f[g-4]:null;g=0;f&&(b.id&&(d+=z(b.id,f)),b.className&&(d+=z(b.className,f)),b.title&&(g+=0<=W(b.title).indexOf(W(f))?1:0),b.alt&&(g+=0<=W(b.alt).indexOf(W(f))?1:0));var h=e.width*e.height,
k=h*a.eb,e=0;b.href&&b.href==window.location.origin+window.location.pathname&&++e;(k=Pc(a,b,k,!0))||(k=Pc(a,b,h,!1));if(k){h=k.u;if(!h||0<=h.indexOf("data:image/"))h="";else{var m=h.lastIndexOf("/");0>m?m=0:++m;var n=h.indexOf(".",m);0>n&&(n=h.length);h=h.substring(m,n)}b:{if(m=h)if(m=m.toLowerCase(),0<=m.indexOf("logo")&&0>m.indexOf("logout")&&0>m.indexOf("no_logo")&&0>m.indexOf("no-logo")){m=1;break b}m=0}h&&f&&(g+=0<=W(h).indexOf(W(f))?1:0);d=d+m+g+e;if(0<d){k.U=d;k.ub=b;d=k;break a}}}d=null}d&&
(a.Ba.push(d),++c);for(b=b.firstChild;b;b=b.nextSibling)d=U(b),null!=d&&Rc(a,d,c)}
function Sc(a){var b=null,c=a.Ba;if(!c||0==c.length)return null;if(1==c.length)return b=c[0];var d=0,e=Infinity,f;for(a=0;b=c[a];++a)f=b.n,e=Math.min(e,f.top),d=Math.max(d,f.bottom);for(a=0;b=c[a];++a)f=b.n,b.U*=Math.sqrt((d-f.top)/(d-e));for(a=f=0;b=c[a];++a)f=Math.max(f,b.U);d=[];for(a=0;b=c[a];++a)b.U==f&&d.push(b);if(1==d.length)return b=d[0];c=d[0];e=c.n;for(a=1;b=d[a];++a)if(f=b.n,e.top>f.top||e.top==f.top&&e.left>f.left||e.top==f.top&&e.left==f.left&&e.width*e.height>f.width*f.height)c=b,e=
c.n;return c}function Tc(a){if(a=document.defaultView.getComputedStyle(a,null)){var b=a.getPropertyValue("background-color");if(b){a:{a=b.indexOf("(");var c=b.lastIndexOf(")");if(a=0<=a&&c>a?b.substring(a+1,c):null){a=a.split(",");for(var b=[],c=0,d=a.length;c<d;++c)if(b[c]=3!=c?parseInt(a[c],10):parseFloat(a[c]),isNaN(b[c])){a=null;break a}a=3==b.length||4==b.length?b:null}else a="transparent"==b?[0,0,0,0]:null}if(a&&(3==a.length||4==a.length&&0!=a[3]))return a}}return null}
l.run=function(){if(!document.body)return null;Rc(this,document.body,0);var a;if((a=Sc(this))&&a.O){var b=a.O,c=null;if("IMG"==a.Q||"SVG"==a.Q)c=rc(b,"background-image");var d=Tc(b),e=null;for(b.parentNode&&(e=U(b.parentNode));e&&!c&&!d;)b=e,c=rc(b,"IMG")||rc(b,"SVG")||rc(b,"background-image"),d=Tc(b),e=b.parentNode?U(b.parentNode):null;a.fb=b;a.backgroundImage=c;a.backgroundColor=d||[255,255,255];a.hb=sc(b)}else a=null;return a};v("pagespeed.MobLogo.prototype.run",Nc.prototype.run);function Uc(){this.pa=[];this.$a=!0;this.L=this.a=this.B=this.T=this.Na=this.W=this.d=null;this.ka=this.X=0;this.$=!1}Uc.prototype.ab="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAQAAABNTyozAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwAACxMBAJqcGAAAATdJREFUeNrt0klOBTEQREHfDI7FTEn/4M2GBULQo22wK+ICKT1lKQAAAAAAAAAAAAAAAAAA/Jm7rmv3o+W5laU8d1uLspQYLc/SLVF8rsVoefokii9rMVqe9oni21qMlqdtovhhLUbL0y5R/LIWo+VZylKeuuX5t4nW8tRPFBtrMV6gmolic+t9xA/VSjRonl6JBs7TI9HgeVonmiDPvkSPmfO0SjRRnhaJJstTO9GEeWom2s7zVgZVI9HEeWokmjzPvkQPmfNcSZQkz9lEifKcSZQsz9FECfMcSZQ0z95E23ley8S2E6XOcz3R9HmuJUqR53yiNHnOJUqV53iidHmOJUqZZ3+itHn2JXopyd3kOZ9IntVE8qwmkmc1kTyrieRZTSTPaiJ5AAAAAAAAAAAAAAAAAGjgA62rM0XB6dNxAAAAAElFTkSuQmCC";
Uc.prototype.bb="R0lGODlhgACAAPAAAAAAAAAAACH5BAEAAAEALAAAAACAAIAAAAL+jI+pCL0Po5y02vuaBrj7D4bMtonmiXrkyqXuC7MsTNefLNv6nuE4D9z5fMFibEg0KkVI5PLZaTah1IlUWs0qrletl9v1VsFcMZQMNivRZHWRnXbz4G25jY621/B1vYuf54cCyCZ4QlhoGIIYqKjC2Oh4AZkoaUEZaWmF2acpwZnpuQAaKjpCWmbag5qqmsAa53oK6yT7SjtkO4r7o7vLS+K7Cuwg/EtsDIGcrMzLHOH8DM0qvUlabY2JXaG9zc3ojYEYLk5IXs53Pgmovo7XfskOTyE//1lv3/yeP53Or0/nH8CAAo/BKTjsIMJb/hYewOcwAMSF5iIamEixYcTMihY5bsRY0GNGkP9Ejtx3poUbk0GCrSR5Z8VLmDRyqBnXMokYnEJq7WT5J8wXni86ZQF3JJYWpCkILiXKBOUYpouAGqEU1eobSCCwHvXqDmxKrmHFPuH07drUbv3UUgHVFtVXuFuijVVLrNjbvLTm8pW79q/bu4LZ7i2M1i9isoEXQz3smObVyBqHUlZ483Kpn5qxCOrs+TNonYZG27RkuoSo1HpXj7YFWtjlZJGlId72l9wy3bjmweI3OJ/hkFqBO7U4KzTyuDKXaykAADs=";
function Vc(a,b){if(!Db(b))return!1;if("IMG"===b.tagName)return!a||null!==b.offsetParent;var c=b.getElementsByTagName("IMG");if(a){for(var d=c.length-1;0<=d;d--)if(null!==c[d].offsetParent)return!0;return!1}return 0<c.length}
function Wc(a){var b=a.parentNode;if(!b||0<b.getElementsByTagName("SCRIPT").length)return!1;for(var c=null!==a.offsetParent,d=!1,e=0,b=b.firstChild;b;b=b.nextSibling)if(b==a)d=!0;else if(null!==b.offsetParent||!c)if(3==b.nodeType||1==b.nodeType){if(Vc(c,b))return!1;var f=oa(b.textContent).length;if(0<f){if(d)return!1;e+=f;if(60<e)return!1}}return!0}
function Xc(a){a.d.style.top=window.scrollY+"px";a.d.style.left=window.scrollX+"px";var b="scale("+window.innerWidth/document.documentElement.clientWidth+")";a.d.style["-webkit-transform"]=b;a.d.style.transform=b;xb(a.d,"hide");b=a.d.offsetHeight;a.T.style.width=b+"px";a.T.style.height=b+"px";a.B.style.width=b+"px";a.B.style.height=b+"px";a.W.style.height=b+"px"}
function Yc(a){if(a.a){a.a.style.top=window.scrollY+"px";a.a.style.left=window.scrollX+"px";var b=.8*window.innerWidth/250,c=K(a.a,"open")?0:-250*b,c="scale("+b+") translatex("+c+"px)";a.a.style["-webkit-transform"]=c;a.a.style.transform=c;c=a.d.getBoundingClientRect();a.a.style.marginTop=c.height+"px";a.a.style.height=(window.innerHeight-c.height)/b+"px"}}
function Zc(a){Xc(a);Yc(a);window.addEventListener("scroll",u(function(a){null!=this.L&&(window.clearTimeout(this.L),this.L=null);this.L=window.setTimeout(u(function(){0==this.X&&(Yc(this),Xc(this));this.L=null},this),50);K(this.a,"open")&&!this.a.contains(a.target)&&(a.stopPropagation(),a.preventDefault())},a),!1);window.addEventListener("touchstart",u(function(a){this.X=a.targetTouches.length;this.ka=a.touches[0].clientY},a),!1);window.addEventListener("touchmove",u(function(a){this.$?a.preventDefault():
L(this.d,"hide")},a),!1);window.addEventListener("touchend",u(function(a){this.X=a.targetTouches.length;null==this.L&&0==this.X&&(Yc(this),Xc(this))},a),!1)}function $c(){if(window.psStaticJs||!window.psConversionLabel)return window.psPhoneNumber;var a=document.cookie.match(/(^|;| )gwcm=([^;]+)/);return a&&a[2]&&(a=ha(unescape(a[2])),a.fallback==window.psPhoneNumber&&a.clabel==window.psConversionLabel)?a.mobile_number:null}
v("psRequestDynamicPhoneNumberAndCall",function(){if(window.psConversionLabel&&window.psPhoneNumber){var a="https://www.googleadservices.com/pagead/conversion/"+window.psConversionId+"/wcm?cl="+escape(window.psConversionLabel)+"&fb="+escape(window.psPhoneNumber);window.psDebugMode&&alert("requesting dynamic phone number: "+a);(new cc(a,"callback")).send(null,ad,function(){window.psDebugMode&&alert("error callback called");window.psPhoneNumber&&bd(window.psPhoneNumber)})}});
function bd(a){location.href="tel:"+a}v("psDialPhone",bd);
function ad(a){var b=null;if(a&&a.wcm){var c=a.wcm;c&&(b=c.mobile_number)}b?(a={expires:c.expires,formatted_number:c.formatted_number,mobile_number:b,clabel:window.psConversionLabel,fallback:window.psPhoneNumber},a=ia(a),window.psDebugMode&&alert("saving phone in cookie: "+a),document.cookie="gwcm="+escape(a)+";path=/;max-age=7776000",bd(b),document.getElementById("psmob-phone-dialer").href='javascript:psDialPhone("'+b+'")'):window.psPhoneNumber&&(window.psDebugMode&&alert("receivePhoneNumber: "+
ia(a)),bd(window.psPhoneNumber))}function cd(a,b,c){var d=[];for(b=b.firstChild;b;b=b.nextSibling)"UL"==b.tagName?d=Ca(d,cd(a,b,c+1)):("A"==b.tagName&&(b.setAttribute("data-mobilize-nav-level",c),d.push(b)),d=Ca(d,cd(a,b,c)));return d}
function dd(){for(var a=document.querySelector(".psmob-nav-panel > ul a"),b={},c=[],d=0,e;e=a[d];d++)if(e.href in b){var f=e.innerHTML.toLowerCase();-1==b[e.href].indexOf(f)?b[e.href].push(f):"LI"==e.parentNode.tagName&&c.push(e.parentNode)}else b[e.href]=[],b[e.href].push(e.innerHTML.toLowerCase());for(d=0;a=c[d];d++)a.parentNode.removeChild(a)}
function fd(a){for(var b=a.a.querySelectorAll("*"),c=0,d;d=b[c];c++)d.removeAttribute("style"),d.removeAttribute("width"),d.removeAttribute("height"),"A"==d.tagName&&""==d.innerText&&d.hasAttribute("title")&&d.appendChild(document.createTextNode(d.getAttribute("title")));a=a.a.querySelectorAll("img:not(.psmob-menu-expand-icon)");for(c=0;b=a[c];++c)d=Math.min(2*b.naturalHeight,40),b.setAttribute("height",d)}
function gd(a){a.a=document.createElement("nav");document.body.insertBefore(a.a,a.d.nextSibling);L(a.a,"psmob-nav-panel");var b=document.createElement("ul");a.a.appendChild(b);L(b,"open");for(var c=0,d;d=a.pa[c];c++)if(d.parentNode){d.setAttribute("data-mobilize-nav-section",c);var e=cd(a,d,0),f=[];f.push(b);for(var g=0,h=e.length;g<h;g++){var k=e[g].getAttribute("data-mobilize-nav-level"),m=g+1==h?k:e[g+1].getAttribute("data-mobilize-nav-level");if(k<m){var n=document.createElement("li"),k=n.appendChild(document.createElement("div")),
m=document.createElement("img");k.appendChild(document.createElement("img"));m.setAttribute("src",a.ab);L(m,"psmob-menu-expand-icon");k.appendChild(document.createTextNode(e[g].textContent||e[g].innerText));f[f.length-1].appendChild(n);k=document.createElement("ul");n.appendChild(k);f.push(k)}else for(n=document.createElement("li"),f[f.length-1].appendChild(n),n.appendChild(e[g].cloneNode(!0)),n=k-m;0<n&&1<f.length;)f.pop(),n--}d.parentNode.removeChild(d)}dd();fd(a);a.a.addEventListener("touchmove",
u(function(a){if(this.$){var b=a.touches[0].clientY;if(1!=a.targetTouches.length)a.preventDefault();else{var c=b>this.ka,d=0==this.a.scrollTop,e=this.a.scrollTop>=this.a.scrollHeight-this.a.offsetHeight-1;(c&&d||!c&&e)&&a.preventDefault();a.stopImmediatePropagation();this.ka=b}}},a),!1);Yc(a)}function hd(a){yb(a.d,"open");yb(a.a,"open");yb(document.body,"noscroll");a.$=!a.$;Yc(a)}
function id(a){document.body.addEventListener("click",function(a){this.T.contains(a.target)?hd(this):K(this.a,"open")&&!this.a.contains(a.target)&&(hd(this),a.stopPropagation(),a.preventDefault())}.bind(a),!0)}function jd(){document.querySelector("nav.psmob-nav-panel > ul").addEventListener("click",function(a){a=Db(a.target)&&K(a.target,"psmob-menu-expand-icon")?a.target.parentNode:a.target;"DIV"==a.tagName&&(yb(a.nextSibling,"open"),yb(a.firstChild,"open"))},!1)};function kd(){this.Ma=null}
kd.prototype.mb=function(a,b,c){var d=document.createElement("span");d.id="psmob-logo-span";if(a&&a.u){var e=document.createElement("IMG");e.src=a.u;e.style.backgroundColor=V(b);e.id="psmob-logo-image";d.appendChild(e)}else d.textContent=window.location.host,d.style.color=V(c);e=document.createElement("button");L(e,"psmob-menu-button");var f=document.createElement("div");L(f,"psmob-hamburger-div");e.appendChild(f);for(var g=V(c),h=0;3>h;++h){var k=document.createElement("div");L(k,"psmob-hamburger-line");
k.style.backgroundColor=g;f.appendChild(k)}b=new qc(c,b,e,d);if(a&&a.O&&a.Q)switch(c=a.O,a.Q){case "IMG":case "SVG":c.parentNode.removeChild(c);break;case "background-image":c.style.backgroundImage="none"}this.nb(b)};function Z(){this.ga=0;this.S={};this.yb=Date.now();this.Fa=!1;this.J=this.va=this.Sa=this.k=this.C=0;this.oa=!1;this.wa=this.ra=0;this.la=new Y(this);this.la.Ja["ps-progress-scrim"]=!0}var ld=new ic(-1,-1);function md(a){if(0==a.J)if(console.log("mobilizing site"),window.psNavMode&&!nc()){++a.ra;var b=a.tb.bind(a);b||alert("Not expecting to start onloads after the callback is called");var c=new kd;c.nb=b;c.Ma=(new Nc(a)).run();(new vc).run(c.Ma,u(c.mb,c))}else nd(a);else a.oa=!0}
Z.prototype.tb=function(a){--this.ra;od(this,this.C,"extract theme");var b=new Uc;console.log("Starting nav resynthesis.");var c=[];if(window.pagespeedNavigationalIds)for(var d=window.pagespeedNavigationalIds.length,e={},f=0;f<d;f++){var g=window.pagespeedNavigationalIds[f],g=document.getElementById(g)||document.querySelector("[id="+uc(g)+"]"),h=g.parentNode;h?(h.id||(g.id.match(/^PageSpeed-.*-[0-9]+$/)?h.id=g.id.replace(/-[0-9]+$/,""):h.id="PageSpeed-"+g.id+"-P"),h.id in e?e[h.id]||c.push(g):(e[h.id]=
Wc(g),c.push(e[h.id]?h:g))):c.push(g)}b.pa=c;c=document.getElementsByTagName("*");for(d=0;e=c[d];d++)f=window.getComputedStyle(e),"fixed"==f.getPropertyValue("position")&&(g=e.getBoundingClientRect().top,e.style.top=String(60+g)+"px"),999999<=f.getPropertyValue("z-index")&&(console.log("Element z-index exceeded 999999, setting to 999998."),e.style.zIndex=999998);b.W=document.createElement("div");document.body.insertBefore(b.W,document.body.childNodes[0]);L(b.W,"psmob-header-spacer-div");b.d=document.createElement("header");
document.body.insertBefore(b.d,b.W);L(b.d,"psmob-header-bar");b.T=a.wb;b.d.appendChild(b.T);b.Na=a.vb;b.d.appendChild(b.Na);b.d.style.borderBottom="thin solid "+V(a.na);b.d.style.backgroundColor=V(a.Oa);window.psPhoneNumber&&(d=a.na,c=document.createElement("img"),c.id="psmob-phone-image",e=window.atob(b.bb),c.src="data:image/gif;base64,"+window.btoa(e.substring(0,13)+String.fromCharCode(d[0],d[1],d[2])+e.substring(16,e.length)),b.B=document.createElement("a"),b.B.id="psmob-phone-dialer",d=$c(),b.B.href=
d?'javascript:psDialPhone("'+d+'")':"javascript:psRequestDynamicPhoneNumberAndCall()",b.B.appendChild(c),b.d.appendChild(b.B));Zc(b);c=b.$a?V(a.Oa):"#3c78d8";a=b.$a?V(a.na):"white";d=document.createElement("style");d.type="text/css";d.appendChild(document.createTextNode(".psmob-header-bar { background-color: "+c+" }\n.psmob-nav-panel { background-color: "+a+" }\n.psmob-nav-panel > ul li { color: "+c+" }\n.psmob-nav-panel > ul li a { color: "+c+" }\n"));document.head.appendChild(d);0==b.pa.length||
nc()||(gd(b),id(b),jd());od(this,this.C,"navigation");nd(this)};Z.prototype.gb=function(a){this.S[a.src]=new ic(a.width,a.height);--this.J;od(this,1E3,"background image");0==this.J&&this.oa&&(md(this),this.oa=!1)};function pd(a,b){var c=Fc(a.la,b);if(null!=c){var d=mc(c);if(d&&(0==d.lastIndexOf("http://",0)||0==d.lastIndexOf("https://",0))&&!a.S[d]){a.S[d]=ld;var e=new Image;++a.J;e.onload=a.gb.bind(a,e);e.onerror=e.onload;e.src=d}for(c=c.firstChild;c;c=c.nextSibling)pd(a,c)}}
Z.prototype.xhrSendHook=function(){++this.ga};Z.prototype.xhrResponseHook=function(){--this.ga;this.k+=this.wa;nd(this)};
Z.prototype.rb=function(){qd(this,window.psDebugMode);this.C=oc(document.body);this.wa=Mc.length/2*this.C;this.k+=this.wa;window.psNavMode&&nc()&&(this.k+=this.C,this.k+=this.C);if(null!=document.body){for(var a in window.psMobStaticImageInfo){var b=window.psMobStaticImageInfo[a];this.S[a]=new ic(b.w,b.h)}pd(this,document.body)}this.k+=1E3*this.J;window.psLayoutMode&&window.pagespeedXhrHijackSetListener(this);md(this)};
function nd(a){if(0==a.ga&&0==a.ra&&0==a.J){if(window.psLayoutMode){var b=a.la;if(null!=document.body)for(var c=0;c<Mc.length;++c){Mc[c].call(b,document.body);++c;var d=b.V;od(d,d.C,Mc[c])}}if(a.Fa){if(a=document.getElementById("ps-progress-remove"))a.textContent="Remove Progress Bar and show mobilized site"}else rd()}}function Ic(a,b){var c=a.S[b];c==ld&&(c=null);return c}
function qd(a,b){a.Fa=b;var c=document.getElementById("ps-progress-log");c&&(c.style.color=b?"#333":"white");b&&(c=document.getElementById("ps-progress-show-log"))&&(c.style.display="none")}function Qc(a){var b=a.getAttribute("ps-save-visibility");b||((a=window.getComputedStyle(a))&&(b=a.getPropertyValue("visibility")),b||(b="visible"));return b}
function od(a,b,c){a.va+=b;b=100;0<a.k&&(b=Math.round(100*a.va/a.k),100<b&&(b=100));if(b!=a.Sa){var d=document.getElementById("ps-progress-span");d&&(d.style.width=b+"%");a.Sa=b}a=""+b+"% "+(Date.now()-a.yb)+"ms: "+c;console.log(a);if(c=document.getElementById("ps-progress-log"))c.textContent+=a+"\n"}function rd(){var a=document.getElementById("ps-progress-scrim");a&&(a.style.display="none",a.parentNode.removeChild(a))}var sd=new Z;window.addEventListener("load",u(sd.rb,sd));
v("psSetDebugMode",function(){qd(sd,!0)});v("psRemoveProgressBar",function(){rd()});})();
