(function(){var p,r=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"string"==typeof a}function u(a){return"function"==ba(a)}function ca(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function da(a,b,c){return a.call.apply(a.bind,arguments)}
function ea(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ea;return v.apply(null,arguments)}var fa=Date.now||function(){return+new Date};
function w(a,b){var c=a.split("."),d=r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function ga(a,b){function c(){}c.prototype=b.prototype;a.ya=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.xa=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function ha(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function ia(a){var b=[];ja(new ka,a,b);return b.join("")}function ka(){}
function ja(a,b,c){switch(typeof b){case "string":la(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==ba(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),ja(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),la(e,c),c.push(":"),ja(a,f,c),d=
","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ma={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},na=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function la(a,b){b.push('"',a.replace(na,function(a){if(a in ma)return ma[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ma[a]=e+b.toString(16)}),'"')};function oa(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function pa(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function x(a,b){this.width=a;this.height=b}p=x.prototype;p.clone=function(){return new x(this.width,this.height)};p.toString=function(){return"("+this.width+" x "+this.height+")"};p.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};p.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};p.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function qa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function ra(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function sa(a){var b=arguments.length;if(1==b&&"array"==ba(arguments[0]))return sa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};sa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));function z(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}ga(z,Error);z.prototype.name="CustomError";var ta=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function ua(a,b){return a<b?-1:a>b?1:0};function va(){this.b=this.a=null}var A=new function(a,b){this.d=100;this.c=a;this.e=b;this.b=0;this.a=null}(function(){return new wa},function(a){a.reset()});va.prototype.add=function(a,b){var c;0<A.b?(A.b--,c=A.a,A.a=c.next,c.next=null):c=A.c();c.a=a;c.b=b;c.next=null;this.b?this.b.next=c:this.a=c;this.b=c};va.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};function wa(){this.next=this.b=this.a=null}
wa.prototype.reset=function(){this.next=this.b=this.a=null};var B=Array.prototype,xa=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ya=B.filter?function(a,b,c){return B.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},za=B.some?function(a,b,c){return B.some.call(a,b,c)}:function(a,
b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function Aa(a){return B.concat.apply(B,arguments)}function Ba(a){return B.concat.apply(B,arguments)};function Ca(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}p=Ca.prototype;p.clone=function(){return new Ca(this.top,this.right,this.bottom,this.left)};p.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};p.contains=function(a){return this&&a?a instanceof Ca?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
p.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};p.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};p.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function Da(a,b){this.b={};this.a=[];this.d=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)Ea(this,arguments[d],arguments[d+1])}else if(a){if(a instanceof Da)d=a.I(),c=a.J();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=ra(a)}for(e=0;e<d.length;e++)Ea(this,d[e],c[e])}}p=Da.prototype;p.J=function(){Fa(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};p.I=function(){Fa(this);return this.a.concat()};
p.clear=function(){this.b={};this.d=this.c=this.a.length=0};p.remove=function(a){return C(this.b,a)?(delete this.b[a],this.c--,this.d++,this.a.length>2*this.c&&Fa(this),!0):!1};function Fa(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];C(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],C(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}function Ga(a,b){return C(a.b,b)?a.b[b]:void 0}
function Ea(a,b,c){C(a.b,b)||(a.c++,a.a.push(b),a.d++);a.b[b]=c}p.forEach=function(a,b){for(var c=this.I(),d=0;d<c.length;d++){var e=c[d];a.call(b,Ga(this,e),e,this)}};p.clone=function(){return new Da(this)};function C(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function D(a){var b=a[0],c=a[1];a=a[2];b=Number(b);c=Number(c);a=Number(a);if(isNaN(b)||0>b||255<b||isNaN(c)||0>c||255<c||isNaN(a)||0>a||255<a)throw Error('"('+b+","+c+","+a+'") is not a valid RGB color');b=Ha(b.toString(16));c=Ha(c.toString(16));a=Ha(a.toString(16));return"#"+b+c+a}function Ha(a){return 1==a.length?"0"+a:a}
function Ia(a,b,c){var d=0,e=0,f=0;if(0==b)f=e=d=c;else{var g=Math.floor(a/60),h=a/60-g;a=c*(1-b);var k=c*(1-b*h);b=c*(1-b*(1-h));switch(g){case 1:d=k;e=c;f=a;break;case 2:d=a;e=c;f=b;break;case 3:d=a;e=k;f=c;break;case 4:d=b;e=a;f=c;break;case 5:d=c;e=a;f=k;break;case 6:case 0:d=c,e=b,f=a}}return[Math.floor(d),Math.floor(e),Math.floor(f)]}
function Ja(a,b,c){var d=Math.max(Math.max(a,b),c),e=Math.min(Math.min(a,b),c);if(e==d)e=a=0;else{var f=d-e,e=f/d;a=60*(a==d?(b-c)/f:b==d?2+(c-a)/f:4+(a-b)/f);0>a&&(a+=360);360<a&&(a-=360)}return[a,e,d]};function Ka(a){if(a.classList)return a.classList;a=a.className;return t(a)&&a.match(/\S+/g)||[]}function E(a,b){var c;a.classList?c=a.classList.contains(b):(c=Ka(a),c=0<=xa(c,b));return c}function F(a,b){a.classList?a.classList.add(b):E(a,b)||(a.className+=0<a.className.length?" "+b:b)}function La(a,b){a.classList?a.classList.remove(b):E(a,b)&&(a.className=ya(Ka(a),function(a){return a!=b}).join(" "))}function G(a,b){E(a,b)?La(a,b):F(a,b)};var H;a:{var Ma=r.navigator;if(Ma){var Na=Ma.userAgent;if(Na){H=Na;break a}}H=""}function I(a){return-1!=H.indexOf(a)};function Oa(){return I("Opera")||I("OPR")};function Pa(a){r.setTimeout(function(){throw a;},0)}var Qa;
function Ra(){var a=r.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!I("Presto")&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=v(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!I("Trident")&&!I("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.V;c.V=null;a()}};return function(a){d.next={V:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){r.setTimeout(a,0)}};function Sa(a,b){Ta||Ua();Va||(Ta(),Va=!0);Wa.add(a,b)}var Ta;function Ua(){if(r.Promise&&r.Promise.resolve){var a=r.Promise.resolve();Ta=function(){a.then(Xa)}}else Ta=function(){var a=Xa;!u(r.setImmediate)||r.Window&&r.Window.prototype&&r.Window.prototype.setImmediate==r.setImmediate?(Qa||(Qa=Ra()),Qa(a)):r.setImmediate(a)}}var Va=!1,Wa=new va;function Xa(){for(var a=null;a=Wa.remove();){try{a.a.call(a.b)}catch(b){Pa(b)}var c=A;c.e(a);c.b<c.d&&(c.b++,a.next=c.a,c.a=a)}Va=!1};function J(a,b){this.b=K;this.f=void 0;this.a=this.c=null;this.d=this.e=!1;if(a==Ya)L(this,Za,b);else try{var c=this;a.call(b,function(a){L(c,Za,a)},function(a){if(!(a instanceof $a))try{if(a instanceof Error)throw a;throw Error("Promise rejected.");}catch(b){}L(c,M,a)})}catch(d){L(this,M,d)}}var K=0,Za=2,M=3;function Ya(){}J.prototype.then=function(a,b,c){return ab(this,u(a)?a:null,u(b)?b:null,c)};oa(J);J.prototype.cancel=function(a){this.b==K&&Sa(function(){var b=new $a(a);bb(this,b)},this)};
function bb(a,b){if(a.b==K)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.v)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.b==K&&1==d?bb(c,b):(d=c.a.splice(e,1)[0],cb(c,d,M,b)))}a.c=null}else L(a,M,b)}function db(a,b){a.a&&a.a.length||a.b!=Za&&a.b!=M||eb(a);a.a||(a.a=[]);a.a.push(b)}
function ab(a,b,c,d){var e={v:null,aa:null,ba:null};e.v=new J(function(a,g){e.aa=b?function(c){try{var e=b.call(d,c);a(e)}catch(m){g(m)}}:a;e.ba=c?function(b){try{var e=c.call(d,b);void 0===e&&b instanceof $a?g(b):a(e)}catch(m){g(m)}}:g});e.v.c=a;db(a,e);return e.v}J.prototype.j=function(a){this.b=K;L(this,Za,a)};J.prototype.k=function(a){this.b=K;L(this,M,a)};
function L(a,b,c){if(a.b==K){if(a==c)b=M,c=new TypeError("Promise cannot resolve to itself");else{if(pa(c)){a.b=1;c.then(a.j,a.k,a);return}if(ca(c))try{var d=c.then;if(u(d)){fb(a,c,d);return}}catch(e){b=M,c=e}}a.f=c;a.b=b;a.c=null;eb(a);b!=M||c instanceof $a||gb(a,c)}}function fb(a,b,c){function d(b){f||(f=!0,a.k(b))}function e(b){f||(f=!0,a.j(b))}a.b=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function eb(a){a.e||(a.e=!0,Sa(a.m,a))}
J.prototype.m=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=null;for(var b=0;b<a.length;b++)cb(this,a[b],this.b,this.f)}this.e=!1};function cb(a,b,c,d){b.v&&(b.v.c=null);if(c==Za)b.aa(d);else{if(b.v)for(;a&&a.d;a=a.c)a.d=!1;b.ba(d)}}function gb(a,b){a.d=!0;Sa(function(){a.d&&hb.call(null,b)})}var hb=Pa;function $a(a){z.call(this,a)}ga($a,z);$a.prototype.name="cancel";var ib=Oa(),N=I("Trident")||I("MSIE"),jb=I("Gecko")&&-1==H.toLowerCase().indexOf("webkit")&&!(I("Trident")||I("MSIE")),kb=-1!=H.toLowerCase().indexOf("webkit");function lb(){var a=r.document;return a?a.documentMode:void 0}var mb=function(){var a="",b;if(ib&&r.opera)return a=r.opera.version,u(a)?a():a;jb?b=/rv\:([^\);]+)(\)|;)/:N?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:kb&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(H))?a[1]:"");return N&&(b=lb(),b>parseFloat(a))?String(b):a}(),nb={};
function ob(a){if(!nb[a]){for(var b=0,c=ta(String(mb)).split("."),d=ta(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var l=k.exec(g)||["","",""],q=m.exec(h)||["","",""];if(0==l[0].length&&0==q[0].length)break;b=ua(0==l[1].length?0:parseInt(l[1],10),0==q[1].length?0:parseInt(q[1],10))||ua(0==l[2].length,0==q[2].length)||ua(l[2],q[2])}while(0==b)}nb[a]=0<=b}}
var pb=r.document,qb=pb&&N?lb()||("CSS1Compat"==pb.compatMode?parseInt(mb,10):5):void 0;var rb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function sb(a){if(tb){tb=!1;var b=r.location;if(b){var c=b.href;if(c&&(c=ub(sb(c)[3]||null))&&c!=b.hostname)throw tb=!0,Error();}}return a.match(rb)}var tb=kb;function ub(a){return a?decodeURI(a):a}
function vb(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g," ")):"")}};function wb(a,b){var c;a instanceof wb?(this.B=void 0!==b?b:a.B,xb(this,a.G),this.U=a.U,this.H=a.H,yb(this,a.S),this.R=a.R,zb(this,a.a.clone()),this.Q=a.Q):a&&(c=sb(String(a)))?(this.B=!!b,xb(this,c[1]||"",!0),this.U=Ab(c[2]||""),this.H=Ab(c[3]||"",!0),yb(this,c[4]),this.R=Ab(c[5]||"",!0),zb(this,c[6]||"",!0),this.Q=Ab(c[7]||"")):(this.B=!!b,this.a=new Bb(null,0,this.B))}p=wb.prototype;p.G="";p.U="";p.H="";p.S=null;p.R="";p.Q="";p.B=!1;
p.toString=function(){var a=[],b=this.G;b&&a.push(Cb(b,Db,!0),":");if(b=this.H){a.push("//");var c=this.U;c&&a.push(Cb(c,Db,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.S;null!=b&&a.push(":",String(b))}if(b=this.R)this.H&&"/"!=b.charAt(0)&&a.push("/"),a.push(Cb(b,"/"==b.charAt(0)?Eb:Fb,!0));(b=this.a.toString())&&a.push("?",b);(b=this.Q)&&a.push("#",Cb(b,Gb));return a.join("")};p.clone=function(){return new wb(this)};
function xb(a,b,c){a.G=c?Ab(b,!0):b;a.G&&(a.G=a.G.replace(/:$/,""))}function yb(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.S=b}else a.S=null}function zb(a,b,c){b instanceof Bb?(a.a=b,Hb(a.a,a.B)):(c||(b=Cb(b,Ib)),a.a=new Bb(b,0,a.B))}function Jb(a,b,c){"array"==ba(c)||(c=[String(c)]);Kb(a.a,b,c)}function Ab(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}
function Cb(a,b,c){return t(a)?(a=encodeURI(a).replace(b,Lb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Lb(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Db=/[#\/\?@]/g,Fb=/[\#\?:]/g,Eb=/[\#\?]/g,Ib=/[\#\?@]/g,Gb=/#/g;function Bb(a,b,c){this.a=a||null;this.b=!!c}function Mb(a){a.l||(a.l=new Da,a.t=0,a.a&&vb(a.a,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}p=Bb.prototype;p.l=null;p.t=null;
p.add=function(a,b){Mb(this);this.a=null;a=Nb(this,a);var c=Ga(this.l,a);c||Ea(this.l,a,c=[]);c.push(b);this.t++;return this};p.remove=function(a){Mb(this);a=Nb(this,a);return C(this.l.b,a)?(this.a=null,this.t-=Ga(this.l,a).length,this.l.remove(a)):!1};p.clear=function(){this.l=this.a=null;this.t=0};p.I=function(){Mb(this);for(var a=this.l.J(),b=this.l.I(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
p.J=function(a){Mb(this);var b=[];if(t(a)){var c=a;Mb(this);c=Nb(this,c);C(this.l.b,c)&&(b=Aa(b,Ga(this.l,Nb(this,a))))}else for(a=this.l.J(),c=0;c<a.length;c++)b=Aa(b,a[c]);return b};function Kb(a,b,c){a.remove(b);if(0<c.length){a.a=null;var d=a.l;b=Nb(a,b);var e;e=c.length;if(0<e){for(var f=Array(e),g=0;g<e;g++)f[g]=c[g];e=f}else e=[];Ea(d,b,e);a.t+=c.length}}
p.toString=function(){if(this.a)return this.a;if(!this.l)return"";for(var a=[],b=this.l.I(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.J(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.a=a.join("&")};p.clone=function(){var a=new Bb;a.a=this.a;this.l&&(a.l=this.l.clone(),a.t=this.t);return a};function Nb(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c}
function Hb(a,b){b&&!a.b&&(Mb(a),a.a=null,a.l.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Kb(this,e,a))},a));a.b=b};var Ob;if(!(Ob=!jb&&!N)){var Pb;if(Pb=N)Pb=N&&9<=qb;Ob=Pb}Ob||jb&&ob("1.9.1");N&&ob("9");function Qb(a,b){qa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Rb?a.setAttribute(Rb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var Rb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Sb(a){return ca(a)&&1==a.nodeType};function Tb(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}N&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Ub(a,b){var c;a:{c=9==b.nodeType?b:b.ownerDocument||b.document;if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(b,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}if("none"!=(c||(b.currentStyle?b.currentStyle.display:null)||b.style&&b.style.display))return a(b);c=b.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";var g=a(b);c.display=d;c.position=f;c.visibility=e;return g}
function Vb(a){var b=a.offsetWidth,c=a.offsetHeight,d=kb&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Tb(a),new x(a.right-a.left,a.bottom-a.top)):new x(b,c)}function Wb(a){if(!a.getBoundingClientRect)return null;a=Ub(Tb,a);return new x(a.right-a.left,a.bottom-a.top)};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function O(a,b){this.e=[];this.s=a;this.r=b||null;this.d=this.a=!1;this.c=void 0;this.m=this.D=this.j=!1;this.f=0;this.b=null;this.k=0}O.prototype.cancel=function(a){if(this.a)this.c instanceof O&&this.c.cancel();else{if(this.b){var b=this.b;delete this.b;a?b.cancel(a):(b.k--,0>=b.k&&b.cancel())}this.s?this.s.call(this.r,this):this.m=!0;this.a||(a=new Xb,Yb(this),Zb(this,!1,a))}};O.prototype.q=function(a,b){this.j=!1;Zb(this,a,b)};function Zb(a,b,c){a.a=!0;a.c=c;a.d=!b;$b(a)}
function Yb(a){if(a.a){if(!a.m)throw new ac;a.m=!1}}function bc(a,b,c,d){a.e.push([b,c,d]);a.a&&$b(a)}O.prototype.then=function(a,b,c){var d,e,f=new J(function(a,b){d=a;e=b});bc(this,d,function(a){a instanceof Xb?f.cancel():e(a)});return f.then(a,b,c)};oa(O);function cc(a){return za(a.e,function(a){return u(a[1])})}
function $b(a){if(a.f&&a.a&&cc(a)){var b=a.f,c=dc[b];c&&(r.clearTimeout(c.C),delete dc[b]);a.f=0}a.b&&(a.b.k--,delete a.b);for(var b=a.c,d=c=!1;a.e.length&&!a.j;){var e=a.e.shift(),f=e[0],g=e[1],e=e[2];if(f=a.d?g:f)try{var h=f.call(e||a.r,b);void 0!==h&&(a.d=a.d&&(h==b||h instanceof Error),a.c=b=h);pa(b)&&(d=!0,a.j=!0)}catch(k){b=k,a.d=!0,cc(a)||(c=!0)}}a.c=b;d&&(h=v(a.q,a,!0),d=v(a.q,a,!1),b instanceof O?(bc(b,h,d),b.D=!0):b.then(h,d));c&&(b=new ec(b),dc[b.C]=b,a.f=b.C)}
function ac(){z.call(this)}ga(ac,z);ac.prototype.message="Deferred has already fired";ac.prototype.name="AlreadyCalledError";function Xb(){z.call(this)}ga(Xb,z);Xb.prototype.message="Deferred was canceled";Xb.prototype.name="CanceledError";function ec(a){this.C=r.setTimeout(v(this.b,this),0);this.a=a}ec.prototype.b=function(){delete dc[this.C];throw this.a;};var dc={};function fc(a,b){var c=b||{},d=c.document||document,e=document.createElement("SCRIPT"),f={ha:e,T:void 0},g=new O(gc,f),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){hc(e,!0);var b=new ic(jc,"Timeout reached for loading script "+a);Yb(g);Zb(g,!1,b)},k),f.T=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(hc(e,c.pa||!1,h),Yb(g),Zb(g,!0,null))};e.onerror=function(){hc(e,!0,h);var b=new ic(kc,"Error while loading script "+
a);Yb(g);Zb(g,!1,b)};Qb(e,{type:"text/javascript",charset:"UTF-8",src:a});lc(d).appendChild(e);return g}function lc(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}function gc(){if(this&&this.ha){var a=this.ha;a&&"SCRIPT"==a.tagName&&hc(a,!0,this.T)}}function hc(a,b,c){null!=c&&r.clearTimeout(c);a.onload=aa;a.onerror=aa;a.onreadystatechange=aa;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var kc=0,jc=1;
function ic(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);z.call(this,c)}ga(ic,z);function mc(a,b){this.b=new wb(a);this.a=b?b:"callback";this.T=5E3}var nc=0;mc.prototype.send=function(a,b,c,d){a=a||null;d=d||"_"+(nc++).toString(36)+fa().toString(36);r._callbacks_||(r._callbacks_={});var e=this.b.clone();if(a)for(var f in a)a.hasOwnProperty&&!a.hasOwnProperty(f)||Jb(e,f,a[f]);b&&(r._callbacks_[d]=oc(d,b),Jb(e,this.a,"_callbacks_."+d));b=fc(e.toString(),{timeout:this.T,pa:!0});bc(b,null,pc(d,a,c),void 0);return{C:d,Y:b}};
mc.prototype.cancel=function(a){a&&(a.Y&&a.Y.cancel(),a.C&&qc(a.C,!1))};function pc(a,b,c){return function(){qc(a,!1);c&&c(b)}}function oc(a,b){return function(c){qc(a,!0);b.apply(void 0,arguments)}}function qc(a,b){r._callbacks_[a]&&(b?delete r._callbacks_[a]:r._callbacks_[a]=aa)};function rc(){this.height=this.width=this.bottom=this.right=this.left=this.top=0}function sc(a,b){this.width=a;this.height=b}function P(a){var b=null;if(a&&"string"==typeof a){var c=a.indexOf("px");-1!=c&&(a=a.substring(0,c));c=a.length-1;a.length<=c?c=!1:(c=a.charCodeAt(c),c=48<=c&&57>=c);c&&(b=parseInt(a,10),isNaN(b)&&(b=null))}return b}function Q(a,b){var c=null;a&&(c=P(a.getPropertyValue(b)));return c}function R(a,b){a.style&&a.style.removeProperty(b);a.removeAttribute(b)}
function tc(a,b){var c=null;a.style&&(c=P(a.style.getPropertyValue(b)));null==c&&(c=P(a.getAttribute(b)));return c}function S(a,b,c){a.style.setProperty(b,c,"important")}function uc(a,b){if(b&&0!=b.length){var c=a.getAttribute("style")||"";0<c.length&&";"!=c[c.length-1]&&(c+=";");a.setAttribute("style",c+b)}}
function vc(a){a=a.getBoundingClientRect();var b=document.body,c=document.documentElement||b.parentNode||b,b="pageXOffset"in window?window.pageXOffset:c.scrollLeft,c="pageYOffset"in window?window.pageYOffset:c.scrollTop;return new Ca(a.top+c,a.right+b,a.bottom+c,a.left+b)}
function wc(a){var b=null,b=a.nodeName.toUpperCase();return"SCRIPT"!=b&&"STYLE"!=b&&a.style&&(a=window.getComputedStyle(a))&&(b=a.getPropertyValue("background-image"),"none"==b&&(b=null),b&&5<b.length&&0==b.indexOf("url(")&&")"==b[b.length-1])?b=b.substring(4,b.length-1):null}function xc(){if(null!=window.parent&&window!=window.parent)try{if(window.parent.document.domain==document.domain)return!0}catch(a){}return!1}function yc(a){var b=1;for(a=a.firstChild;a;a=a.nextSibling)b+=yc(a);return b}
function T(a){return Sb(a)?a:null}var zc={va:"IMG",wa:"SVG",ua:"background-image"};w("pagespeed.MobUtil.ImageSource",zc);function Ac(a,b,c,d,e){this.o=a;this.u=b;this.b=c;this.p=e;this.a=d}function U(a){for(var b=0,c=a.length;b<c;++b){var d=Math.round(a[b]);0>d?d=0:255<d&&(d=255);a[b]=d}return D(a)}function Bc(a){a=a.toLowerCase();for(var b="",c=0,d=a.length;c<d;++c){var e=a.charAt(c);if("a"<=e&&"z">=e||"0"<=e&&"9">=e)b+=e}return b}
function Cc(a){return 0!=a.lastIndexOf(document.location.origin+"/",0)&&0!=a.lastIndexOf("data:image/",0)}function Dc(a){a=vc(a);var b=new rc;b.top=a.top;b.bottom=a.bottom;b.left=a.left;b.right=a.right;b.height=a.bottom-a.top;b.width=a.right-a.left;return b}function Ec(a){var b=P(a.top);a=P(a.left);return null!=b&&-100>b||null!=a&&-100>a}function Fc(a){a=a.replace(/\\/g,"\\\\");a=a.replace(/"/g,'\\"');a=a.replace(/\n/g,"\\a ");a=a.replace(/\f/g,"\\c ");a=a.replace(/\r/g,"\\d ");return'"'+a+'"'}
function V(a){console&&console.log&&console.log(a)};function Gc(){}function Hc(a,b){this.a=a;this.b=b}function Ic(a,b){if(3!=a.length||3!=b.length)return Infinity;var c=a[0]-b[0],d=a[1]-b[1],e=a[2]-b[2];return Math.sqrt(c*c+d*d+e*e)}function Jc(a){a/=255;return a=.03928>=a?a/12.92:Math.pow((a+.055)/1.055,2.4)}
function Kc(a){var b=a.a,c=a.b,d=.2126*Jc(b[0])+.7152*Jc(b[1])+.0722*Jc(b[2]),e=.2126*Jc(c[0])+.7152*Jc(c[1])+.0722*Jc(c[2]);if(1E-10>d&&1E-10>e)return a;d=e/d;1>d&&(d=1/d);if(3<d)return a;b=Ja(b[0],b[1],b[2]);c=Ja(c[0],c[1],c[2]);d=a=null;b[2]<c[2]?(a=b[2],d=c[2]):(a=c[2],d=b[2]);e=(3*a-d)/4;a=a>e?a-e:0;d=d<1-2*e?d+2*e:255;b[2]<c[2]?(b[2]=a,c[2]=d):(c[2]=a,b[2]=d);b=Ia(b[0],b[1],b[2]);c=Ia(c[0],c[1],c[2]);return new Hc(b,c)}
function Lc(a,b,c,d){var e=[],f,g,h;for(g=0;g<d;++g)for(f=0;f<c;++f){var k=4*(g*c+f);h=3*(g*c+f);var m=a[k+3]/255,l=1-m;e[h]=m*a[k]+l*b[0];e[h+1]=m*a[k+1]+l*b[1];e[h+2]=m*a[k+2]+l*b[2]}k=[0,0,0];for(f=m=g=0;f<c;++f)l=(d-1)*c+f,h=3*l,k[0]+=e[h],k[1]+=e[h+1],k[2]+=e[h+2],m+=a[4*l+3],++g;if(m>127.5*g)for(f=0;3>f;++f)k[f]=Math.floor(k[f]/g);else k=b;a=Math.floor(.25*c);b=Math.floor(.75*c);m=Math.floor(.25*d);d=Math.floor(.75*d);var l=0,q=[];for(g=m;g<=d;++g)for(f=a;f<=b;++f)h=3*(g*c+f),q[l]=Ic(e.slice(h,
h+3),k),++l;f=q.sort(function(a,b){return a-b});var y=Math.max(1,f[Math.floor(.75*l)]),l=0,q=[0,0,0];for(g=m;g<=d;++g)for(f=a;f<=b;++f)h=3*(g*c+f),Ic(e.slice(h,h+3),k)>=y&&(q[0]+=e[h],q[1]+=e[h+1],q[2]+=e[h+2],++l);if(0<l)for(f=0;3>f;++f)q[f]=Math.floor(q[f]/l);return Kc(new Hc(k,q))}
Gc.prototype.run=function(a,b){if(a)if(Cc(a.src))V("Found logo but its origin is different from that of HTML. Using default color.");else{V("Found logo. Theme color will be computed from logo.");var c=b||[255,255,255],d=a.naturalWidth,e=a.naturalHeight,f=document.createElement("CANVAS");f.width=d;f.height=e;f=f.getContext("2d");f.drawImage(a,0,0);f=f.getImageData(0,0,d,e);return Lc(f.data,c,d,e)}else V("Did not find logo. Using default color.");c=[0,0,0];b?178.5>=Ja(b[0],b[1],b[2])[2]&&(c=[255,255,
255]):b=[255,255,255];return new Hc(b,c)};function W(a){this.b=a;this.c={};if(a=window.document.documentElement.clientWidth){var b=window.document.body;if(b)for(var b=window.getComputedStyle(b),c=["padding-left","padding-right"],d=0;d<c.length;++d){var e=Q(b,c[d]);e&&(a-=e)}}else a=400;this.a=a;V("window.pagespeed.MobLayout.maxWidth="+this.a)}function X(a,b){this.a=a;this.b=b}
var Mc="padding-left padding-bottom padding-right padding-top margin-left margin-bottom margin-right margin-top border-left-width border-bottom-width border-right-width border-top-width left top".split(" "),Nc={A:!0,DIV:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,P:!0,SPAN:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0},Oc=["left","width"];
function Pc(a,b){if(!b)return!0;var c=b.nodeName.toUpperCase();return"SCRIPT"==c||"STYLE"==c||"IFRAME"==c||Boolean(b.id&&a.c[b.id])||E(b,"psmob-nav-panel")||E(b,"psmob-header-bar")||E(b,"psmob-header-spacer-div")||E(b,"psmob-logo-span")}function Qc(a,b){var c=T(b);return Pc(a,c)?null:c}function Rc(a){var b=[];for(a=a.firstChild;a;a=a.nextSibling)null!=T(a)&&b.push(a);return b}function Sc(a,b,c){for(b=b.firstChild;b;b=b.nextSibling)null!=Qc(a,b)&&c.call(a,b)}p=W.prototype;
p.ia=function(a){var b=window.getComputedStyle(a),c=wc(a);if(c){var c=Tc(this.b,c),d;if(d=c&&c.width&&c.height)"auto"==b.getPropertyValue("background-size")?d=!1:(d=b.getPropertyValue("background-position"),"none"==d?d=!1:(d=d.split(" "),d=2==d.length&&null!=P(d[0])&&null!=P(d[1])?!0:!1)),d=!d;if(d){d=c.width;c=c.height;if(d>this.a){c=Math.round(this.a/d*c);d="background-size:"+this.a+"px "+c+"px;background-repeat:no-repeat;";var e=Q(b,"height");c==e&&(d+="height:"+c+"px;");uc(a,d)}S(a,"min-height",
""+c+"px")}}if("PRE"==a.nodeName.toUpperCase()||"pre"==b.getPropertyValue("white-space")&&a.offsetWidth>this.a)a.style.overflowX="scroll";Sc(this,a,this.ia)};function Uc(a){S(a,"overflow-x","auto");S(a,"width","auto");S(a,"display","block")}p.qa=function(a){Vc(this,a,0)};
function Vc(a,b,c){var d;if(d=vc(b))c=d.top,d=d.bottom;else{if(b.offsetParent==b.parentNode)c+=b.offsetTop;else if(b.offsetParent!=b.parentNode.parentNode)return null;d=c+b.offsetHeight-1}if(Pc(a,b))return d;d=c-1;var e=window.getComputedStyle(b);if(!e)return null;var f=Q(e,"min-height");null!=f&&(d+=f);for(var f=c+b.offsetHeight-1,g=!1,h=!1,k,m=b.firstChild;m;m=m.nextSibling)if(k=T(m)){var l=window.getComputedStyle(k);l&&("absolute"!=l.position||Ec(l)||"0px"==l.getPropertyValue("height")||"hidden"==
l.getPropertyValue("visibility")||(h=!0));k=Vc(a,k,c);null!=k&&(g=!0,d=Math.max(d,k))}if("fixed"==e.getPropertyValue("position")&&g)return null;a=b.nodeName.toUpperCase();"BODY"!=a&&(e=f-c+1,g?d!=f&&(h?S(b,"height",""+(d-c+1)+"px"):S(b,"height","auto")):("IMG"!=a&&0<e&&""==b.style.backgroundSize&&(R(b,"height"),S(b,"height","auto"),b.offsetHeight&&(f=c+b.offsetHeight)),d=f));return d}
p.fa=function(a){for(var b=Rc(a),c=0;c<b.length;++c)this.fa(b[c]);if(!(a.offsetWidth<=this.a))if(b=a.nodeName.toUpperCase(),"TABLE"==b){a:{b=0;for(c=a.firstChild;c;c=c.nextSibling)for(var d=c.firstChild;d;d=d.nextSibling){var e=c.nodeName.toUpperCase();if("THEAD"==e||"TFOOT"==e){b=!0;break a}for(e=d.firstChild;e;e=e.nextSibling){if("TH"==e.nodeName.toUpperCase()){b=!0;break a}++b}}b=3*Wc(this,a)>b?!1:!0}if(b)Uc(a);else if("CSS1Compat"!==document.compatMode){var f,g,h,k=document.createElement("DIV");
k.style.display="inline-block";for(var m=Rc(a),b=0;b<m.length;++b)for(var l=Rc(m[b]),c=0;c<l.length;++c)for(var q=Rc(l[c]),d=0;d<q.length;++d)if(g=q[d],1==g.childNodes.length)f=g.childNodes[0],g.removeChild(f),k.appendChild(f);else if(1<g.childNodes.length){h=document.createElement("DIV");h.style.display="inline-block";for(var y=Rc(g),e=0;e<y.length;++e)f=y[e],g.removeChild(f),h.appendChild(f);k.appendChild(h)}a.parentNode.replaceChild(k,a)}else for(R(a,"width"),S(a,"max-width","100%"),a=a.firstChild;a;a=
a.nextSibling)if(b=T(a),null!=b)for(R(b,"width"),S(b,"max-width","100%"),b=b.firstChild;b;b=b.nextSibling)if(c=T(b),null!=c&&"TR"==c.nodeName.toUpperCase())for(R(c,"width"),S(c,"max-width","100%"),c=c.firstChild;c;c=c.nextSibling)d=T(c),null!=d&&"TD"==d.nodeName.toUpperCase()&&(S(d,"max-width","100%"),S(d,"display","inline-block"))}else{c=null;d=a.offsetWidth;e=a.offsetHeight;f="img";if("IMG"==b)c=a.getAttribute("src");else if(f="background-image",c=wc(a),g=null==c?null:Tc(this.b,c))d=g.width,e=g.height;
null!=c?(g=d/this.a,1<g&&(g=e/g,V("Shrinking "+f+" "+c+" from "+d+"x"+e+" to "+this.a+"x"+g),"IMG"==b?(S(a,"width",""+this.a+"px"),S(a,"height",""+g+"px")):S(a,"background-size",""+this.a+"px "+g+"px"))):"CODE"==b||"PRE"==b||"UL"==b?Uc(a):Nc[b]?(S(a,"max-width","100%"),R(a,"width")):V("Punting on resize of "+b+" which wants to be "+a.offsetWidth+" but this.maxWidth_="+this.a)}};
function Wc(a,b){var c=0,d=b.nodeName.toUpperCase();"DIV"!=d&&"TABLE"!=d&&"UL"!=d||++c;for(d=b.firstChild;d;d=d.nextSibling){var e=T(d);null!=e&&(c+=Wc(a,e))}return c}p.oa=function(a){var b=document.body.style.display;document.body.style.display="none";this.W(a);document.body.style.display=b};
p.W=function(a){var b=window.getComputedStyle(a);"nowrap"==b.getPropertyValue("white-space")&&S(a,"white-space","normal");Sc(this,a,this.W);var b=window.getComputedStyle(a),c,d,e;for(c=0;c<Oc.length;++c)d=Oc[c],(e=b.getPropertyValue(d))&&"100%"!=e&&"auto"!=e&&0<e.length&&"%"==e[e.length-1]&&S(a,d,"auto");c=a.nodeName.toUpperCase();var f="UL"==c||"OL"==c,g="BODY"==c,h=!1,k="";for(c=0;c<Mc.length;++c){d=Mc[c];if(e=f)e=d.length-5,e=0<=e&&d.indexOf("-left",e)==e;e||g&&0==d.lastIndexOf("margin-",0)||(e=
Q(b,d),null!=e&&(4<e?k+=d+":4px !important;":0>e&&(h=!0,"margin-bottom"==d&&(h=-30<e),h?k+=d+":0px !important;":a.setAttribute("data-pagespeed-negative-bottom-margin","1"))))}uc(a,k)};
p.ea=function(a){Sc(this,a,this.ea);if("IMG"==a.nodeName.toUpperCase()){var b=window.getComputedStyle(a),c=tc(a,"width"),d=tc(a,"height");if(c&&d&&b){var e=Q(b,"width"),b=Q(b,"height");if(e&&b&&(e/=c,b/=d,.95<(e>b?b/e:e/b)||(V("aspect ratio problem for "+a.getAttribute("src")),1==a.naturalHeight&&1==a.naturalWidth?(b=Math.min(e,b),R(a,"width"),R(a,"height"),a.style.width=c*b,a.style.height=d*b):e>b?R(a,"height"):(R(a,"width"),R(a,"height"),a.style.maxHeight=d)),.25>e)){for(V("overshrinkage for "+
a.getAttribute("src"));a&&"TD"!=a.nodeName.toUpperCase();)a=a.parentNode;if(a&&(c=a.parentNode)){d=0;for(a=c.firstChild;a;a=a.nextSibling)"TD"==a.nodeName.toUpperCase()&&++d;if(1<d)for(d="width:"+Math.round(100/d)+"%;",c=c.firstChild;c;c=c.nextSibling)a=T(c),null!=a&&"TD"==a.nodeName.toUpperCase()&&uc(a,d)}}}}};
p.ja=function(a){var b=window.getComputedStyle(a).getPropertyValue("position");if("fixed"==b)return"fixed";if(E(a,"nivoSlider"))return b;var c,d,e,f,g=[];c=null;var h,k=!1;for(d=a.firstChild;d;d=d.nextSibling)if(e=Qc(this,d),null!=e){var m=window.getComputedStyle(e);f=this.ja(e);if("fixed"!=f&&null!=m&&null!=Qc(this,e)){"absolute"!=f||Ec(m)||S(e,"position","relative");f=m.getPropertyValue("float");var l="right"==f;h="inline-block";if(l||"left"==f)l&&"right"==m.getPropertyValue("clear")&&(l=!1,h="block",
c&&k&&S(c,"margin-bottom","0px")),S(e,"float","none"),"none"!=m.getPropertyValue("display")&&S(e,"display",h);l&&g.push(e);c=e;e=Q(m,"margin-bottom");k=null!=e&&0>e}}for(c=g.length-1;0<=c;--c)d=g[c],a.removeChild(d);for(c=g.length-1;0<=c;--c)d=g[c],a.appendChild(d);return b};
p.Z=function(a){if("fixed"!=window.getComputedStyle(a).getPropertyValue("position")){var b,c,d,e=[],f=[];for(c=a.firstChild;c;c=c.nextSibling)if(d=Qc(this,c),null!=d){b=window.getComputedStyle(d);var g=b.getPropertyValue("position");"fixed"!=g&&"absolute"!=g&&0!=c.offsetWidth&&(e.push(d),f.push(b))}var h=null;for(c=0;c<e.length;++c)d=e[c],b=c<e.length-1?e[c+1]:null,g=d.offsetLeft+d.offsetWidth,(null==h||d.offsetLeft<h)&&(null==b||b.offsetLeft<g)&&(b=d,h=b.nodeName.toUpperCase(),"INPUT"!=h&&"SELECT"!=
h&&(""==b.style.backgroundSize&&"auto"!=f[c].width&&S(b,"width","auto"),"IMG"!=h&&b.removeAttribute("width"),R(b,"border-left"),R(b,"border-right"),R(b,"margin-left"),R(b,"margin-right"),R(b,"padding-left"),R(b,"padding-right"),b.className=""!=b.className?b.className+" psSingleColumn":"psSingleColumn"),this.Z(d)),a.getAttribute("data-pagespeed-negative-bottom-margin")&&(a.removeAttribute("data-pagespeed-negative-bottom-margin"),b=window.getComputedStyle(a),d=Q(b,"height"),null!=d&&S(a,"margin-bottom",
""+-d+"px")),h=g}};var Xc=[new X(W.prototype.ia,"shrink wide elements"),new X(W.prototype.ja,"string floats"),new X(W.prototype.oa,"cleanup styles"),new X(W.prototype.ea,"repair distored images"),new X(W.prototype.fa,"resize if too wide"),new X(W.prototype.Z,"expand columns"),new X(W.prototype.qa,"resize vertically")];function Yc(a,b,c){this.c=a;this.a=b;this.b=c}function Zc(a){this.k=a;this.b=null;a=document.domain.toLowerCase().split(".");var b=a.length;this.f=4<b&&2==a[b-3].length?a[b-5]:3<b?a[b-4]:null;this.j=window.location.origin+window.location.pathname;this.a=[];this.c=0;this.d=1}function $c(a,b){this.d=a;this.b=b;this.j=[];this.m=[];this.c=this.k=this.f=null;this.a=b;this.backgroundColor=this.e=null}
function ad(a,b){var c;c=b.getAttribute("ps-save-visibility");if(!c){var d=window.getComputedStyle(b);d&&(c=d.getPropertyValue("visibility"));c||(c="visible")}if("hidden"==c)c=null;else{c=null;"IMG"==b.nodeName.toUpperCase()?c=b.src:c=wc(b);if(!c||0<=c.indexOf("data:image/"))c="";else{d=c.lastIndexOf("/");0>d?d=0:++d;var e=c.indexOf(".",d);0>e&&(e=c.length);c=c.substring(d,e)}-1!=c.indexOf("data:image/")&&(c=null);c=[b.title,b.id,b.className,b.alt,c];for(e=d=0;e<c.length;++e)c[e]&&-1!=c[e].toLowerCase().indexOf("logo")&&
++d;if(a.f)for(e=0;e<c.length;++e)c[e]&&0<=Bc(c[e]).indexOf(Bc(a.f))&&++d;b.href==a.j&&++d;c=0<d?new $c(d,b):null}c&&a.a.push(c);for(c=b.firstElementChild;c;c=c.nextElementSibling)ad(a,c)}function bd(a,b){++a.c;b.addEventListener("load",v(a.e,a));b.addEventListener("error",v(a.e,a))}function cd(a,b){var c=document.createElement("IMG");bd(a,c);c.src=b;return c}
function dd(a,b,c,d){var e=null,f;for(f in zc){var e=b,g=zc[f],h=null;switch(g){case "IMG":e.nodeName==g&&(h=e.src);break;case "SVG":e.nodeName==g&&(e=(new XMLSerializer).serializeToString(e),h=(self.URL||self.webkitURL||self).createObjectURL(new Blob([e],{type:"image/svg+xml;charset=utf-8"})));break;case "background-image":h=wc(e)}if(h){var e=h,k=sb(document.location.href),g=k[1],h=k[2],m=k[3],k=k[4],l="";g&&(l+=g+":");m&&(l+="//",h&&(l+=h+"@"),l+=m,k&&(l+=":"+k));g=l;k=ub(sb(g)[3]||null);h=ub(sb(e)[3]||
null);null!=k&&null!=h&&(m=!1,k!=h&&(0<=k.indexOf(h)&&(k=k.split("."),l=k.length,3<=l&&(h==k.slice(0,l-2).join(".")||"www"==k[0]&&(h==k.slice(1,l-2).join(".")||h==k.slice(1,l).join(".")))&&(m=!0)),e=m?g+e.substring(e.indexOf(h)+h.length):e))}else e=null;if(e){g=null;"IMG"==f?(g=b,b.naturalWidth||bd(a,g)):g=cd(a,e);c.push(b);d.push(g);break}}for(b=b.firstElementChild;b;b=b.nextElementSibling)dd(a,b,c,d)}function ed(a,b){var c=a.length-1;b<c&&(a[b]=a[c]);a.pop()}
function fd(a){for(var b=a.a,c=0;c<b.length;++c){for(var d=b[c],e=Dc(d.b),f=e.width*e.height,g=.5*f,h=-1,k=0,m=0;m<d.j.length;++m)if(f=d.j[m])e=Dc(f),f=e.width*e.height,f>=g&&20<e.width&&10<e.height&&400>e.height&&f>k&&(k=f,h=m);0<=h?(d.c=d.j[h],d.a=d.m[h],d.e=e):d.f?(f=d.f,e=Dc(f),f=e.width*e.height,f>=g&&20<e.width&&10<e.height&&400>e.height?(d.c=d.f,d.a=d.k,d.e=e):(ed(b,c),--c)):(ed(b,c),--c)}b=a.a;if(1<b.length){e=0;g=Infinity;for(c=0;d=b[c];++c)h=d.e,g=Math.min(g,h.top),e=Math.max(e,h.bottom);
for(c=0;d=b[c];++c)h=d.e,d.d*=Math.sqrt((e-h.top)/(e-g));if(0<b.length&&1==a.d){e=b[0];for(c=1;c<b.length;++c)d=b[c],0>gd(d,e)&&(e=d);b[0]=e}else b.sort(gd)}c=[];d={};for(e=0;c.length<a.d&&e<b.length;++e)if(g=b[e],!d[g.a.src]){d[g.a.src]=!0;if((h=g)&&h.c){m=null;for(k=h.c;k&&!m;){a:{if(m=document.defaultView.getComputedStyle(k,null))if(f=m.getPropertyValue("background-color")){b:{var m=f.indexOf("("),l=f.lastIndexOf(")");if(m=0<=m&&l>m?f.substring(m+1,l):null){for(var m=m.split(","),f=[],l=0,q=m.length;l<
q;++l)if(f[l]=3!=l?parseInt(m[l],10):parseFloat(m[l]),isNaN(f[l])){m=null;break b}m=3==f.length||4==f.length?f:null}else m="transparent"==f?[0,0,0,0]:null}if(m&&(3==m.length||4==m.length&&0!=m[3]))break a}m=null}k=k.parentElement}h.backgroundColor=m}h=(new Gc).run(g.a,g.backgroundColor);c.push(new Yc(g,h.a,h.b))}b=a.b;a.b=null;b(c)}Zc.prototype.e=function(){--this.c;0==this.c&&fd(this)};var hd=[function(a){return a.top},function(a){return a.left},function(a){return a.width*a.height}];
function gd(a,b){if(a.d>b.d)return-1;if(b.d>a.d)return 1;for(var c=0;c<hd;++c){var d=hd[c],e=d(a.e),d=d(b.e);if(e<d)return-1;if(d<e)return 1}if(a.b&&a.b.src&&b.b&&b.b.src){if(a.b.src<b.b.src)return-1;if(a.b.src>b.b.src)return 1}return 0}
Zc.prototype.run=function(a,b){if(this.b||!document.body)a([]);else{this.b=a;this.d=b;ad(this,document.body);for(var c=this.a,d=0;d<c.length;++d){var e=c[d],f=e.b;dd(this,f,e.j,e.m);for(f.parentNode?f=T(f.parentNode):f=null;f;){var g=wc(f);if(g){e.f=f;e.k=cd(this,g);break}f=f.parentElement}}0==this.c&&fd(this)}};w("pagespeed.MobLogo.prototype.run",Zc.prototype.run);Zc.prototype.n=function(){return this.k};function id(a){this.a=a}
function jd(a,b,c){var d=document.createElement(psConfigMode?"A":"SPAN");a&&a.a?(a=window.psConfigMode||a.c==a.a?a.a.cloneNode(!1):a.a,a.removeAttribute("id")):(a=document.createElement("span"),a.textContent=window.location.host,a.style.color=U(c));d.appendChild(a);var e=document.createElement("BUTTON");F(e,"psmob-menu-button");var f=document.createElement("DIV");F(f,"psmob-hamburger-div");e.appendChild(f);for(var g=U(c),h=0;3>h;++h){var k=document.createElement("DIV");F(k,"psmob-hamburger-line");
k.style.backgroundColor=g;f.appendChild(k)}return new Ac(c,b,e,d,a)}function kd(a,b,c){var d=jd(a,b,c);if(window.psLayoutMode&&a&&a.c){var e=a.c;e.parentNode.removeChild(e)}window.psMobPrecompute&&(window.psMobBackgroundColor=b,window.psMobForegroundColor=c,window.psMobLogoUrl=a?a.a.src:null);return d}id.prototype.b=function(a){if(this.a){1<=a.length?(a=a[0],a=kd(a.c,a.a,a.b)):a=kd(null,[255,255,255],[0,0,0]);ld(a);var b=this.a;this.a=null;b(a)}};
function ld(a){window.psConfigMode&&(a.a.href="javascript:psPickLogo()");a.a.id="psmob-logo-span";a.p.id="psmob-logo-image";a.p.style.backgroundColor=U(a.u)};function md(){this.r=[];this.M=this.f=this.g=this.c=this.a=this.j=this.k=this.e=this.d=this.i=null;this.q=this.O=0;this.F=!1;this.m=[];this.s=!1;this.$=I("Android")&&!((I("Chrome")||I("CriOS"))&&!Oa()||I("Firefox")||Oa()||I("Silk"));this.L=-1<navigator.userAgent.indexOf("Opera Mini");this.b=null}function nd(a,b){if(16>=a.length)return null;var c=window.atob(a);return"data:image/gif;base64,"+window.btoa(c.substring(0,13)+String.fromCharCode(b[0],b[1],b[2])+c.substring(16,c.length))}
function od(a,b){if(!Sb(b))return!1;if("IMG"===b.nodeName.toUpperCase())return!a||null!==b.offsetParent;var c=b.getElementsByTagName("IMG");if(a){for(var d=c.length-1;0<=d;d--)if(null!==c[d].offsetParent)return!0;return!1}return 0<c.length}
function pd(a){var b=a.parentNode;if(!b||0<b.getElementsByTagName("SCRIPT").length)return!1;for(var c=null!==a.offsetParent,d=!1,e=0,b=b.firstChild;b;b=b.nextSibling)if(b==a)d=!0;else if(null!==b.offsetParent||!c)if(3==b.nodeType||1==b.nodeType){if(od(c,b))return!1;var f=ta(b.textContent).length;if(0<f){if(d)return!1;e+=f;if(60<e)return!1}}return!0}
function qd(a){var b="scale("+window.innerWidth/document.documentElement.clientWidth+")";a.i.style["-webkit-transform"]=b;a.i.style.transform=b;La(a.i,"hide");b=a.i.offsetHeight+"px";a.j&&(a.j.style.width=b);var c=0;a.a&&(a.a.style.width=b,c+=a.i.offsetHeight);a.c&&(a.c.style.width=b,c+=a.i.offsetHeight);a.k.style.left=b;a.k.style.right=c+"px";b=Math.round(Wb(a.i).height);c=Ub(Vb,a.e).height;a.e.style.height=b+"px";for(var d=0;d<a.m.length;d++){var e=a.m[d];if(a.s){var f=e.style.top,f=Number(e.style.top.split("px")[0]);
e.style.top=String(f+(b-c))+"px"}else f=vc(e).top,e.style.top=String(f+b)+"px"}a.s&&b!=c&&window.scrollBy(0,b-c);a.i.style.top=window.scrollY+"px";a.i.style.left=window.scrollX+"px";a.s=!0}
function rd(a){if(a.g){var b=.8*window.innerWidth/250,c=E(a.g,"open")?0:-250*b;a.g.style.top=window.scrollY+"px";a.g.style.left=window.scrollX+c+"px";c="scale("+b+")";a.g.style["-webkit-transform"]=c;a.g.style.transform=c;c=a.i.getBoundingClientRect();a.g.style.marginTop=c.height+"px";a.L||(a.g.style.height=(window.innerHeight-c.height)/b+"px")}}
function sd(a){function b(){null!=this.M&&(window.clearTimeout(this.M),this.M=null);this.M=window.setTimeout(v(function(){if(this.$||0==this.O)rd(this),qd(this);this.M=null},this),200)}qd(a);rd(a);window.addEventListener("scroll",v(function(a){this.F||F(this.i,"hide");b.call(this);this.g&&this.F&&!this.g.contains(a.target)&&(a.stopPropagation(),a.preventDefault())},a),!1);window.addEventListener("touchstart",v(function(a){this.O=a.touches.length;this.q=a.touches[0].clientY},a),!1);window.addEventListener("touchmove",
v(function(a){this.F?a.preventDefault():this.$||F(this.i,"hide")},a),!1);window.addEventListener("touchend",v(function(a){this.O=a.touches.length;0==this.O&&b.call(this)},a),!1);window.addEventListener("orientationchange",v(function(){rd(this);qd(this)},a),!1)}function td(){return"https://maps.google.com/maps?q="+window.psMapLocation}
w("psOpenMap",function(){var a=new Image;a.onload=function(){location.href=td()};a.onerror=a.onload;a.src="//www.googleadservices.com/pagead/conversion/"+window.psConversionId+"/?label="+window.psMapConversionLabel+"&amp;guid=ON&amp;script=0"});
function ud(){if(window.psStaticJs||!window.psPhoneConversionLabel)return window.psPhoneNumber;var a=document.cookie.match(/(^|;| )gwcm=([^;]+)/);return a&&a[2]&&(a=ha(unescape(a[2])),a.fallback==window.psPhoneNumber&&a.clabel==window.psPhoneConversionLabel)?a.mobile_number:null}
function vd(){if(window.psPhoneConversionLabel&&window.psPhoneNumber){var a="https://www.googleadservices.com/pagead/conversion/"+window.psConversionId+"/wcm?cl="+escape(window.psPhoneConversionLabel)+"&fb="+escape(window.psPhoneNumber);window.psDebugMode&&alert("requesting dynamic phone number: "+a);(new mc(a,"callback")).send(null,wd,function(){window.psDebugMode&&alert("error callback called");xd()})}}function xd(){window.psPhoneNumber&&(location.href="tel:"+window.psPhoneNumber)}
function wd(a){var b=null;if(a&&a.wcm){var c=a.wcm;c&&(b=c.mobile_number)}b?(a={expires:c.expires,formatted_number:c.formatted_number,mobile_number:b,clabel:window.psPhoneConversionLabel,fallback:window.psPhoneNumber},a=ia(a),window.psDebugMode&&alert("saving phone in cookie: "+a),document.cookie="gwcm="+escape(a)+";path=/;max-age=7776000",window.psPhoneNumber=b):window.psPhoneNumber&&window.psDebugMode&&alert("receivePhoneNumber: "+ia(a));xd()}
function yd(a,b){a.d&&a.d.parentNode.removeChild(a.d);a.a&&(a.a.style.backgroundImage="url("+nd("R0lGODlhgACAAPAAAAAAAAAAACH5BAEAAAEALAAAAACAAIAAAAL+jI+pCL0Po5y02vuaBrj7D4bMtonmiXrkyqXuC7MsTNefLNv6nuE4D9z5fMFibEg0KkVI5PLZaTah1IlUWs0qrletl9v1VsFcMZQMNivRZHWRnXbz4G25jY621/B1vYuf54cCyCZ4QlhoGIIYqKjC2Oh4AZkoaUEZaWmF2acpwZnpuQAaKjpCWmbag5qqmsAa53oK6yT7SjtkO4r7o7vLS+K7Cuwg/EtsDIGcrMzLHOH8DM0qvUlabY2JXaG9zc3ojYEYLk5IXs53Pgmovo7XfskOTyE//1lv3/yeP53Or0/nH8CAAo/BKTjsIMJb/hYewOcwAMSF5iIamEixYcTMihY5bsRY0GNGkP9Ejtx3poUbk0GCrSR5Z8VLmDRyqBnXMokYnEJq7WT5J8wXni86ZQF3JJYWpCkILiXKBOUYpouAGqEU1eobSCCwHvXqDmxKrmHFPuH07drUbv3UUgHVFtVXuFuijVVLrNjbvLTm8pW79q/bu4LZ7i2M1i9isoEXQz3smObVyBqHUlZ483Kpn5qxCOrs+TNonYZG27RkuoSo1HpXj7YFWtjlZJGlId72l9wy3bjmweI3OJ/hkFqBO7U4KzTyuDKXaykAADs=",
b.o)+")");var c=U(b.u),d=U(b.o);a.d=document.createElement("STYLE");a.d.type="text/css";a.d.appendChild(document.createTextNode(".psmob-header-bar { background-color: "+c+"; }\n.psmob-nav-panel { background-color: "+d+"; }\n.psmob-nav-panel > ul li { color: "+c+"; }\n.psmob-nav-panel > ul li a { color: "+c+"; }\n.psmob-nav-panel > ul li div { color: "+c+"; }\n"));document.head.appendChild(a.d)}
function zd(a,b,c,d){var e=[];d=d||!1;for(b=b.firstChild;b;b=b.nextSibling)"UL"==b.nodeName.toUpperCase()?e=Ba(e,zd(a,b,d?c+1:c,!0)):("A"==b.nodeName.toUpperCase()&&(b.setAttribute("data-mobilize-nav-level",c),e.push(b)),e=Ba(e,zd(a,b,c,d)));return e}
function Ad(a){var b=a.g.getElementsByTagName("a"),c={};a=[];for(var d=0,e;e=b[d];d++)if(e.href in c){var f=e.innerHTML.toLowerCase();-1==c[e.href].indexOf(f)?c[e.href].push(f):"LI"==e.parentNode.nodeName.toUpperCase()&&a.push(e.parentNode)}else c[e.href]=[],c[e.href].push(e.innerHTML.toLowerCase());for(d=0;b=a[d];d++)b.parentNode.removeChild(b)}
function Bd(a){for(var b=a.g.querySelectorAll("*"),c=[],d=document.getElementById("psmob-logo-image"),e=d?d.src:"",d=0,f;f=b[d];d++)f.removeAttribute("style"),f.removeAttribute("width"),f.removeAttribute("height"),"A"==f.nodeName.toUpperCase()?(""==f.textContent&&f.hasAttribute("title")&&f.appendChild(document.createTextNode(f.getAttribute("title"))),""==f.href&&c.push(f)):"IMG"==f.nodeName.toUpperCase()&&f.src==e&&c.push(f);for(d=0;f=c[d];d++){for(;"LI"!=f.nodeName.toUpperCase();)f=f.parentNode;
f.parentNode.removeChild(f)}b=a.g.querySelectorAll("img:not(.psmob-menu-expand-icon)");for(d=0;c=b[d];++d)e=Math.min(2*c.naturalHeight,40),c.setAttribute("height",e);if(window.FastClick){c=a.g.getElementsByTagName("a");for(d=0;b=c[d];d++)F(b,"needsclick");c=a.g.getElementsByTagName("div");for(d=0;b=c[d];d++)F(b,"needsclick")}}
function Cd(a){a.f=document.createElement("DIV");a.f.id="psmob-click-detector-div";document.body.insertBefore(a.f,a.g);a.f.addEventListener("click",v(function(){E(this.g,"open")&&Dd(this)},a),!1)}
function Ed(a,b){a.g=document.createElement("NAV");document.body.insertBefore(a.g,a.i.nextSibling);F(a.g,"psmob-nav-panel");var c=document.createElement("UL");a.g.appendChild(c);F(c,"open");for(var d=nd("R0lGODlhkACQAPABAP///wAAACH5BAEAAAEALAAAAACQAJAAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vh8EAJATKIhFWFhziEiluBjT6AgFGdkySclkeZmSqYnE2VnyCUokOhpSagqEmtqxytrjurnqFGtSSztLcvu0+9HLm+sbPPWbURx1XJGMPHyxLPXsEA3dLDFNXP1wzZjNsF01/W31LH6VXG6YjZ7Vu651674VG8/l2s1mL2qXn4nHD6nn3yE+Al+5+fcnQL6EBui1QcUwgb6IEvtRVGDporc/RhobKOooLRBIbSNLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOn0KVUcBADs=",b.u),
e=0,f;f=a.r[e];e++)if(f.parentNode){f.setAttribute("data-mobilize-nav-section",e);var g=zd(a,f,0),h=[];h.push(c);for(var k=0,m=g.length;k<m;k++){var l=g[k].getAttribute("data-mobilize-nav-level"),q=k+1==m?l:g[k+1].getAttribute("data-mobilize-nav-level");if(l<q){var y=document.createElement("LI"),l=y.appendChild(document.createElement("DIV"));d&&(q=document.createElement("IMG"),l.appendChild(q),q.setAttribute("src",d),F(q,"psmob-menu-expand-icon"));l.appendChild(document.createTextNode(g[k].textContent||
g[k].innerText));h[h.length-1].appendChild(y);l=document.createElement("UL");y.appendChild(l);h.push(l)}else for(y=document.createElement("LI"),h[h.length-1].appendChild(y),y.appendChild(g[k].cloneNode(!0)),y=l-q;0<y&&1<h.length;)h.pop(),y--}window.psLayoutMode&&f.parentNode.removeChild(f)}Ad(a);Bd(a);Cd(a);a.g.addEventListener("touchmove",v(function(a){if(this.F){var b=a.touches[0].clientY;if(1!=a.touches.length)a.preventDefault();else{var c=b>this.q,d=0==this.g.scrollTop,e=this.g.scrollTop>=this.g.scrollHeight-
this.g.offsetHeight-1;a.cancelable&&(c&&d||!c&&e)&&a.preventDefault();a.stopImmediatePropagation&&a.stopImmediatePropagation();this.q=b}}},a),!1);rd(a)}function Dd(a){G(a.i,"open");G(a.g,"open");G(a.f,"open");G(document.body,"noscroll");a.F=!a.F;rd(a)}function Fd(a){a.j.addEventListener("click",v(function(){Dd(this)},a),!1)}
function Gd(){document.querySelector("nav.psmob-nav-panel > ul").addEventListener("click",function(a){a=Sb(a.target)&&E(a.target,"psmob-menu-expand-icon")?a.target.parentNode:a.target;"DIV"==a.nodeName.toUpperCase()&&(G(a.nextSibling,"open"),G(a.firstChild,"open"))},!1)}
function Hd(a,b,c){if(c.p.src){var d=U(c.o),e=U(c.u),f=b.document.getElementById("psmob-logo-image");f&&(f.parentNode.replaceChild(c.p,f),a.i&&(a.i.style.backgroundColor=e),a.k.style.backgroundColor=e);if(a=b.document.getElementById("psmob-phone-image"))a.src=nd("R0lGODlhgACAAPAAAAAAAAAAACH5BAEAAAEALAAAAACAAIAAAAL+jI+pCL0Po5y02vuaBrj7D4bMtonmiXrkyqXuC7MsTNefLNv6nuE4D9z5fMFibEg0KkVI5PLZaTah1IlUWs0qrletl9v1VsFcMZQMNivRZHWRnXbz4G25jY621/B1vYuf54cCyCZ4QlhoGIIYqKjC2Oh4AZkoaUEZaWmF2acpwZnpuQAaKjpCWmbag5qqmsAa53oK6yT7SjtkO4r7o7vLS+K7Cuwg/EtsDIGcrMzLHOH8DM0qvUlabY2JXaG9zc3ojYEYLk5IXs53Pgmovo7XfskOTyE//1lv3/yeP53Or0/nH8CAAo/BKTjsIMJb/hYewOcwAMSF5iIamEixYcTMihY5bsRY0GNGkP9Ejtx3poUbk0GCrSR5Z8VLmDRyqBnXMokYnEJq7WT5J8wXni86ZQF3JJYWpCkILiXKBOUYpouAGqEU1eobSCCwHvXqDmxKrmHFPuH07drUbv3UUgHVFtVXuFuijVVLrNjbvLTm8pW79q/bu4LZ7i2M1i9isoEXQz3smObVyBqHUlZ483Kpn5qxCOrs+TNonYZG27RkuoSo1HpXj7YFWtjlZJGlId72l9wy3bjmweI3OJ/hkFqBO7U4KzTyuDKXaykAADs=",
c.o);if(a=b.document.getElementById("psmob-map-image"))a.src=nd("R0lGODlhaQCkAPAAAAAAAAAAACH5BAEAAAEALAAAAABpAKQAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyA9T2jQOzmve+vRP9hsQgh4hEGi3JpnIJcUqf0MX0WqwesNyhNtAN+6rics9oTuN26jYw5o7rXnI5ve524e2rfb3vx3cS+IdCWFhyiEiiuBiCpwDJGEdDOZIXYfmoxsQplIbR9lm2AbopdmR2GuahCkL6ARvLusr1SnuL26GbazvrOwq82zVJ/HtlwlsqHIzcalyMdewcTT0snQh9bd081cv9LVXrfam9Df7MnKqejj2Nvmy+zh5PnyF7Dl9vX4H/7n7PXztlFEyNkyfB00GElVyVU9jQYDeJCByFa+SwGkb+gQs38svnkeHFkOQGkSQ48aQTHir1pWzphSXMlYBmUpFpM2bNnD/08Bzj82eOO0JvwCn6hihSGUjnHC06oykboUGgTv2JhucSrFttkvEKJaeWmV/IjoX5BYzKtGpPsm3r8S3cjXLd1o0rd66ivAbw5qXLV2+gwH33EhYs6bBhxYQOb2nsuPCeyI8nU5ZskXFmzYIuI+YYeXNoTZ4xUyxNurRpVKoTiGrtOiPs1R8vn54NGnZu3SJx9/YNcHak4MJjuyx+HHnJ4g3EMY948zkDmtKbJ6kOvSd2B9G3D9fpfbr28NaBki+/5jz3M+rXG23vPil88TXmR7RfCb/+/fwN+/v/D2CAAg5IoAoFAAA7",
c.o);b=b.document.getElementsByClassName("psmob-hamburger-line");for(c=0;a=b[c];++c)a.style.backgroundColor=d}}
function Id(a,b){function c(){var a=document.createElement("TD");f.appendChild(a);return a}if(a.b)Jd(a);else{var d=document.createElement("TABLE");d.className="psmob-logo-chooser-table";var e=document.createElement("THEAD");d.appendChild(e);var f=document.createElement("TR");e.appendChild(f);f.className="psmob-logo-chooser-column-header";c().textContent="Logo";c().textContent="Foreground";c().textContent="";c().textContent="Background";e=document.createElement("TBODY");d.appendChild(e);for(var g=
0;g<b.length;++g){f=document.createElement("TR");f.className="psmob-logo-chooser-choice";e.appendChild(f);var h=b[g],k=jd(h.c,h.a,h.b);c().appendChild(k.a);k=k.p;k.className="psmob-logo-chooser-image";k.onclick=v(a.D,a,h);k=c();k.style.backgroundColor=D(h.b);k.className="psmob-logo-chooser-color";var m=c();m.className="psmob-logo-chooser-color";var l=document.createElement("IMG");l.className="psmob-logo-chooser-swap";l.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIYAAABaCAAAAABY7nEZAAAABGdBTUEAALGPC/xhBQAAAcpJREFUaN7t2ItxgkAQgOHtADvADkwH2oHpADrADlKCdoAdaAekA0qgBEowYIZRE7jbe+xjktsCnE/m54CFm4qBxEgMIkavgwHlVQUDYHVoNTCGWZ86DYxhdudeA2OYgExiMgIyicvwziQ6wy8TCoZHJkQM10zIGG6ZUDIcMiFmYDOhZ6AymWd8ogdwY8sEvP+j6xgz4WMYM2FlLGfCzBgzqTUwiov81djWvXgb+bFzvFO26MEasqqVPkWXguBlLAbByDAFwcWwBMHDsAbBwMAEQc1ABkHKwAdByHAJgorhGAQJI/8IWC5EYmRF2KolCmN/uYX+TDBjU0dYw4UyQoJI69n/wmhKeUZ3WAMIM/rT2/34EGWc36fjXI7RlKvHU0WIcQ8CZBlTEKKMRxByjJcghBg/g5BgzATBz5gNgpmxFAQnwxAEG8McBBPDFsTzAhY7rgxEED7jxMAFQctAB0HLqPeggTFcj+NGA2Oso8o1MMZ7pcg0MFwyabDjeZgjM2F4tGEy4XnQWzNhe+0xZ8L4EmjKhPeVeDET9g+E+UwkPpdmMpH5ePyVidin9GsmkouFp0yE1yxTJuJLp+9MNKzg2ipPC8nE+LuMLwqlrYBVqy8VAAAAAElFTkSuQmCC";
m.appendChild(l);l=c();l.style.backgroundColor=D(h.a);l.className="psmob-logo-chooser-color";m.onclick=v(a.K,a,h,k,l)}Kd(a,d)}}function Kd(a,b){b.style.visibility="hidden";document.body.appendChild(b);var c=2/3,d=window.innerWidth*c/b.offsetWidth,c=Math.round(.5*(1-c)*window.innerWidth)+"px",d="scale("+d+") translate("+c+","+c+")";b.style["-webkit-transform"]=d;b.style.transform=d;b.style.visibility="visible";null!=a.b&&a.b.parentNode.removeChild(a.b);a.b=b}
md.prototype.D=function(a){a=kd(a.c,a.a,a.b);ld(a);Hd(this,window,a);yd(this,a);var b=document.createElement("PRE");b.className="psmob-logo-chooser-config-fragment";b.textContent='ModPagespeedMobTheme "\n    '+D(a.u)+"\n    "+D(a.o)+"\n    "+a.p.src+'"';Kd(this,b)};md.prototype.K=function(a,b,c){var d=a.a;a.a=a.b;a.b=d;d=b.style["background-color"];b.style["background-color"]=c.style["background-color"];c.style["background-color"]=d};
function Jd(a){a.b&&(a.b.parentNode.removeChild(a.b),a.b=null)};function Y(){this.m=0;this.f={};this.ma=Date.now();this.ca=!1;this.e=this.K=this.ga=this.a=this.c=0;this.s=!1;this.L=this.D=0;this.r=new W(this);this.r.c["ps-progress-scrim"]=!0;this.b=-1;this.q=null;this.X=[];this.j=[];this.d=null;this.ka=new Zc(this);this.k=null}var Ld=new sc(-1,-1);function Md(a){0==a.e?(V("mobilizing site"),window.psNavMode&&!xc()||Nd(a)):a.s=!0}
Y.prototype.na=function(a){--this.D;Od(this,this.c,"extract theme");var b=this.d=new md;V("Starting nav resynthesis.");var c=[];if(window.pagespeedNavigationalIds)for(var d=window.pagespeedNavigationalIds.length,e={},f=0;f<d;f++){var g=window.pagespeedNavigationalIds[f],g=document.getElementById(g)||document.querySelector("[id="+Fc(g)+"]"),h=g.parentNode;h?(h.id||(g.id.match(/^PageSpeed-.*-[0-9]+$/)?h.id=g.id.replace(/-[0-9]+$/,""):h.id="PageSpeed-"+g.id+"-P"),h.id in e?e[h.id]||c.push(g):(e[h.id]=
pd(g),c.push(e[h.id]?h:g))):c.push(g)}b.r=c;c=document.querySelectorAll("* :not(#ps-progress-scrim)");for(d=0;e=c[d];d++)f=window.getComputedStyle(e),g=f.getPropertyValue("position"),("fixed"==g||"absolute"==g&&e.parentNode==document.body)&&b.m.push(e),999998<=f.getPropertyValue("z-index")&&(V("Element z-index exceeded 999998, setting to 999997."),e.style.zIndex=999997);b.e=document.getElementById("ps-spacer");document.body.insertBefore(b.e,document.body.childNodes[0]);F(b.e,"psmob-header-spacer-div");
b.i=document.createElement("HEADER");document.body.insertBefore(b.i,b.e);F(b.i,"psmob-header-bar");c=window.document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new x(c.clientWidth,c.clientHeight);b.i.style.height=Math.round(.1*Math.max(c.height,c.width))+"px";b.j=a.b;b.i.appendChild(b.j);b.k=a.a;b.i.appendChild(a.a);b.i.style.borderBottom="thin solid "+U(a.o);b.i.style.backgroundColor=U(a.u);window.psPhoneNumber&&(b.a=document.createElement("DIV"),b.a.id="psmob-phone-dialer",(c=ud())?
(window.psPhoneNumber=c,b.a.onclick=xd):b.a.onclick=vd,b.i.appendChild(b.a));window.psMapLocation&&(c=a.o,d=document.createElement("IMG"),d.id="psmob-map-image",d.src=nd("R0lGODlhaQCkAPAAAAAAAAAAACH5BAEAAAEALAAAAABpAKQAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyA9T2jQOzmve+vRP9hsQgh4hEGi3JpnIJcUqf0MX0WqwesNyhNtAN+6rics9oTuN26jYw5o7rXnI5ve524e2rfb3vx3cS+IdCWFhyiEiiuBiCpwDJGEdDOZIXYfmoxsQplIbR9lm2AbopdmR2GuahCkL6ARvLusr1SnuL26GbazvrOwq82zVJ/HtlwlsqHIzcalyMdewcTT0snQh9bd081cv9LVXrfam9Df7MnKqejj2Nvmy+zh5PnyF7Dl9vX4H/7n7PXztlFEyNkyfB00GElVyVU9jQYDeJCByFa+SwGkb+gQs38svnkeHFkOQGkSQ48aQTHir1pWzphSXMlYBmUpFpM2bNnD/08Bzj82eOO0JvwCn6hihSGUjnHC06oykboUGgTv2JhucSrFttkvEKJaeWmV/IjoX5BYzKtGpPsm3r8S3cjXLd1o0rd66ivAbw5qXLV2+gwH33EhYs6bBhxYQOb2nsuPCeyI8nU5ZskXFmzYIuI+YYeXNoTZ4xUyxNurRpVKoTiGrtOiPs1R8vn54NGnZu3SJx9/YNcHak4MJjuyx+HHnJ4g3EMY948zkDmtKbJ6kOvSd2B9G3D9fpfbr28NaBki+/5jz3M+rXG23vPil88TXmR7RfCb/+/fwN+/v/D2CAAg5IoAoFAAA7",
c),b.c=document.createElement("A"),b.c.id="psmob-map-button",b.c.href=window.psMapConversionLabel?"javascript:psOpenMap()":td(),b.c.appendChild(d),b.i.appendChild(b.c));sd(b);yd(b,a);0==b.r.length||xc()||(Ed(b,a),Fd(b),Gd());Od(this,this.c,"navigation");Nd(this);(b=Z().n)&&0<=b.b&&(Pd()?Hd(this.d,Z(),a):(c=document.createElement("IFRAME"),c.id="ps-hidden-iframe",c.hidden=!0,document.body.appendChild(c)),b.j.push(a),this.da(!0))};
Y.prototype.ra=function(a){this.f[a.src]=new sc(a.width,a.height);--this.e;Od(this,1E3,"background image");0==this.e&&this.s&&(Md(this),this.s=!1)};function Qd(a,b){var c=Qc(a.r,b);if(null!=c){var d=wc(c);if(d&&(0==d.lastIndexOf("http://",0)||0==d.lastIndexOf("https://",0))&&!a.f[d]){a.f[d]=Ld;var e=new Image;++a.e;e.onload=v(a.ra,a,e);e.onerror=e.onload;e.src=d}for(c=c.firstChild;c;c=c.nextSibling)Qd(a,c)}}Y.prototype.xhrSendHook=function(){++this.m};
Y.prototype.xhrResponseHook=function(){--this.m;this.a+=this.L;Nd(this)};
Y.prototype.ta=function(){Rd(this,window.psDebugMode);this.c=yc(document.body);this.L=this.c*Xc.length;this.a+=this.L;window.psNavMode&&xc()&&(this.a+=this.c,this.a+=this.c);if(null!=document.body){for(var a in window.psMobStaticImageInfo){var b=window.psMobStaticImageInfo[a];this.f[a]=new sc(b.w,b.h)}Boolean(psMobBackgroundColor&&psMobForegroundColor&&!window.psMobPrecompute)&&!window.psLayoutMode||Qd(this,document.body)}this.a+=1E3*this.e;window.psLayoutMode&&window.pagespeedXhrHijackSetListener(this);
Md(this)};function Nd(a){if(0==a.m&&0==a.D&&0==a.e){if(window.psLayoutMode){var b=a.r;if(null!=document.body)for(var c=0,d;d=Xc[c];++c){d.a.call(b,document.body);var e=b.b;Od(e,e.c,d.b)}}if(a.ca){if(a=document.getElementById("ps-progress-remove"))a.textContent="Remove Progress Bar and show mobilized site"}else Sd()}}function Tc(a,b){var c=a.f[b];c==Ld&&(c=null);return c}
function Rd(a,b){a.ca=b;var c=document.getElementById("ps-progress-log");c&&(c.style.color=b?"#333":"white");b&&(c=document.getElementById("ps-progress-show-log"))&&(c.style.display="none")}function Od(a,b,c){a.K+=b;b=100;0<a.a&&(b=Math.round(100*a.K/a.a),100<b&&(b=100));if(b!=a.ga){var d=document.getElementById("ps-progress-span");d&&(d.style.width=b+"%");a.ga=b}a=""+b+"% "+(Date.now()-a.ma)+"ms: "+c;V(a);if(c=document.getElementById("ps-progress-log"))c.textContent+=a+"\n"}
function Sd(){var a=document.getElementById("ps-progress-scrim");a&&(a.style.display="none",a.parentNode.removeChild(a))}
Y.prototype.sa=function(){if(window.psNavMode){++this.D;if(!Pd()&&window.document.body&&-1!=window.location.search.indexOf("PageSpeedSiteWideProcessing")){var a=[],b=window.location.search.indexOf("ModPagespeedMobIframe"),c=null;-1!=b&&(c=window.location.search.substring(b),(c=c.split("#")[0].split("&")[0])&&(c="?"+c));Td(this,c,window.document.body,a);Z().n.X=a;if(b=prompt(a.length+' links have been found in this page. If you want to compute theme from them, enter the number of links below and press "OK". It may take a while to process them. Once processing completes, you will see another dialog.',
a.length.toString()))isFinite(b)&&(b=String(b)),b=t(b)?/^\s*-?0x/i.test(b)?parseInt(b,16):parseInt(b,10):NaN,this.b=0>b?0:b>a.length?a.length:b}b=this.ka;a=v(this.na,this);window.psConfigMode?(c=b.n(),a=new id(a),b.run(v(c.la,c,a),5)):psMobBackgroundColor&&psMobForegroundColor&&!window.psMobPrecompute?(b=null,psMobLogoUrl&&(b=document.createElement("IMG"),b.src=psMobLogoUrl,b=new $c(1,b)),b=kd(b,psMobBackgroundColor,psMobForegroundColor),ld(b),a(b)):(a=new id(a),b.run(v(a.b,a),1))}};window.n=new Y;
Y.prototype.la=function(a,b){this.k=b;a.b(b);Id(this.d,b)};window.addEventListener("DOMContentLoaded",v(window.n.sa,window.n));window.addEventListener("load",v(window.n.ta,window.n));w("psSetDebugMode",function(){Rd(window.n,!0)});w("psRemoveProgressBar",function(){Sd()});w("psPickLogo",function(){var a=window.n;null!=a.k&&0<a.k.length&&Id(a.d,a.k)});function Pd(){return xc()&&null!=window.frameElement&&"ps-hidden-iframe"==window.frameElement.id}function Z(){return Pd()?window.parent:window}
function Ud(a){var b=Z().n;if(b&&b.j&&0!=b.j.length){for(var c={},d,e=0;d=b.j[e];++e){var f=d.p.src;f&&(f=f+U(d.o)+U(d.u),c[f]?++c[f].count:c[f]={N:d,count:1})}b=ra(c);b.sort(function(a,b){if(a.count<b.count)return 1;if(a.count>b.count)return-1;var c=a.N.p.src,d=b.N.p.src;return c<d?-1:c>d?1:0});c="\nFinish site-wide theme extraction. ";if(0<b.length){c+="Found "+b.length+" logo images. Details are shown below:\n";Hd(a.d,Z(),b[0].N);for(e in b)d=b[e].N,c+='"'+U(d.u)+" "+U(d.o)+" "+d.p.src+'" COUNT: '+
b[e].count+"\n";c+="\n";for(e in b)d=b[e].N,c+='ModPagespeedMobTheme "\n    '+D(d.u)+"\n    "+D(d.o)+"\n    "+d.p.src+'"\n'}else c+="No logo was found.";V(c+"\n")}}
Y.prototype.da=function(a){a||V("Time out.");a=Z().n;var b=Z();if(a){b.clearTimeout(a.q);a.q=null;var c=a.X.pop();if(0<a.b&&c){V("Next URL is "+c+". "+a.b+" more to go.");var d=b.document.getElementById("ps-hidden-iframe");d&&(d.src=c,a.q=b.setTimeout(v(a.da,a),1E4));--a.b}else 0==a.b&&(Ud(this),alert("All URLs have been processed. The header bar shows the best result. Details can be found in console log."),a.b=-1)}};
function Td(a,b,c,d){if(!(100<=d.length)){var e=c.tagName.toUpperCase();if(("A"==e||"FORM"==e)&&(e=c.href)&&!Cc(e)&&ub(sb(e)[5]||null).toLowerCase()!=window.location.pathname.toLowerCase()){if(b)var f=e.indexOf("?"),e=-1==f?e+b:e.substring(0,f)+b+"&"+e.substring(f+1);-1==d.indexOf(e)&&d.push(e)}for(c=c.firstElementChild;c;c=c.nextElementSibling)Td(a,b,c,d)}};})();
