(function(){var l=this;
function n(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function p(a){return"string"==typeof a};var q=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function s(a,b){return a<b?-1:a>b?1:0};var t;a:{var v=l.navigator;if(v){var w=v.userAgent;if(w){t=w;break a}}t=""};var x=Array.prototype,y=x.indexOf?function(a,b,c){return x.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(p(a))return p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},z=x.filter?function(a,b,c){return x.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],e=0,g=p(a)?a.split(""):a,m=0;m<d;m++)if(m in g){var k=g[m];b.call(c,k,m,a)&&(f[e++]=k)}return f};function A(a){return x.concat.apply(x,arguments)}
function B(a){return x.concat.apply(x,arguments)}function C(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var D=-1!=t.indexOf("Opera")||-1!=t.indexOf("OPR"),E=-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE"),F=-1!=t.indexOf("Gecko")&&-1==t.toLowerCase().indexOf("webkit")&&!(-1!=t.indexOf("Trident")||-1!=t.indexOf("MSIE")),G=-1!=t.toLowerCase().indexOf("webkit");function H(){var a=l.document;return a?a.documentMode:void 0}
var I=function(){var a="",b;if(D&&l.opera)return a=l.opera.version,"function"==n(a)?a():a;F?b=/rv\:([^\);]+)(\)|;)/:E?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:G&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(t))?a[1]:"");return E&&(b=H(),b>parseFloat(a))?String(b):a}(),J={};
function K(a){if(!J[a]){for(var b=0,c=q(String(I)).split("."),d=q(String(a)).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",m=d[e]||"",k=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var h=k.exec(g)||["","",""],u=r.exec(m)||["","",""];if(0==h[0].length&&0==u[0].length)break;b=s(0==h[1].length?0:parseInt(h[1],10),0==u[1].length?0:parseInt(u[1],10))||s(0==h[2].length,0==u[2].length)||s(h[2],u[2])}while(0==b)}J[a]=0<=b}}
var L=l.document,M=L&&E?H()||("CSS1Compat"==L.compatMode?parseInt(I,10):5):void 0;function N(a){if(a.classList)return a.classList;a=a.className;return p(a)&&a.match(/\S+/g)||[]}function O(a,b){var c;a.classList?c=a.classList.contains(b):(c=N(a),c=0<=y(c,b));return c}function P(a,b){a.classList?a.classList.add(b):O(a,b)||(a.className+=0<a.className.length?" "+b:b)}function aa(a,b){a.classList?a.classList.remove(b):O(a,b)&&(a.className=z(N(a),function(a){return a!=b}).join(" "))}function Q(a,b){O(a,b)?aa(a,b):P(a,b)};var R;if(!(R=!F&&!E)){var S;if(S=E)S=E&&9<=M;R=S}R||F&&K("1.9.1");E&&K("9");function T(){this.a=[];this.b=!0}T.prototype.c="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAQAAABNTyozAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAlwSFlzAAALEwAACxMBAJqcGAAAATdJREFUeNrt0klOBTEQREHfDI7FTEn/4M2GBULQo22wK+ICKT1lKQAAAAAAAAAAAAAAAAAA/Jm7rmv3o+W5laU8d1uLspQYLc/SLVF8rsVoefokii9rMVqe9oni21qMlqdtovhhLUbL0y5R/LIWo+VZylKeuuX5t4nW8tRPFBtrMV6gmolic+t9xA/VSjRonl6JBs7TI9HgeVonmiDPvkSPmfO0SjRRnhaJJstTO9GEeWom2s7zVgZVI9HEeWokmjzPvkQPmfNcSZQkz9lEifKcSZQsz9FECfMcSZQ0z95E23ley8S2E6XOcz3R9HmuJUqR53yiNHnOJUqV53iidHmOJUqZZ3+itHn2JXopyd3kOZ9IntVE8qwmkmc1kTyrieRZTSTPaiJ5AAAAAAAAAAAAAAAAAGjgA62rM0XB6dNxAAAAAElFTkSuQmCC";
function U(a,b,c){var d=[];for(b=b.firstChild;b;b=b.nextSibling)"UL"==b.tagName?d=B(d,U(a,b,c+1)):("A"==b.tagName&&(b.setAttribute("data-mobilize-nav-level",c),d.push(b)),d=B(d,U(a,b,c)));return d}function V(){var a=document.querySelector(".psmob-nav-panel"),b=document.querySelector(".psmob-header-bar");Q(b,"open");Q(a,"open");Q(document.body,"noscroll")}
function ba(a){var b=document.querySelector(".psmob-menu-button");document.body.addEventListener("click",function(a){if(b.contains(a.target))V();else{var d=document.querySelector(".psmob-nav-panel");O(d,"open")&&!d.contains(a.target)&&(V(),a.stopPropagation(),a.preventDefault())}}.bind(a),!0)}
function ca(){document.querySelector("nav.psmob-nav-panel > ul").addEventListener("click",function(a){var b=a.target,c=typeof b;a=("object"==c&&null!=b||"function"==c)&&1==b.nodeType&&O(a.target,"psmob-menu-expand-icon")?a.target.parentNode:a.target;"DIV"==a.tagName&&(Q(a.nextSibling,"open"),Q(a.firstChild,"open"))})}
function W(){var a=new T;console.log("Starting nav resynthesis.");a.a=A(C(document.querySelectorAll('[data-mobile-role="navigational"]')),C(document.querySelectorAll(".topNavList")));for(var b=document.getElementsByTagName("*"),c=0,d;d=b[c];c++){var f=window.getComputedStyle(d);if("fixed"==f.getPropertyValue("position")){var e=d.getBoundingClientRect().top;d.style.top=String(60+e)+"px"}999999<=f.getPropertyValue("z-index")&&(console.log("Element z-index exceeded 999999, setting to 999998."),d.style.zIndex=
999998)}c=document.createElement("div");document.body.insertBefore(c,document.body.childNodes[0]);P(c,"psmob-header-spacer-div");b=document.createElement("header");document.body.insertBefore(b,c);P(b,"psmob-header-bar");b.innerHTML=psHeaderBarHtml;b.style.borderBottom="thin solid "+psMenuFrontColor;(c=document.getElementsByClassName("psmob-logo-span")[0])&&b.appendChild(c);if(c=document.querySelector('[data-mobile-role="logo"]'))b.style.backgroundColor=c.style.backgroundColor;b=a.b&&psMenuBackColor?
psMenuBackColor:"#3c78d8";b=".psmob-header-bar { background-color: "+b+" }\n.psmob-nav-panel { background-color: "+(a.b&&psMenuFrontColor?psMenuFrontColor:"white")+" }\n.psmob-nav-panel > ul li { color: "+b+" }\n.psmob-nav-panel > ul li a { color: "+b+" }\n";c=document.createElement("style");c.type="text/css";c.appendChild(document.createTextNode(b));document.head.appendChild(c);if(0!=a.a.length&&!psInFriendlyIframe()){b=document.getElementsByClassName("psmob-header-bar")[0];b=document.body.insertBefore(document.createElement("nav"),
b.nextSibling);P(b,"psmob-nav-panel");b=b.appendChild(document.createElement("ul"));P(b,"open");for(c=0;d=a.a[c];c++){d.setAttribute("data-mobilize-nav-section",c);f=U(a,d,0);e=[];e.push(b);for(var g=0,m=f.length;g<m;g++){var k=f[g].getAttribute("data-mobilize-nav-level"),r=g+1==m?k:f[g+1].getAttribute("data-mobilize-nav-level");if(k<r){var h=document.createElement("li"),k=h.appendChild(document.createElement("div")),r=k.appendChild(document.createElement("img"));r.setAttribute("src",a.c);P(r,"psmob-menu-expand-icon");
k.appendChild(document.createTextNode(f[g].textContent||f[g].innerText));e[e.length-1].appendChild(h);k=document.createElement("ul");h.appendChild(k);e.push(k)}else for(h=document.createElement("li"),e[e.length-1].appendChild(h),h.appendChild(f[g].cloneNode(!0)),h=k-r;0<h&&1<e.length;)e.pop(),h--}d.parentNode.removeChild(d)}d=document.querySelector(".psmob-nav-panel > ul a");f={};b=[];for(c=0;e=d[c];c++)e.href in f?(g=e.innerHTML.toLowerCase(),-1==f[e.href].indexOf(g)?f[e.href].push(g):"LI"==e.parentNode.tagName&&
b.push(e.parentNode)):(f[e.href]=[],f[e.href].push(e.innerHTML.toLowerCase()));for(c=0;d=b[c];c++)d.parentNode.removeChild(d);c=document.querySelectorAll(".psmob-nav-panel *");for(b=0;d=c[b];b++)d.removeAttribute("style"),d.removeAttribute("width"),d.removeAttribute("height"),"A"==d.tagName&&""==d.innerText&&d.hasAttribute("title")&&d.appendChild(document.createTextNode(d.getAttribute("title")));c=document.querySelectorAll(".psmob-nav-panel img:not(.psmob-menu-expand-icon)");for(b=0;d=c[b];++b)f=
Math.min(2*d.naturalHeight,40),d.setAttribute("height",f);ba(a);ca()}}var X=["fixNav"],Y=l;X[0]in Y||!Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());){var $;if($=!X.length)$=void 0!==W;$?Y[Z]=W:Y=Y[Z]?Y[Z]:Y[Z]={}};})();
