(function(){var f;
function g(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var k="closure_uid_"+(1E9*Math.random()>>>0),l=0;function m(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};function n(a){if("function"==typeof a.g)return a.g();if("string"==typeof a)return a.split("");var b=g(a);if("array"==b||"object"==b&&"number"==typeof a.length){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return m(a)};function p(a,b){this.b={};this.a=[];this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.e(a)}f=p.prototype;f.g=function(){q(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};function r(a){q(a);return a.a.concat()}f.clear=function(){this.b={};this.f=this.a.length=0};
f.remove=function(a){return s(this.b,a)?(delete this.b[a],this.f--,this.a.length>2*this.f&&q(this),!0):!1};function q(a){if(a.f!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];s(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.f!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],s(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}f.get=function(a,b){return s(this.b,a)?this.b[a]:b};f.set=function(a,b){s(this.b,a)||(this.f++,this.a.push(a));this.b[a]=b};
f.e=function(a){var b;if(a instanceof p)b=r(a),a=a.g();else{b=[];var c=0,d;for(d in a)b[c++]=d;a=m(a)}for(c=0;c<b.length;c++)this.set(b[c],a[c])};f.forEach=function(a,b){for(var c=r(this),d=0;d<c.length;d++){var e=c[d],h=this.get(e);a.call(b,h,e,this)}};f.clone=function(){return new p(this)};function s(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function t(a){this.b=new p;a&&this.e(a)}function u(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[k]||(a[k]=++l)):b.substr(0,1)+a}f=t.prototype;f.add=function(a){this.b.set(u(a),a)};f.e=function(a){a=n(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};f.remove=function(a){return this.b.remove(u(a))};f.clear=function(){this.b.clear()};f.contains=function(a){a=u(a);return s(this.b.b,a)};f.g=function(){return this.b.g()};f.clone=function(){return new t(this)};google.load("visualization","1.0",{packages:["corechart"]});function v(a){window.console&&console.error(a)}
function x(){this.c=[];this.n=new t;this.h=this.k=null;this.q={width:900,height:255,colors:["#4ECDC4","#556270","#C7F464"],legend:{position:"bottom"},hAxis:{format:"MMM d, y hh:mma",gridlines:{color:"#F2F2F2"},baselineColor:"#E5E5E5"},vAxis:{format:"#.###%",minValue:0,viewWindowMode:"explicit",viewWindow:{min:0},gridlines:{color:"#F2F2F2"},baselineColor:"#E5E5E5"},chartArea:{left:60,top:20,width:800},pointSize:2}}function y(a){var b={};b.d=new t([a]);b.evaluate=function(b){return b(a)};return b}
function z(a){var b={};b.d=new t;for(var c=0;c<a.length;c++)b.d.e(a[c].d);b.evaluate=function(b){for(var c=0,h=0;h<a.length;h++)c+=a[h].evaluate(b);return c};return b}function A(a,b){var c={};c.d=new t;c.d.e(a.d);c.d.e(b.d);c.evaluate=function(c){var e=b.evaluate(c);return 0==e?0:a.evaluate(c)/e};return c}function B(a,b){return A(a,z([a,b]))}
function C(){var a=new x;D(a,"Resources not loaded because of fetch failures","fetch-failure",A(y("serf_fetch_failure_count"),y("serf_fetch_request_count")));D(a,"Resources not rewritten because domain wasn't authorized","not-authorized",B(y("resource_url_domain_rejections"),y("resource_url_domain_acceptances")));D(a,"Resources not rewritten because of restrictive Cache-Control headers","cache-control",B(y("num_cache_control_not_rewritable_resources"),y("num_cache_control_rewritable_resources")));
var b=z([y("cache_backend_misses"),y("cache_backend_hits")]);D(a,"Cache misses","cache-miss",A(y("cache_backend_misses"),b));D(a,"Cache lookups that were expired","cache-expired",A(y("cache_expirations"),b));D(a,"CSS files not rewritten because of parse errors","css-error",B(y("css_filter_parse_failures"),y("css_filter_blocks_rewritten")));D(a,"JavaScript minification failures","js-error",B(y("javascript_minification_failures"),y("javascript_blocks_minified")));var b=z([y("image_rewrites"),y("image_rewrites_dropped_nosaving_resize"),
y("image_rewrites_dropped_nosaving_noresize")]),c=z([y("image_norewrites_high_resolution"),y("image_rewrites_dropped_decode_failure"),y("image_rewrites_dropped_due_to_load"),y("image_rewrites_dropped_mime_type_unknown"),y("image_rewrites_dropped_server_write_fail")]);D(a,"Image rewrite failures","image-error",B(c,b));b=new Date;E(a,new Date(b-864E5),b);return a}var F=["pagespeed","startConsole"],G=this;F[0]in G||!G.execScript||G.execScript("var "+F[0]);
for(var H;F.length&&(H=F.shift());){var I;if(I=!F.length)I=void 0!==C;I?G[H]=C:G=G[H]?G[H]:G[H]={}}function D(a,b,c,d){var e={};e.title=b;e.p="https://developers.google.com/speed/pagespeed/module/console#"+c;e.value=d;e.r=a.c.length;e.i=null;e.j=null;e.l=null;e.m=null;a.c.push(e);a.n.e(d.d)}function J(a,b,c){var d=pagespeedStatisticsUrl+"?json",d=d+("&start_time="+b.getTime()),d=d+("&end_time="+c.getTime()),d=d+"&granularity=60000&var_titles=";for(b=0;b<a.length;b++)d+=a[b]+",";return d}
function E(a,b,c){var d=new XMLHttpRequest;b=J(a.n.g(),b,c);d.onreadystatechange=function(){if(4==this.readyState)if(200!=this.status||1>this.responseText.length||"{"!=this.responseText[0])v("XHR request failed.");else{var b=JSON.parse(this.responseText);K(a,b)}};d.open("GET",b);d.send()}
function K(a,b){a.k=b.variables;a.h=b.timestamps;L(a.h,a.k);for(var c=0;c<a.c.length;c++){for(var d=[],e=0;e<a.h.length;e++)d.push(a.c[c].value.evaluate(function(a){return function(b){if(b in a)return a[b][e];v("JSON data missing required variable.");return 0}}(a.k)));a.c[c].i=d[d.length-1];a.c[c].j=a.c[c].i;a.c[c].l=N(a.c[c].title,a.h,d)}a.c.sort(function(a,b){return b.j-a.j});for(c=0;c<a.c.length;c++)O(a,a.c[c])}
function L(a,b){for(var c in b)a.length!=b[c].length&&v("JSON response is malformed. ("+a.length+" != "+b[c].length+")")}function N(a,b,c){var d=new google.s.t;d.o("datetime","Time");d.o("number",a);for(var e=0;e<b.length;e++)d.v([new Date(b[e]),c[e]]);0==d.A()&&v("Data failed to load for graph "+a);return d}
function O(a,b){var c=google.s.u,d=b.title,e=b.i,h=b.p,M=b.r,w=document.createElement("div");w.setAttribute("class","pagespeed-widgets");w.appendChild(P(d,e,h,M));d=document.createElement("div");d.setAttribute("class","pagespeed-graph");w.appendChild(d);document.getElementById("pagespeed-graphs-container").appendChild(w);b.m=new c(d);b.m.w(b.l,a.q)}
function P(a,b,c,d){var e=document.createElement("div");e.setAttribute("class","pagespeed-widgets-topbar");var h=document.createElement("span");h.setAttribute("class","pagespeed-title");h.setAttribute("id","pagespeed-title"+d);h.appendChild(document.createTextNode(a+": "+(100*b).toFixed(2)+"% ("));a=document.createElement("a");a.setAttribute("href",c);a.appendChild(document.createTextNode("doc"));h.appendChild(a);h.appendChild(document.createTextNode(")"));e.appendChild(h);return e};})();
