(function(){var e=window,f=document,g="push",h="exec",i="createElement",k="addEventListener",l="setAttribute",m="attachEvent",n="documentElement",o="toString",p="length",q="prototype",r="call",s="getAttribute",t="querySelectorAll",u="parentNode",v="",y="\n",z='");',A="*",B=":not([psa_not_processed])",C="<div>_</div>",D='=document.getElementById("',E="Add to queue str: ",F="Add to queue url: ",G="DOMContentLoaded",H="Evaluated: ",I="Exception while evaluating.",J="Exception while overriding document.readyState.",
aa="Executed: ",ba="Firefox",ca="HTMLEvents",da="PSA ERROR: ",K="SCRIPT",ea="Unable to insert nodes, no context element found",fa="[psa_not_processed]",ga="application/ecmascript",ha="application/javascript",ia="application/x-ecmascript",ja="application/x-javascript",ka="complete",la="data:text/javascript,",ma="div",na="domready: ",oa="dw: ",pa="error",qa="executing domready: ",ra="executing pageload: ",sa="handle_dw: ",L="id",M="language",N="load",ta="loaded",ua="loading",O="on",va="onDOMContentLoaded",
wa="onload",xa="onload: ",ya="onreadystatechange",P="orig_src",za="orig_type",Aa="psa_dw_target",Q="psa_not_processed",Ba="readyState",R="readystatechange",S="script",Ca="span",T="src",Da="text/",Ea="text/ecmascript",U="text/javascript",Fa="text/javascript1.0",Ga="text/javascript1.1",Ha="text/javascript1.2",Ia="text/javascript1.3",Ja="text/javascript1.4",Ka="text/javascript1.5",La="text/jscript",Ma="text/livescript",V="text/psajs",Na="text/x-ecmascript",Oa="text/x-javascript",Pa="true",W="type",Qa=
"var ",X;e.pagespeed=e.pagespeed||{};var Y=e.pagespeed,Z=function(){this.i=[];this.f=[];this.g=0;this.a=null;this.b=v;this.j=[];this.h=[];this.n=[];this.m=[];this.s=[ga,ha,ia,ja,Ea,U,Fa,Ga,Ha,Ia,Ja,Ka,La,Ma,Na,Oa];this.q=f.getElementById;this.r=f.getElementsByTagName;this.e=0},$=!1;X=Z[q];X.log=function(a,b){this.f&&(this.f[g](v+a),b&&(this.f[g](b),"undefined"!=typeof console&&"undefined"!=typeof console.log&&console.log(da+a+b.message)))};X.u=function(a,b){this.i.splice(b?b:this.i[p],0,a)};
X.B=function(a){var b=f[i](S);b.text=a;b[l](W,U);this.a[u].insertBefore(b,this.a)};X.K=function(){for(var a=f.getElementsByTagName(A),b=v,c=0;c<a[p];c++)if(a[c].hasAttribute(L)){var d=a[c][s](L);d&&-1==d.search(/[-:.]/)&&-1==d.search(/^[0-9]/)&&e[d]&&e[d].tagName&&(b+=Qa+d+D+d+z)}b&&this.B(b)};X.F=function(a,b){var c=a[s](P)||a[s](T);c&&this.addUrl(c,a,b);if(!c||!$)(c=a.innerHTML||a.textContent||a.data)&&this.G(c,a,b)};
X.G=function(a,b,c){if(this.M())this.addUrl(la+encodeURIComponent(a),b,c);else{this.f[g](E+a);var d=this;this.u(function(){d.a=b;d.l(b);try{d.B(a)}catch(c){d.log(I,c)}d.log(H+a);d.o()},c)}};Z[q].addStr=Z[q].G;
Z[q].addUrl=function(a,b,c){this.f[g](F+a);var d=this;this.u(function(){d.a=b;d.l(b);var c=f[i](S);c[l](W,U);var j=function(){d.log(aa+a);d.o()};Y.z(c,j);Y.k(c,pa,j);9>d.d()&&Y.k(c,R,function(){if(c.readyState==ka||c.readyState==ta)c.onreadystatechange=null,j()});c[l](T,a);if($){var x=b.innerHTML||b.textContent||b.data;x&&c.appendChild(f.createTextNode(x))}d.a[u].insertBefore(c,d.a)},c)};Z[q].addUrl=Z[q].addUrl;X=Z[q];
X.l=function(a){if($&&f[t]&&!(8>=this.d()))for(var b=f[t](fa),c=0;c<b[p];c++){var d=b.item(c);if(d==a)break;d[s](W)!=V&&d.removeAttribute(Q)}};X.L=function(){if($)for(var a=this.r[r](f,A),b=0;b<a[p];b++)a.item(b)[l](Q,v)};
X.P=function(){this.l();this.d()&&f[n].originalDoScroll&&(f[n].doScroll=f[n].originalDoScroll);Object.defineProperty&&delete f.readyState;$&&(f.getElementById=this.q,f[t]&&!(8>=this.d())&&(f.getElementsByTagName=this.r));f.a?(f.addEventListener=f.a,e.addEventListener=e.a):f.b&&(f.attachEvent=f.b,e.attachEvent=e.b);this.I();this.J();this.e=3;this.H()};X.o=function(){this.t();this.g<this.i[p]?(this.g++,this.i[this.g-1][r](e)):this.P()};
X.D=function(a){for(var b=[],c=a[p],d=0;d<c;++d)b[g](a.item(d));return b};
X.Q=function(){var a=f[i](Ca);a[l](Aa,Pa);f.body.appendChild(a);this.a=a;this.d()&&this.K();this.L();if(Object.defineProperty)try{Object.defineProperty(f,Ba,{configurable:!0,get:function(){return ua}})}catch(b){this.log(J,b)}this.d()&&(f[n].originalDoScroll=f[n].doScroll,f[n].doScroll=function(){throw"psa exception";});this.v(f);this.v(e);f.writeln=function(a){Y.c.w(a+y)};f.write=function(a){Y.c.w(a)};f.open=function(){};f.close=function(){};$&&(f.getElementById=function(a){Y.c.t();return Y.c.q[r](f,
a)},f[t]&&!(8>=Y.c.d())&&(f.getElementsByTagName=function(a){return f[t](a+B)}))};X.$=function(){2<=this.e||(this.O(),this.e=2,this.Q(),this.o())};Z[q].run=Z[q].$;X=Z[q];X.T=function(a){var b=f[i](ma);b.innerHTML=C+a;b.removeChild(b.firstChild);return b};X.V=function(a){var b=a[u];b&&b.removeChild(a)};X.S=function(a,b){for(var c=this.D(a),d=c[p],w=b[u],j=0;j<d;++j){var x=c[j];this.V(x);w.insertBefore(x,b)}};
X.U=function(a){return a.nodeName!=K?!1:a.hasAttribute(W)?(a=a[s](W),!a||-1!=this.s.indexOf(a)):a.hasAttribute(M)?(a=a[s](M),!a||-1!=this.s.indexOf(Da+a.toLowerCase())):!0};X.C=function(a,b){if(a.childNodes)for(var c=this.D(a.childNodes),d=c[p],w=0;w<d;++w){var j=c[w];$&&1==j.nodeType&&j[l](Q,v);j.nodeName==K?this.U(j)&&(b[g](j),j[l](za,j.type),j[l](W,V),j[l](P,j.src),j[l](T,v)):this.C(j,b)}};X.R=function(a,b){for(var c=a[p],d=0;d<c;++d)this.F(a[d],b+d)};
X.N=function(a,b,c){var a=this.T(a),d=[];this.C(a,d);c?this.S(a.childNodes,c):this.log(ea);this.R(d,b)};X.t=function(){if(this.b!=v){this.log(sa+this.b);var a=this.b;this.b=v;this.N(a,this.g,this.a)}};X.w=function(a){this.log(oa+a);this.b+=a};X.A=function(a,b){this.log(na+b[o]());this.j[g](function(){b[r](a)})};X.p=function(a,b){this.log(xa+b[o]());if(3==this.e)b[r](a);else{var c;8>=this.d()||(c=f.createEvent(ca),c.initEvent(N,!1,!1));this.h[g](function(){b[r](a,c)})}};Z[q].addOnloadListeners=Z[q].p;
Z[q].Y=function(a){this.n[g](a)};Z[q].addBeforeDeferRunFunctions=Z[q].Y;Z[q].X=function(a){this.m[g](a)};Z[q].addAfterDeferRunFunctions=Z[q].X;X=Z[q];X.I=function(){for(var a=0;a<this.j[p];a++)this.log(qa+this.j[a][o]()),this[h](this.j[a]);f.onreadystatechange&&this[h](f.onreadystatechange,f)};X.J=function(){for(var a=0;a<this.h[p];a++)this.log(ra+this.h[a][o]()),this[h](this.h[a])};X.O=function(){for(var a=0;a<this.n[p];a++)this[h](this.n[a])};X.H=function(){for(var a=0;a<this.m[p];a++)this[h](this.m[a])};
X.exec=function(a,b){try{a[r](b||e)}catch(c){this.log(I,c)}};X.v=function(a){a[k]&&!a.a?(a.a=a[k],a.addEventListener=function(b,c,d){b==G||b==R?Y.c.A(a,c):b==N?Y.c.p(a,c):a.a(b,c,d)}):a[m]&&!a.b&&(a.b=a[m],a.attachEvent=function(b,c){b==va||b==ya?Y.c.A(a,c):b==wa?Y.c.p(a,c):a.b(b,c)})};X.Z=function(){if(!(1<=this.e)){this.e=1;for(var a=f.getElementsByTagName(S),b=a[p],c=0;c<b;++c){var d=a[c];d[s](W)==V&&this.F(d)}}};Z[q].registerScriptTags=Z[q].Z;Y.z=function(a,b){Y.k(a,N,b)};Y.addOnload=Y.z;
Y.k=function(a,b,c){if(a[k])a[k](b,c,!1);else if(a[m])a[m](O+b,c);else{var d=a[O+b];a[O+b]=function(){c[r](this);d&&d[r](this)}}};Y.addHandler=Y.k;Y.outerHTML=function(a){return a.outerHTML||(new XMLSerializer).serializeToString(a)};Z[q].M=function(){return-1!=navigator.userAgent.indexOf(ba)};Z[q].d=function(){var a=/(?:MSIE.(\d+\.\d+))/[h](navigator.userAgent);return a&&a[1]?f.documentMode||parseFloat(a[1]):NaN};
Y.W=function(){Y.c||(e.localStorage&&($=e.localStorage.defer_js_experimental),Y.c=new Z,Y.deferJs=Y.c)};Y.deferInit=Y.W;})();
