(function(){var e=window,f=document,g="push",i="createElement",j="addEventListener",k="setAttribute",l="attachEvent",m="documentElement",n="toString",o="length",p="prototype",q="call",r="getAttribute",s="parentNode",u="",v="\n",w='");',x="*",y="<div>_</div>",z='=document.getElementById("',A="Add to queue str: ",B="Add to queue url: ",C="DOMContentLoaded",D="Evaluated: ",E="Exception while evaluating.",F="Exception while overriding document.readyState.",G="Executed: ",H="Firefox",I="PSA ERROR: ",J="SCRIPT",L=
"Unable to insert nodes, no context element found",M="application/ecmascript",aa="application/javascript",ba="application/x-ecmascript",ca="application/x-javascript",da="complete",ea="data:text/javascript,",fa="div",ga="domready: ",ha="dw: ",ia="error",ja="executing domready: ",ka="executing pageload: ",la="handle_dw: ",N="id",O="language",P="load",ma="loaded",na="loading",Q="on",oa="onDOMContentLoaded",pa="onload",qa="onload: ",ra="onreadystatechange",R="orig_src",sa="orig_type",ta="psa_dw_target",
ua="readyState",S="readystatechange",T="script",va="span",U="src",wa="text/",xa="text/ecmascript",V="text/javascript",ya="text/javascript1.0",za="text/javascript1.1",Aa="text/javascript1.2",Ba="text/javascript1.3",Ca="text/javascript1.4",Da="text/javascript1.5",Ea="text/jscript",Fa="text/livescript",W="text/psajs",Ga="text/x-ecmascript",Ha="text/x-javascript",Ia="true",X="type",Ja="var ",Y;e.pagespeed=e.pagespeed||{};
var Z=e.pagespeed,$=function(){this.g=[];this.d=[];this.f=0;this.a=null;this.b=u;this.h=[];this.i=[];this.m=[M,aa,ba,ca,xa,V,ya,za,Aa,Ba,Ca,Da,Ea,Fa,Ga,Ha]};Y=$[p];Y.log=function(a,b){this.d&&(this.d[g](u+a),b&&(this.d[g](b),"undefined"!=typeof console&&"undefined"!=typeof console.log&&console.log(I+a+b.message)))};Y.n=function(a,b){this.g.splice(b?b:this.g[o],0,a)};Y.r=function(a){var b=f[i](T);b.text=a;b[k](X,V);this.a[s].insertBefore(b,this.a)};
Y.F=function(){for(var a=f.getElementsByTagName(x),b=u,c=0;c<a[o];c++)if(a[c].hasAttribute(N)){var d=a[c][r](N);d&&-1==d.search(/[-:.]/)&&-1==d.search(/^[0-9]/)&&e[d]&&e[d].tagName&&(b+=Ja+d+z+d+w)}b&&this.r(b)};Y.z=function(a,b){var c=a[r](R)||a[r](U);c&&this.l(c,a,b);(c=a.innerHTML||a.textContent||a.data)&&this.w(c,a,b)};
Y.w=function(a,b,c){if(this.A())this.l(ea+encodeURIComponent(a),b,c);else{this.d[g](A+a);var d=this;this.n(function(){b&&(d.a=b);try{d.r(a)}catch(c){d.log(E,c)}d.log(D+a);d.k()},c)}};$[p].addStr=$[p].w;$[p].l=function(a,b,c){this.d[g](B+a);var d=this;this.n(function(){b&&(d.a=b);var c=f[i](T);c[k](X,V);var h=function(){d.log(G+a);d.k()};Z.o(c,h);Z.j(c,ia,h);9>d.e()&&Z.j(c,S,function(){if(c.readyState==da||c.readyState==ma){c.onreadystatechange=null;h()}});c[k](U,a);d.a[s].insertBefore(c,d.a)},c)};
$[p].addUrl=$[p].l;Y=$[p];Y.H=function(){this.e()&&f[m].originalDoScroll&&(f[m].doScroll=f[m].originalDoScroll);Object.defineProperty&&delete f.readyState;f.a?(f.addEventListener=f.a,e.addEventListener=e.a):f.b&&(f.attachEvent=f.b,e.attachEvent=e.b);this.B();this.C()};Y.k=function(){this.G();this.f<this.g[o]?(this.f++,this.g[this.f-1][q](e)):this.H()};Y.u=function(a){for(var b=[],c=a[o],d=0;d<c;++d)b[g](a.item(d));return b};
Y.M=function(){if(Object.defineProperty)try{Object.defineProperty(f,ua,{configurable:!0,get:function(){return na}})}catch(a){this.log(F,a)}this.e()&&(f[m].originalDoScroll=f[m].doScroll,f[m].doScroll=function(){throw"psa exception";});this.s(f);this.s(e);var b=f[i](va);b[k](ta,Ia);f.body.appendChild(b);this.a=b;this.e()&&this.F()};Y.Q=function(){this.M();this.k()};$[p].run=$[p].Q;Y=$[p];Y.K=function(a){var b=f[i](fa);b.innerHTML=y+a;b.removeChild(b.firstChild);return b};
Y.N=function(a){var b=a[s];b&&b.removeChild(a)};Y.J=function(a,b){for(var c=this.u(a),d=c[o],t=b[s],h=0;h<d;++h){var K=c[h];this.N(K);t.insertBefore(K,b)}};Y.L=function(a){return a.nodeName!=J?!1:a.hasAttribute(X)?(a=a[r](X),!a||-1!=this.m.indexOf(a)):a.hasAttribute(O)?(a=a[r](O),!a||-1!=this.m.indexOf(wa+a.toLowerCase())):!0};
Y.t=function(a,b){if(a.childNodes)for(var c=this.u(a.childNodes),d=c[o],t=0;t<d;++t){var h=c[t];h.nodeName==J?this.L(h)&&(b[g](h),h[k](sa,h.type),h[k](X,W),h[k](R,h.src),h[k](U,u)):this.t(h,b)}};Y.I=function(a,b){for(var c=a[o],d=0;d<c;++d)this.z(a[d],b+d)};Y.D=function(a,b,c){var a=this.K(a),d=[];this.t(a,d);c?this.J(a.childNodes,c):this.log(L);this.I(d,b)};Y.G=function(){if(this.b!=u){this.log(la+this.b);var a=this.b;this.b=u;this.D(a,this.f,this.a)}};Y.v=function(a){this.log(ha+a);this.b+=a};
Y.p=function(a){this.log(ga+a[n]());this.h[g](a)};Y.q=function(a){this.log(qa+a[n]());this.i[g](a)};Y.B=function(){for(var a=0;a<this.h[o];a++)this.log(ja+this.h[a][n]()),this.h[a][q](e);if(f.onreadystatechange)f.onreadystatechange()};Y.C=function(){for(var a=0;a<this.i[o];a++)this.log(ka+this.i[a][n]()),this.i[a][q](e)};
Y.s=function(a){a[j]&&!a.a?(a.a=a[j],a.addEventListener=function(b,c,d){b==C||b==S?Z.c.p(c):b==P?Z.c.q(c):a.a(b,c,d)}):a[l]&&!a.b&&(a.b=a[l],a.attachEvent=function(b,c){b==oa||b==ra?Z.c.p(c):b==pa?Z.c.q(c):a.b(b,c)})};Y.P=function(){for(var a=f.getElementsByTagName(T),b=a[o],c=0;c<b;++c){var d=a[c];d[r](X)==W&&this.z(d)}};$[p].registerScriptTags=$[p].P;Z.o=function(a,b){Z.j(a,P,b)};Z.addOnload=Z.o;
Z.j=function(a,b,c){if(a[j])a[j](b,c,!1);else if(a[l])a[l](Q+b,c);else{var d=a[Q+b];a[Q+b]=function(){c[q](this);d&&d[q](this)}}};Z.addHandler=Z.j;Z.outerHTML=function(a){return a.outerHTML||(new XMLSerializer).serializeToString(a)};$[p].A=function(){return-1!=navigator.userAgent.indexOf(H)};$[p].e=function(){var a=/(?:MSIE.(\d+\.\d+))/.exec(navigator.userAgent);return a&&a[1]?f.documentMode||parseFloat(a[1]):NaN};
Z.O=function(){Z.c=new $;Z.deferJs=Z.c;f.writeln=function(a){Z.c.v(a+v)};f.write=function(a){Z.c.v(a)};f.open=function(){};f.close=function(){}};Z.deferInit=Z.O;})();
