(function(){var d=window,f=document;function g(a,b){return a.addEventListener=b}function h(a,b){return a.attachEvent=b}
var i="push",j="createElement",l="addEventListener",m="setAttribute",n="attachEvent",o="documentElement",p="length",r="prototype",s="call",t="getAttribute",u="querySelectorAll",v="fireEvent",w="parentNode",x="",y="\n",z='");',B="*",C=":not([psa_not_processed])",D="<div>_</div>",E='=document.getElementById("',F="Add to queue str: ",aa="Add to queue url: ",ba="Evaluated: ",G="Exception while evaluating.",ca="Exception while overriding document.readyState.",da="Executed: ",ea="Firefox",fa="Firing Event: ",
ga="HTMLEvents",ha="PSA ERROR: ",H="SCRIPT",ia="Unable to insert nodes, no context element found",ja="[psa_not_processed]",ka="application/ecmascript",la="application/javascript",ma="application/x-ecmascript",na="application/x-javascript",oa="complete",pa="data:text/javascript,",qa="div",ra="dw: ",sa="error",ta="handle_dw: ",I="id",J="language",K="load",ua="loaded",va="loading",L="on",wa="onDOMContentLoaded",M="onafterscripts",N="onbeforescripts",O="onload",xa="onload: ",ya="onreadystatechange",P=
"orig_src",za="orig_type",Aa="psa_dw_target",Q="psa_not_processed",Ba="readyState",Ca="readystatechange",R="script",Da="span",S="src",Ea="text/",Fa="text/ecmascript",T="text/javascript",Ga="text/javascript1.0",Ha="text/javascript1.1",Ia="text/javascript1.2",Ja="text/javascript1.3",Ka="text/javascript1.4",La="text/javascript1.5",Ma="text/jscript",Na="text/livescript",U="text/psajs",Oa="text/x-ecmascript",Pa="text/x-javascript",Qa="true",V="type",Ra="var ",W;d.pagespeed=d.pagespeed||{};
var X=d.pagespeed,Y=function(){this.i=[];this.f=[];this.h=0;this.b=null;this.e=x;this.g={};this.s=[ka,la,ma,na,Fa,T,Ga,Ha,Ia,Ja,Ka,La,Ma,Na,Oa,Pa];this.m=f.getElementById;this.n=f.getElementsByTagName;this.H=f.write;this.I=f.writeln;this.G=f.open;this.F=f.close;this.o=f[l];this.q=d[l];this.p=f[n];this.r=d[n];this.d=0},Z=!1;W=Y[r];W.log=function(a,b){this.f&&(this.f[i](x+a),b&&(this.f[i](b),"undefined"!=typeof console&&"undefined"!=typeof console.log&&console.log(ha+a+b.message)))};
W.u=function(a,b){this.i.splice(b?b:this.i[p],0,a)};W.z=function(a){var b=f[j](R);b.text=a;b[m](V,T);this.b[w].insertBefore(b,this.b)};W.J=function(){for(var a=f.getElementsByTagName(B),b=x,c=0;c<a[p];c++)if(a[c].hasAttribute(I)){var e=a[c][t](I);e&&-1==e.search(/[-:.]/)&&-1==e.search(/^[0-9]/)&&d[e]&&d[e].tagName&&(b+=Ra+e+E+e+z)}b&&this.z(b)};W.C=function(a,b){var c=a[t](P)||a[t](S);c&&this.addUrl(c,a,b);if(!c||!Z)(c=a.innerHTML||a.textContent||a.data)&&this.D(c,a,b)};
W.D=function(a,b,c){if(this.N())this.addUrl(pa+encodeURIComponent(a),b,c);else{this.f[i](F+a);var e=this;this.u(function(){e.b=b;e.k(b);try{e.z(a)}catch(c){e.log(G,c)}e.log(ba+a);e.l()},c)}};Y[r].addStr=Y[r].D;
Y[r].addUrl=function(a,b,c){this.f[i](aa+a);var e=this;this.u(function(){e.b=b;e.k(b);var c=f[j](R);c[m](V,T);var k=function(){e.log(da+a);e.l()};X.w(c,k);X.j(c,sa,k);9>e.c()&&X.j(c,Ca,function(){if(c.readyState==oa||c.readyState==ua)c.onreadystatechange=null,k()});c[m](S,a);if(Z){var A=b.innerHTML||b.textContent||b.data;A&&c.appendChild(f.createTextNode(A))}e.b[w].insertBefore(c,e.b)},c)};Y[r].addUrl=Y[r].addUrl;W=Y[r];
W.k=function(a){if(Z&&f[u]&&!(8>=this.c()))for(var b=f[u](ja),c=0;c<b[p];c++){var e=b.item(c);if(e==a)break;e[t](V)!=U&&e.removeAttribute(Q)}};W.L=function(){if(Z)for(var a=this.n[s](f,B),b=0;b<a[p];b++)a.item(b)[m](Q,x)};
W.P=function(){this.k();this.c()&&f[o].originalDoScroll&&(f[o].doScroll=f[o].originalDoScroll);Object.defineProperty&&delete f.readyState;Z&&(f.getElementById=this.m,f[u]&&!(8>=this.c())&&(f.getElementsByTagName=this.n));this.M();f.open=this.G;f.close=this.F;f.write=this.H;f.writeln=this.I;this[v](0);f.onreadystatechange&&this.exec(f.onreadystatechange,f);this[v](1);this.d=3;this[v](3)};W.l=function(){this.t();this.h<this.i[p]?(this.h++,this.i[this.h-1][s](d)):this.P()};
W.B=function(a){for(var b=[],c=a[p],e=0;e<c;++e)b[i](a.item(e));return b};
W.Q=function(){var a=f[j](Da);a[m](Aa,Qa);f.body.appendChild(a);this.b=a;this.c()&&this.J();this.L();if(Object.defineProperty)try{Object.defineProperty(f,Ba,{configurable:!0,get:function(){return va}})}catch(b){this.log(ca,b)}this.c()&&(f[o].originalDoScroll=f[o].doScroll,f[o].doScroll=function(){throw"psa exception";});this.K();f.writeln=function(a){X.a.v(a+y)};f.write=function(a){X.a.v(a)};f.open=function(){};f.close=function(){};Z&&(f.getElementById=function(a){X.a.t();return X.a.m[s](f,a)},f[u]&&
!(8>=X.a.c())&&(f.getElementsByTagName=function(a){return f[u](a+C)}))};W.aa=function(){2<=this.d||(this[v](2),this.d=2,this.Q(),this.l())};Y[r].run=Y[r].aa;W=Y[r];W.T=function(a){var b=f[j](qa);b.innerHTML=D+a;b.removeChild(b.firstChild);return b};W.V=function(a){var b=a[w];b&&b.removeChild(a)};W.S=function(a,b){for(var c=this.B(a),e=c[p],q=b[w],k=0;k<e;++k){var A=c[k];this.V(A);q.insertBefore(A,b)}};
W.U=function(a){return a.nodeName!=H?!1:a.hasAttribute(V)?(a=a[t](V),!a||-1!=this.s.indexOf(a)):a.hasAttribute(J)?(a=a[t](J),!a||-1!=this.s.indexOf(Ea+a.toLowerCase())):!0};W.A=function(a,b){if(a.childNodes)for(var c=this.B(a.childNodes),e=c[p],q=0;q<e;++q){var k=c[q];Z&&1==k.nodeType&&k[m](Q,x);k.nodeName==H?this.U(k)&&(b[i](k),k[m](za,k.type),k[m](V,U),k[m](P,k.src),k[m](S,x)):this.A(k,b)}};W.R=function(a,b){for(var c=a[p],e=0;e<c;++e)this.C(a[e],b+e)};
W.O=function(a,b,c){var a=this.T(a),e=[];this.A(a,e);c?this.S(a.childNodes,c):this.log(ia);this.R(e,b)};W.t=function(){if(this.e!=x){this.log(ta+this.e);var a=this.e;this.e=x;this.O(a,this.h,this.b)}};W.v=function(a){this.log(ra+a);this.e+=a};W.W=function(a,b){this.log(xa+b.toString());if(3==this.d)b[s](a);else{var c;8>=this.c()||(c=f.createEvent(ga),c.initEvent(K,!1,!1));$(a,O,function(){b[s](a,c)})}};Y[r].addOnloadListeners=Y[r].W;Y[r].Z=function(a){$(d,N,a)};Y[r].addBeforeDeferRunFunctions=Y[r].Z;
Y[r].Y=function(a){$(d,M,a)};Y[r].addAfterDeferRunFunctions=Y[r].Y;Y[r].fireEvent=function(a){this.log(fa+a);for(var a=this.g[a]||[],b=0;b<a[p];++b)this.exec(a[b])};Y[r].exec=function(a,b){try{a[s](b||d)}catch(c){this.log(G,c)}};Y[r].K=function(){d[l]?(g(f,function(a,b,c){$(f,L+a,b,c,X.a.o)}),g(d,function(a,b,c){$(d,L+a,b,c,X.a.q)})):d[n]&&(h(f,function(a,b){$(f,a,b,void 0,X.a.p)}),h(d,function(a,b){$(d,a,b,void 0,X.a.r)}))};
Y[r].M=function(){d[l]?(g(f,this.o),g(d,this.q)):d[n]&&(h(f,this.p),h(d,this.r))};var $=function(a,b,c,e,q){if(!(3<=X.a.d)){if(b==wa||b==ya)b=0;else if(b==O)b=1;else if(b==N)b=2;else if(b==M)b=3;else{q&&q(b,c,e);return}X.a.g[b]||(X.a.g[b]=[]);X.a.g[b][i](function(){c[s](a)})}};Y[r].$=function(){if(!(1<=this.d)){this.d=1;for(var a=f.getElementsByTagName(R),b=a[p],c=0;c<b;++c){var e=a[c];e[t](V)==U&&this.C(e)}}};Y[r].registerScriptTags=Y[r].$;X.w=function(a,b){X.j(a,K,b)};X.addOnload=X.w;
X.j=function(a,b,c){if(a[l])a[l](b,c,!1);else if(a[n])a[n](L+b,c);else{var e=a[L+b];a[L+b]=function(){c[s](this);e&&e[s](this)}}};X.addHandler=X.j;X.outerHTML=function(a){return a.outerHTML||(new XMLSerializer).serializeToString(a)};Y[r].N=function(){return-1!=navigator.userAgent.indexOf(ea)};Y[r].c=function(){var a=/(?:MSIE.(\d+\.\d+))/.exec(navigator.userAgent);return a&&a[1]?f.documentMode||parseFloat(a[1]):NaN};
X.X=function(){X.a||(d.localStorage&&(Z=d.localStorage.defer_js_experimental),X.a=new Y,X.deferJs=X.a)};X.deferInit=X.X;})();
