(function(){var f=function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent("on"+b,c);else{var d=a["on"+b];a["on"+b]=function(){c.call(this);d&&d.call(this)}}};window.pagespeed=window.pagespeed||{};
var g=window.pagespeed,k=function(a){this.d=[];this.e=0;this.c=!1;this.h=a;this.f=null;this.i=0;this.b=!1;this.a=0},l=function(a,b){var c=b.getAttribute("pagespeed_lazy_position");if(c)return parseInt(c,0);var c=b.offsetTop,d=b.offsetParent;d&&(c+=l(a,d));c=Math.max(c,0);b.setAttribute("pagespeed_lazy_position",c);return c},m=function(a,b){var c,d,e;if(!a.b&&(0==b.offsetHeight||0==b.offsetWidth))return!1;e:if(b.currentStyle)d=b.currentStyle.position;else{if(document.defaultView&&document.defaultView.getComputedStyle&&
(d=document.defaultView.getComputedStyle(b,null))){d=d.getPropertyValue("position");break e}d=b.style&&b.style.position?b.style.position:""}if("relative"==d)return!0;e=0;"number"==typeof window.pageYOffset?e=window.pageYOffset:document.body&&document.body.scrollTop?e=document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop&&(e=document.documentElement.scrollTop);c=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight;d=e;e=e+c;var h=b.getBoundingClientRect();
h?(e=h.top-c,d=h.bottom):(h=l(a,b),c=h+b.offsetHeight,e=h-e,d=c-d);return e<=a.e&&0<=d+a.e};
k.prototype.j=function(a){p(a);var b=this;window.setTimeout(function(){var c=a.getAttribute("pagespeed_lazy_src");if(null!=c)if((b.c||m(b,a))&&-1!=a.src.indexOf(b.h)){var d=a.parentNode,e=a.nextSibling;d&&d.removeChild(a);a.g&&(a.getAttribute=a.g);a.removeAttribute("onload");a.tagName&&"IMG"==a.tagName&&g.CriticalImages&&f(a,"load",function(){g.CriticalImages.checkImageForCriticality(this);b.b&&(b.a--,0==b.a&&g.CriticalImages.checkCriticalImages())});a.removeAttribute("pagespeed_lazy_src");a.removeAttribute("pagespeed_lazy_replaced_functions");
d&&d.insertBefore(a,e);a.src=c}else b.d.push(a)},0)};k.prototype.loadIfVisibleAndMaybeBeacon=k.prototype.j;k.prototype.k=function(){this.c=!0;q(this)};k.prototype.loadAllImages=k.prototype.k;var q=function(a){var b=a.d,c=b.length;a.d=[];for(var d=0;d<c;++d)a.j(b[d])},s=function(a,b){return a.a?null!=a.a(b):null!=a.getAttribute(b)};k.prototype.l=function(){for(var a=document.getElementsByTagName("img"),b=0,c;c=a[b];b++)s(c,"pagespeed_lazy_src")&&p(c)};k.prototype.overrideAttributeFunctions=k.prototype.l;
var p=function(a){s(a,"pagespeed_lazy_replaced_functions")||(a.g=a.getAttribute,a.getAttribute=function(a){"src"==a.toLowerCase()&&s(this,"pagespeed_lazy_src")&&(a="pagespeed_lazy_src");return this.g(a)},a.setAttribute("pagespeed_lazy_replaced_functions","1"))};
g.m=function(a,b){var c=new k(b);g.lazyLoadImages=c;f(window,"load",function(){c.b=!0;c.c=a;c.e=200;if(g.CriticalImages){for(var b=0,d=document.getElementsByTagName("img"),r=0,n;n=d[r];r++)-1!=n.src.indexOf(c.h)&&s(n,"pagespeed_lazy_src")&&b++;c.a=b;0==c.a&&g.CriticalImages.checkCriticalImages()}q(c)});0!=b.indexOf("data")&&((new Image).src=b);var d=function(){if(!(c.b&&a||c.f)){var b=200;200<(new Date).getTime()-c.i&&(b=0);c.f=window.setTimeout(function(){c.i=(new Date).getTime();q(c);c.f=null},
b)}};f(window,"scroll",d);f(window,"resize",d)};g.lazyLoadInit=g.m;})();
