(function(){var f=window,g=document,h="replace",l="insertBefore",n="firstChild",p="deferJs",r="childNodes",t="documentElement",u="time",x="size",y="style",z="pagespeed",D="push",E="length",F="prototype",G="parentNode";function H(a){if(!a)throw"CHECK failed";}function I(a,b,c){H(a[G]==b[G]);for(var d=[];a!=b.nextSibling;a=a.nextSibling)8==a.nodeType&&(new RegExp("GooglePanel end "+c+"$")).test(a.data)?d[D](a):a.tagName&&a[n]&&(d=d.concat(I(a[n],a.lastChild,c)));return d}
function J(a,b,c){for(var d in c)if(c.hasOwnProperty(d)&&"xpath"!=d&&"dont_bind"!=d&&"instance_html"!=d&&"images"!=d&&"contiguous"!=d){var q=c[d],P=I(a,b,d);H(!q[E]||!q[0].contiguous);for(var A=0,N=0;A<q[E];A++){0<A&&!q[A].contiguous&&N++;var m=P[N],s=q[A],e=d;if(s&&!s.dont_bind){if(!m){H(s.xpath);i:{for(var m=e,e=s.xpath.split("/"),k=/(?:.*\[@id=")(.*)(?:"\])/,v=/(?:.*\[)(\d+)(?:\])/,w=g.body,B=2;B<e[E];++B){var C=k.exec(e[B]);if(C)w=g.getElementById(C[1]),H(w);else if(C=v.exec(e[B])){if(B==e[E]-
1){e=w;k=Number(C[1]);H(e&&0<k);k=e.children[k-1]||null;e[l](g.createComment("GooglePanel begin "+m),k);m=g.createComment("GooglePanel end "+m);e[l](m,k);break i}w=w.children[C[1]-1];H(w)}else H(0)}m=void 0}H(m)}if(s.instance_html){k=m[G].tagName;v=s.instance_html;"HEAD"==k&&(k="div");e=void 0;"Microsoft Internet Explorer"!=navigator.appName||"TABLE"!=k&&"TBODY"!=k?(e=g.createElement(k),e.innerHTML=v):(e=g.createElement("div"),e.innerHTML="<table>"+v+"</table>",e=e.getElementsByTagName("tbody")[0]);
for(k=g.createDocumentFragment();0<e[r][E];)e[r][0].tagName&&(e.setAttribute("psa_not_processed",""),e.setAttribute("priority_psa_not_processed","")),k.appendChild(e[r][0]);e=k;k=e[n];v=e.lastChild;m[G][l](e,m);J(k,v,s)}else J(m[G],m[G],s)}}}}
var K=function(a){var b=g[t];J(b[n],b.lastChild,a);b=g[t].getElementsByTagName("img");a=[];for(var c=0;c<b[E];c++){var d=b[c];d.hasAttribute("pagespeed_high_res_src")&&a[D](d)}b={};if(a)for(c=0;c<a[E];c++){var d=a[c],q=d.getAttribute("pagespeed_high_res_src");q&&(void 0==b[q]&&(b[q]=[]),b[q][D](d))}};f.pagespeed=f[z]||{};var L=f[z],O=function(){this.h=!1;this.c=null;this.f={};this.g=!1;this.a={};this.i=0;this.b={time:{},size:{}};this.d=0;this.j=!1;f.performance?this.k=f.performance.timing.navigationStart:this.k=f.mod_pagespeed_start;M(this,"cdl",0)};
O[F].e=function(){if(this.g&&this.h&&"ncl"!=this.state){K(this.f);for(var a in this.a)if(this.a.hasOwnProperty(a))for(var b=this.a[a],c=0;c<b[E];++c)b[c].dont_bind=!1;K(this.a);M(this,"ncl");(a=f.location.hash)&&"#"==a[0]&&g.getElementById(a.slice(1))&&f.location[h](a);f[z]&&f[z][p]&&(f[z][p].registerScriptTags(),setTimeout(function(){f[z][p].run()},1))}};O[F].loadData=O[F].e;
O[F].n=function(){var a="",b;for(b in this.b[u])a+=b+"."+this.b[u][b]+",";for(b in this.b[x])a+=b+"_sz."+this.b[x][b]+",";return a};O[F].getCsiTimingsString=O[F].n;
var M=function(a,b,c){a.state=b;var d=new Date-a.k;a.b[u][b]=d;c&&(a.b[x][b]=c);"cdl"==b&&(a.d+=c?c/1024:0,a.i=d);b=new Date;c=g.getElementById("dashboard_area")||f.dashboard_area;if(a.j||f.localStorage&&"1"==f.localStorage.psa_debug)c||(c=g.createElement("div"),c.id="dashboard_area",c[y].color="gray",c[y].fontSize="10px",c[y].a="Arial",c[y].backgroundColor="white",g.body[l](c,g.body[r][0])),d="TIME:\n"+JSON.stringify(a.b[u])[h](/["{}]/g,"")[h](/,/g," "),d+="\nSIZE:\n"+JSON.stringify(a.b[x])[h](/["{}]/g,
"")[h](/,/g," "),c.innerHTML='<span title="'+d+'">'+a.i+"ms; "+a.d.toFixed()+"KB;"+b.toGMTString()+"</span>"},Q=function(a){f[z]&&f[z][p]&&(f[z][p].registerScriptTags(function(){a.l()},L.lastScriptIndexBeforePanelStub),f[z][p].run())};O[F].r=function(){this.j=!0};O[F].setRequestFromInternalIp=O[F].r;O[F].o=function(a){for(var b=0;b<a[E];b++)g.cookie=a[b]};O[F].loadCookies=O[F].o;
O[F].p=function(a){if("ncl"!=this.state)for(var b in a)a.hasOwnProperty(b)&&(this.a[b]=this.a[b]||[],this.a[b][D](a[b]),0<I(g[t],g[t],b)[E]?(K(this.a),this.a[b].pop(),this.a[b][D]({})):a[b].dont_bind=!0)};O[F].loadNonCacheableObject=O[F].p;O[F].l=function(){this.h=!0;this.e()};O[F].criticalScriptsDone=O[F].l;O[F].m=function(a,b){b?this.c=a:(this.c&&(a=this.c),"ncl"!=this.state&&(this.f=a,this.g=!0,this.e()))};O[F].bufferNonCriticalData=O[F].m;
L.q=function(){if(!L.panelLoader){var a=new O;L.panelLoader=a;Q(a)}};L.panelLoaderInit=L.q;})();
