(function(){var e=window,f=document,k="replace",l="insertBefore",p="firstChild",q="deferJs",r="documentElement",t="time",w="size",x="hasOwnProperty",A="style",D="state",E="pagespeed",F="push",G="length",H="prototype",I="parentNode",J="",K="\nSIZE:\n",L=" ",M='">',aa="$",N=",",ba=".",ca="/",da="1",ea="10px",fa="</span>",ga="</table>",ha='<span title="',ia="<table>",ja="Arial",ka="GooglePanel begin ",O="GooglePanel end ",la="HEAD",ma="KB;",na="Microsoft Internet Explorer",oa="TABLE",pa="TBODY",qa="TIME:\n",ra=
"_sz.",P="cdl",sa="contiguous",Q="dashboard_area",R="div",ta="dont_bind",ua="gray",va="images",wa="img",xa="instance_html",ya="ms; ",T="ncl",U="pagespeed_high_res_src",za="src",Aa="tbody",Ba="white",Ca="xpath";function V(b){if(!b)throw"CHECK failed";}function W(b,a,d){V(b[I]==a[I]);for(var c=[];b!=a.nextSibling;b=b.nextSibling)8==b.nodeType&&RegExp(O+d+aa).test(b.data)?c[F](b):b.tagName&&b[p]&&(c=c.concat(W(b[p],b.lastChild,d)));return c}
function X(b,a,d){for(var c in d)if(d[x](c)&&c!=Ca&&c!=ta&&c!=xa&&c!=va&&c!=sa){var m=d[c],S=W(b,a,c);V(!m[G]||!m[0].contiguous);for(var s=0,v=0;s<m[G];s++){0<s&&!m[s].contiguous&&v++;var n=S[v],u=m[s],g=c;if(u&&!u.dont_bind){if(!n){V(u.xpath);i:{for(var n=g,g=u.xpath.split(ca),h=/(?:.*\[@id=")(.*)(?:"\])/,y=/(?:.*\[)(\d+)(?:\])/,z=f.body,B=2;B<g[G];++B){var C=h.exec(g[B]);if(C)z=f.getElementById(C[1]),V(z);else if(C=y.exec(g[B])){if(B==g[G]-1){g=z;h=Number(C[1]);V(g&&0<h);h=g.children[h-1]||null;
g[l](f.createComment(ka+n),h);n=f.createComment(O+n);g[l](n,h);break i}z=z.children[C[1]-1];V(z)}else V(0)}n=void 0}V(n)}if(u.instance_html){h=n[I].tagName;y=u.instance_html;h==la&&(h=R);g=void 0;navigator.appName!=na||h!=oa&&h!=pa?(g=f.createElement(h),g.innerHTML=y):(g=f.createElement(R),g.innerHTML=ia+y+ga,g=g.getElementsByTagName(Aa)[0]);for(h=f.createDocumentFragment();0<g.childNodes[G];)h.appendChild(g.childNodes[0]);g=h;h=g[p];y=g.lastChild;n[I][l](g,n);X(h,y,u)}else X(n[I],n[I],u)}}}}
function Y(){}Y[H].a=function(b){var a=f[r];X(a[p],a.lastChild,b);a=f[r].getElementsByTagName(wa);b=[];for(var d=0;d<a[G];d++){var c=a[d];c.hasAttribute(U)&&b[F](c)}a={};if(b)for(d=0;d<b[G];d++){var c=b[d],m=c.getAttribute(U);m&&(void 0==a[m]&&(a[m]=[]),a[m][F](c))}return a};e.pagespeed=e[E]||{};var Z=e[E],$=function(){this.c=!1;this.f=null;this.j={};this.k=!1;this.a={};this.e=new Y;this.i=0;this.b={time:{},size:{}};this.d=0;this.m=!1;this.l(P,0)};$[H].o=function(b,a,d){for(var c in a)if(a[x](c))for(var m=a[c],S=b[c]||c,s=0;s<m[G];s++){var v=m[s];v.getAttribute(za)!=c&&(v.onload=v.onerror=d,v.src=S)}};
$[H].g=function(){if(this.k&&this.c&&this[D]!=T){var b=this.e.a(this.j),a;for(a in this.a)if(this.a[x](a))for(var d=this.a[a],c=0;c<d[G];++c)d[c].dont_bind=!1;this.e.a(this.a);this.l(T);this.o(J,b,function(){});e[E]&&e[E][q]&&(e[E][q].registerScriptTags(),setTimeout(function(){e[E][q].run()},1))}};$[H].loadData=$[H].g;$[H].q=function(b){return b==P};$[H].v=function(){var b=J,a;for(a in this.b[t])b+=a+ba+this.b[t][a]+N;for(a in this.b[w])b+=a+ra+this.b[w][a]+N;return b};$[H].getCsiTimingsString=$[H].v;
$[H].r=function(){var b=new Date,a=f.getElementById(Q)||e.dashboard_area;if(this.m||e.localStorage&&e.localStorage.psa_debug==da){a||(a=f.createElement(R),a.id=Q,a[A].color=ua,a[A].fontSize=ea,a[A].a=ja,a[A].backgroundColor=Ba,f.body[l](a,f.body.childNodes[0]));var d=qa+JSON.stringify(this.b[t])[k](/["{}]/g,J)[k](/,/g,L),d=d+(K+JSON.stringify(this.b[w])[k](/["{}]/g,J)[k](/,/g,L));a.innerHTML=ha+d+M+this.i+ya+this.d.toFixed()+ma+b.toGMTString()+fa}};
$[H].l=function(b,a){this.state=b;var d=new Date-this.C;this.p(b,d,a);this.q(b)&&(this.d+=a?a/1024:0,this.i=d);this.r()};$[H].s=function(){if(e[E]&&e[E][q]){var b=this;e[E][q].registerScriptTags(function(){b.n()},Z.lastScriptIndexBeforePanelStub);e[E][q].run()}};$[H].B=function(){this.m=!0};$[H].setRequestFromInternalIp=$[H].B;$[H].p=function(b,a,d){this.b[t][b]=a;d&&(this.b[w][b]=d)};$[H].w=function(b){for(var a=0;a<b[G];a++)f.cookie=b[a]};$[H].loadCookies=$[H].w;
$[H].A=function(b){if(this[D]!=T)for(var a in b)b[x](a)&&(this.a[a]=this.a[a]||[],this.a[a][F](b[a]),0<W(f[r],f[r],a)[G]?(this.e.a(this.a),this.a[a].pop(),this.a[a][F]({})):b[a].dont_bind=!0)};$[H].loadNonCacheableObject=$[H].A;$[H].n=function(){this.c=!0;this.g()};$[H].criticalScriptsDone=$[H].n;$[H].t=function(b,a){a?this.f=b:(this.f&&(b=this.f),this[D]!=T&&(this[D]==P&&(this.c=!0),this.j=b,this.k=!0,Z.num_high_res_images_loaded==Z.num_low_res_images_inlined&&this.g()))};
$[H].bufferNonCriticalData=$[H].t;Z.u=function(){Z.h||(Z.h=new $,Z.panelLoader=Z.h,Z.h.s())};Z.panelLoaderInit=Z.u;})();
