(function(){var f=this;
function h(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function l(a,b,c){return a.call.apply(a.bind,arguments)}function p(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}
function q(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?l:p;return q.apply(null,arguments)};var r=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function t(a,b){return a<b?-1:a>b?1:0}function v(a){var b=Number(a);return 0==b&&/^[\s\xa0]*$/.test(a)?NaN:b};var w;a:{var x=f.navigator;if(x){var y=x.userAgent;if(y){w=y;break a}}w=""};var z=-1!=w.indexOf("Opera")||-1!=w.indexOf("OPR"),A=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),B=-1!=w.indexOf("Gecko")&&-1==w.toLowerCase().indexOf("webkit")&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE")),C=-1!=w.toLowerCase().indexOf("webkit"),D=C&&-1!=w.indexOf("Mobile");function E(){var a=f.document;return a?a.documentMode:void 0}
var F=function(){var a="",b;if(z&&f.opera)return a=f.opera.version,"function"==h(a)?a():a;B?b=/rv\:([^\);]+)(\)|;)/:A?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:C&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(w))?a[1]:"");return A&&(b=E(),b>parseFloat(a))?String(b):a}(),G={};
function H(a){if(!G[a]){for(var b=0,c=r(String(F)).split("."),d=r(String(a)).split("."),k=Math.max(c.length,d.length),g=0;0==b&&g<k;g++){var e=c[g]||"",u=d[g]||"",O=RegExp("(\\d*)(\\D*)","g"),P=RegExp("(\\d*)(\\D*)","g");do{var m=O.exec(e)||["","",""],n=P.exec(u)||["","",""];if(0==m[0].length&&0==n[0].length)break;b=t(0==m[1].length?0:parseInt(m[1],10),0==n[1].length?0:parseInt(n[1],10))||t(0==m[2].length,0==n[2].length)||t(m[2],n[2])}while(0==b)}G[a]=0<=b}}
var I=f.document,J=I&&A?E()||("CSS1Compat"==I.compatMode?parseInt(F,10):5):void 0;var K;if(!(K=!B&&!A)){var L;if(L=A)L=A&&9<=J;K=L}K||B&&H("1.9.1");A&&H("9");function M(a){return window.matchMedia("(-webkit-min-device-pixel-ratio: "+a+"),(min--moz-device-pixel-ratio: "+a+"),(min-resolution: "+a+"dppx)").matches?a:0};function N(a,b){this.c=a;this.url=b}function Q(a){this.f=a;this.e=0;this.a=[]}function R(){this.d=[]}function S(a,b){var c=new Image;c.onload=function(){a.src=b};c.src=b}Q.prototype.b=function(a){if(a>this.e)for(var b=this.a.length,c=0;c<b;++c)if(a<=this.a[c].c){this.e=this.a[c].c;S(this.f,this.a[c].url);break}};
R.prototype.b=function(){var a;a=document.documentElement.clientWidth/window.innerWidth;var b=window,c=B&&D;a*=void 0===b.devicePixelRatio||c?b.matchMedia?M(.75)||M(1.5)||M(2)||M(3)||1:1:b.devicePixelRatio;b=this.d.length;for(c=0;c<b;++c)this.d[c].b(a)};
function T(a,b){for(var c=new Q(a),d=b.split(","),k=d.length,g=0;g<k;++g){var e=d[g].trim().split(/\s+/);if(2!=e.length)return null;var u=e[0],e=e[1];if(1<e.length&&"x"==e[e.length-1]){e=v(e.substr(0,e.length-1));if(isNaN(e))return null;c.a.push(new N(e,u))}else return null}c.a.sort(function(a,b){return a.c-b.c});return c}
(function(){for(var a=new R,b=document.getElementsByTagName("IMG"),c=0,d;d=b[c];++c){var k=d.getAttribute("srcset");k&&(d=T(d,k),null!=d&&a.d.push(d))}window.addEventListener("resize",q(a.b,a));window.addEventListener("touchmove",q(function(a){1<a.touches.length&&this.b()},a));a.b()})();})();
