(function(){var l,p=this;function q(a){return void 0!==a}function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"string"==typeof a}function u(a){return"function"==ba(a)}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return v.apply(null,arguments)}var ga=Date.now||function(){return+new Date};
function ha(a,b){var c=a.split("."),d=p;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&q(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}function w(a,b){function c(){}c.prototype=b.prototype;a.Ha=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.La=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(x,Error);x.prototype.name="CustomError";function ia(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function ja(){}
function ka(a,b,c){switch(typeof b){case "string":la(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==ba(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),ka(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),la(e,c),c.push(":"),ka(a,f,c),d=
","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ma={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},na=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function la(a,b){b.push('"',a.replace(na,function(a){if(a in ma)return ma[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ma[a]=e+b.toString(16)}),'"')};function oa(a,b){this.width=a;this.height=b}l=oa.prototype;l.clone=function(){return new oa(this.width,this.height)};l.toString=function(){return"("+this.width+" x "+this.height+")"};l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function pa(a){this.a=a}var qa=/\s*;\s*/;function ra(a,b,c,d,e,f){if(/[;=\s]/.test(b))throw Error('Invalid cookie name "'+b+'"');if(/[;\r\n]/.test(c))throw Error('Invalid cookie value "'+c+'"');q(d)||(d=-1);f=f?";domain="+f:"";e=e?";path="+e:"";d=0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(ga()+1E3*d)).toUTCString();a.a.cookie=b+"="+c+f+e+d+""}
function sa(a,b){for(var c=b+"=",d=(a.a.cookie||"").split(qa),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==b)return""}}pa.prototype.remove=function(a,b,c){var d=q(sa(this,a));ra(this,a,"",0,b,c);return d};pa.prototype.O=function(){return ta(this).keys};pa.prototype.u=function(){return ta(this).values};pa.prototype.clear=function(){for(var a=ta(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
function ta(a){a=(a.a.cookie||"").split(qa);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};function ua(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function va(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function wa(a){var b=arguments.length;if(1==b&&"array"==ba(arguments[0]))return wa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};wa("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));function xa(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function ya(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function y(a,b){return 0==a.lastIndexOf(b,0)}function za(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function Ba(a,b){return a<b?-1:a>b?1:0};var z=Array.prototype,Ca=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Da=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ea=z.filter?function(a,b,c){return z.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},Fa=z.some?function(a,b,c){return z.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function Ga(a){return z.concat.apply(z,arguments)};function Ha(){this.b=this.a=null}var A=new function(a,b){this.f=100;this.c=a;this.g=b;this.b=0;this.a=null}(function(){return new Ia},function(a){a.reset()});Ha.prototype.add=function(a,b){var c;0<A.b?(A.b--,c=A.a,A.a=c.next,c.next=null):c=A.c();c.a=a;c.b=b;c.next=null;this.b?this.b.next=c:this.a=c;this.b=c};Ha.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};function Ia(){this.next=this.b=this.a=null}
Ia.prototype.reset=function(){this.next=this.b=this.a=null};function Ja(a){if(a.classList)return a.classList;a=a.className;return t(a)&&a.match(/\S+/g)||[]}function Ka(a,b){var c;a.classList?c=a.classList.contains(b):(c=Ja(a),c=0<=Ca(c,b));return c}function B(a,b){a.classList?a.classList.add(b):Ka(a,b)||(a.className+=0<a.className.length?" "+b:b)}function La(a,b){a.classList?a.classList.remove(b):Ka(a,b)&&(a.className=Ea(Ja(a),function(a){return a!=b}).join(" "))}function Ma(a,b){Ka(a,b)?La(a,b):B(a,b)}function Na(a){La(a,"open");B(a,"psmob-open")};var C;a:{var Oa=p.navigator;if(Oa){var Qa=Oa.userAgent;if(Qa){C=Qa;break a}}C=""}function D(a){return-1!=C.indexOf(a)};function Ra(){return D("Opera")||D("OPR")}function Sa(){return D("Android")&&!((D("Chrome")||D("CriOS"))&&!Ra()||D("Firefox")||Ra()||D("Silk"))};function Ta(a){p.setTimeout(function(){throw a;},0)}var Ua;
function Va(){var a=p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!D("Presto")&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=v(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!D("Trident")&&!D("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(q(c.next)){c=c.next;var a=c.fa;c.fa=null;a()}};return function(a){d.next={fa:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){p.setTimeout(a,0)}};function E(a){var b=a[0],c=a[1];a=a[2];b=Number(b);c=Number(c);a=Number(a);if(isNaN(b)||0>b||255<b||isNaN(c)||0>c||255<c||isNaN(a)||0>a||255<a)throw Error('"('+b+","+c+","+a+'") is not a valid RGB color');b=Wa(b.toString(16));c=Wa(c.toString(16));a=Wa(a.toString(16));return"#"+b+c+a}function Wa(a){return 1==a.length?"0"+a:a}
function Xa(a,b,c){var d=0,e=0,f=0;if(0==b)f=e=d=c;else{var g=Math.floor(a/60),h=a/60-g;a=c*(1-b);var k=c*(1-b*h);b=c*(1-b*(1-h));switch(g){case 1:d=k;e=c;f=a;break;case 2:d=a;e=c;f=b;break;case 3:d=a;e=k;f=c;break;case 4:d=b;e=a;f=c;break;case 5:d=c;e=a;f=k;break;case 6:case 0:d=c,e=b,f=a}}return[Math.floor(d),Math.floor(e),Math.floor(f)]}
function Ya(a,b,c){var d=Math.max(Math.max(a,b),c),e=Math.min(Math.min(a,b),c);if(e==d)e=a=0;else{var f=d-e,e=f/d;a=60*(a==d?(b-c)/f:b==d?2+(c-a)/f:4+(a-b)/f);0>a&&(a+=360);360<a&&(a-=360)}return[a,e,d]};function Za(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}l=Za.prototype;l.clone=function(){return new Za(this.top,this.right,this.bottom,this.left)};l.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};l.contains=function(a){return this&&a?a instanceof Za?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
l.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};l.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};l.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function $a(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)ab(this,arguments[d],arguments[d+1])}else if(a){if(a instanceof $a)d=a.O(),c=a.u();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=va(a)}for(e=0;e<d.length;e++)ab(this,d[e],c[e])}}l=$a.prototype;l.u=function(){bb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};l.O=function(){bb(this);return this.a.concat()};
l.clear=function(){this.b={};this.f=this.c=this.a.length=0};l.remove=function(a){return F(this.b,a)?(delete this.b[a],this.c--,this.f++,this.a.length>2*this.c&&bb(this),!0):!1};function bb(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];F(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],F(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}function cb(a,b){return F(a.b,b)?a.b[b]:void 0}
function ab(a,b,c){F(a.b,b)||(a.c++,a.a.push(b),a.f++);a.b[b]=c}l.forEach=function(a,b){for(var c=this.O(),d=0;d<c.length;d++){var e=c[d];a.call(b,cb(this,e),e,this)}};l.clone=function(){return new $a(this)};function F(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function db(a){if("function"==typeof a.u)return a.u();if(t(a))return a.split("");var b=ba(a);if("array"==b||"object"==b&&"number"==typeof a.length){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return va(a)};function eb(a){this.a=new $a;if(a){a=db(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}}function fb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ca]||(a[ca]=++da)):b.substr(0,1)+a}l=eb.prototype;l.add=function(a){ab(this.a,fb(a),a)};l.remove=function(a){return this.a.remove(fb(a))};l.clear=function(){this.a.clear()};l.contains=function(a){a=fb(a);return F(this.a.b,a)};l.u=function(){return this.a.u()};l.clone=function(){return new eb(this)};function gb(a,b){hb||ib();jb||(hb(),jb=!0);kb.add(a,b)}var hb;function ib(){if(p.Promise&&p.Promise.resolve){var a=p.Promise.resolve();hb=function(){a.then(lb)}}else hb=function(){var a=lb;!u(p.setImmediate)||p.Window&&p.Window.prototype&&p.Window.prototype.setImmediate==p.setImmediate?(Ua||(Ua=Va()),Ua(a)):p.setImmediate(a)}}var jb=!1,kb=new Ha;function lb(){for(var a=null;a=kb.remove();){try{a.a.call(a.b)}catch(b){Ta(b)}var c=A;c.g(a);c.b<c.f&&(c.b++,a.next=c.a,c.a=a)}jb=!1};function G(a,b){this.b=H;this.i=void 0;this.a=this.c=null;this.f=this.g=!1;if(a==mb)I(this,nb,b);else try{var c=this;a.call(b,function(a){I(c,nb,a)},function(a){if(!(a instanceof J))try{if(a instanceof Error)throw a;throw Error("Promise rejected.");}catch(b){}I(c,K,a)})}catch(d){I(this,K,d)}}var H=0,nb=2,K=3;function mb(){}G.prototype.then=function(a,b,c){return ob(this,u(a)?a:null,u(b)?b:null,c)};xa(G);G.prototype.cancel=function(a){this.b==H&&gb(function(){var b=new J(a);pb(this,b)},this)};
function pb(a,b){if(a.b==H)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.L)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.b==H&&1==d?pb(c,b):(d=c.a.splice(e,1)[0],qb(c,d,K,b)))}a.c=null}else I(a,K,b)}function rb(a,b){a.a&&a.a.length||a.b!=nb&&a.b!=K||sb(a);a.a||(a.a=[]);a.a.push(b)}
function ob(a,b,c,d){var e={L:null,ma:null,na:null};e.L=new G(function(a,g){e.ma=b?function(c){try{var e=b.call(d,c);a(e)}catch(m){g(m)}}:a;e.na=c?function(b){try{var e=c.call(d,b);!q(e)&&b instanceof J?g(b):a(e)}catch(m){g(m)}}:g});e.L.c=a;rb(a,e);return e.L}G.prototype.l=function(a){this.b=H;I(this,nb,a)};G.prototype.o=function(a){this.b=H;I(this,K,a)};
function I(a,b,c){if(a.b==H){if(a==c)b=K,c=new TypeError("Promise cannot resolve to itself");else{if(ya(c)){a.b=1;c.then(a.l,a.o,a);return}var d=typeof c;if("object"==d&&null!=c||"function"==d)try{var e=c.then;if(u(e)){tb(a,c,e);return}}catch(f){b=K,c=f}}a.i=c;a.b=b;a.c=null;sb(a);b!=K||c instanceof J||ub(a,c)}}function tb(a,b,c){function d(b){f||(f=!0,a.o(b))}function e(b){f||(f=!0,a.l(b))}a.b=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function sb(a){a.g||(a.g=!0,gb(a.s,a))}
G.prototype.s=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=null;for(var b=0;b<a.length;b++)qb(this,a[b],this.b,this.i)}this.g=!1};function qb(a,b,c,d){b.L&&(b.L.c=null);if(c==nb)b.ma(d);else{if(b.L)for(;a&&a.f;a=a.c)a.f=!1;b.na(d)}}function ub(a,b){a.f=!0;gb(function(){a.f&&vb.call(null,b)})}var vb=Ta;function J(a){x.call(this,a)}w(J,x);J.prototype.name="cancel";var wb=Ra(),L=D("Trident")||D("MSIE"),xb=D("Gecko")&&-1==C.toLowerCase().indexOf("webkit")&&!(D("Trident")||D("MSIE")),yb=-1!=C.toLowerCase().indexOf("webkit"),zb=yb&&D("Mobile");function Ab(){var a=p.document;return a?a.documentMode:void 0}var Bb=function(){var a="",b;if(wb&&p.opera)return a=p.opera.version,u(a)?a():a;xb?b=/rv\:([^\);]+)(\)|;)/:L?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:yb&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(C))?a[1]:"");return L&&(b=Ab(),b>parseFloat(a))?String(b):a}(),Cb={};
function Db(a){var b;if(!(b=Cb[a])){b=0;for(var c=Aa(String(Bb)).split("."),d=Aa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var n=k.exec(g)||["","",""],r=m.exec(h)||["","",""];if(0==n[0].length&&0==r[0].length)break;b=Ba(0==n[1].length?0:parseInt(n[1],10),0==r[1].length?0:parseInt(r[1],10))||Ba(0==n[2].length,0==r[2].length)||Ba(n[2],r[2])}while(0==b)}b=Cb[a]=0<=b}return b}
var Eb=p.document,Fb=Eb&&L?Ab()||("CSS1Compat"==Eb.compatMode?parseInt(Bb,10):5):void 0;var Gb;if(!(Gb=!xb&&!L)){var Hb;if(Hb=L)Hb=L&&9<=Fb;Gb=Hb}var Ib=Gb||xb&&Db("1.9.1");L&&Db("9");function Jb(a){var b=document;return t(a)?b.getElementById(a):a}function Kb(a,b){ua(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Lb?a.setAttribute(Lb[d],b):y(d,"aria-")||y(d,"data-")?a.setAttribute(d,b):a[d]=b})}var Lb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Mb(a){return Ib&&void 0!=a.children?a.children:Ea(a.childNodes,function(a){return 1==a.nodeType})}function Nb(a){return window.matchMedia("(-webkit-min-device-pixel-ratio: "+a+"),(min--moz-device-pixel-ratio: "+a+"),(min-resolution: "+a+"dppx)").matches?a:0};function Ob(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}L&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}function Pb(a){"number"==typeof a&&(a=Math.round(a)+"px");return a}
function Qb(a){if(!a.getBoundingClientRect)return null;var b;b:{b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue("display")||"";break b}b=""}if("none"!=(b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display))a=Ob(a);else{b=a.style;var c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Ob(a);b.display=c;
b.position=e;b.visibility=d}return new oa(a.right-a.left,a.bottom-a.top)};var Rb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function Sb(a){if(Tb){Tb=!1;var b=p.location;if(b){var c=b.href;if(c&&(c=Ub(Sb(c)[3]||null))&&c!=b.hostname)throw Tb=!0,Error();}}return a.match(Rb)}var Tb=yb;function Ub(a){return a?decodeURI(a):a}
function Vb(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g," ")):"")}};function Wb(a,b){var c;a instanceof Wb?(this.M=q(b)?b:a.M,Xb(this,a.R),this.aa=a.aa,this.C=a.C,Yb(this,a.Z),this.Y=a.Y,Zb(this,a.a.clone()),this.X=a.X):a&&(c=Sb(String(a)))?(this.M=!!b,Xb(this,c[1]||"",!0),this.aa=$b(c[2]||""),this.C=$b(c[3]||"",!0),Yb(this,c[4]),this.Y=$b(c[5]||"",!0),Zb(this,c[6]||"",!0),this.X=$b(c[7]||"")):(this.M=!!b,this.a=new ac(null,0,this.M))}l=Wb.prototype;l.R="";l.aa="";l.C="";l.Z=null;l.Y="";l.X="";l.M=!1;
l.toString=function(){var a=[],b=this.R;b&&a.push(bc(b,cc,!0),":");if(b=this.C){a.push("//");var c=this.aa;c&&a.push(bc(c,cc,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.Z;null!=b&&a.push(":",String(b))}if(b=this.Y)this.C&&"/"!=b.charAt(0)&&a.push("/"),a.push(bc(b,"/"==b.charAt(0)?dc:ec,!0));(b=this.a.toString())&&a.push("?",b);(b=this.X)&&a.push("#",bc(b,fc));return a.join("")};l.clone=function(){return new Wb(this)};
function Xb(a,b,c){a.R=c?$b(b,!0):b;a.R&&(a.R=a.R.replace(/:$/,""))}function gc(a){return a.C}function Yb(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.Z=b}else a.Z=null}function Zb(a,b,c){b instanceof ac?(a.a=b,hc(a.a,a.M)):(c||(b=bc(b,ic)),a.a=new ac(b,0,a.M))}function jc(a,b,c){"array"==ba(c)||(c=[String(c)]);kc(a.a,b,c)}function $b(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}
function bc(a,b,c){return t(a)?(a=encodeURI(a).replace(b,lc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function lc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var cc=/[#\/\?@]/g,ec=/[\#\?:]/g,dc=/[\#\?]/g,ic=/[\#\?@]/g,fc=/#/g;function ac(a,b,c){this.a=a||null;this.b=!!c}function mc(a){a.m||(a.m=new $a,a.D=0,a.a&&Vb(a.a,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}l=ac.prototype;l.m=null;l.D=null;
l.add=function(a,b){mc(this);this.a=null;a=nc(this,a);var c=cb(this.m,a);c||ab(this.m,a,c=[]);c.push(b);this.D++;return this};l.remove=function(a){mc(this);a=nc(this,a);return F(this.m.b,a)?(this.a=null,this.D-=cb(this.m,a).length,this.m.remove(a)):!1};l.clear=function(){this.m=this.a=null;this.D=0};l.O=function(){mc(this);for(var a=this.m.u(),b=this.m.O(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
l.u=function(a){mc(this);var b=[];if(t(a)){var c=a;mc(this);c=nc(this,c);F(this.m.b,c)&&(b=Ga(b,cb(this.m,nc(this,a))))}else for(a=this.m.u(),c=0;c<a.length;c++)b=Ga(b,a[c]);return b};function kc(a,b,c){a.remove(b);if(0<c.length){a.a=null;var d=a.m;b=nc(a,b);var e;e=c.length;if(0<e){for(var f=Array(e),g=0;g<e;g++)f[g]=c[g];e=f}else e=[];ab(d,b,e);a.D+=c.length}}
l.toString=function(){if(this.a)return this.a;if(!this.m)return"";for(var a=[],b=this.m.O(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.u(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.a=a.join("&")};l.clone=function(){var a=new ac;a.a=this.a;this.m&&(a.m=this.m.clone(),a.D=this.D);return a};function nc(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c}
function hc(a,b){b&&!a.b&&(mc(a),a.a=null,a.m.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),kc(this,e,a))},a));a.b=b};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function M(a,b){this.g=[];this.K=a;this.I=b||null;this.f=this.a=!1;this.c=void 0;this.s=this.N=this.l=!1;this.i=0;this.b=null;this.o=0}M.prototype.cancel=function(a){if(this.a)this.c instanceof M&&this.c.cancel();else{if(this.b){var b=this.b;delete this.b;a?b.cancel(a):(b.o--,0>=b.o&&b.cancel())}this.K?this.K.call(this.I,this):this.s=!0;this.a||(a=new oc,pc(this),qc(this,!1,a))}};M.prototype.H=function(a,b){this.l=!1;qc(this,a,b)};function qc(a,b,c){a.a=!0;a.c=c;a.f=!b;rc(a)}
function pc(a){if(a.a){if(!a.s)throw new sc;a.s=!1}}function tc(a,b,c,d){a.g.push([b,c,d]);a.a&&rc(a)}M.prototype.then=function(a,b,c){var d,e,f=new G(function(a,b){d=a;e=b});tc(this,d,function(a){a instanceof oc?f.cancel():e(a)});return f.then(a,b,c)};xa(M);function uc(a){return Fa(a.g,function(a){return u(a[1])})}
function rc(a){if(a.i&&a.a&&uc(a)){var b=a.i,c=vc[b];c&&(p.clearTimeout(c.F),delete vc[b]);a.i=0}a.b&&(a.b.o--,delete a.b);for(var b=a.c,d=c=!1;a.g.length&&!a.l;){var e=a.g.shift(),f=e[0],g=e[1],e=e[2];if(f=a.f?g:f)try{var h=f.call(e||a.I,b);q(h)&&(a.f=a.f&&(h==b||h instanceof Error),a.c=b=h);ya(b)&&(d=!0,a.l=!0)}catch(k){b=k,a.f=!0,uc(a)||(c=!0)}}a.c=b;d&&(h=v(a.H,a,!0),d=v(a.H,a,!1),b instanceof M?(tc(b,h,d),b.N=!0):b.then(h,d));c&&(b=new wc(b),vc[b.F]=b,a.i=b.F)}function sc(){x.call(this)}
w(sc,x);sc.prototype.message="Deferred has already fired";sc.prototype.name="AlreadyCalledError";function oc(){x.call(this)}w(oc,x);oc.prototype.message="Deferred was canceled";oc.prototype.name="CanceledError";function wc(a){this.F=p.setTimeout(v(this.b,this),0);this.a=a}wc.prototype.b=function(){delete vc[this.F];throw this.a;};var vc={};function xc(a,b){var c=b||{},d=c.document||document,e=document.createElement("SCRIPT"),f={qa:e,$:void 0},g=new M(yc,f),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){zc(e,!0);var b=new Ac(Bc,"Timeout reached for loading script "+a);pc(g);qc(g,!1,b)},k),f.$=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(zc(e,c.Ca||!1,h),pc(g),qc(g,!0,null))};e.onerror=function(){zc(e,!0,h);var b=new Ac(Cc,"Error while loading script "+
a);pc(g);qc(g,!1,b)};Kb(e,{type:"text/javascript",charset:"UTF-8",src:a});Dc(d).appendChild(e);return g}function Dc(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}function yc(){if(this&&this.qa){var a=this.qa;a&&"SCRIPT"==a.tagName&&zc(a,!0,this.$)}}function zc(a,b,c){null!=c&&p.clearTimeout(c);a.onload=aa;a.onerror=aa;a.onreadystatechange=aa;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var Cc=0,Bc=1;
function Ac(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);x.call(this,c)}w(Ac,x);function Ec(a,b){this.b=new Wb(a);this.a=b?b:"callback";this.$=5E3}var Fc=0;Ec.prototype.send=function(a,b,c,d){a=a||null;d=d||"_"+(Fc++).toString(36)+ga().toString(36);p._callbacks_||(p._callbacks_={});var e=this.b.clone();if(a)for(var f in a)a.hasOwnProperty&&!a.hasOwnProperty(f)||jc(e,f,a[f]);b&&(p._callbacks_[d]=Gc(d,b),jc(e,this.a,"_callbacks_."+d));b=xc(e.toString(),{timeout:this.$,Ca:!0});tc(b,null,Hc(d,a,c),void 0);return{F:d,ja:b}};
Ec.prototype.cancel=function(a){a&&(a.ja&&a.ja.cancel(),a.F&&Ic(a.F,!1))};function Hc(a,b,c){return function(){Ic(a,!1);c&&c(b)}}function Gc(a,b){return function(c){Ic(a,!0);b.apply(void 0,arguments)}}function Ic(a,b){p._callbacks_[a]&&(b?delete p._callbacks_[a]:p._callbacks_[a]=aa)};var Jc="border-bottom-width border-left-width border-right-width border-top-width left margin-bottom margin-left margin-right margin-top padding-bottom padding-left padding-right padding-top top".split(" "),Kc="border-left border-right margin-left margin-right padding-left padding-right".split(" "),Lc=["padding-left","padding-right"],Mc={A:!0,DIV:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,P:!0,SPAN:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0},Nc={SCRIPT:!0,STYLE:!0,IFRAME:!0},Oc=["left","width"],Pc=["CODE",
"PRE","UL"];function Qc(){this.height=this.width=this.bottom=this.right=this.left=this.top=0}function Rc(a,b){this.width=a;this.height=b}function N(a){var b=null;if(a&&"string"==typeof a){var c=a.indexOf("px");-1!=c&&(a=a.substring(0,c));c=a.length-1;a.length<=c?c=!1:(c=a.charCodeAt(c),c=48<=c&&57>=c);c&&(b=parseInt(a,10),isNaN(b)&&(b=null))}return b}function O(a,b){var c=null;a&&(c=N(a.getPropertyValue(b)));return c}function P(a,b){a.style&&a.style.removeProperty(b);a.removeAttribute(b)}
function Sc(a,b){var c=null;a.style&&(c=N(a.style.getPropertyValue(b)));null==c&&(c=N(a.getAttribute(b)));return c}function Q(a,b,c){a.style.setProperty(b,c,"important")}function Tc(a,b){if(b&&0!=b.length){var c=a.getAttribute("style")||"";0<c.length&&";"!=c[c.length-1]&&(c+=";");a.setAttribute("style",c+b)}}
function Uc(a){a=a.getBoundingClientRect();var b=document.body,c=document.documentElement||b.parentNode||b,b="pageXOffset"in window?window.pageXOffset:c.scrollLeft,c="pageYOffset"in window?window.pageYOffset:c.scrollTop;return new Za(a.top+c,a.right+b,a.bottom+c,a.left+b)}
function Vc(a){var b=null,b=a.nodeName.toUpperCase();return"SCRIPT"!=b&&"STYLE"!=b&&a.style&&(a=window.getComputedStyle(a))&&(b=a.getPropertyValue("background-image"),"none"==b&&(b=null),b&&5<b.length&&0==b.indexOf("url(")&&")"==b[b.length-1])?b=b.substring(4,b.length-1):null}function Wc(){if(null!=window.parent&&window!=window.parent)try{if(window.parent.document.domain==document.domain)return!0}catch(a){}return!1}
function Xc(a){if(!a)return 0;var b=1;for(a=a.firstChild;a;a=a.nextSibling)b+=Xc(a);return b}var Yc={Ja:"IMG",Ka:"SVG",Ia:"background-image"};ha("pagespeed.MobUtil.ImageSource",Yc);function Zc(a,b,c){this.v=a;this.B=b;this.J=c}function R(a){for(var b=0,c=a.length;b<c;++b){var d=Math.round(a[b]);0>d?d=0:255<d&&(d=255);a[b]=d}return E(a)}function $c(a){a=a.toLowerCase();for(var b="",c=0,d=a.length;c<d;++c){var e=a.charAt(c);if("a"<=e&&"z">=e||"0"<=e&&"9">=e)b+=e}return b}
function ad(a){if(!a||0<=a.indexOf("data:image/"))return"";var b=a.lastIndexOf("/");0>b?b=0:++b;var c=a.indexOf(".",b);0>c&&(c=a.length);return a.substring(b,c)}function bd(a,b){var c=window.atob(a);return"data:image/gif;base64,"+window.btoa(c.substring(0,13)+String.fromCharCode(b[0],b[1],b[2])+c.substring(16,c.length))}function cd(a){return!y(a,document.location.origin+"/")&&!y(a,"data:image/")}
function dd(a){a=Uc(a);var b=new Qc;b.top=a.top;b.bottom=a.bottom;b.left=a.left;b.right=a.right;b.height=a.bottom-a.top;b.width=a.right-a.left;return b}function ed(a){var b=N(a.top);a=N(a.left);return null!=b&&-100>b||null!=a&&-100>a}function T(a){window.psDebugMode&&console&&console.log&&console.log(a)}
function U(a,b,c){!window.psMobBeaconUrl&&b?b():(a=window.psMobBeaconUrl+"?id=psmob&url="+encodeURIComponent(document.URL)+"&el="+a,c&&(a+=c),c=document.createElement("IMG"),c.src=a,b&&(b=fd(b),c.addEventListener("load",b),c.addEventListener("error",b),window.setTimeout(b,500)))}function fd(a){var b=!1;return function(){b||(b=!0,a())}}
function gd(){var a=1;"desktop"!=window.psDeviceType&&(a=90==Math.abs(window.orientation)&&screen.height>screen.width?window.innerHeight/screen.width*a:window.innerWidth/screen.width*a);if(Sa()){var b;b=window;var c=xb&&zb;b=q(b.devicePixelRatio)&&!c?b.devicePixelRatio:b.matchMedia?Nb(.75)||Nb(1.5)||Nb(2)||Nb(3)||1:1;a=a*b}return a};function V(a,b,c,d){this.a=document.createElement("A");this.F=a;this.N=b;this.K=c;this.s=d;this.i()}V.prototype.i=function(){this.a.id=this.F;B(this.a,"psmob-button");this.a.onclick=v(this.g,this);var a=document.createElement("DIV");B(a,"psmob-button-icon");a.style.backgroundImage="url("+bd(this.N,this.K)+")";this.a.appendChild(a);this.s&&(a=document.createElement("P"),B(a,"psmob-button-text"),this.a.appendChild(a),a.appendChild(document.createTextNode(this.s)))};
function hd(a,b){this.b=b;V.call(this,"psmob-menu-button","R0lGODlhYABgAPAAAAAAAAAAACH5BAEAAAEALAAAAABgAGAAAAK6jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8agCKJfMpvMJjUqnTg71is1qldat97vtgsfkp7iMJp/T7PCmDXdr4vQr8o7P6/f8vv8PGCg4SHhTdxi1hriouHjY6EgHGQk3SclmeYmWqalW+AkaKjpKWmp6ipqqatH5+NYq+QpbKTuLWWu7iZvrOcebxvlrt0pcbHyMnKy8zNzs/AwdLT1NXW19TVoAADs=",a,null)}w(hd,V);hd.prototype.g=function(){this.b()};
function id(a,b,c,d){this.f=b;this.b=c;this.c=d;V.call(this,"psmob-map-button","R0lGODlhYABgAPAAAAAAAAAAACH5BAEAAAEAIf8LSW1hZ2VNYWdpY2sHZ2FtbWE9MQAsAAAAAGAAYAAAAv6Mj6nL7Q+jnLTai7PevPsPhuJIluaJpuo6Au4Ls3IA1/Y7l/fO5x8P7Pk0weJteDEqj0jJ8llrQqBUnJRRzQKuCq2We/B6wWIxtzyWos3IdbntTufi7zldLmMj9Cx895tX5SQYCEVB2Ed1qJhoWIGYAjnoqMJoYRlJ+aiJgrn41LiE4XlCOim6YhqhSiK5ytoCiyUr4upgW0q7pxuSdQpaiGvgV0nMF3rHW5vs68OsHPuM6iw9TV0dpIadrb3N1O0ddRYeQ0ZuZU4OFna+zu7t/r4dLy9NX/98j3+nv8vc7y8ZwIBxBhJ0Y/BgnYT7ADFs2OwhRE4SaRyrOMwhRjeF1jZOBOJxFrCQf0aSTGDyJEojKm9xa9kAJEyXO2Y+qGnzpricOl3wHPQzqNChRIsaPYo0acUCADs=",a,
"GET DIRECTIONS")}w(id,V);id.prototype.g=function(){U("psmob-map-button",v(this.l,this))};function jd(a){return"https://maps.google.com/maps?q="+encodeURIComponent(a.f)}id.prototype.l=function(){if(this.b&&this.c){var a=new Image;a.onload=v(function(){p.location=jd(this)},this);a.onerror=a.onload;a.src="//www.googleadservices.com/pagead/conversion/"+this.b+"/?label="+this.c+"&amp;guid=ON&amp;script=0"}else p.location=jd(this)};
function kd(a,b,c,d){this.c=b;this.b=null;this.H=c;this.f=d;this.l=new pa(document);this.o=null;V.call(this,"psmob-dialer-button","R0lGODlhYABgAPAAAAAAAAAAACH5BAEAAAEAIf8LSW1hZ2VNYWdpY2sHZ2FtbWE9MQAsAAAAAGAAYAAAAv6Mj6nL7Q+jnLTai7PevPsPhuJIluaJpurKtu4Lx/KsAvaN5zcd6r7P8/yGuSCHiAQYN0niUtMcPjPR3xRTBV4tWd2W28V9K2HxeFI2nyNp21rSVr4h8Tm9bX/E5fnFvt9QB+iHN6ggaIiAmHiQxngY9giZJTkZVUnYhJmJtMmQ5PnpFMrpRSqqdWpZpFqq1tpoBZsgNRsraxtQmzvKu2v7O9sLHAw7bHzc2ulbrLpM3IzGegV6UW10Le0Ik3232KLp/cfdvfoNHm5+7pJ+u7dDc2nwbhpPv81zX/akT8nf324JwGdTBkbDZnDamITw3jDsY9BQP0b3MK171IVZqhBcHDt6/AgypMiRJEuaDFUAADs=",
a,"CALL US")}w(kd,V);kd.prototype.i=function(){kd.Ha.i.call(this);var a;a:{if(a=sa(this.l,"psgwcm"))if(a=ia(window.decodeURIComponent(a)),a.fallback==this.c&&a.clabel==this.f){a=a.mobile_number;break a}a=null}this.b=a};
kd.prototype.g=function(){U("psmob-phone-dialer");if(this.b)ld(this);else{var a;this.f&&this.H?(a=window.encodeURIComponent(this.f),a="https://www.googleadservices.com/pagead/conversion/"+window.encodeURIComponent(this.H)+"/wcm?cl="+a+"&fb="+window.encodeURIComponent(this.c)):a=null;a?(window.psDebugMode&&window.alert("requesting dynamic phone number: "+a),a=new Ec(a),this.o=Date.now(),a.send(null,v(this.I,this,!0),v(this.I,this,!1))):ld(this)}};
function ld(a){var b;a.b?(b=a.b,a="call-gv-number"):(b=a.c,a="call-fallback-number");U(a,function(){p.location="tel:"+b})}
kd.prototype.I=function(a,b){U("call-conversion-response",null,"&s="+a.toString()+"&t="+(Date.now()-this.o));var c=b&&b.wcm,d=c&&c.mobile_number;if(d){var c={expires:c.expires,formatted_number:c.formatted_number,mobile_number:d,clabel:this.f,fallback:this.c},e=[];ka(new ja,c,e);c=e.join("");window.psDebugMode&&window.alert("saving phoneNumber in cookie: "+c);ra(this.l,"psgwcm",window.encodeURIComponent(c),7776E3,"/");this.b=d}ld(this)};function md(){}function nd(a,b){this.a=a;this.b=b}function od(a,b){if(3!=a.length||3!=b.length)return Infinity;var c=a[0]-b[0],d=a[1]-b[1],e=a[2]-b[2];return Math.sqrt(c*c+d*d+e*e)}function pd(a){a/=255;return a=.03928>=a?a/12.92:Math.pow((a+.055)/1.055,2.4)}
function qd(a){var b=a.a,c=a.b,d=.2126*pd(b[0])+.7152*pd(b[1])+.0722*pd(b[2]),e=.2126*pd(c[0])+.7152*pd(c[1])+.0722*pd(c[2]);if(1E-10>d&&1E-10>e)return a;d=e/d;1>d&&(d=1/d);if(3<d)return a;b=Ya(b[0],b[1],b[2]);c=Ya(c[0],c[1],c[2]);d=a=null;b[2]<c[2]?(a=b[2],d=c[2]):(a=c[2],d=b[2]);e=(3*a-d)/4;a=a>e?a-e:0;d=d<1-2*e?d+2*e:255;b[2]<c[2]?(b[2]=a,c[2]=d):(c[2]=a,b[2]=d);b=Xa(b[0],b[1],b[2]);c=Xa(c[0],c[1],c[2]);return new nd(b,c)}
function rd(a,b,c,d){var e=[],f,g,h;for(g=0;g<d;++g)for(f=0;f<c;++f){var k=4*(g*c+f);h=3*(g*c+f);var m=a[k+3]/255,n=1-m;e[h]=m*a[k]+n*b[0];e[h+1]=m*a[k+1]+n*b[1];e[h+2]=m*a[k+2]+n*b[2]}k=[0,0,0];for(f=m=g=0;f<c;++f)n=(d-1)*c+f,h=3*n,k[0]+=e[h],k[1]+=e[h+1],k[2]+=e[h+2],m+=a[4*n+3],++g;if(m>127.5*g)for(f=0;3>f;++f)k[f]=Math.floor(k[f]/g);else k=b;a=Math.floor(.25*c);b=Math.floor(.75*c);m=Math.floor(.25*d);d=Math.floor(.75*d);var n=0,r=[];for(g=m;g<=d;++g)for(f=a;f<=b;++f)h=3*(g*c+f),r[n]=od(e.slice(h,
h+3),k),++n;f=r.sort(function(a,b){return a-b});var Pa=Math.max(1,f[Math.floor(.75*n)]),n=0,r=[0,0,0];for(g=m;g<=d;++g)for(f=a;f<=b;++f)h=3*(g*c+f),od(e.slice(h,h+3),k)>=Pa&&(r[0]+=e[h],r[1]+=e[h+1],r[2]+=e[h+2],++n);if(0<n)for(f=0;3>f;++f)r[f]=Math.floor(r[f]/n);return qd(new nd(k,r))}
md.prototype.run=function(a,b){if(a)if(cd(a.src))T("Found logo but its origin is different from that of HTML. Using default color.");else{T("Found logo. Theme color will be computed from logo.");var c=b||[255,255,255],d=a.naturalWidth,e=a.naturalHeight,f=document.createElement("CANVAS");f.width=d;f.height=e;f=f.getContext("2d");f.drawImage(a,0,0);f=f.getImageData(0,0,d,e);return rd(f.data,c,d,e)}else T("Did not find logo. Using default color.");c=[0,0,0];b?178.5>=Ya(b[0],b[1],b[2])[2]&&(c=[255,255,
255]):b=[255,255,255];return new nd(b,c)};function sd(){}sd.prototype.run=function(){var a=document.createElement("DIV");document.body.appendChild(a);a.id="psmob-iframe-container";a.appendChild(Jb("psmob-spacer"));a.appendChild(Jb("psmob-iframe"))};function td(){var a=window.document.documentElement.clientWidth;if(!a)return 400;var b=window.document.body;if(b){var c=window.getComputedStyle(b);Da(Lc,function(b){(b=O(c,b))&&(a-=b)})}return a}function ud(a){Q(a,"overflow-x","auto");Q(a,"width","auto");Q(a,"display","block")}function vd(a){var b=0,c=a.tagName.toUpperCase();"DIV"!=c&&"TABLE"!=c&&"UL"!=c||++b;for(a=a.firstElementChild;a;a=a.nextElementSibling)b+=vd(a);return b}
function wd(a){var b=[],c=a.tagName.toUpperCase();if("SCRIPT"==c||"STYLE"==c||!a.style)return b;a=window.getComputedStyle(a);if(!a)return b;a=a.getPropertyValue("background-image");if(!a||"none"==a)return b;if(-1!=a.indexOf("'")||-1!=a.indexOf('"'))return null;a=a.split(",");for(c=0;c<a.length;++c){var d=Aa(a[c]);if(y(d,"url(")){if(")"!=d.charAt(d.length-1))return null;b.push(d.substring(4,d.length-1))}}return b}function xd(a,b){for(var c=1;c<arguments.length;++c)P(a,arguments[c])};function W(a){this.f=a;this.c={"psmob-nav-panel":!0,"psmob-header-bar":!0,"psmob-spacer":!0,"psmob-logo-span":!0};this.a=td();this.b=[new X(W.prototype.ra,"scroll wide pre-tags"),new X(W.prototype.sa,"string floats"),new X(W.prototype.Ba,"cleanup styles"),new X(W.prototype.oa,"repair distored images"),new X(W.prototype.pa,"resize if too wide"),new X(W.prototype.ka,"expand columns"),new X(W.prototype.Ga,"resize vertically")];T("window.pagespeed.MobLayout.maxWidth="+this.a)}
function X(a,b){this.a=a;this.b=b}function yd(a,b){return b?Nc[b.tagName.toUpperCase()]||!(!b.id||!a.c[b.id]):!0}function zd(a,b,c){for(b=b.firstElementChild;b;b=b.nextElementSibling)yd(a,b)||c.call(a,b)}l=W.prototype;l.ra=function(a){("PRE"==a.tagName.toUpperCase()||a.offsetWidth>this.a&&"pre"==window.getComputedStyle(a).getPropertyValue("white-space"))&&ud(a);zd(this,a,v(this.ra,this))};l.Ga=function(a){Ad(this,a,0)};
function Ad(a,b,c){var d;(d=Uc(b))?(c=d.top,d=d.bottom):(b.offsetParent==b.parentNode&&(c+=b.offsetTop),d=c+b.offsetHeight-1);d=[c,d];if(!d)return null;c=d[0];d=d[1];if(yd(a,b))return d;d=c-1;var e=window.getComputedStyle(b);if(!e)return null;var f=O(e,"min-height");null!=f&&(d+=f);for(var f=c+b.offsetHeight-1,g=!1,h=!1,k,m=b.firstElementChild;m;m=m.nextElementSibling)(k=window.getComputedStyle(m))&&"absolute"==k.position&&!ed(k)&&0!=N(k.getPropertyValue("height"))&&"hidden"!=k.getPropertyValue("visibility")&&
(h=!0),k=Ad(a,m,c),null!=k&&(g=!0,d=Math.max(d,k));if(g&&"fixed"==e.getPropertyValue("position"))return null;a=b.tagName.toUpperCase();"BODY"!=a&&(e=f-c+1,g?d!=f&&(h?Q(b,"height",""+(d-c+1)+"px"):Q(b,"height","auto")):("IMG"!=a&&0<e&&!b.style.backgroundSize&&(P(b,"height"),Q(b,"height","auto"),b.offsetHeight&&(f=c+b.offsetHeight)),d=f));return d}
l.pa=function(a){zd(this,a,v(this.pa,this));if(!(a.offsetWidth<=this.a)){var b=a.tagName.toUpperCase();if("TABLE"==b){var c;a:{c=0;for(b=a.firstElementChild;b;b=b.nextElementSibling)for(var d=b.firstElementChild;d;d=d.nextElementSibling){var e=b.tagName.toUpperCase();if("THEAD"==e||"TFOOT"==e){c=!0;break a}for(e=d.firstElementChild;e;e=e.nextElementSibling){if("TH"==e.tagName.toUpperCase()){c=!0;break a}++c}}c=3*vd(a)<=c}if(c)ud(a);else if("CSS1Compat"!==document.compatMode){var f,g,h,k=document.createElement("DIV");
k.style.display="inline-block";var m=Mb(a);for(c=0;c<m.length;++c)for(var n=Mb(m[c]),b=0;b<n.length;++b)for(var r=Mb(n[b]),d=0;d<r.length;++d)if(g=r[d],1==g.childNodes.length)f=g.childNodes[0],g.removeChild(f),k.appendChild(f);else if(1<g.childNodes.length){h=document.createElement("DIV");h.style.display="inline-block";for(var Pa=Mb(g),e=0;e<Pa.length;++e)f=Pa[e],g.removeChild(f),h.appendChild(f);k.appendChild(h)}a.parentNode.replaceChild(k,a)}else for(P(a,"width"),Q(a,"max-width","100%"),a=a.firstElementChild;a;a=
a.nextElementSibling)for(P(a,"width"),Q(a,"max-width","100%"),c=a.firstElementChild;c;c=c.nextElementSibling)if("TR"==c.tagName.toUpperCase())for(P(c,"width"),Q(c,"max-width","100%"),b=c.firstElementChild;b;b=b.nextElementSibling)"TD"==b.tagName.toUpperCase()&&(Q(b,"max-width","100%"),Q(b,"display","inline-block"))}else if("IMG"==b)c=this.a,b=a.offsetHeight,d=a.offsetWidth/c,1<d&&(b=b/d,Q(a,"width",""+c+"px"),Q(a,"height",""+b+"px"));else if(d=wd(a),c=window.getComputedStyle(a),d&&c&&1==d.length){b=
this.f.i[d[0]];b==Bd&&(b=null);if(d=b&&b.width&&b.height)"auto"==c.getPropertyValue("background-size")?d=!1:(d=c.getPropertyValue("background-position"),"none"==d?d=!1:(d=d.split(" "),d=!(2!=d.length||null==N(d[0])||null==N(d[1])))),d=!d;d&&(d=this.a,e=b.width,b=b.height,e>d&&(b=Math.round(d/e*b),d="background-size:"+d+"px "+b+"px;background-repeat:no-repeat;",c=O(c,"height"),b==c&&(d+="height:"+b+"px;"),Tc(a,d)),Q(a,"min-height",""+b+"px"))}else 0<=Ca(Pc,b)?ud(a):Mc[b]?(Q(a,"max-width","100%"),P(a,
"width")):T("Punting on resize of "+b+" which wants to be "+a.offsetWidth+" but this.maxWidth_="+this.a)}};l.Ba=function(a){var b=document.body.style.display;document.body.style.display="none";this.ha(a);document.body.style.display=b};
l.ha=function(a){"nowrap"==window.getComputedStyle(a).getPropertyValue("white-space")&&Q(a,"white-space","normal");zd(this,a,this.ha);var b=window.getComputedStyle(a);if(b){for(var c=0;c<Oc.length;++c){var d=Oc[c],e=b.getPropertyValue(d);e&&"100%"!=e&&"auto"!=e&&za(e,"%")&&Q(a,d,"auto")}for(var d=a.tagName.toUpperCase(),c="UL"==d||"OL"==d,d="BODY"==d,e=!1,f="",g=0;g<Jc.length;++g){var h=Jc[g];if(!(c&&za(h,"-left")||d&&y(h,"margin-"))){var k=O(b,h);null!=k&&(4<k?f+=h+":4px !important;":0>k&&(e=!0,
"margin-bottom"==h&&(e=-30<k),e?f+=h+":0px !important;":a.setAttribute("data-pagespeed-negative-bottom-margin","1")))}}Tc(a,f)}};
l.oa=function(a){zd(this,a,this.oa);if("IMG"==a.tagName.toUpperCase()){var b=window.getComputedStyle(a),c=Sc(a,"width"),d=Sc(a,"height");if(c&&d&&b){var e=O(b,"width"),b=O(b,"height");if(e&&b&&(e/=c,b/=d,.95<(e>b?b/e:e/b)||(T("aspect ratio problem for "+a.getAttribute("src")),1==a.naturalHeight&&1==a.naturalWidth?(b=Math.min(e,b),xd(a,["width","height"]),a.style.width=c*b,a.style.height=d*b):e>b?P(a,"height"):(xd(a,["width","height"]),a.style.maxHeight=d)),.25>e)){for(T("overshrinkage for "+a.getAttribute("src"));a&&
"TD"!=a.tagName.toUpperCase();)a=a.parentNode;if(a&&(a=a.parentNode)){d=0;for(c=a.firstElementChild;c;c=c.nextElementSibling)"TD"==c.tagName.toUpperCase()&&++d;if(1<d)for(d="width:"+Math.round(100/d)+"%;",c=a.firstElementChild;c;c=c.nextElementSibling)"TD"==c.tagName.toUpperCase()&&Tc(c,d)}}}}};
l.sa=function(a){var b=window.getComputedStyle(a).getPropertyValue("position");if("fixed"==b)return"fixed";if(Ka(a,"nivoSlider"))return b;var c=[],d=null,e=!1;zd(this,a,function(a){var b=window.getComputedStyle(a),f=this.sa(a);if("fixed"!=f&&b&&!yd(this,a)){"absolute"!=f||ed(b)||Q(a,"position","relative");var f=b.getPropertyValue("float"),g="right"==f,r="inline-block";g&&"right"==b.getPropertyValue("clear")&&(g=!1,r="block",d&&e&&Q(d,"margin-bottom","0"));if(g||"left"==f||"block"==r)Q(a,"float","none"),
"none"!=b.getPropertyValue("display")&&Q(a,"display",r);g&&c.push(a);d=a;a=O(b,"margin-bottom");e=null!=a&&0>a}}.bind(this));var f,g;for(f=c.length-1;0<=f;--f)g=c[f],a.removeChild(g);for(f=c.length-1;0<=f;--f)g=c[f],a.appendChild(g);return b};
l.ka=function(a){for(var b=Cd(this,a),c=null,d=0;d<b.length;++d){var e=b[d],f=d<b.length-1?b[d+1]:null,g=e.offsetLeft+e.offsetWidth;if((null==c||e.offsetLeft<c)&&(null==f||f.offsetLeft<g)&&(c=window.getComputedStyle(e))){var f=e,h=f.tagName.toUpperCase();"INPUT"!=h&&"SELECT"!=h&&(f.style.backgroundSize||"auto"==c.width||Q(f,"width","auto"),"IMG"!=h&&f.removeAttribute("width"),xd(f,Kc),f.className+=f.className?" ":"",f.a+="psmob-single-column");this.ka(e)}a.getAttribute("data-pagespeed-negative-bottom-margin")&&
(a.removeAttribute("data-pagespeed-negative-bottom-margin"),e=window.getComputedStyle(a),e=O(e,"height"),null!=e&&Q(a,"margin-bottom",""+-e+"px"));c=g}};function Cd(a,b){var c=[];if("fixed"==window.getComputedStyle(b).getPropertyValue("position"))return c;zd(a,b,function(a){var b=window.getComputedStyle(a).getPropertyValue("position");("fixed"!=b&&"absolute"!=b||0!=a.offsetWidth)&&c.push(a)});return c};function Dd(a,b,c){this.c=a;this.a=b;this.b=c}function Ed(){this.b=null;var a=document.domain.toLowerCase().split("."),b=a.length;this.Fa=4<b&&2==a[b-3].length?a[b-5]:3<b?a[b-4]:null;this.i=window.location.origin+window.location.pathname;this.a=[];this.c=0;this.f=1}function Fd(a,b){this.c=a;this.a=b;this.i=[];this.s=[];this.l=this.o=this.g=null;this.b=b;this.backgroundColor=this.f=null}
function Gd(a,b){function c(a){a&&"string"==typeof a&&(-1!=a.toLowerCase().indexOf("logo")&&++e,this.Ma&&0<=$c(a).indexOf($c(this.Fa))&&++e)}if("hidden"==window.getComputedStyle(b).getPropertyValue("visibility"))return null;var d=null;"IMG"==b.nodeName.toUpperCase()?d=b.src:d=Vc(b);d=ad(d);-1!=d.indexOf("data:image/")&&(d=null);var e=0;c(b.title);c(b.id);c(b.className);c(b.alt);c(d);b.href==a.i&&++e;return 0<e?new Fd(e,b):null}
function Hd(a,b){var c=Gd(a,b);c&&a.a.push(c);for(c=b.firstElementChild;c;c=c.nextElementSibling)Hd(a,c)}function Id(a,b){++a.c;b.addEventListener("load",v(a.g,a));b.addEventListener("error",v(a.g,a))}function Jd(a,b){var c=document.createElement("IMG");Id(a,c);c.src=b;return c}
function Kd(a,b,c,d){var e=null,f;for(f in Yc){var e=b,g=Yc[f],h=null;switch(g){case "IMG":e.nodeName==g&&(h=e.src);break;case "SVG":e.nodeName==g&&(e=(new XMLSerializer).serializeToString(e),h=(self.URL||self.webkitURL||self).createObjectURL(new Blob([e],{type:"image/svg+xml;charset=utf-8"})));break;case "background-image":h=Vc(e)}if(h){var e=h,k=Sb(document.location.href),g=k[1],h=k[2],m=k[3],k=k[4],n="";g&&(n+=g+":");m&&(n+="//",h&&(n+=h+"@"),n+=m,k&&(n+=":"+k));g=n;k=Ub(Sb(g)[3]||null);h=Ub(Sb(e)[3]||
null);null!=k&&null!=h&&(m=!1,k!=h&&(0<=k.indexOf(h)&&(k=k.split("."),n=k.length,3<=n&&(h==k.slice(0,n-2).join(".")||"www"==k[0]&&(h==k.slice(1,n-2).join(".")||h==k.slice(1,n).join(".")))&&(m=!0)),e=m?g+e.substring(e.indexOf(h)+h.length):e))}else e=null;if(e){g=null;"IMG"==f?(g=b,b.naturalWidth||Id(a,g)):g=Jd(a,e);c.push(b);d.push(g);break}}for(b=b.firstElementChild;b;b=b.nextElementSibling)Kd(a,b,c,d)}function Ld(a,b){var c=a.length-1;b<c&&(a[b]=a[c]);a.pop()}
function Md(a){for(var b=a.a,c=0;c<b.length;++c){for(var d=b[c],e=dd(d.a),f=e.width*e.height,g=.5*f,h=-1,k=0,m=0;m<d.i.length;++m)if(f=d.i[m])e=dd(f),f=e.width*e.height,f>=g&&20<e.width&&10<e.height&&400>e.height&&f>k&&(k=f,h=m);0<=h?(d.l=d.i[h],d.b=d.s[h],d.f=e):d.g?(f=d.g,e=dd(f),f=e.width*e.height,f>=g&&20<e.width&&10<e.height&&400>e.height?(d.l=d.g,d.b=d.o,d.f=e):(Ld(b,c),--c)):(Ld(b,c),--c)}b=a.a;if(1<b.length){e=0;g=Infinity;for(c=0;d=b[c];++c)h=d.f,g=Math.min(g,h.top),e=Math.max(e,h.bottom);
for(c=0;d=b[c];++c)h=d.f,d.c*=Math.sqrt((e-h.top)/(e-g));if(0<b.length&&1==a.f){e=b[0];for(c=1;c<b.length;++c)d=b[c],0>Nd(d,e)&&(e=d);b[0]=e}else b.sort(Nd)}c=[];d={};for(e=0;c.length<a.f&&e<b.length;++e)if(g=b[e],!d[g.b.src]){d[g.b.src]=!0;if((h=g)&&h.l){m=null;for(k=h.l;k&&!m;){a:{if(m=document.defaultView.getComputedStyle(k,null))if(f=m.getPropertyValue("background-color")){b:{var m=f.indexOf("("),n=f.lastIndexOf(")");if(m=0<=m&&n>m?f.substring(m+1,n):null){for(var m=m.split(","),f=[],n=0,r=m.length;n<
r;++n)if(f[n]=3!=n?parseInt(m[n],10):parseFloat(m[n]),isNaN(f[n])){m=null;break b}m=3==f.length||4==f.length?f:null}else m="transparent"==f?[0,0,0,0]:null}if(m&&(3==m.length||4==m.length&&0!=m[3]))break a}m=null}k=k.parentElement}h.backgroundColor=m}h=(new md).run(g.b,g.backgroundColor);c.push(new Dd(g,h.a,h.b))}b=a.b;a.b=null;b(c)}Ed.prototype.g=function(){--this.c;0==this.c&&Md(this)};var Od=[function(a){return a.top},function(a){return a.left},function(a){return a.width*a.height}];
function Nd(a,b){if(a.c>b.c)return-1;if(b.c>a.c)return 1;for(var c=0;c<Od.length;++c){var d=Od[c],e=d(a.f),d=d(b.f);if(e<d)return-1;if(d<e)return 1}if(a.a&&a.a.src&&b.a&&b.a.src){if(a.a.src<b.a.src)return-1;if(a.a.src>b.a.src)return 1}return 0}
Ed.prototype.run=function(a,b){if(this.b||!document.body)a([]);else{this.b=a;this.f=b;Hd(this,document.body);for(var c=this.a,d=0;d<c.length;++d){var e=c[d],f=e.a;Kd(this,f,e.i,e.s);for(f=f.parentElement;f;){var g=Vc(f);if(g){e.g=f;e.o=Jd(this,g);break}f=f.parentElement}}0==this.c&&Md(this)}};Ed.prototype.run=Ed.prototype.run;function Pd(a){this.a=a}function Qd(a,b,c){var d=new Zc(a,b,c);window.psMobPrecompute&&(window.psMobLogoUrl=a,window.psMobBackgroundColor=b,window.psMobForegroundColor=c);return d}Pd.prototype.b=function(a){if(this.a){1<=a.length?(a=a[0],a=Qd(a.c.b.src,a.a,a.b)):a=Qd(null,[255,255,255],[0,0,0]);var b=this.a;this.a=null;b(a)}};function Rd(a,b){this.a=a;this.g=b;this.b=null;this.c=0;Sd(this)}
function Sd(a){document.body.appendChild(a.a);for(var b=a.a.getElementsByClassName("open"),c=0,d=b.length;c<d;c++)Na(b[c]);Td(a);Ud(a);Vd(a);a.a.addEventListener("touchmove",v(function(a){if(Y(this)){var b=a.touches[0].clientY;if(1!=a.touches.length)a.preventDefault();else{var c=b>this.c,d=0==this.a.scrollTop,k=this.a.scrollTop>=this.a.scrollHeight-this.a.offsetHeight-1;a.cancelable&&(c&&d||!c&&k)&&a.preventDefault();a.stopImmediatePropagation&&a.stopImmediatePropagation();this.c=b}}},a),!1);window.addEventListener("scroll",
v(function(a){Y(this)&&!this.a.contains(a.target)&&(a.stopPropagation(),a.preventDefault())},a));window.addEventListener("touchstart",v(function(a){this.c=a.touches[0].clientY},a),!1)}function Wd(a,b){var c=gd(),d="scale("+c+")";a.a.style.webkitTransform=d;a.a.style.transform=d;d=Y(a)?0:-Qb(a.a).width;a.a.style.top=window.scrollY+"px";a.a.style.left=window.scrollX+d+"px";b&&(a.a.style.marginTop=b+"px",a.a.style.height=(window.innerHeight-b)/c+"px")}
function Ud(a){a.b=document.createElement("DIV");a.b.id="psmob-click-detector-div";document.body.insertBefore(a.b,a.a);a.b.addEventListener("click",v(function(){Y(this)&&this.f()},a),!1)}
function Td(a){var b=a.a.querySelectorAll("DIV > A"),c=b.length;if(0!=c){a=bd("R0lGODlhkACQAPABAP///wAAACH5BAEAAAEALAAAAACQAJAAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vh8EAJATKIhFWFhziEiluBjT6AgFGdkySclkeZmSqYnE2VnyCUokOhpSagqEmtqxytrjurnqFGtSSztLcvu0+9HLm+sbPPWbURx1XJGMPHyxLPXsEA3dLDFNXP1wzZjNsF01/W31LH6VXG6YjZ7Vu651674VG8/l2s1mL2qXn4nHD6nn3yE+Al+5+fcnQL6EBui1QcUwgb6IEvtRVGDporc/RhobKOooLRBIbSNLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOn0KVUcBADs=",a.g);
for(var d=0;d<c;d++){var e=document.createElement("IMG"),f=b[d];f.insertBefore(e,f.firstChild);e.setAttribute("src",a);B(e,"psmob-menu-expand-icon")}}}Rd.prototype.f=function(){U(Y(this)?"psmob-menu-button-close":"psmob-menu-button-open");Ma(this.a,"psmob-open");Ma(this.b,"psmob-open");Ma(document.body,"noscroll");Wd(this)};function Xd(a,b){var c=new Wb(a);return c.C==document.domain||c.C==b?(c.C=b,c.toString()):null}
function Vd(a){for(var b=a.a.querySelectorAll("DIV"),c=0,d;d=b[c];++c)d.addEventListener("click",function(a){a.preventDefault();a=a.currentTarget;Ma(a.nextSibling,"psmob-open");Ma(a.firstChild.firstChild,"psmob-open")},!1);if(b=document.getElementById("psmob-iframe")){d=gc(new Wb(b.src));for(var e=a.a.querySelectorAll("LI > A"),c=0,f;f=e[c];c++){var g=Xd(f.href,d);g&&f.addEventListener("click",v(function(a,b,c){this.f();c.preventDefault();a.src=b},a,b,g))}}}
function Y(a){return Ka(a.a,"psmob-open")};function Yd(){this.j=Jb("psmob-header-bar");this.a=null;this.b=Jb("psmob-spacer");this.U=this.G=this.g=this.c=this.s=this.f=null;this.W=0;this.i=-1;this.o=new eb;this.l=!1;this.la=Sa()}
function Zd(a,b,c){if(!b.className||"ps-progress-scrim"!=b.className&&t(b.className)&&!y(b.className,"psmob-")&&!y(b.id,"psmob-")){var d=window.getComputedStyle(b),e=d.getPropertyValue("position");"static"!=e&&(null==N(d.getPropertyValue("top"))||"fixed"!=e&&(c||"absolute"!=e)||a.o.add(b),c=!0);for(b=b.firstElementChild;b;b=b.nextElementSibling)Zd(a,b,c)}}
Yd.prototype.T=function(){if(this.j){var a=-1==this.i?Math.round(Qb(this.j).height):this.i,b=gd(),c="scale("+b.toString()+")";this.j.style.webkitTransform=c;this.j.style.transform=c;c=window.innerWidth;if("hidden"!=window.getComputedStyle(document.body).getPropertyValue("overflow-y")){var d=document.createElement("div");d.style.cssText="overflow:auto;position:absolute;top:0;width:100px;height:100px";var e=document.createElement("div"),f="200px",g;f instanceof oa?(g=f.height,f=f.width):g="200px";e.style.width=
Pb(f);e.style.height=Pb(g);d.appendChild(e);document.body.appendChild(d);e=d.offsetWidth-d.clientWidth;d&&d.parentNode&&d.parentNode.removeChild(d);c=c-e}this.j.style.width=c/b+"px";La(this.j,"psmob-hide");b=Math.round(Qb(this.j).height);this.b.style.height=b+"px";this.i=b;c=this.o.u();for(d=0;d<c.length;d++)e=c[d],g=window.getComputedStyle(e),f=g.getPropertyValue("position"),g=N(g.getPropertyValue("top")),"static"!=f&&null!=g&&(this.l?(f=e.style.top,f=N(e.style.top),null!=f&&(e.style.top=String(f+
(b-a))+"px")):(f=Uc(e).top,e.style.top=String(f+b)+"px"));this.l&&b!=a&&window.scrollBy(0,b-a);this.j.style.top=window.scrollY+"px";this.j.style.left=window.scrollX+"px";this.l=!0}this.G&&Wd(this.G,this.j.getBoundingClientRect().height)};
function $d(a){function b(){null!=this.U&&(window.clearTimeout(this.U),this.U=null);this.U=window.setTimeout(v(function(){(this.la||0==this.W)&&this.T();this.U=null},this),200)}a.T();window.addEventListener("scroll",v(function(){b.call(this);this.G&&Y(this.G)||B(this.j,"psmob-hide")},a),!1);window.addEventListener("touchstart",v(function(a){this.W=a.touches.length},a),!1);window.addEventListener("touchmove",v(function(a){this.G&&Y(this.G)?a.preventDefault():this.la||B(this.j,"psmob-hide")},a),!1);
window.addEventListener("touchend",v(function(a){this.W=a.touches.length;0==this.W&&b.call(this)},a),!1);window.addEventListener("orientationchange",v(function(){this.T()},a),!1);window.addEventListener("resize",v(function(){this.T()},a),!1)}
function ae(a,b){document.body.insertBefore(a.b,document.body.childNodes[0]);document.body.insertBefore(a.j,a.b);window.psLabeledMode&&B(a.j,"psmob-labeled");window.psConfigMode&&B(a.j,"psmob-theme-config");var c=document.getElementById("psmob-nav-panel");!window.psLabeledMode&&c&&(a.G=new Rd(c,b.J),a.s=new hd(b.B,v(a.G.f,a.G)),a.j.appendChild(a.s.a));b.v&&(a.f=document.createElement("SPAN"),a.f.id="psmob-logo-span",c=document.createElement("IMG"),c.src=b.v,c.id="psmob-logo-image",a.f.appendChild(c),
a.j.appendChild(a.f));a.j.style.borderBottomColor=R(b.B);a.j.style.backgroundColor=R(b.J);window.psPhoneNumber&&(a.c=new kd(b.B,window.psPhoneNumber,window.psConversionId,window.psPhoneConversionLabel),a.j.appendChild(a.c.a));window.psMapLocation&&(a.g=new id(b.B,window.psMapLocation,window.psConversionId,window.psMapConversionLabel),a.j.appendChild(a.g.a));(window.psLabeledMode||a.c&&!a.g||!a.c&&a.g)&&B(a.j,"psmob-show-button-text");$d(a);a.a&&a.a.parentNode.removeChild(a.a);var c=R(b.J),d=R(b.B);
a.a=document.createElement("STYLE");a.a.type="text/css";a.a.appendChild(document.createTextNode("#psmob-header-bar { background-color: "+c+"; }\n#psmob-header-bar *  { color: "+d+"; }\n#psmob-nav-panel { background-color: "+d+"; }\n#psmob-nav-panel *  { color: "+c+"; }\n"));document.head.appendChild(a.a)}
Yd.prototype.run=function(a){if(!Wc()){for(var b=document.querySelectorAll("*"),c=0,d;d=b[c];c++){var e=d.id;(!e||"ps-progress-scrim"!=e&&"psmob-header-bar"!=e&&"psmob-nav-panel"!=e)&&999998<=window.getComputedStyle(d).getPropertyValue("z-index")&&(T("Element z-index exceeded 999998, setting to 999997."),d.style.zIndex=999997)}window.document.body&&Zd(this,window.document.body,!1);ae(this,a);U("nav-done");window.addEventListener("load",v(this.T,this));document.getElementById("psmob-iframe")&&(new sd).run()}};
function be(a,b){a.j.remove();a.b.remove();a.b=document.createElement("DIV");a.b.id="psmob-spacer";a.j=document.createElement("HEADER");a.j.id="psmob-header-bar";ae(a,b)};function ce(){this.a=null;this.c=new Yd;this.b=null}l=ce.prototype;l.run=function(){window.addEventListener("DOMContentLoaded",v(this.Da,this))};l.Da=function(){(new Ed).run(v(this.Ea,this),5)};l.Ea=function(a){this.b=a;0==this.b.length?console.log("No logos detected."):(a=this.b[0],this.c.run(new Zc(a.c.b.src,a.a,a.b)),this.ga())};
l.ga=function(){function a(){var a=document.createElement("TD");d.appendChild(a);return a}if(this.a)this.a&&(this.a.parentNode.removeChild(this.a),this.a=null);else{var b=document.createElement("TABLE");b.className="psmob-logo-chooser-table";var c=document.createElement("THEAD");b.appendChild(c);var d=document.createElement("TR");c.appendChild(d);d.className="psmob-logo-chooser-column-header";a().textContent="Logo";a().textContent="Foreground";a().textContent="";a().textContent="Background";c=document.createElement("TBODY");
b.appendChild(c);for(var e=0;e<this.b.length;++e){d=document.createElement("TR");d.className="psmob-logo-chooser-choice";c.appendChild(d);var f=this.b[e],g=document.createElement("IMG");g.src=f.c.b.src;a().appendChild(g);g.className="psmob-logo-chooser-image";g.onclick=v(this.za,this,f);g=a();g.style.backgroundColor=E(f.b);g.className="psmob-logo-chooser-color";var h=a();h.className="psmob-logo-chooser-color";var k=document.createElement("IMG");k.className="psmob-logo-chooser-swap";k.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIYAAABaCAAAAABY7nEZAAAABGdBTUEAALGPC/xhBQAAAcpJREFUaN7t2ItxgkAQgOHtADvADkwH2oHpADrADlKCdoAdaAekA0qgBEowYIZRE7jbe+xjktsCnE/m54CFm4qBxEgMIkavgwHlVQUDYHVoNTCGWZ86DYxhdudeA2OYgExiMgIyicvwziQ6wy8TCoZHJkQM10zIGG6ZUDIcMiFmYDOhZ6AymWd8ogdwY8sEvP+j6xgz4WMYM2FlLGfCzBgzqTUwiov81djWvXgb+bFzvFO26MEasqqVPkWXguBlLAbByDAFwcWwBMHDsAbBwMAEQc1ABkHKwAdByHAJgorhGAQJI/8IWC5EYmRF2KolCmN/uYX+TDBjU0dYw4UyQoJI69n/wmhKeUZ3WAMIM/rT2/34EGWc36fjXI7RlKvHU0WIcQ8CZBlTEKKMRxByjJcghBg/g5BgzATBz5gNgpmxFAQnwxAEG8McBBPDFsTzAhY7rgxEED7jxMAFQctAB0HLqPeggTFcj+NGA2Oso8o1MMZ7pcg0MFwyabDjeZgjM2F4tGEy4XnQWzNhe+0xZ8L4EmjKhPeVeDET9g+E+UwkPpdmMpH5ePyVidin9GsmkouFp0yE1yxTJuJLp+9MNKzg2ipPC8nE+LuMLwqlrYBVqy8VAAAAAElFTkSuQmCC";
h.appendChild(k);k=a();k.style.backgroundColor=E(f.a);k.className="psmob-logo-chooser-swap";h.onclick=v(this.Aa,this,f,g,k)}de(this,b)}};function de(a,b){b.style.visibility="hidden";document.body.appendChild(b);var c=2/3,d=window.innerWidth*c/b.offsetWidth,c=Math.round(.5*(1-c)*window.innerWidth)+"px",d="scale("+d+") translate("+c+","+c+")";b.style["-webkit-transform"]=d;b.style.transform=d;b.style.visibility="visible";null!=a.a&&a.a.parentNode.removeChild(a.a);a.a=b}
l.za=function(a){a=new Zc(a.c.b.src,a.a,a.b);be(this.c,a);document.getElementById("psmob-logo-span").addEventListener("click",v(this.ga,this));var b=document.createElement("PRE");b.className="psmob-logo-chooser-config-fragment";b.textContent='ModPagespeedMobTheme "\n    '+E(a.J)+"\n    "+E(a.B)+"\n    "+a.v+'"';de(this,b)};l.Aa=function(a,b,c){var d=a.a;a.a=a.b;a.b=d;d=b.style["background-color"];b.style["background-color"]=c.style["background-color"];c.style["background-color"]=d};U("initial-event");window.addEventListener("load",function(){U("load-event")});function Z(){this.s=0;this.i={};this.xa=Date.now();this.ca=!1;this.g=this.N=this.ea=this.a=this.c=0;this.I=!1;this.ba=this.K=0;this.o=new W(this);this.o.c["ps-progress-scrim"]=!0;this.b=-1;this.H=null;this.ia=[];this.l=[];this.f=null;this.wa=new Ed}var Bd=new Rc(-1,-1);function ee(a){0==a.g?(T("mobilizing site"),window.psNavMode&&!Wc()||fe(a)):a.I=!0}
Z.prototype.ya=function(a){--this.K;ge(this,this.c,"extract theme");this.f=new Yd;this.f.run(a);ge(this,this.c,"navigation");fe(this);var b=he().S;if(b&&0<=b.b){if(ie())be(this.f,a);else{var c=document.createElement("IFRAME");c.id="ps-hidden-iframe";c.hidden=!0;document.body.appendChild(c)}b.l.push(a);this.da(!0)}window.parent!=window&&(b="Theme:  "+R(a.J)+" "+R(a.B),a.v&&(b+=" "+a.v),a=document.location.origin.split("."),c=a.length,2<=c&&(a="http://"+a[c-2]+"."+a[c-1],window.parent.postMessage(b,
a),T("Post message ("+b+") to "+a)))};Z.prototype.ta=function(a){this.i[a.src]=new Rc(a.width,a.height);--this.g;ge(this,1E3,"background image");0==this.g&&this.I&&(ee(this),this.I=!1)};function je(a,b){if(!yd(a.o,b)){var c=Vc(b);if(c&&(y(c,"http://")||y(c,"https://"))&&!a.i[c]){a.i[c]=Bd;var d=new Image;++a.g;d.onload=v(a.ta,a,d);d.onerror=d.onload;d.src=c}for(c=b.firstElementChild;c;c=c.nextElementSibling)je(a,c)}}Z.prototype.xhrSendHook=function(){++this.s};
Z.prototype.xhrResponseHook=function(){--this.s;this.a+=this.ba;fe(this)};
Z.prototype.va=function(){ke(this,window.psDebugMode);this.c=Xc(document.body);this.ba=this.c*this.o.b.length;this.a+=this.ba;window.psNavMode&&Wc()&&(this.a+=this.c,this.a+=this.c);if(null!=document.body){for(var a in window.psMobStaticImageInfo){var b=window.psMobStaticImageInfo[a];this.i[a]=new Rc(b.w,b.h)}Boolean(window.psMobBackgroundColor&&window.psMobForegroundColor&&!window.psMobPrecompute)&&!window.psLayoutMode||je(this,document.body)}this.a+=1E3*this.g;window.psLayoutMode&&window.pagespeedXhrHijackSetListener(this);
ee(this)};function fe(a){if(0==a.s&&0==a.K&&0==a.g){if(window.psLayoutMode){var b=a.o;if(document.body)for(var c=0;c<b.b.length;++c){var d=b.b[c];d.a.call(b,document.body);var e=b.f;ge(e,e.c,d.b)}}if(a.ca){if(a=document.getElementById("ps-progress-remove"))a.textContent="Remove Progress Bar and show mobilized site"}else le()}}
function ke(a,b){a.ca=b;var c=document.getElementById("ps-progress-log");c&&(c.style.color=b?"#333":"white");b&&(c=document.getElementById("ps-progress-show-log"))&&(c.style.display="none")}function ge(a,b,c){a.N+=b;b=100;0<a.a&&(b=Math.round(100*a.N/a.a),100<b&&(b=100));if(b!=a.ea){var d=document.getElementById("ps-progress-span");d&&(d.style.width=b+"%");a.ea=b}a=""+b+"% "+(Date.now()-a.xa)+"ms: "+c;T(a);if(c=document.getElementById("ps-progress-log"))c.textContent+=a+"\n"}
function le(){var a=document.getElementById("ps-progress-scrim");a&&(a.style.display="none",a.parentNode.removeChild(a))}
Z.prototype.ua=function(){if(window.psNavMode){++this.K;if(!ie()&&window.document.body&&-1!=window.location.search.indexOf("PageSpeedSiteWideProcessing")){var a=[],b=window.location.search.indexOf("ModPagespeedMobIframe"),c=null;-1!=b&&(c=window.location.search.substring(b),(c=c.split("#")[0].split("&")[0])&&(c="?"+c));me(this,c,window.document.body,a);he().S.ia=a;if(b=prompt(a.length+' links have been found in this page. If you want to compute theme from them, enter the number of links below and press "OK". It may take a while to process them. Once processing completes, you will see another dialog.',
a.length.toString()))isFinite(b)&&(b=String(b)),b=t(b)?/^\s*-?0x/i.test(b)?parseInt(b,16):parseInt(b,10):NaN,this.b=0>b?0:b>a.length?a.length:b}a=this.wa;b=v(this.ya,this);window.psMobBackgroundColor&&window.psMobForegroundColor&&!window.psMobPrecompute?(a=Qd(window.psMobLogoUrl,window.psMobBackgroundColor,window.psMobForegroundColor),b(a)):(b=new Pd(b),a.run(v(b.b,b),1))}};window.S=new Z;ha("psSetDebugMode",function(){ke(window.S,!0)});ha("psRemoveProgressBar",function(){le()});
function ie(){return Wc()&&null!=window.frameElement&&"ps-hidden-iframe"==window.frameElement.id}function he(){return ie()?window.parent:window}
function ne(a){var b=he().S;if(b&&b.l&&0!=b.l.length){for(var c={},d,e=0;d=b.l[e];++e){var f=d.v;f&&(f=f+R(d.B)+R(d.J),c[f]?++c[f].count:c[f]={V:d,count:1})}b=va(c);b.sort(function(a,b){if(a.count<b.count)return 1;if(a.count>b.count)return-1;var c=a.V.v,d=b.V.v;return c<d?-1:c>d?1:0});c="\nFinish site-wide theme extraction. ";if(0<b.length){c+="Found "+b.length+" logo images. Details are shown below:\n";be(a.f,b[0].V);for(e in b)d=b[e].V,c+='"'+R(d.J)+" "+R(d.B)+" "+d.v+'" COUNT: '+b[e].count+"\n";
c+="\n";for(e in b)d=b[e].V,c+='ModPagespeedMobTheme "\n    '+E(d.J)+"\n    "+E(d.B)+"\n    "+d.v+'"\n'}else c+="No logo was found.";T(c+"\n")}}
Z.prototype.da=function(a){a||T("Time out.");a=he().S;var b=he();if(a){b.clearTimeout(a.H);a.H=null;var c=a.ia.pop();if(0<a.b&&c){T("Next URL is "+c+". "+a.b+" more to go.");var d=b.document.getElementById("ps-hidden-iframe");d&&(d.src=c,a.H=b.setTimeout(v(a.da,a),1E4));--a.b}else 0==a.b&&(ne(this),alert("All URLs have been processed. The header bar shows the best result. Details can be found in console log."),a.b=-1)}};
function me(a,b,c,d){if(!(100<=d.length)){var e=c.tagName.toUpperCase();if(("A"==e||"FORM"==e)&&(e=c.href)&&!cd(e)&&Ub(Sb(e)[5]||null).toLowerCase()!=window.location.pathname.toLowerCase()){if(b)var f=e.indexOf("?"),e=-1==f?e+b:e.substring(0,f)+b+"&"+e.substring(f+1);-1==d.indexOf(e)&&d.push(e)}for(c=c.firstElementChild;c;c=c.nextElementSibling)me(a,b,c,d)}}
ha("pagespeed.Mob.start",function(){var a=new Z;if(window.psConfigMode)(new ce).run();else{if(window.psMobBackgroundColor&&window.psMobForegroundColor){var b=new Zc(window.psMobLogoUrl,window.psMobForegroundColor,window.psMobBackgroundColor);a.f=new Yd;a.f.run(b)}else window.addEventListener("DOMContentLoaded",v(a.ua,a));window.psLayoutMode&&window.addEventListener("load",v(a.va,a))}});})();
