(function(){var l,p=this;function q(a){return void 0!==a}function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"string"==typeof a}function u(a){return"function"==ba(a)}var ca="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return v.apply(null,arguments)}var ga=Date.now||function(){return+new Date};
function ha(a,b){var c=a.split("."),d=p;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&q(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}}function w(a,b){function c(){}c.prototype=b.prototype;a.Ha=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.La=function(a,c,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function ia(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function ja(){}
function ka(a,b,c){switch(typeof b){case "string":la(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==ba(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),ka(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),la(e,c),c.push(":"),ka(a,f,c),d=
","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ma={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},na=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function la(a,b){b.push('"',a.replace(na,function(a){if(a in ma)return ma[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ma[a]=e+b.toString(16)}),'"')};function x(a){if(Error.captureStackTrace)Error.captureStackTrace(this,x);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(x,Error);x.prototype.name="CustomError";function oa(a,b){this.width=a;this.height=b}l=oa.prototype;l.clone=function(){return new oa(this.width,this.height)};l.toString=function(){return"("+this.width+" x "+this.height+")"};l.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};l.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};l.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function pa(a){this.a=a}var qa=/\s*;\s*/;function ra(a,b,c,d,e,f){if(/[;=\s]/.test(b))throw Error('Invalid cookie name "'+b+'"');if(/[;\r\n]/.test(c))throw Error('Invalid cookie value "'+c+'"');q(d)||(d=-1);f=f?";domain="+f:"";e=e?";path="+e:"";d=0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(ga()+1E3*d)).toUTCString();a.a.cookie=b+"="+c+f+e+d+""}
function sa(a,b){for(var c=b+"=",d=(a.a.cookie||"").split(qa),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==b)return""}}pa.prototype.remove=function(a,b,c){var d=q(sa(this,a));ra(this,a,"",0,b,c);return d};pa.prototype.O=function(){return ta(this).keys};pa.prototype.u=function(){return ta(this).values};pa.prototype.clear=function(){for(var a=ta(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
function ta(a){a=(a.a.cookie||"").split(qa);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};function y(a,b){return 0==a.lastIndexOf(b,0)}function ua(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var va=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function wa(a,b){return a<b?-1:a>b?1:0};var z;a:{var xa=p.navigator;if(xa){var ya=xa.userAgent;if(ya){z=ya;break a}}z=""}function A(a){return-1!=z.indexOf(a)};function za(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Aa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ba(a){var b=arguments.length;if(1==b&&"array"==ba(arguments[0]))return Ba.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};function Ca(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function Da(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var B=Array.prototype,Ea=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Fa=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ga=B.filter?function(a,b,c){return B.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?
a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e},Ha=B.some?function(a,b,c){return B.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function Ia(a){return B.concat.apply(B,arguments)};function Ja(a){if("function"==typeof a.u)return a.u();if(t(a))return a.split("");var b=ba(a);if("array"==b||"object"==b&&"number"==typeof a.length){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Aa(a)};function Ka(){return A("Opera")||A("OPR")}function La(){return A("Android")&&!((A("Chrome")||A("CriOS"))&&!Ka()||A("Firefox")||Ka()||A("Silk"))};function Ma(){this.b=this.a=null}var C=new function(a,b){this.f=100;this.c=a;this.g=b;this.b=0;this.a=null}(function(){return new Na},function(a){a.reset()});Ma.prototype.add=function(a,b){var c;0<C.b?(C.b--,c=C.a,C.a=c.next,c.next=null):c=C.c();c.a=a;c.b=b;c.next=null;this.b?this.b.next=c:this.a=c;this.b=c};Ma.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};function Na(){this.next=this.b=this.a=null}
Na.prototype.reset=function(){this.next=this.b=this.a=null};function Oa(a){p.setTimeout(function(){throw a;},0)}var Qa;
function Ra(){var a=p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=v(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!A("Trident")&&!A("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(q(c.next)){c=c.next;var a=c.fa;c.fa=null;a()}};return function(a){d.next={fa:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){p.setTimeout(a,0)}};function Sa(a,b){Ta||Ua();Va||(Ta(),Va=!0);Wa.add(a,b)}var Ta;function Ua(){if(p.Promise&&p.Promise.resolve){var a=p.Promise.resolve();Ta=function(){a.then(Xa)}}else Ta=function(){var a=Xa;!u(p.setImmediate)||p.Window&&p.Window.prototype&&p.Window.prototype.setImmediate==p.setImmediate?(Qa||(Qa=Ra()),Qa(a)):p.setImmediate(a)}}var Va=!1,Wa=new Ma;function Xa(){for(var a=null;a=Wa.remove();){try{a.a.call(a.b)}catch(b){Oa(b)}var c=C;c.g(a);c.b<c.f&&(c.b++,a.next=c.a,c.a=a)}Va=!1};function D(a){var b=a[0],c=a[1];a=a[2];b=Number(b);c=Number(c);a=Number(a);if(isNaN(b)||0>b||255<b||isNaN(c)||0>c||255<c||isNaN(a)||0>a||255<a)throw Error('"('+b+","+c+","+a+'") is not a valid RGB color');b=Ya(b.toString(16));c=Ya(c.toString(16));a=Ya(a.toString(16));return"#"+b+c+a}function Ya(a){return 1==a.length?"0"+a:a}
function Za(a,b,c){var d=0,e=0,f=0;if(0==b)f=e=d=c;else{var g=Math.floor(a/60),h=a/60-g;a=c*(1-b);var k=c*(1-b*h);b=c*(1-b*(1-h));switch(g){case 1:d=k;e=c;f=a;break;case 2:d=a;e=c;f=b;break;case 3:d=a;e=k;f=c;break;case 4:d=b;e=a;f=c;break;case 5:d=c;e=a;f=k;break;case 6:case 0:d=c,e=b,f=a}}return[Math.floor(d),Math.floor(e),Math.floor(f)]}
function $a(a,b,c){var d=Math.max(Math.max(a,b),c),e=Math.min(Math.min(a,b),c);if(e==d)e=a=0;else{var f=d-e,e=f/d;a=60*(a==d?(b-c)/f:b==d?2+(c-a)/f:4+(a-b)/f);0>a&&(a+=360);360<a&&(a-=360)}return[a,e,d]};function ab(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)bb(this,arguments[d],arguments[d+1])}else if(a){if(a instanceof ab)d=a.O(),c=a.u();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=Aa(a)}for(e=0;e<d.length;e++)bb(this,d[e],c[e])}}l=ab.prototype;l.u=function(){cb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};l.O=function(){cb(this);return this.a.concat()};
l.clear=function(){this.b={};this.f=this.c=this.a.length=0};l.remove=function(a){return E(this.b,a)?(delete this.b[a],this.c--,this.f++,this.a.length>2*this.c&&cb(this),!0):!1};function cb(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];E(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],E(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}function db(a,b){return E(a.b,b)?a.b[b]:void 0}
function bb(a,b,c){E(a.b,b)||(a.c++,a.a.push(b),a.f++);a.b[b]=c}l.forEach=function(a,b){for(var c=this.O(),d=0;d<c.length;d++){var e=c[d];a.call(b,db(this,e),e,this)}};l.clone=function(){return new ab(this)};function E(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function eb(a){this.a=new ab;if(a){a=Ja(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}}function fb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ca]||(a[ca]=++da)):b.substr(0,1)+a}l=eb.prototype;l.add=function(a){bb(this.a,fb(a),a)};l.remove=function(a){return this.a.remove(fb(a))};l.clear=function(){this.a.clear()};l.contains=function(a){a=fb(a);return E(this.a.b,a)};l.u=function(){return this.a.u()};l.clone=function(){return new eb(this)};function gb(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}l=gb.prototype;l.clone=function(){return new gb(this.top,this.right,this.bottom,this.left)};l.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};l.contains=function(a){return this&&a?a instanceof gb?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
l.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};l.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};l.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};var hb=Ka(),F=A("Trident")||A("MSIE"),ib=A("Gecko")&&-1==z.toLowerCase().indexOf("webkit")&&!(A("Trident")||A("MSIE")),jb=-1!=z.toLowerCase().indexOf("webkit"),kb=jb&&A("Mobile");function lb(){var a=p.document;return a?a.documentMode:void 0}var mb=function(){var a="",b;if(hb&&p.opera)return a=p.opera.version,u(a)?a():a;ib?b=/rv\:([^\);]+)(\)|;)/:F?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:jb&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(z))?a[1]:"");return F&&(b=lb(),b>parseFloat(a))?String(b):a}(),nb={};
function ob(a){var b;if(!(b=nb[a])){b=0;for(var c=va(String(mb)).split("."),d=va(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",k=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var n=k.exec(g)||["","",""],r=m.exec(h)||["","",""];if(0==n[0].length&&0==r[0].length)break;b=wa(0==n[1].length?0:parseInt(n[1],10),0==r[1].length?0:parseInt(r[1],10))||wa(0==n[2].length,0==r[2].length)||wa(n[2],r[2])}while(0==b)}b=nb[a]=0<=b}return b}
var pb=p.document,qb=pb&&F?lb()||("CSS1Compat"==pb.compatMode?parseInt(mb,10):5):void 0;function G(a,b){this.b=H;this.i=void 0;this.a=this.c=null;this.f=this.g=!1;if(a==rb)I(this,sb,b);else try{var c=this;a.call(b,function(a){I(c,sb,a)},function(a){if(!(a instanceof tb))try{if(a instanceof Error)throw a;throw Error("Promise rejected.");}catch(b){}I(c,J,a)})}catch(d){I(this,J,d)}}var H=0,sb=2,J=3;function rb(){}G.prototype.then=function(a,b,c){return ub(this,u(a)?a:null,u(b)?b:null,c)};Ca(G);G.prototype.cancel=function(a){this.b==H&&Sa(function(){var b=new tb(a);vb(this,b)},this)};
function vb(a,b){if(a.b==H)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,g;g=c.a[f];f++)if(g=g.L)if(d++,g==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.b==H&&1==d?vb(c,b):(d=c.a.splice(e,1)[0],wb(c,d,J,b)))}a.c=null}else I(a,J,b)}function xb(a,b){a.a&&a.a.length||a.b!=sb&&a.b!=J||yb(a);a.a||(a.a=[]);a.a.push(b)}
function ub(a,b,c,d){var e={L:null,ma:null,na:null};e.L=new G(function(a,g){e.ma=b?function(c){try{var e=b.call(d,c);a(e)}catch(m){g(m)}}:a;e.na=c?function(b){try{var e=c.call(d,b);!q(e)&&b instanceof tb?g(b):a(e)}catch(m){g(m)}}:g});e.L.c=a;xb(a,e);return e.L}G.prototype.l=function(a){this.b=H;I(this,sb,a)};G.prototype.o=function(a){this.b=H;I(this,J,a)};
function I(a,b,c){if(a.b==H){if(a==c)b=J,c=new TypeError("Promise cannot resolve to itself");else{if(Da(c)){a.b=1;c.then(a.l,a.o,a);return}var d=typeof c;if("object"==d&&null!=c||"function"==d)try{var e=c.then;if(u(e)){zb(a,c,e);return}}catch(f){b=J,c=f}}a.i=c;a.b=b;a.c=null;yb(a);b!=J||c instanceof tb||Ab(a,c)}}function zb(a,b,c){function d(b){f||(f=!0,a.o(b))}function e(b){f||(f=!0,a.l(b))}a.b=1;var f=!1;try{c.call(b,e,d)}catch(g){d(g)}}function yb(a){a.g||(a.g=!0,Sa(a.s,a))}
G.prototype.s=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=null;for(var b=0;b<a.length;b++)wb(this,a[b],this.b,this.i)}this.g=!1};function wb(a,b,c,d){b.L&&(b.L.c=null);if(c==sb)b.ma(d);else{if(b.L)for(;a&&a.f;a=a.c)a.f=!1;b.na(d)}}function Ab(a,b){a.f=!0;Sa(function(){a.f&&Bb.call(null,b)})}var Bb=Oa;function tb(a){x.call(this,a)}w(tb,x);tb.prototype.name="cancel";/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function K(a,b){this.g=[];this.J=a;this.I=b||null;this.f=this.a=!1;this.c=void 0;this.s=this.N=this.l=!1;this.i=0;this.b=null;this.o=0}K.prototype.cancel=function(a){if(this.a)this.c instanceof K&&this.c.cancel();else{if(this.b){var b=this.b;delete this.b;a?b.cancel(a):(b.o--,0>=b.o&&b.cancel())}this.J?this.J.call(this.I,this):this.s=!0;this.a||(a=new Cb,Db(this),Eb(this,!1,a))}};K.prototype.H=function(a,b){this.l=!1;Eb(this,a,b)};function Eb(a,b,c){a.a=!0;a.c=c;a.f=!b;Fb(a)}
function Db(a){if(a.a){if(!a.s)throw new Gb;a.s=!1}}function Hb(a,b,c,d){a.g.push([b,c,d]);a.a&&Fb(a)}K.prototype.then=function(a,b,c){var d,e,f=new G(function(a,b){d=a;e=b});Hb(this,d,function(a){a instanceof Cb?f.cancel():e(a)});return f.then(a,b,c)};Ca(K);function Ib(a){return Ha(a.g,function(a){return u(a[1])})}
function Fb(a){if(a.i&&a.a&&Ib(a)){var b=a.i,c=Jb[b];c&&(p.clearTimeout(c.G),delete Jb[b]);a.i=0}a.b&&(a.b.o--,delete a.b);for(var b=a.c,d=c=!1;a.g.length&&!a.l;){var e=a.g.shift(),f=e[0],g=e[1],e=e[2];if(f=a.f?g:f)try{var h=f.call(e||a.I,b);q(h)&&(a.f=a.f&&(h==b||h instanceof Error),a.c=b=h);Da(b)&&(d=!0,a.l=!0)}catch(k){b=k,a.f=!0,Ib(a)||(c=!0)}}a.c=b;d&&(h=v(a.H,a,!0),d=v(a.H,a,!1),b instanceof K?(Hb(b,h,d),b.N=!0):b.then(h,d));c&&(b=new Kb(b),Jb[b.G]=b,a.i=b.G)}function Gb(){x.call(this)}
w(Gb,x);Gb.prototype.message="Deferred has already fired";Gb.prototype.name="AlreadyCalledError";function Cb(){x.call(this)}w(Cb,x);Cb.prototype.message="Deferred was canceled";Cb.prototype.name="CanceledError";function Kb(a){this.G=p.setTimeout(v(this.b,this),0);this.a=a}Kb.prototype.b=function(){delete Jb[this.G];throw this.a;};var Jb={};function Lb(a){if(a.classList)return a.classList;a=a.className;return t(a)&&a.match(/\S+/g)||[]}function L(a,b){var c;a.classList?c=a.classList.contains(b):(c=Lb(a),c=0<=Ea(c,b));return c}function M(a,b){a.classList?a.classList.add(b):L(a,b)||(a.className+=0<a.className.length?" "+b:b)}function Mb(a,b){a.classList?a.classList.remove(b):L(a,b)&&(a.className=Ga(Lb(a),function(a){return a!=b}).join(" "))}function Nb(a,b){L(a,b)?Mb(a,b):M(a,b)};var Ob;if(!(Ob=!ib&&!F)){var Pb;if(Pb=F)Pb=F&&9<=qb;Ob=Pb}var Qb=Ob||ib&&ob("1.9.1");F&&ob("9");Ba("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));function Rb(a){var b=document;return t(a)?b.getElementById(a):a}function Sb(a,b){za(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Tb?a.setAttribute(Tb[d],b):y(d,"aria-")||y(d,"data-")?a.setAttribute(d,b):a[d]=b})}var Tb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Ub(a){return Qb&&void 0!=a.children?a.children:Ga(a.childNodes,function(a){return 1==a.nodeType})}function Vb(a){return window.matchMedia("(-webkit-min-device-pixel-ratio: "+a+"),(min--moz-device-pixel-ratio: "+a+"),(min-resolution: "+a+"dppx)").matches?a:0};function Wb(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}F&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}function Xb(a){"number"==typeof a&&(a=Math.round(a)+"px");return a}
function Yb(a){if(!a.getBoundingClientRect)return null;var b;b:{b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue("display")||"";break b}b=""}if("none"!=(b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display))a=Wb(a);else{b=a.style;var c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Wb(a);b.display=c;
b.position=e;b.visibility=d}return new oa(a.right-a.left,a.bottom-a.top)};function Zb(a,b){var c=b||{},d=c.document||document,e=document.createElement("SCRIPT"),f={qa:e,aa:void 0},g=new K($b,f),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){ac(e,!0);var b=new bc(cc,"Timeout reached for loading script "+a);Db(g);Eb(g,!1,b)},k),f.aa=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(ac(e,c.Ca||!1,h),Db(g),Eb(g,!0,null))};e.onerror=function(){ac(e,!0,h);var b=new bc(dc,"Error while loading script "+
a);Db(g);Eb(g,!1,b)};Sb(e,{type:"text/javascript",charset:"UTF-8",src:a});ec(d).appendChild(e);return g}function ec(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}function $b(){if(this&&this.qa){var a=this.qa;a&&"SCRIPT"==a.tagName&&ac(a,!0,this.aa)}}function ac(a,b,c){null!=c&&p.clearTimeout(c);a.onload=aa;a.onerror=aa;a.onreadystatechange=aa;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var dc=0,cc=1;
function bc(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);x.call(this,c)}w(bc,x);var fc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function gc(a){if(hc){hc=!1;var b=p.location;if(b){var c=b.href;if(c&&(c=ic(gc(c)[3]||null))&&c!=b.hostname)throw hc=!0,Error();}}return a.match(fc)}var hc=jb;function ic(a){return a?decodeURI(a):a}
function jc(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g," ")):"")}};function kc(a,b){var c;a instanceof kc?(this.M=q(b)?b:a.M,lc(this,a.R),this.ba=a.ba,this.D=a.D,mc(this,a.$),this.Z=a.Z,nc(this,a.a.clone()),this.Y=a.Y):a&&(c=gc(String(a)))?(this.M=!!b,lc(this,c[1]||"",!0),this.ba=oc(c[2]||""),this.D=oc(c[3]||"",!0),mc(this,c[4]),this.Z=oc(c[5]||"",!0),nc(this,c[6]||"",!0),this.Y=oc(c[7]||"")):(this.M=!!b,this.a=new pc(null,0,this.M))}l=kc.prototype;l.R="";l.ba="";l.D="";l.$=null;l.Z="";l.Y="";l.M=!1;
l.toString=function(){var a=[],b=this.R;b&&a.push(qc(b,rc,!0),":");if(b=this.D){a.push("//");var c=this.ba;c&&a.push(qc(c,rc,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.$;null!=b&&a.push(":",String(b))}if(b=this.Z)this.D&&"/"!=b.charAt(0)&&a.push("/"),a.push(qc(b,"/"==b.charAt(0)?sc:tc,!0));(b=this.a.toString())&&a.push("?",b);(b=this.Y)&&a.push("#",qc(b,uc));return a.join("")};l.clone=function(){return new kc(this)};
function lc(a,b,c){a.R=c?oc(b,!0):b;a.R&&(a.R=a.R.replace(/:$/,""))}function vc(a){return a.D}function mc(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.$=b}else a.$=null}function nc(a,b,c){b instanceof pc?(a.a=b,wc(a.a,a.M)):(c||(b=qc(b,xc)),a.a=new pc(b,0,a.M))}function yc(a,b,c){"array"==ba(c)||(c=[String(c)]);zc(a.a,b,c)}function oc(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}
function qc(a,b,c){return t(a)?(a=encodeURI(a).replace(b,Ac),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Ac(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var rc=/[#\/\?@]/g,tc=/[\#\?:]/g,sc=/[\#\?]/g,xc=/[\#\?@]/g,uc=/#/g;function pc(a,b,c){this.a=a||null;this.b=!!c}function Bc(a){a.m||(a.m=new ab,a.F=0,a.a&&jc(a.a,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}l=pc.prototype;l.m=null;l.F=null;
l.add=function(a,b){Bc(this);this.a=null;a=Cc(this,a);var c=db(this.m,a);c||bb(this.m,a,c=[]);c.push(b);this.F++;return this};l.remove=function(a){Bc(this);a=Cc(this,a);return E(this.m.b,a)?(this.a=null,this.F-=db(this.m,a).length,this.m.remove(a)):!1};l.clear=function(){this.m=this.a=null;this.F=0};l.O=function(){Bc(this);for(var a=this.m.u(),b=this.m.O(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
l.u=function(a){Bc(this);var b=[];if(t(a)){var c=a;Bc(this);c=Cc(this,c);E(this.m.b,c)&&(b=Ia(b,db(this.m,Cc(this,a))))}else for(a=this.m.u(),c=0;c<a.length;c++)b=Ia(b,a[c]);return b};function zc(a,b,c){a.remove(b);if(0<c.length){a.a=null;var d=a.m;b=Cc(a,b);var e;e=c.length;if(0<e){for(var f=Array(e),g=0;g<e;g++)f[g]=c[g];e=f}else e=[];bb(d,b,e);a.F+=c.length}}
l.toString=function(){if(this.a)return this.a;if(!this.m)return"";for(var a=[],b=this.m.O(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.u(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.a=a.join("&")};l.clone=function(){var a=new pc;a.a=this.a;this.m&&(a.m=this.m.clone(),a.F=this.F);return a};function Cc(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c}
function wc(a,b){b&&!a.b&&(Bc(a),a.a=null,a.m.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),zc(this,e,a))},a));a.b=b};function Dc(a,b){this.b=new kc(a);this.a=b?b:"callback";this.aa=5E3}var Ec=0;Dc.prototype.send=function(a,b,c,d){a=a||null;d=d||"_"+(Ec++).toString(36)+ga().toString(36);p._callbacks_||(p._callbacks_={});var e=this.b.clone();if(a)for(var f in a)a.hasOwnProperty&&!a.hasOwnProperty(f)||yc(e,f,a[f]);b&&(p._callbacks_[d]=Fc(d,b),yc(e,this.a,"_callbacks_."+d));b=Zb(e.toString(),{timeout:this.aa,Ca:!0});Hb(b,null,Gc(d,a,c),void 0);return{G:d,ja:b}};
Dc.prototype.cancel=function(a){a&&(a.ja&&a.ja.cancel(),a.G&&Hc(a.G,!1))};function Gc(a,b,c){return function(){Hc(a,!1);c&&c(b)}}function Fc(a,b){return function(c){Hc(a,!0);b.apply(void 0,arguments)}}function Hc(a,b){p._callbacks_[a]&&(b?delete p._callbacks_[a]:p._callbacks_[a]=aa)};var Ic="border-bottom-width border-left-width border-right-width border-top-width left margin-bottom margin-left margin-right margin-top padding-bottom padding-left padding-right padding-top top".split(" "),Jc="border-left border-right margin-left margin-right padding-left padding-right".split(" "),Kc=["padding-left","padding-right"],Lc={A:!0,DIV:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,P:!0,SPAN:!0,TBODY:!0,TD:!0,TFOOT:!0,TH:!0,THEAD:!0,TR:!0},Mc={SCRIPT:!0,STYLE:!0,IFRAME:!0},Nc=["left","width"],Oc=["CODE",
"PRE","UL"];function Pc(){this.height=this.width=this.bottom=this.right=this.left=this.top=0}function Qc(a,b){this.width=a;this.height=b}function N(a){var b=null;if(a&&"string"==typeof a){var c=a.indexOf("px");-1!=c&&(a=a.substring(0,c));c=a.length-1;a.length<=c?c=!1:(c=a.charCodeAt(c),c=48<=c&&57>=c);c&&(b=parseInt(a,10),isNaN(b)&&(b=null))}return b}function O(a,b){var c=null;a&&(c=N(a.getPropertyValue(b)));return c}function P(a,b){a.style&&a.style.removeProperty(b);a.removeAttribute(b)}
function Rc(a,b){var c=null;a.style&&(c=N(a.style.getPropertyValue(b)));null==c&&(c=N(a.getAttribute(b)));return c}function Q(a,b,c){a.style.setProperty(b,c,"important")}function Sc(a,b){if(b&&0!=b.length){var c=a.getAttribute("style")||"";0<c.length&&";"!=c[c.length-1]&&(c+=";");a.setAttribute("style",c+b)}}
function Tc(a){a=a.getBoundingClientRect();var b=document.body,c=document.documentElement||b.parentNode||b,b="pageXOffset"in window?window.pageXOffset:c.scrollLeft,c="pageYOffset"in window?window.pageYOffset:c.scrollTop;return new gb(a.top+c,a.right+b,a.bottom+c,a.left+b)}
function Uc(a){var b=null,b=a.nodeName.toUpperCase();return"SCRIPT"!=b&&"STYLE"!=b&&a.style&&(a=window.getComputedStyle(a))&&(b=a.getPropertyValue("background-image"),"none"==b&&(b=null),b&&5<b.length&&0==b.indexOf("url(")&&")"==b[b.length-1])?b=b.substring(4,b.length-1):null}function Vc(){if(null!=window.parent&&window!=window.parent)try{if(window.parent.document.domain==document.domain)return!0}catch(a){}return!1}
function Wc(a){if(!a)return 0;var b=1;for(a=a.firstChild;a;a=a.nextSibling)b+=Wc(a);return b}var Xc={Ja:"IMG",Ka:"SVG",Ia:"background-image"};ha("pagespeed.MobUtil.ImageSource",Xc);function Yc(a,b,c){this.B=a;this.C=b;this.K=c}function R(a){for(var b=0,c=a.length;b<c;++b){var d=Math.round(a[b]);0>d?d=0:255<d&&(d=255);a[b]=d}return D(a)}function Zc(a){a=a.toLowerCase();for(var b="",c=0,d=a.length;c<d;++c){var e=a.charAt(c);if("a"<=e&&"z">=e||"0"<=e&&"9">=e)b+=e}return b}
function $c(a){if(!a||0<=a.indexOf("data:image/"))return"";var b=a.lastIndexOf("/");0>b?b=0:++b;var c=a.indexOf(".",b);0>c&&(c=a.length);return a.substring(b,c)}function ad(a,b){var c=window.atob(a);return"data:image/gif;base64,"+window.btoa(c.substring(0,13)+String.fromCharCode(b[0],b[1],b[2])+c.substring(16,c.length))}function bd(a){return!y(a,document.location.origin+"/")&&!y(a,"data:image/")}
function cd(a){a=Tc(a);var b=new Pc;b.top=a.top;b.bottom=a.bottom;b.left=a.left;b.right=a.right;b.height=a.bottom-a.top;b.width=a.right-a.left;return b}function dd(a){var b=N(a.top);a=N(a.left);return null!=b&&-100>b||null!=a&&-100>a}function S(a){window.psDebugMode&&console&&console.log&&console.log(a)}
function U(a,b,c){!window.psMobBeaconUrl&&b?b():(a=window.psMobBeaconUrl+"?id=psmob&url="+encodeURIComponent(document.URL)+"&el="+a,c&&(a+=c),c=document.createElement("IMG"),c.src=a,b&&(b=ed(b),c.addEventListener("load",b),c.addEventListener("error",b),window.setTimeout(b,500)))}function ed(a){var b=!1;return function(){b||(b=!0,a())}}
function fd(){var a=.1;"desktop"!=window.psDeviceType&&(a=90==Math.abs(window.orientation)&&screen.height>screen.width?window.innerHeight/screen.width*a:window.innerWidth/screen.width*a);if(La()){var b;b=window;var c=ib&&kb;b=q(b.devicePixelRatio)&&!c?b.devicePixelRatio:b.matchMedia?Vb(.75)||Vb(1.5)||Vb(2)||Vb(3)||1:1;a=a*b}return a};function V(a,b,c,d){this.a=document.createElement("A");this.G=a;this.S=b;this.N=c;this.H=d;this.i()}V.prototype.i=function(){this.a.id=this.G;M(this.a,"psmob-button");this.a.onclick=v(this.g,this);var a=document.createElement("DIV");M(a,"psmob-button-icon");a.style.backgroundImage="url("+ad(this.S,this.N)+")";this.a.appendChild(a);this.H&&(a=document.createElement("P"),M(a,"psmob-button-text"),this.a.appendChild(a),a.appendChild(document.createTextNode(this.H)))};
function gd(a,b){this.b=b;V.call(this,"psmob-menu-button","R0lGODlhYABgAPAAAAAAAAAAACH5BAEAAAEALAAAAABgAGAAAAK6jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8agCKJfMpvMJjUqnTg71is1qldat97vtgsfkp7iMJp/T7PCmDXdr4vQr8o7P6/f8vv8PGCg4SHhTdxi1hriouHjY6EgHGQk3SclmeYmWqalW+AkaKjpKWmp6ipqqatH5+NYq+QpbKTuLWWu7iZvrOcebxvlrt0pcbHyMnKy8zNzs/AwdLT1NXW19TVoAADs=",a,null)}w(gd,V);gd.prototype.g=function(){this.b()};
function hd(a,b,c,d){this.f=b;this.b=c;this.c=d;V.call(this,"psmob-map-button","R0lGODlhYABgAPAAAAAAAAAAACH5BAEAAAEAIf8LSW1hZ2VNYWdpY2sHZ2FtbWE9MQAsAAAAAGAAYAAAAv6Mj6nL7Q+jnLTai7PevPsPhuJIluaJpuo6Au4Ls3IA1/Y7l/fO5x8P7Pk0weJteDEqj0jJ8llrQqBUnJRRzQKuCq2We/B6wWIxtzyWos3IdbntTufi7zldLmMj9Cx895tX5SQYCEVB2Ed1qJhoWIGYAjnoqMJoYRlJ+aiJgrn41LiE4XlCOim6YhqhSiK5ytoCiyUr4upgW0q7pxuSdQpaiGvgV0nMF3rHW5vs68OsHPuM6iw9TV0dpIadrb3N1O0ddRYeQ0ZuZU4OFna+zu7t/r4dLy9NX/98j3+nv8vc7y8ZwIBxBhJ0Y/BgnYT7ADFs2OwhRE4SaRyrOMwhRjeF1jZOBOJxFrCQf0aSTGDyJEojKm9xa9kAJEyXO2Y+qGnzpricOl3wHPQzqNChRIsaPYo0acUCADs=",a,
"GET DIRECTIONS")}w(hd,V);hd.prototype.g=function(){U("psmob-map-button",v(this.l,this))};function id(a){return"https://maps.google.com/maps?q="+encodeURIComponent(a.f)}hd.prototype.l=function(){if(this.b&&this.c){var a=new Image;a.onload=v(function(){p.location=id(this)},this);a.onerror=a.onload;a.src="//www.googleadservices.com/pagead/conversion/"+this.b+"/?label="+this.c+"&amp;guid=ON&amp;script=0"}else p.location=id(this)};
function W(a,b,c,d){this.b=b;this.f=null;this.I=c;this.c=d;this.o=new pa(document);this.s=null;V.call(this,"psmob-dialer-button","R0lGODlhYABgAPAAAAAAAAAAACH5BAEAAAEAIf8LSW1hZ2VNYWdpY2sHZ2FtbWE9MQAsAAAAAGAAYAAAAv6Mj6nL7Q+jnLTai7PevPsPhuJIluaJpurKtu4Lx/KsAvaN5zcd6r7P8/yGuSCHiAQYN0niUtMcPjPR3xRTBV4tWd2W28V9K2HxeFI2nyNp21rSVr4h8Tm9bX/E5fnFvt9QB+iHN6ggaIiAmHiQxngY9giZJTkZVUnYhJmJtMmQ5PnpFMrpRSqqdWpZpFqq1tpoBZsgNRsraxtQmzvKu2v7O9sLHAw7bHzc2ulbrLpM3IzGegV6UW10Le0Ik3232KLp/cfdvfoNHm5+7pJ+u7dDc2nwbhpPv81zX/akT8nf324JwGdTBkbDZnDamITw3jDsY9BQP0b3MK171IVZqhBcHDt6/AgypMiRJEuaDFUAADs=",
a,"CALL US")}w(W,V);W.prototype.i=function(){W.Ha.i.call(this);var a;a:if(this.c){if(a=sa(this.o,"psgwcm"))if(a=ia(window.decodeURIComponent(a)),a.fallback==this.b&&a.clabel==this.c){a=a.mobile_number;break a}a=null}else a=this.b;this.f=a};
W.prototype.g=function(){if(this.f)U("psmob-phone-dialer",v(this.l,this));else{U("psmob-phone-dialer");var a;this.c&&this.I?(a=window.encodeURIComponent(this.c),a="https://www.googleadservices.com/pagead/conversion/"+window.encodeURIComponent(this.I)+"/wcm?cl="+a+"&fb="+window.encodeURIComponent(this.b)):a=null;a?(window.psDebugMode&&window.alert("requesting dynamic phone number: "+a),a=new Dc(a),this.s=Date.now(),a.send(null,v(this.J,this),v(this.J,this))):this.l()}};
W.prototype.l=function(){p.location="tel:"+(this.f||this.b)};W.prototype.J=function(a){U("call-conversion-response",null,"&t="+(Date.now()-this.s));var b=a&&a.wcm;if(a=b&&b.mobile_number){var b={expires:b.expires,formatted_number:b.formatted_number,mobile_number:a,clabel:this.c,fallback:this.b},c=[];ka(new ja,b,c);b=c.join("");window.psDebugMode&&window.alert("saving phoneNumber in cookie: "+b);ra(this.o,"psgwcm",window.encodeURIComponent(b),7776E3,"/");this.f=a}this.l()};function jd(){}function kd(a,b){this.a=a;this.b=b}function ld(a,b){if(3!=a.length||3!=b.length)return Infinity;var c=a[0]-b[0],d=a[1]-b[1],e=a[2]-b[2];return Math.sqrt(c*c+d*d+e*e)}function md(a){a/=255;return a=.03928>=a?a/12.92:Math.pow((a+.055)/1.055,2.4)}
function nd(a){var b=a.a,c=a.b,d=.2126*md(b[0])+.7152*md(b[1])+.0722*md(b[2]),e=.2126*md(c[0])+.7152*md(c[1])+.0722*md(c[2]);if(1E-10>d&&1E-10>e)return a;d=e/d;1>d&&(d=1/d);if(3<d)return a;b=$a(b[0],b[1],b[2]);c=$a(c[0],c[1],c[2]);d=a=null;b[2]<c[2]?(a=b[2],d=c[2]):(a=c[2],d=b[2]);e=(3*a-d)/4;a=a>e?a-e:0;d=d<1-2*e?d+2*e:255;b[2]<c[2]?(b[2]=a,c[2]=d):(c[2]=a,b[2]=d);b=Za(b[0],b[1],b[2]);c=Za(c[0],c[1],c[2]);return new kd(b,c)}
function od(a,b,c,d){var e=[],f,g,h;for(g=0;g<d;++g)for(f=0;f<c;++f){var k=4*(g*c+f);h=3*(g*c+f);var m=a[k+3]/255,n=1-m;e[h]=m*a[k]+n*b[0];e[h+1]=m*a[k+1]+n*b[1];e[h+2]=m*a[k+2]+n*b[2]}k=[0,0,0];for(f=m=g=0;f<c;++f)n=(d-1)*c+f,h=3*n,k[0]+=e[h],k[1]+=e[h+1],k[2]+=e[h+2],m+=a[4*n+3],++g;if(m>127.5*g)for(f=0;3>f;++f)k[f]=Math.floor(k[f]/g);else k=b;a=Math.floor(.25*c);b=Math.floor(.75*c);m=Math.floor(.25*d);d=Math.floor(.75*d);var n=0,r=[];for(g=m;g<=d;++g)for(f=a;f<=b;++f)h=3*(g*c+f),r[n]=ld(e.slice(h,
h+3),k),++n;f=r.sort(function(a,b){return a-b});var Pa=Math.max(1,f[Math.floor(.75*n)]),n=0,r=[0,0,0];for(g=m;g<=d;++g)for(f=a;f<=b;++f)h=3*(g*c+f),ld(e.slice(h,h+3),k)>=Pa&&(r[0]+=e[h],r[1]+=e[h+1],r[2]+=e[h+2],++n);if(0<n)for(f=0;3>f;++f)r[f]=Math.floor(r[f]/n);return nd(new kd(k,r))}
jd.prototype.run=function(a,b){if(a)if(bd(a.src))S("Found logo but its origin is different from that of HTML. Using default color.");else{S("Found logo. Theme color will be computed from logo.");var c=b||[255,255,255],d=a.naturalWidth,e=a.naturalHeight,f=document.createElement("CANVAS");f.width=d;f.height=e;f=f.getContext("2d");f.drawImage(a,0,0);f=f.getImageData(0,0,d,e);return od(f.data,c,d,e)}else S("Did not find logo. Using default color.");c=[0,0,0];b?178.5>=$a(b[0],b[1],b[2])[2]&&(c=[255,255,
255]):b=[255,255,255];return new kd(b,c)};function pd(){}pd.prototype.run=function(){var a=document.createElement("DIV");document.body.appendChild(a);a.id="psmob-iframe-container";a.appendChild(Rb("psmob-spacer"));a.appendChild(Rb("psmob-iframe"))};function qd(){var a=window.document.documentElement.clientWidth;if(!a)return 400;var b=window.document.body;if(b){var c=window.getComputedStyle(b);Fa(Kc,function(b){(b=O(c,b))&&(a-=b)})}return a}function rd(a){Q(a,"overflow-x","auto");Q(a,"width","auto");Q(a,"display","block")}function sd(a){var b=0,c=a.tagName.toUpperCase();"DIV"!=c&&"TABLE"!=c&&"UL"!=c||++b;for(a=a.firstElementChild;a;a=a.nextElementSibling)b+=sd(a);return b}
function td(a){var b=[],c=a.tagName.toUpperCase();if("SCRIPT"==c||"STYLE"==c||!a.style)return b;a=window.getComputedStyle(a);if(!a)return b;a=a.getPropertyValue("background-image");if(!a||"none"==a)return b;if(-1!=a.indexOf("'")||-1!=a.indexOf('"'))return null;a=a.split(",");for(c=0;c<a.length;++c){var d=va(a[c]);if(y(d,"url(")){if(")"!=d.charAt(d.length-1))return null;b.push(d.substring(4,d.length-1))}}return b}function ud(a,b){for(var c=1;c<arguments.length;++c)P(a,arguments[c])};function X(a){this.f=a;this.c={"psmob-nav-panel":!0,"psmob-header-bar":!0,"psmob-spacer":!0,"psmob-logo-span":!0};this.a=qd();this.b=[new Y(X.prototype.ra,"scroll wide pre-tags"),new Y(X.prototype.sa,"string floats"),new Y(X.prototype.Ba,"cleanup styles"),new Y(X.prototype.oa,"repair distored images"),new Y(X.prototype.pa,"resize if too wide"),new Y(X.prototype.ka,"expand columns"),new Y(X.prototype.Ga,"resize vertically")];S("window.pagespeed.MobLayout.maxWidth="+this.a)}
function Y(a,b){this.a=a;this.b=b}function vd(a,b){return b?Mc[b.tagName.toUpperCase()]||!(!b.id||!a.c[b.id]):!0}function wd(a,b,c){for(b=b.firstElementChild;b;b=b.nextElementSibling)vd(a,b)||c.call(a,b)}l=X.prototype;l.ra=function(a){("PRE"==a.tagName.toUpperCase()||a.offsetWidth>this.a&&"pre"==window.getComputedStyle(a).getPropertyValue("white-space"))&&rd(a);wd(this,a,v(this.ra,this))};l.Ga=function(a){xd(this,a,0)};
function xd(a,b,c){var d;(d=Tc(b))?(c=d.top,d=d.bottom):(b.offsetParent==b.parentNode&&(c+=b.offsetTop),d=c+b.offsetHeight-1);d=[c,d];if(!d)return null;c=d[0];d=d[1];if(vd(a,b))return d;d=c-1;var e=window.getComputedStyle(b);if(!e)return null;var f=O(e,"min-height");null!=f&&(d+=f);for(var f=c+b.offsetHeight-1,g=!1,h=!1,k,m=b.firstElementChild;m;m=m.nextElementSibling)(k=window.getComputedStyle(m))&&"absolute"==k.position&&!dd(k)&&0!=N(k.getPropertyValue("height"))&&"hidden"!=k.getPropertyValue("visibility")&&
(h=!0),k=xd(a,m,c),null!=k&&(g=!0,d=Math.max(d,k));if(g&&"fixed"==e.getPropertyValue("position"))return null;a=b.tagName.toUpperCase();"BODY"!=a&&(e=f-c+1,g?d!=f&&(h?Q(b,"height",""+(d-c+1)+"px"):Q(b,"height","auto")):("IMG"!=a&&0<e&&!b.style.backgroundSize&&(P(b,"height"),Q(b,"height","auto"),b.offsetHeight&&(f=c+b.offsetHeight)),d=f));return d}
l.pa=function(a){wd(this,a,v(this.pa,this));if(!(a.offsetWidth<=this.a)){var b=a.tagName.toUpperCase();if("TABLE"==b){var c;a:{c=0;for(b=a.firstElementChild;b;b=b.nextElementSibling)for(var d=b.firstElementChild;d;d=d.nextElementSibling){var e=b.tagName.toUpperCase();if("THEAD"==e||"TFOOT"==e){c=!0;break a}for(e=d.firstElementChild;e;e=e.nextElementSibling){if("TH"==e.tagName.toUpperCase()){c=!0;break a}++c}}c=3*sd(a)<=c}if(c)rd(a);else if("CSS1Compat"!==document.compatMode){var f,g,h,k=document.createElement("DIV");
k.style.display="inline-block";var m=Ub(a);for(c=0;c<m.length;++c)for(var n=Ub(m[c]),b=0;b<n.length;++b)for(var r=Ub(n[b]),d=0;d<r.length;++d)if(g=r[d],1==g.childNodes.length)f=g.childNodes[0],g.removeChild(f),k.appendChild(f);else if(1<g.childNodes.length){h=document.createElement("DIV");h.style.display="inline-block";for(var Pa=Ub(g),e=0;e<Pa.length;++e)f=Pa[e],g.removeChild(f),h.appendChild(f);k.appendChild(h)}a.parentNode.replaceChild(k,a)}else for(P(a,"width"),Q(a,"max-width","100%"),a=a.firstElementChild;a;a=
a.nextElementSibling)for(P(a,"width"),Q(a,"max-width","100%"),c=a.firstElementChild;c;c=c.nextElementSibling)if("TR"==c.tagName.toUpperCase())for(P(c,"width"),Q(c,"max-width","100%"),b=c.firstElementChild;b;b=b.nextElementSibling)"TD"==b.tagName.toUpperCase()&&(Q(b,"max-width","100%"),Q(b,"display","inline-block"))}else if("IMG"==b)c=this.a,b=a.offsetHeight,d=a.offsetWidth/c,1<d&&(b=b/d,Q(a,"width",""+c+"px"),Q(a,"height",""+b+"px"));else if(d=td(a),c=window.getComputedStyle(a),d&&c&&1==d.length){b=
this.f.i[d[0]];b==yd&&(b=null);if(d=b&&b.width&&b.height)"auto"==c.getPropertyValue("background-size")?d=!1:(d=c.getPropertyValue("background-position"),"none"==d?d=!1:(d=d.split(" "),d=!(2!=d.length||null==N(d[0])||null==N(d[1])))),d=!d;d&&(d=this.a,e=b.width,b=b.height,e>d&&(b=Math.round(d/e*b),d="background-size:"+d+"px "+b+"px;background-repeat:no-repeat;",c=O(c,"height"),b==c&&(d+="height:"+b+"px;"),Sc(a,d)),Q(a,"min-height",""+b+"px"))}else 0<=Ea(Oc,b)?rd(a):Lc[b]?(Q(a,"max-width","100%"),P(a,
"width")):S("Punting on resize of "+b+" which wants to be "+a.offsetWidth+" but this.maxWidth_="+this.a)}};l.Ba=function(a){var b=document.body.style.display;document.body.style.display="none";this.ha(a);document.body.style.display=b};
l.ha=function(a){"nowrap"==window.getComputedStyle(a).getPropertyValue("white-space")&&Q(a,"white-space","normal");wd(this,a,this.ha);var b=window.getComputedStyle(a);if(b){for(var c=0;c<Nc.length;++c){var d=Nc[c],e=b.getPropertyValue(d);e&&"100%"!=e&&"auto"!=e&&ua(e,"%")&&Q(a,d,"auto")}for(var d=a.tagName.toUpperCase(),c="UL"==d||"OL"==d,d="BODY"==d,e=!1,f="",g=0;g<Ic.length;++g){var h=Ic[g];if(!(c&&ua(h,"-left")||d&&y(h,"margin-"))){var k=O(b,h);null!=k&&(4<k?f+=h+":4px !important;":0>k&&(e=!0,
"margin-bottom"==h&&(e=-30<k),e?f+=h+":0px !important;":a.setAttribute("data-pagespeed-negative-bottom-margin","1")))}}Sc(a,f)}};
l.oa=function(a){wd(this,a,this.oa);if("IMG"==a.tagName.toUpperCase()){var b=window.getComputedStyle(a),c=Rc(a,"width"),d=Rc(a,"height");if(c&&d&&b){var e=O(b,"width"),b=O(b,"height");if(e&&b&&(e/=c,b/=d,.95<(e>b?b/e:e/b)||(S("aspect ratio problem for "+a.getAttribute("src")),1==a.naturalHeight&&1==a.naturalWidth?(b=Math.min(e,b),ud(a,["width","height"]),a.style.width=c*b,a.style.height=d*b):e>b?P(a,"height"):(ud(a,["width","height"]),a.style.maxHeight=d)),.25>e)){for(S("overshrinkage for "+a.getAttribute("src"));a&&
"TD"!=a.tagName.toUpperCase();)a=a.parentNode;if(a&&(a=a.parentNode)){d=0;for(c=a.firstElementChild;c;c=c.nextElementSibling)"TD"==c.tagName.toUpperCase()&&++d;if(1<d)for(d="width:"+Math.round(100/d)+"%;",c=a.firstElementChild;c;c=c.nextElementSibling)"TD"==c.tagName.toUpperCase()&&Sc(c,d)}}}}};
l.sa=function(a){var b=window.getComputedStyle(a).getPropertyValue("position");if("fixed"==b)return"fixed";if(L(a,"nivoSlider"))return b;var c=[],d=null,e=!1;wd(this,a,function(a){var b=window.getComputedStyle(a),f=this.sa(a);if("fixed"!=f&&b&&!vd(this,a)){"absolute"!=f||dd(b)||Q(a,"position","relative");var f=b.getPropertyValue("float"),g="right"==f,r="inline-block";g&&"right"==b.getPropertyValue("clear")&&(g=!1,r="block",d&&e&&Q(d,"margin-bottom","0"));if(g||"left"==f||"block"==r)Q(a,"float","none"),
"none"!=b.getPropertyValue("display")&&Q(a,"display",r);g&&c.push(a);d=a;a=O(b,"margin-bottom");e=null!=a&&0>a}}.bind(this));var f,g;for(f=c.length-1;0<=f;--f)g=c[f],a.removeChild(g);for(f=c.length-1;0<=f;--f)g=c[f],a.appendChild(g);return b};
l.ka=function(a){for(var b=zd(this,a),c=null,d=0;d<b.length;++d){var e=b[d],f=d<b.length-1?b[d+1]:null,g=e.offsetLeft+e.offsetWidth;if((null==c||e.offsetLeft<c)&&(null==f||f.offsetLeft<g)&&(c=window.getComputedStyle(e))){var f=e,h=f.tagName.toUpperCase();"INPUT"!=h&&"SELECT"!=h&&(f.style.backgroundSize||"auto"==c.width||Q(f,"width","auto"),"IMG"!=h&&f.removeAttribute("width"),ud(f,Jc),f.className+=f.className?" ":"",f.a+="psmob-single-column");this.ka(e)}a.getAttribute("data-pagespeed-negative-bottom-margin")&&
(a.removeAttribute("data-pagespeed-negative-bottom-margin"),e=window.getComputedStyle(a),e=O(e,"height"),null!=e&&Q(a,"margin-bottom",""+-e+"px"));c=g}};function zd(a,b){var c=[];if("fixed"==window.getComputedStyle(b).getPropertyValue("position"))return c;wd(a,b,function(a){var b=window.getComputedStyle(a).getPropertyValue("position");("fixed"!=b&&"absolute"!=b||0!=a.offsetWidth)&&c.push(a)});return c};function Ad(a,b,c){this.c=a;this.a=b;this.b=c}function Bd(){this.b=null;var a=document.domain.toLowerCase().split("."),b=a.length;this.Fa=4<b&&2==a[b-3].length?a[b-5]:3<b?a[b-4]:null;this.i=window.location.origin+window.location.pathname;this.a=[];this.c=0;this.f=1}function Cd(a,b){this.c=a;this.a=b;this.i=[];this.s=[];this.l=this.o=this.g=null;this.b=b;this.backgroundColor=this.f=null}
function Dd(a,b){function c(a){a&&"string"==typeof a&&(-1!=a.toLowerCase().indexOf("logo")&&++e,this.Ma&&0<=Zc(a).indexOf(Zc(this.Fa))&&++e)}if("hidden"==window.getComputedStyle(b).getPropertyValue("visibility"))return null;var d=null;"IMG"==b.nodeName.toUpperCase()?d=b.src:d=Uc(b);d=$c(d);-1!=d.indexOf("data:image/")&&(d=null);var e=0;c(b.title);c(b.id);c(b.className);c(b.alt);c(d);b.href==a.i&&++e;return 0<e?new Cd(e,b):null}
function Ed(a,b){var c=Dd(a,b);c&&a.a.push(c);for(c=b.firstElementChild;c;c=c.nextElementSibling)Ed(a,c)}function Fd(a,b){++a.c;b.addEventListener("load",v(a.g,a));b.addEventListener("error",v(a.g,a))}function Gd(a,b){var c=document.createElement("IMG");Fd(a,c);c.src=b;return c}
function Hd(a,b,c,d){var e=null,f;for(f in Xc){var e=b,g=Xc[f],h=null;switch(g){case "IMG":e.nodeName==g&&(h=e.src);break;case "SVG":e.nodeName==g&&(e=(new XMLSerializer).serializeToString(e),h=(self.URL||self.webkitURL||self).createObjectURL(new Blob([e],{type:"image/svg+xml;charset=utf-8"})));break;case "background-image":h=Uc(e)}if(h){var e=h,k=gc(document.location.href),g=k[1],h=k[2],m=k[3],k=k[4],n="";g&&(n+=g+":");m&&(n+="//",h&&(n+=h+"@"),n+=m,k&&(n+=":"+k));g=n;k=ic(gc(g)[3]||null);h=ic(gc(e)[3]||
null);null!=k&&null!=h&&(m=!1,k!=h&&(0<=k.indexOf(h)&&(k=k.split("."),n=k.length,3<=n&&(h==k.slice(0,n-2).join(".")||"www"==k[0]&&(h==k.slice(1,n-2).join(".")||h==k.slice(1,n).join(".")))&&(m=!0)),e=m?g+e.substring(e.indexOf(h)+h.length):e))}else e=null;if(e){g=null;"IMG"==f?(g=b,b.naturalWidth||Fd(a,g)):g=Gd(a,e);c.push(b);d.push(g);break}}for(b=b.firstElementChild;b;b=b.nextElementSibling)Hd(a,b,c,d)}function Id(a,b){var c=a.length-1;b<c&&(a[b]=a[c]);a.pop()}
function Jd(a){for(var b=a.a,c=0;c<b.length;++c){for(var d=b[c],e=cd(d.a),f=e.width*e.height,g=.5*f,h=-1,k=0,m=0;m<d.i.length;++m)if(f=d.i[m])e=cd(f),f=e.width*e.height,f>=g&&20<e.width&&10<e.height&&400>e.height&&f>k&&(k=f,h=m);0<=h?(d.l=d.i[h],d.b=d.s[h],d.f=e):d.g?(f=d.g,e=cd(f),f=e.width*e.height,f>=g&&20<e.width&&10<e.height&&400>e.height?(d.l=d.g,d.b=d.o,d.f=e):(Id(b,c),--c)):(Id(b,c),--c)}b=a.a;if(1<b.length){e=0;g=Infinity;for(c=0;d=b[c];++c)h=d.f,g=Math.min(g,h.top),e=Math.max(e,h.bottom);
for(c=0;d=b[c];++c)h=d.f,d.c*=Math.sqrt((e-h.top)/(e-g));if(0<b.length&&1==a.f){e=b[0];for(c=1;c<b.length;++c)d=b[c],0>Kd(d,e)&&(e=d);b[0]=e}else b.sort(Kd)}c=[];d={};for(e=0;c.length<a.f&&e<b.length;++e)if(g=b[e],!d[g.b.src]){d[g.b.src]=!0;if((h=g)&&h.l){m=null;for(k=h.l;k&&!m;){a:{if(m=document.defaultView.getComputedStyle(k,null))if(f=m.getPropertyValue("background-color")){b:{var m=f.indexOf("("),n=f.lastIndexOf(")");if(m=0<=m&&n>m?f.substring(m+1,n):null){for(var m=m.split(","),f=[],n=0,r=m.length;n<
r;++n)if(f[n]=3!=n?parseInt(m[n],10):parseFloat(m[n]),isNaN(f[n])){m=null;break b}m=3==f.length||4==f.length?f:null}else m="transparent"==f?[0,0,0,0]:null}if(m&&(3==m.length||4==m.length&&0!=m[3]))break a}m=null}k=k.parentElement}h.backgroundColor=m}h=(new jd).run(g.b,g.backgroundColor);c.push(new Ad(g,h.a,h.b))}b=a.b;a.b=null;b(c)}Bd.prototype.g=function(){--this.c;0==this.c&&Jd(this)};var Ld=[function(a){return a.top},function(a){return a.left},function(a){return a.width*a.height}];
function Kd(a,b){if(a.c>b.c)return-1;if(b.c>a.c)return 1;for(var c=0;c<Ld.length;++c){var d=Ld[c],e=d(a.f),d=d(b.f);if(e<d)return-1;if(d<e)return 1}if(a.a&&a.a.src&&b.a&&b.a.src){if(a.a.src<b.a.src)return-1;if(a.a.src>b.a.src)return 1}return 0}
Bd.prototype.run=function(a,b){if(this.b||!document.body)a([]);else{this.b=a;this.f=b;Ed(this,document.body);for(var c=this.a,d=0;d<c.length;++d){var e=c[d],f=e.a;Hd(this,f,e.i,e.s);for(f=f.parentElement;f;){var g=Uc(f);if(g){e.g=f;e.o=Gd(this,g);break}f=f.parentElement}}0==this.c&&Jd(this)}};Bd.prototype.run=Bd.prototype.run;function Md(a){this.a=a}function Nd(a,b,c){var d=new Yc(a,b,c);window.psMobPrecompute&&(window.psMobLogoUrl=a,window.psMobBackgroundColor=b,window.psMobForegroundColor=c);return d}Md.prototype.b=function(a){if(this.a){1<=a.length?(a=a[0],a=Nd(a.c.b.src,a.a,a.b)):a=Nd(null,[255,255,255],[0,0,0]);var b=this.a;this.a=null;b(a)}};function Od(a,b){this.a=a;this.g=b;this.b=null;this.c=0;Pd(this)}
function Pd(a){document.body.appendChild(a.a);Qd(a);Rd(a);Sd(a);a.a.addEventListener("touchmove",v(function(a){if(Td(this)){var c=a.touches[0].clientY;if(1!=a.touches.length)a.preventDefault();else{var d=c>this.c,e=0==this.a.scrollTop,f=this.a.scrollTop>=this.a.scrollHeight-this.a.offsetHeight-1;a.cancelable&&(d&&e||!d&&f)&&a.preventDefault();a.stopImmediatePropagation&&a.stopImmediatePropagation();this.c=c}}},a),!1);window.addEventListener("scroll",v(function(a){Td(this)&&!this.a.contains(a.target)&&
(a.stopPropagation(),a.preventDefault())},a));window.addEventListener("touchstart",v(function(a){this.c=a.touches[0].clientY},a),!1)}function Ud(a,b){var c=fd(),d="scale("+c+")";a.a.style.webkitTransform=d;a.a.style.transform=d;d=L(a.a,"open")?0:-Yb(a.a).width;a.a.style.top=window.scrollY+"px";a.a.style.left=window.scrollX+d+"px";b&&(a.a.style.marginTop=b+"px",a.a.style.height=(window.innerHeight-b)/c+"px")}
function Rd(a){a.b=document.createElement("DIV");a.b.id="psmob-click-detector-div";document.body.insertBefore(a.b,a.a);a.b.addEventListener("click",v(function(){L(this.a,"open")&&this.f()},a),!1)}
function Qd(a){var b=a.a.querySelectorAll("DIV > A"),c=b.length;if(0!=c){a=ad("R0lGODlhkACQAPABAP///wAAACH5BAEAAAEALAAAAACQAJAAAAL+jI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvmMTqvX7Lb7DY/L5/S6/Y7P6/f8vh8EAJATKIhFWFhziEiluBjT6AgFGdkySclkeZmSqYnE2VnyCUokOhpSagqEmtqxytrjurnqFGtSSztLcvu0+9HLm+sbPPWbURx1XJGMPHyxLPXsEA3dLDFNXP1wzZjNsF01/W31LH6VXG6YjZ7Vu651674VG8/l2s1mL2qXn4nHD6nn3yE+Al+5+fcnQL6EBui1QcUwgb6IEvtRVGDporc/RhobKOooLRBIbSNLmjyJMqXKlSxbunwJM6bMmTRr2ryJM6fOnTx7+vwJNKjQoUSLGj2KNKnSpUybOn0KVUcBADs=",a.g);
for(var d=0;d<c;d++){var e=document.createElement("IMG"),f=b[d];f.insertBefore(e,f.firstChild);e.setAttribute("src",a);M(e,"psmob-menu-expand-icon")}}}Od.prototype.f=function(){U(Td(this)?"psmob-menu-button-close":"psmob-menu-button-open");Nb(this.a,"open");Nb(this.b,"open");Nb(document.body,"noscroll");Ud(this)};function Vd(a,b){var c=new kc(a);return c.D==document.domain||c.D==b?(c.D=b,c.toString()):null}
function Sd(a){for(var b=a.a.querySelectorAll("DIV"),c=0,d;d=b[c];++c)d.addEventListener("click",function(a){a.preventDefault();a=a.currentTarget;Nb(a.nextSibling,"open");Nb(a.firstChild.firstChild,"open")},!1);if(b=document.getElementById("psmob-iframe")){d=vc(new kc(b.src));for(var e=a.a.querySelectorAll("LI > A"),c=0,f;f=e[c];c++){var g=Vd(f.href,d);g&&f.addEventListener("click",v(function(a,b,c){this.f();c.preventDefault();a.src=b},a,b,g))}}}function Td(a){return L(a.a,"open")};function Wd(){this.j=Rb("psmob-header-bar");this.b=null;this.a=Rb("psmob-spacer");this.V=this.v=this.g=this.c=this.s=this.f=null;this.X=0;this.i=-1;this.o=new eb;this.l=!1;this.la=La()}
function Xd(a,b,c){if(!b.className||"ps-progress-scrim"!=b.className&&t(b.className)&&!y(b.className,"psmob-")&&!y(b.id,"psmob-")){var d=window.getComputedStyle(b),e=d.getPropertyValue("position");"static"!=e&&(null==N(d.getPropertyValue("top"))||"fixed"!=e&&(c||"absolute"!=e)||a.o.add(b),c=!0);for(b=b.firstElementChild;b;b=b.nextElementSibling)Xd(a,b,c)}}
Wd.prototype.U=function(){if(this.j){var a=-1==this.i?Math.round(Yb(this.j).height):this.i,b=fd(),c="scale("+b.toString()+")";this.j.style.webkitTransform=c;this.j.style.transform=c;c=window.innerWidth;if("hidden"!=window.getComputedStyle(document.body).getPropertyValue("overflow-y")){var d=document.createElement("div");d.style.cssText="overflow:auto;position:absolute;top:0;width:100px;height:100px";var e=document.createElement("div"),f="200px",g;f instanceof oa?(g=f.height,f=f.width):g="200px";e.style.width=
Xb(f);e.style.height=Xb(g);d.appendChild(e);document.body.appendChild(d);e=d.offsetWidth-d.clientWidth;d&&d.parentNode&&d.parentNode.removeChild(d);c=c-e}this.j.style.width=c/b+"px";Mb(this.j,"hide");b=Math.round(Yb(this.j).height);this.a.style.height=b+"px";this.i=b;c=this.o.u();for(d=0;d<c.length;d++)e=c[d],g=window.getComputedStyle(e),f=g.getPropertyValue("position"),g=N(g.getPropertyValue("top")),"static"!=f&&null!=g&&(this.l?(f=e.style.top,f=N(e.style.top),null!=f&&(e.style.top=String(f+(b-a))+
"px")):(f=Tc(e).top,e.style.top=String(f+b)+"px"));this.l&&b!=a&&window.scrollBy(0,b-a);this.j.style.top=window.scrollY+"px";this.j.style.left=window.scrollX+"px";this.l=!0}this.v&&Ud(this.v,this.j.getBoundingClientRect().height)};
function Yd(a){function b(){null!=this.V&&(window.clearTimeout(this.V),this.V=null);this.V=window.setTimeout(v(function(){(this.la||0==this.X)&&this.U();this.V=null},this),200)}a.U();window.addEventListener("scroll",v(function(){b.call(this);this.v&&Td(this.v)||M(this.j,"hide")},a),!1);window.addEventListener("touchstart",v(function(a){this.X=a.touches.length},a),!1);window.addEventListener("touchmove",v(function(a){this.v&&Td(this.v)?a.preventDefault():this.la||M(this.j,"hide")},a),!1);window.addEventListener("touchend",
v(function(a){this.X=a.touches.length;0==this.X&&b.call(this)},a),!1);window.addEventListener("orientationchange",v(function(){this.U()},a),!1);window.addEventListener("resize",v(function(){this.U()},a),!1)}
function Zd(a,b){document.body.insertBefore(a.a,document.body.childNodes[0]);document.body.insertBefore(a.j,a.a);window.psLabeledMode&&M(a.j,"labeled");window.psConfigMode&&M(a.j,"psmob-theme-config");var c=document.getElementById("psmob-nav-panel");!window.psLabeledMode&&c&&(a.v=new Od(c,b.K),a.s=new gd(b.C,v(a.v.f,a.v)),a.j.appendChild(a.s.a));b.B&&(a.f=document.createElement("SPAN"),a.f.id="psmob-logo-span",c=document.createElement("IMG"),c.src=b.B,c.id="psmob-logo-image",a.f.appendChild(c),a.j.appendChild(a.f));
a.j.style.borderBottomColor=R(b.C);a.j.style.backgroundColor=R(b.K);window.psPhoneNumber&&(a.c=new W(b.C,window.psPhoneNumber,window.psConversionId,window.psPhoneConversionLabel),a.j.appendChild(a.c.a));window.psMapLocation&&(a.g=new hd(b.C,window.psMapLocation,window.psConversionId,window.psMapConversionLabel),a.j.appendChild(a.g.a));if("mobile"==window.psDeviceType||"tablet"==window.psDeviceType)M(a.j,"mobile"),M(a.a,"mobile"),a.v&&M(a.v.a,"mobile");(window.psLabeledMode||a.c&&!a.g||!a.c&&a.g)&&
M(a.j,"show-button-text");Yd(a);a.b&&a.b.parentNode.removeChild(a.b);var c=R(b.K),d=R(b.C);a.b=document.createElement("STYLE");a.b.type="text/css";a.b.appendChild(document.createTextNode("#psmob-header-bar { background-color: "+c+"; }\n#psmob-header-bar *  { color: "+d+"; }\n#psmob-nav-panel { background-color: "+d+"; }\n#psmob-nav-panel *  { color: "+c+"; }\n"));document.head.appendChild(a.b)}
Wd.prototype.run=function(a){if(!Vc()){for(var b=document.querySelectorAll("*"),c=0,d;d=b[c];c++){var e=d.id;(!e||"ps-progress-scrim"!=e&&"psmob-header-bar"!=e&&"psmob-nav-panel"!=e)&&999998<=window.getComputedStyle(d).getPropertyValue("z-index")&&(S("Element z-index exceeded 999998, setting to 999997."),d.style.zIndex=999997)}window.document.body&&Xd(this,window.document.body,!1);Zd(this,a);U("nav-done");window.addEventListener("load",v(this.U,this));document.getElementById("psmob-iframe")&&(new pd).run()}};
function $d(a,b){a.j.remove();a.a.remove();a.a=document.createElement("DIV");a.a.id="psmob-spacer";a.j=document.createElement("HEADER");a.j.id="psmob-header-bar";Zd(a,b)};function ae(){this.a=null;this.c=new Wd;this.b=null}l=ae.prototype;l.run=function(){window.addEventListener("DOMContentLoaded",v(this.Da,this))};l.Da=function(){(new Bd).run(v(this.Ea,this),5)};l.Ea=function(a){this.b=a;0==this.b.length?console.log("No logos detected."):(a=this.b[0],this.c.run(new Yc(a.c.b.src,a.a,a.b)),this.ga())};
l.ga=function(){function a(){var a=document.createElement("TD");d.appendChild(a);return a}if(this.a)this.a&&(this.a.parentNode.removeChild(this.a),this.a=null);else{var b=document.createElement("TABLE");b.className="psmob-logo-chooser-table";var c=document.createElement("THEAD");b.appendChild(c);var d=document.createElement("TR");c.appendChild(d);d.className="psmob-logo-chooser-column-header";a().textContent="Logo";a().textContent="Foreground";a().textContent="";a().textContent="Background";c=document.createElement("TBODY");
b.appendChild(c);for(var e=0;e<this.b.length;++e){d=document.createElement("TR");d.className="psmob-logo-chooser-choice";c.appendChild(d);var f=this.b[e],g=document.createElement("IMG");g.src=f.c.b.src;a().appendChild(g);g.className="psmob-logo-chooser-image";g.onclick=v(this.za,this,f);g=a();g.style.backgroundColor=D(f.b);g.className="psmob-logo-chooser-color";var h=a();h.className="psmob-logo-chooser-color";var k=document.createElement("IMG");k.className="psmob-logo-chooser-swap";k.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIYAAABaCAAAAABY7nEZAAAABGdBTUEAALGPC/xhBQAAAcpJREFUaN7t2ItxgkAQgOHtADvADkwH2oHpADrADlKCdoAdaAekA0qgBEowYIZRE7jbe+xjktsCnE/m54CFm4qBxEgMIkavgwHlVQUDYHVoNTCGWZ86DYxhdudeA2OYgExiMgIyicvwziQ6wy8TCoZHJkQM10zIGG6ZUDIcMiFmYDOhZ6AymWd8ogdwY8sEvP+j6xgz4WMYM2FlLGfCzBgzqTUwiov81djWvXgb+bFzvFO26MEasqqVPkWXguBlLAbByDAFwcWwBMHDsAbBwMAEQc1ABkHKwAdByHAJgorhGAQJI/8IWC5EYmRF2KolCmN/uYX+TDBjU0dYw4UyQoJI69n/wmhKeUZ3WAMIM/rT2/34EGWc36fjXI7RlKvHU0WIcQ8CZBlTEKKMRxByjJcghBg/g5BgzATBz5gNgpmxFAQnwxAEG8McBBPDFsTzAhY7rgxEED7jxMAFQctAB0HLqPeggTFcj+NGA2Oso8o1MMZ7pcg0MFwyabDjeZgjM2F4tGEy4XnQWzNhe+0xZ8L4EmjKhPeVeDET9g+E+UwkPpdmMpH5ePyVidin9GsmkouFp0yE1yxTJuJLp+9MNKzg2ipPC8nE+LuMLwqlrYBVqy8VAAAAAElFTkSuQmCC";
h.appendChild(k);k=a();k.style.backgroundColor=D(f.a);k.className="psmob-logo-chooser-swap";h.onclick=v(this.Aa,this,f,g,k)}be(this,b)}};function be(a,b){b.style.visibility="hidden";document.body.appendChild(b);var c=2/3,d=window.innerWidth*c/b.offsetWidth,c=Math.round(.5*(1-c)*window.innerWidth)+"px",d="scale("+d+") translate("+c+","+c+")";b.style["-webkit-transform"]=d;b.style.transform=d;b.style.visibility="visible";null!=a.a&&a.a.parentNode.removeChild(a.a);a.a=b}
l.za=function(a){a=new Yc(a.c.b.src,a.a,a.b);$d(this.c,a);document.getElementById("psmob-logo-span").addEventListener("click",v(this.ga,this));var b=document.createElement("PRE");b.className="psmob-logo-chooser-config-fragment";b.textContent='ModPagespeedMobTheme "\n    '+D(a.K)+"\n    "+D(a.C)+"\n    "+a.B+'"';be(this,b)};l.Aa=function(a,b,c){var d=a.a;a.a=a.b;a.b=d;d=b.style["background-color"];b.style["background-color"]=c.style["background-color"];c.style["background-color"]=d};function Z(){this.s=0;this.i={};this.xa=Date.now();this.ca=!1;this.g=this.N=this.ea=this.a=this.c=0;this.I=!1;this.S=this.J=0;this.o=new X(this);this.o.c["ps-progress-scrim"]=!0;this.b=-1;this.H=null;this.ia=[];this.l=[];this.f=null;this.wa=new Bd}var yd=new Qc(-1,-1);function ce(a){0==a.g?(S("mobilizing site"),window.psNavMode&&!Vc()||de(a)):a.I=!0}
Z.prototype.ya=function(a){--this.J;ee(this,this.c,"extract theme");this.f=new Wd;this.f.run(a);ee(this,this.c,"navigation");de(this);var b=fe().T;if(b&&0<=b.b){if(ge())$d(this.f,a);else{var c=document.createElement("IFRAME");c.id="ps-hidden-iframe";c.hidden=!0;document.body.appendChild(c)}b.l.push(a);this.da(!0)}window.parent!=window&&(b="Theme:  "+R(a.K)+" "+R(a.C),a.B&&(b+=" "+a.B),a=document.location.origin.split("."),c=a.length,2<=c&&(a="http://"+a[c-2]+"."+a[c-1],window.parent.postMessage(b,
a),S("Post message ("+b+") to "+a)))};Z.prototype.ta=function(a){this.i[a.src]=new Qc(a.width,a.height);--this.g;ee(this,1E3,"background image");0==this.g&&this.I&&(ce(this),this.I=!1)};function he(a,b){if(!vd(a.o,b)){var c=Uc(b);if(c&&(y(c,"http://")||y(c,"https://"))&&!a.i[c]){a.i[c]=yd;var d=new Image;++a.g;d.onload=v(a.ta,a,d);d.onerror=d.onload;d.src=c}for(c=b.firstElementChild;c;c=c.nextElementSibling)he(a,c)}}Z.prototype.xhrSendHook=function(){++this.s};
Z.prototype.xhrResponseHook=function(){--this.s;this.a+=this.S;de(this)};
Z.prototype.va=function(){U("load-event");ie(this,window.psDebugMode);this.c=Wc(document.body);this.S=this.c*this.o.b.length;this.a+=this.S;window.psNavMode&&Vc()&&(this.a+=this.c,this.a+=this.c);if(null!=document.body){for(var a in window.psMobStaticImageInfo){var b=window.psMobStaticImageInfo[a];this.i[a]=new Qc(b.w,b.h)}Boolean(window.psMobBackgroundColor&&window.psMobForegroundColor&&!window.psMobPrecompute)&&!window.psLayoutMode||he(this,document.body)}this.a+=1E3*this.g;window.psLayoutMode&&
window.pagespeedXhrHijackSetListener(this);ce(this)};function de(a){if(0==a.s&&0==a.J&&0==a.g){if(window.psLayoutMode){var b=a.o;if(document.body)for(var c=0;c<b.b.length;++c){var d=b.b[c];d.a.call(b,document.body);var e=b.f;ee(e,e.c,d.b)}}if(a.ca){if(a=document.getElementById("ps-progress-remove"))a.textContent="Remove Progress Bar and show mobilized site"}else je()}}
function ie(a,b){a.ca=b;var c=document.getElementById("ps-progress-log");c&&(c.style.color=b?"#333":"white");b&&(c=document.getElementById("ps-progress-show-log"))&&(c.style.display="none")}function ee(a,b,c){a.N+=b;b=100;0<a.a&&(b=Math.round(100*a.N/a.a),100<b&&(b=100));if(b!=a.ea){var d=document.getElementById("ps-progress-span");d&&(d.style.width=b+"%");a.ea=b}a=""+b+"% "+(Date.now()-a.xa)+"ms: "+c;S(a);if(c=document.getElementById("ps-progress-log"))c.textContent+=a+"\n"}
function je(){var a=document.getElementById("ps-progress-scrim");a&&(a.style.display="none",a.parentNode.removeChild(a))}
Z.prototype.ua=function(){if(window.psNavMode){++this.J;if(!ge()&&window.document.body&&-1!=window.location.search.indexOf("PageSpeedSiteWideProcessing")){var a=[],b=window.location.search.indexOf("ModPagespeedMobIframe"),c=null;-1!=b&&(c=window.location.search.substring(b),(c=c.split("#")[0].split("&")[0])&&(c="?"+c));ke(this,c,window.document.body,a);fe().T.ia=a;if(b=prompt(a.length+' links have been found in this page. If you want to compute theme from them, enter the number of links below and press "OK". It may take a while to process them. Once processing completes, you will see another dialog.',
a.length.toString()))isFinite(b)&&(b=String(b)),b=t(b)?/^\s*-?0x/i.test(b)?parseInt(b,16):parseInt(b,10):NaN,this.b=0>b?0:b>a.length?a.length:b}a=this.wa;b=v(this.ya,this);window.psMobBackgroundColor&&window.psMobForegroundColor&&!window.psMobPrecompute?(a=Nd(window.psMobLogoUrl,window.psMobBackgroundColor,window.psMobForegroundColor),b(a)):(b=new Md(b),a.run(v(b.b,b),1))}};window.T=new Z;ha("psSetDebugMode",function(){ie(window.T,!0)});ha("psRemoveProgressBar",function(){je()});
function ge(){return Vc()&&null!=window.frameElement&&"ps-hidden-iframe"==window.frameElement.id}function fe(){return ge()?window.parent:window}
function le(a){var b=fe().T;if(b&&b.l&&0!=b.l.length){for(var c={},d,e=0;d=b.l[e];++e){var f=d.B;f&&(f=f+R(d.C)+R(d.K),c[f]?++c[f].count:c[f]={W:d,count:1})}b=Aa(c);b.sort(function(a,b){if(a.count<b.count)return 1;if(a.count>b.count)return-1;var c=a.W.B,d=b.W.B;return c<d?-1:c>d?1:0});c="\nFinish site-wide theme extraction. ";if(0<b.length){c+="Found "+b.length+" logo images. Details are shown below:\n";$d(a.f,b[0].W);for(e in b)d=b[e].W,c+='"'+R(d.K)+" "+R(d.C)+" "+d.B+'" COUNT: '+b[e].count+"\n";
c+="\n";for(e in b)d=b[e].W,c+='ModPagespeedMobTheme "\n    '+D(d.K)+"\n    "+D(d.C)+"\n    "+d.B+'"\n'}else c+="No logo was found.";S(c+"\n")}}
Z.prototype.da=function(a){a||S("Time out.");a=fe().T;var b=fe();if(a){b.clearTimeout(a.H);a.H=null;var c=a.ia.pop();if(0<a.b&&c){S("Next URL is "+c+". "+a.b+" more to go.");var d=b.document.getElementById("ps-hidden-iframe");d&&(d.src=c,a.H=b.setTimeout(v(a.da,a),1E4));--a.b}else 0==a.b&&(le(this),alert("All URLs have been processed. The header bar shows the best result. Details can be found in console log."),a.b=-1)}};
function ke(a,b,c,d){if(!(100<=d.length)){var e=c.tagName.toUpperCase();if(("A"==e||"FORM"==e)&&(e=c.href)&&!bd(e)&&ic(gc(e)[5]||null).toLowerCase()!=window.location.pathname.toLowerCase()){if(b)var f=e.indexOf("?"),e=-1==f?e+b:e.substring(0,f)+b+"&"+e.substring(f+1);-1==d.indexOf(e)&&d.push(e)}for(c=c.firstElementChild;c;c=c.nextElementSibling)ke(a,b,c,d)}}
ha("pagespeed.Mob.start",function(){var a=new Z;if(window.psConfigMode)(new ae).run();else{if(window.psMobBackgroundColor&&window.psMobForegroundColor){var b=new Yc(window.psMobLogoUrl,window.psMobForegroundColor,window.psMobBackgroundColor);a.f=new Wd;a.f.run(b)}else window.addEventListener("DOMContentLoaded",v(a.ua,a));window.psLayoutMode&&window.addEventListener("load",v(a.va,a))}});})();
