(function(){function f(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}var h="closure_uid_"+(1E9*Math.random()>>>0),k=0;function l(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b};function m(a){if(a.g&&"function"==typeof a.g)return a.g();if("string"==typeof a)return a.split("");var b=f(a);if("array"==b||"object"==b&&"number"==typeof a.length){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return l(a)};function n(a,b){this.b={};this.a=[];this.h=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof n)d=p(a),c=a.g();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=l(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}}n.prototype.g=function(){q(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};function p(a){q(a);return a.a.concat()}
n.prototype.clear=function(){this.b={};this.h=this.c=this.a.length=0};function q(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];r(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],r(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}n.prototype.get=function(a,b){return r(this.b,a)?this.b[a]:b};n.prototype.set=function(a,b){r(this.b,a)||(this.c++,this.a.push(a),this.h++);this.b[a]=b};
n.prototype.forEach=function(a,b){for(var c=p(this),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};n.prototype.clone=function(){return new n(this)};function r(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function t(a){this.a=new n;a&&u(this,a)}function v(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[h]||(a[h]=++k)):b.substr(0,1)+a}function u(a,b){for(var c=m(b),d=c.length,e=0;e<d;e++){var g=c[e];a.a.set(v(g),g)}}t.prototype.removeAll=function(a){a=m(a);for(var b=a.length,c=0;c<b;c++){var d=this.a,e=v(a[c]);r(d.b,e)&&(delete d.b[e],d.c--,d.h++,d.a.length>2*d.c&&q(d))}};t.prototype.clear=function(){this.a.clear()};t.prototype.contains=function(a){a=v(a);return r(this.a.b,a)};
t.prototype.g=function(){return this.a.g()};t.prototype.clone=function(){return new t(this)};google.load("visualization","1.0",{packages:["corechart"]});function w(a){window.console&&console.error(a)}
function y(){this.a=[];this.h=new t;this.b=this.c=null;this.s={width:900,height:255,colors:["#4ECDC4","#556270","#C7F464"],legend:{position:"bottom"},hAxis:{format:"MMM d, y hh:mma",gridlines:{color:"#F2F2F2"},baselineColor:"#E5E5E5"},vAxis:{format:"#.###%",minValue:0,viewWindowMode:"explicit",viewWindow:{min:0},gridlines:{color:"#F2F2F2"},baselineColor:"#E5E5E5"},chartArea:{left:60,top:20,width:800},pointSize:2}}function z(a){var b={};b.f=new t([a]);b.evaluate=function(b){return b(a)};return b}
function A(a){var b={};b.f=new t;for(var c=0;c<a.length;c++)u(b.f,a[c].f);b.evaluate=function(b){for(var c=0,g=0;g<a.length;g++)c+=a[g].evaluate(b);return c};return b}function B(a,b){var c={};c.f=new t;u(c.f,a.f);u(c.f,b.f);c.evaluate=function(c){var e=b.evaluate(c);return 0==e?0:a.evaluate(c)/e};return c}function C(a,b){return B(a,A([a,b]))}
function D(){var a=new y;E(a,"Resources not loaded because of fetch failures","fetch-failure",B(z("serf_fetch_failure_count"),z("serf_fetch_request_count")));E(a,"Resources not rewritten because domain wasn't authorized","not-authorized",C(z("resource_url_domain_rejections"),z("resource_url_domain_acceptances")));E(a,"Resources not rewritten because of restrictive Cache-Control headers","cache-control",C(z("num_cache_control_not_rewritable_resources"),z("num_cache_control_rewritable_resources")));
var b=A([z("cache_backend_misses"),z("cache_backend_hits")]);E(a,"Cache misses","cache-miss",B(z("cache_backend_misses"),b));E(a,"Cache lookups that were expired","cache-expired",B(z("cache_expirations"),b));E(a,"CSS files not rewritten because of parse errors","css-error",C(z("css_filter_parse_failures"),z("css_filter_blocks_rewritten")));E(a,"JavaScript minification failures","js-error",C(z("javascript_minification_failures"),z("javascript_blocks_minified")));var b=A([z("image_rewrites"),z("image_rewrites_dropped_nosaving_resize"),
z("image_rewrites_dropped_nosaving_noresize")]),c=A([z("image_norewrites_high_resolution"),z("image_rewrites_dropped_decode_failure"),z("image_rewrites_dropped_due_to_load"),z("image_rewrites_dropped_mime_type_unknown"),z("image_rewrites_dropped_server_write_fail")]);E(a,"Image rewrite failures","image-error",C(c,b));b=new Date;F(a,new Date(b-864E5),b);return a}var G=["pagespeed","startConsole"],H=this;G[0]in H||!H.execScript||H.execScript("var "+G[0]);
for(var I;G.length&&(I=G.shift());){var J;if(J=!G.length)J=void 0!==D;J?H[I]=D:H[I]?H=H[I]:H=H[I]={}}function E(a,b,c,d){var e={};e.title=b;e.o="https://developers.google.com/speed/pagespeed/module/console#"+c;e.value=d;e.u=a.a.length;e.i=null;e.j=null;e.l=null;e.m=null;a.a.push(e);u(a.h,d.f)}function K(a,b,c){var d=pagespeedStatisticsUrl+"?json",d=d+("&start_time="+b.getTime()),d=d+("&end_time="+c.getTime()),d=d+"&granularity=60000&var_titles=";for(b=0;b<a.length;b++)d+=a[b]+",";return d}
function F(a,b,c){var d=new XMLHttpRequest;b=K(a.h.g(),b,c);d.onreadystatechange=function(){if(4==this.readyState)if(200!=this.status||1>this.responseText.length||"{"!=this.responseText[0])w("XHR request failed.");else{var b=JSON.parse(this.responseText);L(a,b)}};d.open("GET",b);d.send()}
function L(a,b){a.c=b.variables;a.b=b.timestamps;M(a.b,a.c);for(var c=0;c<a.a.length;c++){for(var d=[],e=0;e<a.b.length;e++)d.push(a.a[c].value.evaluate(function(a){return function(b){if(b in a)return a[b][e];w("JSON data missing required variable.");return 0}}(a.c)));a.a[c].i=d[d.length-1];a.a[c].j=a.a[c].i;a.a[c].l=O(a.a[c].title,a.b,d)}a.a.sort(function(a,b){return b.j-a.j});for(c=0;c<a.a.length;c++)P(a,a.a[c])}
function M(a,b){for(var c in b)a.length!=b[c].length&&w("JSON response is malformed. ("+a.length+" != "+b[c].length+")")}function O(a,b,c){var d=new google.visualization.DataTable;d.addColumn("datetime","Time");d.addColumn("number",a);for(var e=0;e<b.length;e++)d.addRow([new Date(b[e]),c[e]]);0==d.getNumberOfRows()&&w("Data failed to load for graph "+a);return d}
function P(a,b){var c=google.visualization.LineChart,d=b.title,e=b.i,g=b.o,N=b.u,x=document.createElement("div");x.setAttribute("class","pagespeed-widgets");x.appendChild(Q(d,e,g,N));d=document.createElement("div");d.setAttribute("class","pagespeed-graph");x.appendChild(d);document.getElementById("pagespeed-graphs-container").appendChild(x);b.m=new c(d);b.m.draw(b.l,a.s)}
function Q(a,b,c,d){var e=document.createElement("div");e.setAttribute("class","pagespeed-widgets-topbar");var g=document.createElement("span");g.setAttribute("class","pagespeed-title");g.setAttribute("id","pagespeed-title"+d);g.appendChild(document.createTextNode(a+": "+(100*b).toFixed(2)+"% ("));a=document.createElement("a");a.setAttribute("href",c);a.appendChild(document.createTextNode("doc"));g.appendChild(a);g.appendChild(document.createTextNode(")"));e.appendChild(g);return e};})();
