#!/bin/sh

case "$1" in
    remove)
        test -e /etc/apache2/mods-enabled/pagespeed.load && a2dismod pagespeed
    ;;
    upgrade|deconfigure|failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
