/**
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by:
// ./generate_javascript_metadata.sh /home/jmaessen/jslibs/
// Intended for inclusion in javascript_library_identification.cc

namespace net_instaweb {

static const LibraryInfo kLibraryMetadata[] = {
    {NULL, NULL, 0ULL, 0ULL, 0},
    { "prototype", "1.6.0.2", 0x84e682bac0395621ULL, 0x653fea1c8f19898aULL,
      93688},
    { "prototype", "1.6.0.3", 0x6d056fb74c5f131cULL, 0xd2d4d6cebc445a40ULL,
      95326},
    { "prototype", "1.6.1.0", 0x6ddb883a16ace985ULL, 0x023a481bab5452e4ULL,
      105538}
};

}  // namespace net_instaweb
